/*
 * SPDX-FileCopyrightText: (c) 2022 Project CHIP Authors
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#pragma once

// ---- Lighting Example App Config ----

#define FUNCTION_BUTTON DK_BTN1
#define FUNCTION_BUTTON_MASK DK_BTN1_MSK
#define DIMMER_SWITCH_BUTTON DK_BTN2
#define DIMMER_SWITCH_BUTTON_MASK DK_BTN2_MSK
#define GENERIC_SWITCH_BUTTON DK_BTN3
#define GENERIC_SWITCH_BUTTON_MASK DK_BTN3_MSK
#define BLE_ADVERTISEMENT_START_BUTTON DK_BTN4
#define BLE_ADVERTISEMENT_START_BUTTON_MASK DK_BTN4_MSK

#define SYSTEM_STATE_LED DK_LED1
#define DFU_BLE_LED DK_LED2
#define IDENTIFY_LED DK_LED3
