# Platform groups defining maintainers and their corresponding paths.
# Git-style wildmatch globs are supported (via python pathspec).

nxp:
  maintainers:
    - Martin-NXP
    - dinabenamar
    - marian-chereji-nxp
    - chapongatien
    - doru91
    - andrei-menzopol
    - sujaygkulkarni-nxp
  paths:
    - "src/platform/nxp/**"
    - "examples/platform/nxp/**"
    - "examples/**/nxp/**"

silabs:
  maintainers:
    - jmartinez-silabs
    - mkardous-silabs
    - chirag-silabs
    - arun-silabs
    - rosahay-silabs
    - jepenven-silabs
    - lpbeliveau-silabs
  paths:
    - "src/platform/silabs/**"
    - "examples/platform/silabs/**"
    - "examples/**/silabs/**"

esp32:
  maintainers:
    - shubhamdp
    - wqx6
    - shripad621git
    - jadhavrohit924
  paths:
    - "src/platform/ESP32/**"
    - "examples/platform/esp32/**"
    - "examples/**/esp32/**"

telink:
  maintainers:
    - s07641069
    - interfer
  paths:
    - "src/platform/telink/**"
    - "examples/platform/telink/**"
    - "examples/**/telink/**"

nrfconnect:
  maintainers:
    - ArekBalysNordic
    - adigie
    - kkasperczyk-no
  paths:
    - "src/platform/nrfconnect/**"
    - "examples/platform/nrfconnect/**"
    - "examples/**/nrfconnect/**"

tizen:
  maintainers:
    - enkiusz
    - arkq
  paths:
    - "src/platform/Tizen/**"
    - "examples/platform/tizen/**"
    - "examples/**/tizen/**"

realtek:
  maintainers:
    - pankore
  paths:
    - "src/platform/realtek/**"
    - "src/platform/Ameba/**"
    - "examples/platform/realtek/**"
    - "examples/platform/ameba/**"
    - "examples/**/realtek/**"
    - "examples/**/ameba/**"

asr:
  maintainers:
    - tx2rx
  paths:
    - "src/platform/ASR/**"
    - "examples/platform/asr/**"
    - "examples/**/asr/**"

beken:
  maintainers:
    - zhengyaohan
  paths:
    - "src/platform/Beken/**"
    - "examples/platform/beken/**"
    - "examples/**/beken/**"

bouffalolab:
  maintainers:
    - wy-hh
  paths:
    - "src/platform/bouffalolab/**"
    - "examples/platform/bouffalolab/**"
    - "examples/**/bouffalolab/**"

qpg:
  maintainers:
    - dvdm-qorvo
    - kliffwong
    - tima-q
  paths:
    - "src/platform/qpg/**"
    - "examples/platform/qpg/**"
    - "examples/**/qpg/**"

stm32:
  maintainers:
    - STYoannZamaron
  paths:
    - "src/platform/stm32/**"
    - "examples/platform/stm32/**"
    - "examples/**/stm32/**"

webos:
  maintainers:
    - joonhaengHeo
  paths:
    - "src/platform/webos/**"

mt793x:
  maintainers:
    - pakls
  paths:
    - "src/platform/mt793x/**"
    - "examples/platform/mt793x/**"

ti:
  maintainers:
    - s-jain2022
    - abiradarti
  paths:
    - "src/platform/ti/**"
    - "src/platform/cc32xx/**"
    - "examples/platform/ti/**"
    - "examples/platform/cc32xx/**"
    - "examples/**/ti/**"
    - "examples/**/cc32xx/**"
