[cfg]
# 0: no erase, 1:programmed section erase, 2: chip erase
erase = 1
# skip mode set first para is skip addr, second para is skip len, multi-segment region with ; separated
skip_mode = 0x0, 0x0
# 0: not use isp mode, #1: isp mode
boot2_isp_mode = 0

[boot2]
filedir = ./build/build_out/boot2_*.bin
address = 0x000000

[partition]
filedir = ./build/build_out/partition*.bin
address = 0xE000

[FW]
filedir = ./build/build_out/chip-bflb-contact-sensor-example_$(CHIPNAME)*.bin
address = @partition

# To flash a Matter factory-data bin into the [mfg] partition, run
# `make flash MFD_FILE=path/to/factory.bin`.
