/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP
// This file is generated from clusters-Structs.h.zapt

#pragma once

#include <app/data-model/DecodableList.h>
#include <app/data-model/List.h>
#include <app/data-model/Nullable.h>
#include <lib/core/DataModelTypes.h>
#include <lib/core/Optional.h>
#include <lib/core/TLV.h>
#include <lib/support/BitMask.h>

#include <clusters/shared/Structs.h>

#include <cstdint>

namespace chip {
namespace app {
namespace Clusters {
namespace ProximityRanging {
namespace Structs {
namespace RDRStruct {
enum class Fields : uint8_t
{
    kAzimuth           = 0,
    kElevation         = 1,
    kAzimuthAccuracy   = 2,
    kElevationAccuracy = 3,
    kReference         = 4,
};

struct Type
{
public:
    uint16_t azimuth           = static_cast<uint16_t>(0);
    int16_t elevation          = static_cast<int16_t>(0);
    uint8_t azimuthAccuracy    = static_cast<uint8_t>(0);
    uint8_t elevationAccuracy  = static_cast<uint8_t>(0);
    RDRReferenceEnum reference = static_cast<RDRReferenceEnum>(0);

    CHIP_ERROR Decode(TLV::TLVReader & reader);

    static constexpr bool kIsFabricScoped = false;

    CHIP_ERROR Encode(TLV::TLVWriter & aWriter, TLV::Tag aTag) const;
};

using DecodableType = Type;

} // namespace RDRStruct
namespace RangingMeasurementDataStruct {
enum class Fields : uint8_t
{
    kWiFiDevIK               = 0,
    kBLEDeviceID             = 1,
    kBLTDevIK                = 2,
    kTimeOfMeasurement       = 3,
    kTimeOfMeasurementOffset = 4,
    kDistance                = 5,
    kErrorMargin             = 6,
    kRdr                     = 7,
    kDetectedAttackLevel     = 8,
    kRssi                    = 9,
    kTxPower                 = 10,
};

struct Type
{
public:
    Optional<chip::ByteSpan> wiFiDevIK;
    Optional<uint64_t> BLEDeviceID;
    Optional<chip::ByteSpan> BLTDevIK;
    Optional<uint32_t> timeOfMeasurement;
    Optional<uint32_t> timeOfMeasurementOffset;
    DataModel::Nullable<uint16_t> distance;
    Optional<uint16_t> errorMargin;
    Optional<Structs::RDRStruct::Type> rdr;
    Optional<NADMEnum> detectedAttackLevel;
    Optional<DataModel::Nullable<int8_t>> rssi;
    Optional<DataModel::Nullable<int8_t>> txPower;

    CHIP_ERROR Decode(TLV::TLVReader & reader);

    static constexpr bool kIsFabricScoped = false;

    CHIP_ERROR Encode(TLV::TLVWriter & aWriter, TLV::Tag aTag) const;
};

using DecodableType = Type;

} // namespace RangingMeasurementDataStruct
namespace BLERangingDeviceRoleConfigStruct {
enum class Fields : uint8_t
{
    kRole            = 0,
    kPeerBLEDeviceID = 1,
};

struct Type
{
public:
    RangingRoleEnum role     = static_cast<RangingRoleEnum>(0);
    uint64_t peerBLEDeviceID = static_cast<uint64_t>(0);

    CHIP_ERROR Decode(TLV::TLVReader & reader);

    static constexpr bool kIsFabricScoped = false;

    CHIP_ERROR Encode(TLV::TLVWriter & aWriter, TLV::Tag aTag) const;
};

using DecodableType = Type;

} // namespace BLERangingDeviceRoleConfigStruct
namespace BLTChannelSoundingDeviceRoleConfigStruct {
enum class Fields : uint8_t
{
    kRole               = 0,
    kPeerBLTDevIK       = 1,
    kBLTCSMode          = 2,
    kBLTCSSecurityLevel = 3,
    kLtk                = 4,
};

struct Type
{
public:
    RangingRoleEnum role = static_cast<RangingRoleEnum>(0);
    chip::ByteSpan peerBLTDevIK;
    Optional<BLTCSModeEnum> BLTCSMode;
    Optional<BLTCSSecurityLevelEnum> BLTCSSecurityLevel;
    Optional<chip::ByteSpan> ltk;

    CHIP_ERROR Decode(TLV::TLVReader & reader);

    static constexpr bool kIsFabricScoped = false;

    CHIP_ERROR Encode(TLV::TLVWriter & aWriter, TLV::Tag aTag) const;
};

using DecodableType = Type;

} // namespace BLTChannelSoundingDeviceRoleConfigStruct
namespace RangingCapabilitiesStruct {
enum class Fields : uint8_t
{
    kTechnology             = 0,
    kFrequencyBand          = 1,
    kPeriodicRangingSupport = 2,
};

struct Type
{
public:
    RangingTechEnum technology                   = static_cast<RangingTechEnum>(0);
    chip::BitMask<RadioBandBitmap> frequencyBand = static_cast<chip::BitMask<RadioBandBitmap>>(0);
    bool periodicRangingSupport                  = static_cast<bool>(0);

    CHIP_ERROR Decode(TLV::TLVReader & reader);

    static constexpr bool kIsFabricScoped = false;

    CHIP_ERROR Encode(TLV::TLVWriter & aWriter, TLV::Tag aTag) const;
};

using DecodableType = Type;

} // namespace RangingCapabilitiesStruct
namespace RangingTriggerConditionStruct {
enum class Fields : uint8_t
{
    kStartTime               = 0,
    kEndTime                 = 1,
    kRangingInstanceInterval = 2,
};

struct Type
{
public:
    uint32_t startTime = static_cast<uint32_t>(0);
    uint32_t endTime   = static_cast<uint32_t>(0);
    Optional<uint32_t> rangingInstanceInterval;

    CHIP_ERROR Decode(TLV::TLVReader & reader);

    static constexpr bool kIsFabricScoped = false;

    CHIP_ERROR Encode(TLV::TLVWriter & aWriter, TLV::Tag aTag) const;
};

using DecodableType = Type;

} // namespace RangingTriggerConditionStruct
namespace ReportingConditionStruct {
enum class Fields : uint8_t
{
    kMinDistanceCondition = 0,
    kMaxDistanceCondition = 1,
    kErrorMarginCondition = 2,
};

struct Type
{
public:
    Optional<uint16_t> minDistanceCondition;
    Optional<uint16_t> maxDistanceCondition;
    Optional<uint16_t> errorMarginCondition;

    CHIP_ERROR Decode(TLV::TLVReader & reader);

    static constexpr bool kIsFabricScoped = false;

    CHIP_ERROR Encode(TLV::TLVWriter & aWriter, TLV::Tag aTag) const;
};

using DecodableType = Type;

} // namespace ReportingConditionStruct
namespace WiFiRangingDeviceRoleConfigStruct {
enum class Fields : uint8_t
{
    kRole          = 0,
    kPeerWiFiDevIK = 1,
    kPmk           = 2,
};

struct Type
{
public:
    RangingRoleEnum role = static_cast<RangingRoleEnum>(0);
    chip::ByteSpan peerWiFiDevIK;
    Optional<chip::ByteSpan> pmk;

    CHIP_ERROR Decode(TLV::TLVReader & reader);

    static constexpr bool kIsFabricScoped = false;

    CHIP_ERROR Encode(TLV::TLVWriter & aWriter, TLV::Tag aTag) const;
};

using DecodableType = Type;

} // namespace WiFiRangingDeviceRoleConfigStruct
} // namespace Structs
} // namespace ProximityRanging
} // namespace Clusters
} // namespace app
} // namespace chip
