/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP
// This file is generated from clusters-Events.h.zapt

#pragma once

#include <app/EventLoggingTypes.h>
#include <app/data-model/DecodableList.h>
#include <app/data-model/List.h>
#include <app/data-model/Nullable.h>
#include <lib/core/DataModelTypes.h>
#include <lib/core/TLV.h>
#include <lib/support/BitMask.h>

#include <clusters/shared/Enums.h>
#include <clusters/shared/Structs.h>

#include <clusters/CommissionerControl/ClusterId.h>
#include <clusters/CommissionerControl/Enums.h>
#include <clusters/CommissionerControl/EventIds.h>
#include <clusters/CommissionerControl/Structs.h>

#include <cstdint>

namespace chip {
namespace app {
namespace Clusters {
namespace CommissionerControl {
namespace Events {
namespace CommissioningRequestResult {
static constexpr PriorityLevel kPriorityLevel = PriorityLevel::Info;

enum class Fields : uint8_t
{
    kRequestID    = 0,
    kClientNodeID = 1,
    kStatusCode   = 2,
    kFabricIndex  = 254,
};

struct Type
{
public:
    static constexpr PriorityLevel GetPriorityLevel() { return kPriorityLevel; }
    static constexpr EventId GetEventId() { return Events::CommissioningRequestResult::Id; }
    static constexpr ClusterId GetClusterId() { return Clusters::CommissionerControl::Id; }
    static constexpr bool kIsFabricScoped = true;

    uint64_t requestID            = static_cast<uint64_t>(0);
    chip::NodeId clientNodeID     = static_cast<chip::NodeId>(0);
    uint8_t statusCode            = static_cast<uint8_t>(0);
    chip::FabricIndex fabricIndex = static_cast<chip::FabricIndex>(0);

    auto GetFabricIndex() const { return fabricIndex; }

    CHIP_ERROR Encode(TLV::TLVWriter & aWriter, TLV::Tag aTag) const;
};

struct DecodableType
{
public:
    static constexpr PriorityLevel GetPriorityLevel() { return kPriorityLevel; }
    static constexpr EventId GetEventId() { return Events::CommissioningRequestResult::Id; }
    static constexpr ClusterId GetClusterId() { return Clusters::CommissionerControl::Id; }

    uint64_t requestID            = static_cast<uint64_t>(0);
    chip::NodeId clientNodeID     = static_cast<chip::NodeId>(0);
    uint8_t statusCode            = static_cast<uint8_t>(0);
    chip::FabricIndex fabricIndex = static_cast<chip::FabricIndex>(0);

    CHIP_ERROR Decode(TLV::TLVReader & reader);
};
} // namespace CommissioningRequestResult
} // namespace Events
} // namespace CommissionerControl
} // namespace Clusters
} // namespace app
} // namespace chip
