; This is a config file used by prepend_header tool to generate MP header for a given image.
; 
; The following four sections are mandatory: BinID, Version, PartNumber and DataLength. Among
; which the DataLength key is not really needed to write in this file, as it would be calculated
; by the prepend_header tool and automatically filled in the MP header.
; 
; Note that MP header is a 512 bytes fixed data area, pay attention to the long strings you have
; written and ensure they are not out of bound of the header.


[MandatoryInfo]

; To recognize what is this .bin and where is came from. Defined IDs are: ID_APP, ID_PATCH, 
; ID_SOCV_CONFIG, ID_OEM_CONFIG, ID_FSBL, ID_OTA_HEADER, ID_APP_DATA, ID_APP_DSP_PARAM, ID_DSP_SYS, 
; ID_DSP_PATCH, ID_DSP_SCENARIO1, ID_DSP_SCENARIO2, ID_FACTORY_MP and ID_BOOT_PATCH
BinID=ID_APP

; This bin version. Range: 0.0.0.0 ~ 255.255.255.255
Version=1.0.0.0

; This bin is for what IC part number, ASCII type, 32 bytes maximum.
PartNumber=RTL8773


[OptionalInfo]

; Optional. Depended on what other .bins, for .bin merging check. Fill the required version number
; in specific field if specific image is needed. Item would be ignored if the format of the value
; is wrong or the value is not exist.
DependOnSocvConfig      =
DependOnOemConfig       =
DependOnFactoryMp       =
DependOnFsbl            =
DependOnOtaHeader       =
DependOnPatch           =
DependOnApp             =
DependOnAppData         =
DependOnAppDataTone     =
DependOnAppDataVp       =
DependOnAppDspParam     =
DependOnDspSys          =
DependOnDspPatch        =
DependOnDspScenario1    =
DependOnDspScenario2    =

; Optional ASCII type comment string, 255 bytes maximum.
Comment=

; Optional ASCII type author information string, 255 bytes maximum.
Author=

; Optional ASCII type date and time string, 255 bytes maximum.
Date=

; Optional bin header format revision.
Revision=0x01
