# Use: west build -p always -b esp32c6_devkitc/esp32c6/hpcore -- -DEXTRA_CONF_FILE=overlay-thread.conf

CONFIG_OPENTHREAD=y
CONFIG_NET_L2_OPENTHREAD=y

CONFIG_CHIP_WIFI=n
CONFIG_CHIP_ENABLE_WIFI_STATION=n
CONFIG_WIFI=n
CONFIG_WIFI_ESP32=n
CONFIG_NET_STATISTICS_WIFI=n

CONFIG_NET_IPV4=n
CONFIG_NET_DHCPV4=n
