/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP

// Prevent multiple inclusion
#pragma once

// This file contains the tokens for attributes stored in flash

// Identifier tags for tokens

// Types for the tokens
#ifdef DEFINETYPES
#endif // DEFINETYPES

// Actual token definitions
#ifdef DEFINETOKENS
#endif // DEFINETOKENS

// Macro snippet that loads all the attributes from tokens
#define GENERATED_TOKEN_LOADER(endpoint)                                                                                           \
    do                                                                                                                             \
    {                                                                                                                              \
    } while (false)

// Macro snippet that saves the attribute to token
#define GENERATED_TOKEN_SAVER                                                                                                      \
    do                                                                                                                             \
    {                                                                                                                              \
    } while (false)
