/*
 * SPDX-FileCopyrightText: 2022 Project CHIP Authors
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#pragma once

#define FUNCTION_BUTTON DK_BTN1
#define FUNCTION_BUTTON_MASK DK_BTN1_MSK
#define OPEN_BUTTON DK_BTN2
#define OPEN_BUTTON_MASK DK_BTN2_MSK
#define CLOSE_BUTTON DK_BTN3
#define CLOSE_BUTTON_MASK DK_BTN3_MSK
#define BLE_ADVERTISEMENT_START_BUTTON DK_BTN4
#define BLE_ADVERTISEMENT_START_BUTTON_MASK DK_BTN4_MSK

#define SYSTEM_STATE_LED DK_LED1
#define LIFT_STATE_LED DK_LED2
#define TILT_STATE_LED DK_LED3
#define FACTORY_RESET_SIGNAL_LED DK_LED4
