/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP
// This file is generated from clusters-Commands.h.zapt

#pragma once

#include <app/data-model/DecodableList.h>
#include <app/data-model/Encode.h>
#include <app/data-model/List.h>
#include <app/data-model/NullObject.h>
#include <app/data-model/Nullable.h>
#include <lib/core/DataModelTypes.h>
#include <lib/core/Optional.h>
#include <lib/core/TLV.h>
#include <lib/support/BitMask.h>

#include <clusters/shared/Enums.h>
#include <clusters/shared/Structs.h>

#include <clusters/ElectricalAlarm/ClusterId.h>
#include <clusters/ElectricalAlarm/CommandIds.h>
#include <clusters/ElectricalAlarm/Enums.h>
#include <clusters/ElectricalAlarm/Structs.h>

#include <cstdint>

namespace chip {
namespace app {
namespace Clusters {
namespace ElectricalAlarm {
namespace Commands {
// Forward-declarations so we can reference these later.

namespace Reset {
struct Type;
struct DecodableType;
} // namespace Reset

namespace ModifyEnabledAlarms {
struct Type;
struct DecodableType;
} // namespace ModifyEnabledAlarms

namespace SetElectricalAlarmThresholds {
struct Type;
struct DecodableType;
} // namespace SetElectricalAlarmThresholds

} // namespace Commands

namespace Commands {
namespace Reset {
enum class Fields : uint8_t
{
    kAlarms = 0,
};

struct Type
{
public:
    // Use GetCommandId instead of commandId directly to avoid naming conflict with CommandIdentification in ExecutionOfACommand
    static constexpr CommandId GetCommandId() { return Commands::Reset::Id; }
    static constexpr ClusterId GetClusterId() { return Clusters::ElectricalAlarm::Id; }

    chip::BitMask<AlarmBitmap> alarms = static_cast<chip::BitMask<AlarmBitmap>>(0);

    CHIP_ERROR Encode(TLV::TLVWriter & aWriter, TLV::Tag aTag) const;

    using ResponseType = DataModel::NullObjectType;

    static constexpr bool MustUseTimedInvoke() { return false; }
};

struct DecodableType
{
public:
    static constexpr CommandId GetCommandId() { return Commands::Reset::Id; }
    static constexpr ClusterId GetClusterId() { return Clusters::ElectricalAlarm::Id; }
    static constexpr bool kIsFabricScoped = false;

    chip::BitMask<AlarmBitmap> alarms = static_cast<chip::BitMask<AlarmBitmap>>(0);

    CHIP_ERROR Decode(TLV::TLVReader & reader);
};
}; // namespace Reset
namespace ModifyEnabledAlarms {
enum class Fields : uint8_t
{
    kMask = 0,
};

struct Type
{
public:
    // Use GetCommandId instead of commandId directly to avoid naming conflict with CommandIdentification in ExecutionOfACommand
    static constexpr CommandId GetCommandId() { return Commands::ModifyEnabledAlarms::Id; }
    static constexpr ClusterId GetClusterId() { return Clusters::ElectricalAlarm::Id; }

    chip::BitMask<AlarmBitmap> mask = static_cast<chip::BitMask<AlarmBitmap>>(0);

    CHIP_ERROR Encode(TLV::TLVWriter & aWriter, TLV::Tag aTag) const;

    using ResponseType = DataModel::NullObjectType;

    static constexpr bool MustUseTimedInvoke() { return false; }
};

struct DecodableType
{
public:
    static constexpr CommandId GetCommandId() { return Commands::ModifyEnabledAlarms::Id; }
    static constexpr ClusterId GetClusterId() { return Clusters::ElectricalAlarm::Id; }
    static constexpr bool kIsFabricScoped = false;

    chip::BitMask<AlarmBitmap> mask = static_cast<chip::BitMask<AlarmBitmap>>(0);

    CHIP_ERROR Decode(TLV::TLVReader & reader);
};
}; // namespace ModifyEnabledAlarms
namespace SetElectricalAlarmThresholds {
enum class Fields : uint8_t
{
    kOverVoltageThreshold    = 0,
    kUnderVoltageThreshold   = 1,
    kOverFrequencyThreshold  = 2,
    kUnderFrequencyThreshold = 3,
    kOverPowerThreshold      = 4,
    kUnderPowerThreshold     = 5,
    kOverCurrentThreshold    = 6,
    kUnderCurrentThreshold   = 7,
    kPowerImportThreshold    = 8,
    kPowerExportThreshold    = 9,
};

struct Type
{
public:
    // Use GetCommandId instead of commandId directly to avoid naming conflict with CommandIdentification in ExecutionOfACommand
    static constexpr CommandId GetCommandId() { return Commands::SetElectricalAlarmThresholds::Id; }
    static constexpr ClusterId GetClusterId() { return Clusters::ElectricalAlarm::Id; }

    Optional<int64_t> overVoltageThreshold;
    Optional<int64_t> underVoltageThreshold;
    Optional<int64_t> overFrequencyThreshold;
    Optional<int64_t> underFrequencyThreshold;
    Optional<int64_t> overPowerThreshold;
    Optional<int64_t> underPowerThreshold;
    Optional<int64_t> overCurrentThreshold;
    Optional<int64_t> underCurrentThreshold;
    Optional<int64_t> powerImportThreshold;
    Optional<int64_t> powerExportThreshold;

    CHIP_ERROR Encode(TLV::TLVWriter & aWriter, TLV::Tag aTag) const;

    using ResponseType = DataModel::NullObjectType;

    static constexpr bool MustUseTimedInvoke() { return false; }
};

struct DecodableType
{
public:
    static constexpr CommandId GetCommandId() { return Commands::SetElectricalAlarmThresholds::Id; }
    static constexpr ClusterId GetClusterId() { return Clusters::ElectricalAlarm::Id; }
    static constexpr bool kIsFabricScoped = false;

    Optional<int64_t> overVoltageThreshold;
    Optional<int64_t> underVoltageThreshold;
    Optional<int64_t> overFrequencyThreshold;
    Optional<int64_t> underFrequencyThreshold;
    Optional<int64_t> overPowerThreshold;
    Optional<int64_t> underPowerThreshold;
    Optional<int64_t> overCurrentThreshold;
    Optional<int64_t> underCurrentThreshold;
    Optional<int64_t> powerImportThreshold;
    Optional<int64_t> powerExportThreshold;

    CHIP_ERROR Decode(TLV::TLVReader & reader);
};
}; // namespace SetElectricalAlarmThresholds
} // namespace Commands
} // namespace ElectricalAlarm
} // namespace Clusters
} // namespace app
} // namespace chip
