/**
 *
 *    Copyright (c) 2020 Silicon Labs
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */
/***************************************************************************//**
 * @file
 * @brief DMP Tuning and Testing Profiles.
 *******************************************************************************
   ******************************************************************************/

#ifndef _DMP_TUNING_PROFILES_H_
#define _DMP_TUNING_PROFILES_H_

#include "app/framework/include/af.h"

#if defined(EMBER_AF_PLUGIN_DMP_TUNING_PROFILE_BLE)
#define EMBER_AF_PLUGIN_DMP_TUNING_ZB_ACTIVE_TX_PRIORITY 100
#define EMBER_AF_PLUGIN_DMP_TUNING_ZB_ACTIVE_RX_PRIORITY 255
#define EMBER_AF_PLUGIN_DMP_TUNING_ZB_BACKGROUND_RX_PRIORIY 255
#define EMBER_AF_PLUGIN_DMP_TUNING_BLE_ADVERTISEMENT_PRIORITY_MIN 175
#define EMBER_AF_PLUGIN_DMP_TUNING_BLE_ADVERTISEMENT_PRIORITY_MAX 127
#define EMBER_AF_PLUGIN_DMP_TUNING_BLE_SCAN_PRIORITY_MIN 191
#define EMBER_AF_PLUGIN_DMP_TUNING_BLE_SCAN_PRIORITY_MAX 143
#define EMBER_AF_PLUGIN_DMP_TUNING_BLE_CONNECTION_INIT_PRIORITY_MIN 55
#define EMBER_AF_PLUGIN_DMP_TUNING_BLE_CONNECTION_INIT_PRIORITY_MAX 15
#define EMBER_AF_PLUGIN_DMP_TUNING_BLE_CONNECTION_PRIORITY_MIN 135
#define EMBER_AF_PLUGIN_DMP_TUNING_BLE_CONNECTION_PRIORITY_MAX 0
#define EMBER_AF_PLUGIN_DMP_TUNING_BLE_RAIL_MAPPING_OFFSET 16
#define EMBER_AF_PLUGIN_DMP_TUNING_BLE_RAIL_MAPPING_RANGE 16
#endif // EMBER_AF_PLUGIN_DMP_TUNING_PROFILE_BLE

#if defined(EMBER_AF_PLUGIN_DMP_TUNING_PROFILE_ZIGBEE)
#define EMBER_AF_PLUGIN_DMP_TUNING_ZB_ACTIVE_TX_PRIORITY 75
#define EMBER_AF_PLUGIN_DMP_TUNING_ZB_ACTIVE_RX_PRIORITY 75
#define EMBER_AF_PLUGIN_DMP_TUNING_ZB_BACKGROUND_RX_PRIORIY 255
#define EMBER_AF_PLUGIN_DMP_TUNING_BLE_ADVERTISEMENT_PRIORITY_MIN 175
#define EMBER_AF_PLUGIN_DMP_TUNING_BLE_ADVERTISEMENT_PRIORITY_MAX 127
#define EMBER_AF_PLUGIN_DMP_TUNING_BLE_SCAN_PRIORITY_MIN 191
#define EMBER_AF_PLUGIN_DMP_TUNING_BLE_SCAN_PRIORITY_MAX 143
#define EMBER_AF_PLUGIN_DMP_TUNING_BLE_CONNECTION_INIT_PRIORITY_MIN 55
#define EMBER_AF_PLUGIN_DMP_TUNING_BLE_CONNECTION_INIT_PRIORITY_MAX 15
#define EMBER_AF_PLUGIN_DMP_TUNING_BLE_CONNECTION_PRIORITY_MIN 135
#define EMBER_AF_PLUGIN_DMP_TUNING_BLE_CONNECTION_PRIORITY_MAX 0
#define EMBER_AF_PLUGIN_DMP_TUNING_BLE_RAIL_MAPPING_OFFSET 100
#define EMBER_AF_PLUGIN_DMP_TUNING_BLE_RAIL_MAPPING_RANGE 16
#endif //EMBER_AF_PLUGIN_DMP_TUNING_PROFILE_ZIGBEE

#if defined(EMBER_AF_PLUGIN_DMP_TUNING_PROFILE_BALANCED)
#define EMBER_AF_PLUGIN_DMP_TUNING_ZB_ACTIVE_TX_PRIORITY 75
#define EMBER_AF_PLUGIN_DMP_TUNING_ZB_ACTIVE_RX_PRIORITY 75
#define EMBER_AF_PLUGIN_DMP_TUNING_ZB_BACKGROUND_RX_PRIORIY 255
#define EMBER_AF_PLUGIN_DMP_TUNING_BLE_ADVERTISEMENT_PRIORITY_MIN 175
#define EMBER_AF_PLUGIN_DMP_TUNING_BLE_ADVERTISEMENT_PRIORITY_MAX 127
#define EMBER_AF_PLUGIN_DMP_TUNING_BLE_SCAN_PRIORITY_MIN 191
#define EMBER_AF_PLUGIN_DMP_TUNING_BLE_SCAN_PRIORITY_MAX 143
#define EMBER_AF_PLUGIN_DMP_TUNING_BLE_CONNECTION_INIT_PRIORITY_MIN 55
#define EMBER_AF_PLUGIN_DMP_TUNING_BLE_CONNECTION_INIT_PRIORITY_MAX 15
#define EMBER_AF_PLUGIN_DMP_TUNING_BLE_CONNECTION_PRIORITY_MIN 135
#define EMBER_AF_PLUGIN_DMP_TUNING_BLE_CONNECTION_PRIORITY_MAX 0
#define EMBER_AF_PLUGIN_DMP_TUNING_BLE_RAIL_MAPPING_OFFSET 0
#define EMBER_AF_PLUGIN_DMP_TUNING_BLE_RAIL_MAPPING_RANGE 255
#endif //EMBER_AF_PLUGIN_DMP_TUNING_PROFILE_BALANCED

#endif // _DMP_TUNING_PROFILES_H_
