/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP
// This file is generated from clusters-Attributes.h.zapt

#pragma once

#include <app/ConcreteAttributePath.h>
#include <app/data-model/DecodableList.h>
#include <app/data-model/List.h>
#include <app/data-model/Nullable.h>
#include <app/util/basic-types.h>
#include <lib/core/TLV.h>
#include <lib/support/BitMask.h>

#include <clusters/shared/Attributes.h>
#include <clusters/shared/Enums.h>
#include <clusters/shared/Structs.h>

#include <clusters/AppleStabilityDiagnostics/AttributeIds.h>
#include <clusters/AppleStabilityDiagnostics/ClusterId.h>
#include <clusters/AppleStabilityDiagnostics/Enums.h>
#include <clusters/AppleStabilityDiagnostics/Structs.h>

namespace chip {
namespace app {
namespace Clusters {
namespace AppleStabilityDiagnostics {
namespace Attributes {

namespace AppleExpectedBootCount {
struct TypeInfo
{
    using Type             = uint16_t;
    using DecodableType    = uint16_t;
    using DecodableArgType = uint16_t;

    static constexpr ClusterId GetClusterId() { return Clusters::AppleStabilityDiagnostics::Id; }
    static constexpr AttributeId GetAttributeId() { return Attributes::AppleExpectedBootCount::Id; }
    static constexpr bool MustUseTimedWrite() { return false; }
};
} // namespace AppleExpectedBootCount
namespace AppleSystemCrashCount {
struct TypeInfo
{
    using Type             = uint16_t;
    using DecodableType    = uint16_t;
    using DecodableArgType = uint16_t;

    static constexpr ClusterId GetClusterId() { return Clusters::AppleStabilityDiagnostics::Id; }
    static constexpr AttributeId GetAttributeId() { return Attributes::AppleSystemCrashCount::Id; }
    static constexpr bool MustUseTimedWrite() { return false; }
};
} // namespace AppleSystemCrashCount
namespace AppleSystemHangCount {
struct TypeInfo
{
    using Type             = uint16_t;
    using DecodableType    = uint16_t;
    using DecodableArgType = uint16_t;

    static constexpr ClusterId GetClusterId() { return Clusters::AppleStabilityDiagnostics::Id; }
    static constexpr AttributeId GetAttributeId() { return Attributes::AppleSystemHangCount::Id; }
    static constexpr bool MustUseTimedWrite() { return false; }
};
} // namespace AppleSystemHangCount
namespace AppleLastRebootReason {
struct TypeInfo
{
    using Type          = chip::app::DataModel::Nullable<chip::app::Clusters::AppleStabilityDiagnostics::AppleBootReasonEnum>;
    using DecodableType = chip::app::DataModel::Nullable<chip::app::Clusters::AppleStabilityDiagnostics::AppleBootReasonEnum>;
    using DecodableArgType =
        const chip::app::DataModel::Nullable<chip::app::Clusters::AppleStabilityDiagnostics::AppleBootReasonEnum> &;

    static constexpr ClusterId GetClusterId() { return Clusters::AppleStabilityDiagnostics::Id; }
    static constexpr AttributeId GetAttributeId() { return Attributes::AppleLastRebootReason::Id; }
    static constexpr bool MustUseTimedWrite() { return false; }
};
} // namespace AppleLastRebootReason
namespace AppleActiveHardwareFaults {
struct TypeInfo
{
    using Type = chip::app::DataModel::Nullable<
        chip::app::DataModel::List<const chip::app::Clusters::AppleStabilityDiagnostics::AppleHardwareFaultEnum>>;
    using DecodableType = chip::app::DataModel::Nullable<
        chip::app::DataModel::DecodableList<chip::app::Clusters::AppleStabilityDiagnostics::AppleHardwareFaultEnum>>;
    using DecodableArgType = const chip::app::DataModel::Nullable<
        chip::app::DataModel::DecodableList<chip::app::Clusters::AppleStabilityDiagnostics::AppleHardwareFaultEnum>> &;

    static constexpr ClusterId GetClusterId() { return Clusters::AppleStabilityDiagnostics::Id; }
    static constexpr AttributeId GetAttributeId() { return Attributes::AppleActiveHardwareFaults::Id; }
    static constexpr bool MustUseTimedWrite() { return false; }
};
} // namespace AppleActiveHardwareFaults
namespace AppleUnspecifiedRebootCount {
struct TypeInfo
{
    using Type             = uint16_t;
    using DecodableType    = uint16_t;
    using DecodableArgType = uint16_t;

    static constexpr ClusterId GetClusterId() { return Clusters::AppleStabilityDiagnostics::Id; }
    static constexpr AttributeId GetAttributeId() { return Attributes::AppleUnspecifiedRebootCount::Id; }
    static constexpr bool MustUseTimedWrite() { return false; }
};
} // namespace AppleUnspecifiedRebootCount
namespace ApplePowerOnRebootCount {
struct TypeInfo
{
    using Type             = uint16_t;
    using DecodableType    = uint16_t;
    using DecodableArgType = uint16_t;

    static constexpr ClusterId GetClusterId() { return Clusters::AppleStabilityDiagnostics::Id; }
    static constexpr AttributeId GetAttributeId() { return Attributes::ApplePowerOnRebootCount::Id; }
    static constexpr bool MustUseTimedWrite() { return false; }
};
} // namespace ApplePowerOnRebootCount
namespace AppleBrownOutResetCount {
struct TypeInfo
{
    using Type             = uint16_t;
    using DecodableType    = uint16_t;
    using DecodableArgType = uint16_t;

    static constexpr ClusterId GetClusterId() { return Clusters::AppleStabilityDiagnostics::Id; }
    static constexpr AttributeId GetAttributeId() { return Attributes::AppleBrownOutResetCount::Id; }
    static constexpr bool MustUseTimedWrite() { return false; }
};
} // namespace AppleBrownOutResetCount
namespace AppleSoftwareWatchdogRebootCount {
struct TypeInfo
{
    using Type             = uint16_t;
    using DecodableType    = uint16_t;
    using DecodableArgType = uint16_t;

    static constexpr ClusterId GetClusterId() { return Clusters::AppleStabilityDiagnostics::Id; }
    static constexpr AttributeId GetAttributeId() { return Attributes::AppleSoftwareWatchdogRebootCount::Id; }
    static constexpr bool MustUseTimedWrite() { return false; }
};
} // namespace AppleSoftwareWatchdogRebootCount
namespace AppleHardwareWatchdogRebootCount {
struct TypeInfo
{
    using Type             = uint16_t;
    using DecodableType    = uint16_t;
    using DecodableArgType = uint16_t;

    static constexpr ClusterId GetClusterId() { return Clusters::AppleStabilityDiagnostics::Id; }
    static constexpr AttributeId GetAttributeId() { return Attributes::AppleHardwareWatchdogRebootCount::Id; }
    static constexpr bool MustUseTimedWrite() { return false; }
};
} // namespace AppleHardwareWatchdogRebootCount
namespace AppleSoftwareUpdateRebootCount {
struct TypeInfo
{
    using Type             = uint16_t;
    using DecodableType    = uint16_t;
    using DecodableArgType = uint16_t;

    static constexpr ClusterId GetClusterId() { return Clusters::AppleStabilityDiagnostics::Id; }
    static constexpr AttributeId GetAttributeId() { return Attributes::AppleSoftwareUpdateRebootCount::Id; }
    static constexpr bool MustUseTimedWrite() { return false; }
};
} // namespace AppleSoftwareUpdateRebootCount
namespace AppleSoftwareRebootCount {
struct TypeInfo
{
    using Type             = uint16_t;
    using DecodableType    = uint16_t;
    using DecodableArgType = uint16_t;

    static constexpr ClusterId GetClusterId() { return Clusters::AppleStabilityDiagnostics::Id; }
    static constexpr AttributeId GetAttributeId() { return Attributes::AppleSoftwareRebootCount::Id; }
    static constexpr bool MustUseTimedWrite() { return false; }
};
} // namespace AppleSoftwareRebootCount
namespace AppleSoftwareExceptionRebootCount {
struct TypeInfo
{
    using Type             = uint16_t;
    using DecodableType    = uint16_t;
    using DecodableArgType = uint16_t;

    static constexpr ClusterId GetClusterId() { return Clusters::AppleStabilityDiagnostics::Id; }
    static constexpr AttributeId GetAttributeId() { return Attributes::AppleSoftwareExceptionRebootCount::Id; }
    static constexpr bool MustUseTimedWrite() { return false; }
};
} // namespace AppleSoftwareExceptionRebootCount
namespace AppleHardwareFaultRebootCount {
struct TypeInfo
{
    using Type             = uint16_t;
    using DecodableType    = uint16_t;
    using DecodableArgType = uint16_t;

    static constexpr ClusterId GetClusterId() { return Clusters::AppleStabilityDiagnostics::Id; }
    static constexpr AttributeId GetAttributeId() { return Attributes::AppleHardwareFaultRebootCount::Id; }
    static constexpr bool MustUseTimedWrite() { return false; }
};
} // namespace AppleHardwareFaultRebootCount
namespace AppleStackOverflowRebootCount {
struct TypeInfo
{
    using Type             = uint16_t;
    using DecodableType    = uint16_t;
    using DecodableArgType = uint16_t;

    static constexpr ClusterId GetClusterId() { return Clusters::AppleStabilityDiagnostics::Id; }
    static constexpr AttributeId GetAttributeId() { return Attributes::AppleStackOverflowRebootCount::Id; }
    static constexpr bool MustUseTimedWrite() { return false; }
};
} // namespace AppleStackOverflowRebootCount
namespace AppleHeapOverflowRebootCount {
struct TypeInfo
{
    using Type             = uint16_t;
    using DecodableType    = uint16_t;
    using DecodableArgType = uint16_t;

    static constexpr ClusterId GetClusterId() { return Clusters::AppleStabilityDiagnostics::Id; }
    static constexpr AttributeId GetAttributeId() { return Attributes::AppleHeapOverflowRebootCount::Id; }
    static constexpr bool MustUseTimedWrite() { return false; }
};
} // namespace AppleHeapOverflowRebootCount
namespace AppleTemperatureLimitRebootCount {
struct TypeInfo
{
    using Type             = uint16_t;
    using DecodableType    = uint16_t;
    using DecodableArgType = uint16_t;

    static constexpr ClusterId GetClusterId() { return Clusters::AppleStabilityDiagnostics::Id; }
    static constexpr AttributeId GetAttributeId() { return Attributes::AppleTemperatureLimitRebootCount::Id; }
    static constexpr bool MustUseTimedWrite() { return false; }
};
} // namespace AppleTemperatureLimitRebootCount
namespace GeneratedCommandList {
struct TypeInfo : public Clusters::Globals::Attributes::GeneratedCommandList::TypeInfo
{
    static constexpr ClusterId GetClusterId() { return Clusters::AppleStabilityDiagnostics::Id; }
};
} // namespace GeneratedCommandList
namespace AcceptedCommandList {
struct TypeInfo : public Clusters::Globals::Attributes::AcceptedCommandList::TypeInfo
{
    static constexpr ClusterId GetClusterId() { return Clusters::AppleStabilityDiagnostics::Id; }
};
} // namespace AcceptedCommandList
namespace AttributeList {
struct TypeInfo : public Clusters::Globals::Attributes::AttributeList::TypeInfo
{
    static constexpr ClusterId GetClusterId() { return Clusters::AppleStabilityDiagnostics::Id; }
};
} // namespace AttributeList
namespace FeatureMap {
struct TypeInfo : public Clusters::Globals::Attributes::FeatureMap::TypeInfo
{
    static constexpr ClusterId GetClusterId() { return Clusters::AppleStabilityDiagnostics::Id; }
};
} // namespace FeatureMap
namespace ClusterRevision {
struct TypeInfo : public Clusters::Globals::Attributes::ClusterRevision::TypeInfo
{
    static constexpr ClusterId GetClusterId() { return Clusters::AppleStabilityDiagnostics::Id; }
};
} // namespace ClusterRevision

struct TypeInfo
{
    struct DecodableType
    {
        static constexpr ClusterId GetClusterId() { return Clusters::AppleStabilityDiagnostics::Id; }

        CHIP_ERROR Decode(TLV::TLVReader & reader, const ConcreteAttributePath & path);

        Attributes::AppleExpectedBootCount::TypeInfo::DecodableType appleExpectedBootCount = static_cast<uint16_t>(0);
        Attributes::AppleSystemCrashCount::TypeInfo::DecodableType appleSystemCrashCount   = static_cast<uint16_t>(0);
        Attributes::AppleSystemHangCount::TypeInfo::DecodableType appleSystemHangCount     = static_cast<uint16_t>(0);
        Attributes::AppleLastRebootReason::TypeInfo::DecodableType appleLastRebootReason;
        Attributes::AppleActiveHardwareFaults::TypeInfo::DecodableType appleActiveHardwareFaults;
        Attributes::AppleUnspecifiedRebootCount::TypeInfo::DecodableType appleUnspecifiedRebootCount = static_cast<uint16_t>(0);
        Attributes::ApplePowerOnRebootCount::TypeInfo::DecodableType applePowerOnRebootCount         = static_cast<uint16_t>(0);
        Attributes::AppleBrownOutResetCount::TypeInfo::DecodableType appleBrownOutResetCount         = static_cast<uint16_t>(0);
        Attributes::AppleSoftwareWatchdogRebootCount::TypeInfo::DecodableType appleSoftwareWatchdogRebootCount =
            static_cast<uint16_t>(0);
        Attributes::AppleHardwareWatchdogRebootCount::TypeInfo::DecodableType appleHardwareWatchdogRebootCount =
            static_cast<uint16_t>(0);
        Attributes::AppleSoftwareUpdateRebootCount::TypeInfo::DecodableType appleSoftwareUpdateRebootCount =
            static_cast<uint16_t>(0);
        Attributes::AppleSoftwareRebootCount::TypeInfo::DecodableType appleSoftwareRebootCount = static_cast<uint16_t>(0);
        Attributes::AppleSoftwareExceptionRebootCount::TypeInfo::DecodableType appleSoftwareExceptionRebootCount =
            static_cast<uint16_t>(0);
        Attributes::AppleHardwareFaultRebootCount::TypeInfo::DecodableType appleHardwareFaultRebootCount = static_cast<uint16_t>(0);
        Attributes::AppleStackOverflowRebootCount::TypeInfo::DecodableType appleStackOverflowRebootCount = static_cast<uint16_t>(0);
        Attributes::AppleHeapOverflowRebootCount::TypeInfo::DecodableType appleHeapOverflowRebootCount   = static_cast<uint16_t>(0);
        Attributes::AppleTemperatureLimitRebootCount::TypeInfo::DecodableType appleTemperatureLimitRebootCount =
            static_cast<uint16_t>(0);
        Attributes::GeneratedCommandList::TypeInfo::DecodableType generatedCommandList;
        Attributes::AcceptedCommandList::TypeInfo::DecodableType acceptedCommandList;
        Attributes::AttributeList::TypeInfo::DecodableType attributeList;
        Attributes::FeatureMap::TypeInfo::DecodableType featureMap           = static_cast<uint32_t>(0);
        Attributes::ClusterRevision::TypeInfo::DecodableType clusterRevision = static_cast<uint16_t>(0);
    };
};
} // namespace Attributes
} // namespace AppleStabilityDiagnostics
} // namespace Clusters
} // namespace app
} // namespace chip
