set(SDK_PATH "/Volumes/Resources/git/matter/stash/third_party/silabs/gecko_sdk")
set(COPIED_SDK_PATH "gecko_sdk_4.4.0")

add_library(slc_generator OBJECT
    "${SDK_PATH}/../../../examples/platform/silabs/provision/AttestationKeyPSA.cpp"
    "${SDK_PATH}/../../../examples/platform/silabs/provision/ProvisionChannelRTT.cpp"
    "${SDK_PATH}/../../../examples/platform/silabs/provision/ProvisionEncoder.cpp"
    "${SDK_PATH}/../../../examples/platform/silabs/provision/ProvisionManager.cpp"
    "${SDK_PATH}/../../../examples/platform/silabs/provision/ProvisionProtocolV1.cpp"
    "${SDK_PATH}/../../../examples/platform/silabs/provision/ProvisionProtocolV2.cpp"
    "${SDK_PATH}/../../../examples/platform/silabs/provision/ProvisionStorage.cpp"
    "${SDK_PATH}/../../../examples/platform/silabs/provision/ProvisionStorageCustom.cpp"
    "${SDK_PATH}/../../../examples/platform/silabs/provision/ProvisionStorageDefault.cpp"
    "${SDK_PATH}/../../../src/crypto/CHIPCryptoPALPSA.cpp"
    "${SDK_PATH}/../../../src/lib/support/Base64.cpp"
    "${SDK_PATH}/../../../src/lib/support/BytesToHex.cpp"
    "${SDK_PATH}/../../../src/lib/support/logging/TextOnlyLogging.cpp"
    "${SDK_PATH}/../../../src/platform/silabs/Logging.cpp"
    "${SDK_PATH}/../../../src/platform/silabs/SilabsConfig.cpp"
    "${SDK_PATH}/../../../src/setup_payload/Base38Encode.cpp"
    "${SDK_PATH}/platform/bootloader/app_properties/app_properties.c"
    "${SDK_PATH}/platform/CMSIS/RTOS2/Source/os_systick.c"
    "${SDK_PATH}/platform/common/src/sl_assert.c"
    "${SDK_PATH}/platform/common/src/sl_syscalls.c"
    "${SDK_PATH}/platform/common/src/sli_cmsis_os2_ext_task_register.c"
    "${SDK_PATH}/platform/common/toolchain/src/sl_memory.c"
    "${SDK_PATH}/platform/Device/SiliconLabs/EFR32MG12P/Source/startup_efr32mg12p.c"
    "${SDK_PATH}/platform/Device/SiliconLabs/EFR32MG12P/Source/system_efr32mg12p.c"
    "${SDK_PATH}/platform/emdrv/nvm3/src/nvm3_default_common_linker.c"
    "${SDK_PATH}/platform/emdrv/nvm3/src/nvm3_hal_flash.c"
    "${SDK_PATH}/platform/emdrv/nvm3/src/nvm3_lock.c"
    "${SDK_PATH}/platform/emlib/src/em_cmu.c"
    "${SDK_PATH}/platform/emlib/src/em_core.c"
    "${SDK_PATH}/platform/emlib/src/em_crypto.c"
    "${SDK_PATH}/platform/emlib/src/em_emu.c"
    "${SDK_PATH}/platform/emlib/src/em_gpio.c"
    "${SDK_PATH}/platform/emlib/src/em_msc.c"
    "${SDK_PATH}/platform/emlib/src/em_rtcc.c"
    "${SDK_PATH}/platform/emlib/src/em_system.c"
    "${SDK_PATH}/platform/emlib/src/em_timer.c"
    "${SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/src/crypto_aes.c"
    "${SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/src/crypto_ecp.c"
    "${SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/src/error.c"
    "${SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/src/mbedtls_sha.c"
    "${SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/src/sl_entropy_hardware.c"
    "${SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/src/sl_mbedtls.c"
    "${SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/src/sl_psa_crypto.c"
    "${SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/src/sli_psa_crypto.c"
    "${SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/crypto_management.c"
    "${SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sl_psa_its_nvm3.c"
    "${SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_crypto_transparent_driver_aead.c"
    "${SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_crypto_transparent_driver_cipher.c"
    "${SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_crypto_transparent_driver_hash.c"
    "${SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_crypto_transparent_driver_mac.c"
    "${SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_crypto_trng_driver.c"
    "${SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_psa_driver_common.c"
    "${SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_psa_driver_init.c"
    "${SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_psa_trng.c"
    "${SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_se_version_dependencies.c"
    "${SDK_PATH}/platform/service/device_init/src/sl_device_init_dcdc_s1.c"
    "${SDK_PATH}/platform/service/device_init/src/sl_device_init_emu_s1.c"
    "${SDK_PATH}/platform/service/device_init/src/sl_device_init_nvic.c"
    "${SDK_PATH}/platform/service/iostream/src/sl_iostream.c"
    "${SDK_PATH}/platform/service/iostream/src/sl_iostream_rtt.c"
    "${SDK_PATH}/platform/service/sleeptimer/src/sl_sleeptimer.c"
    "${SDK_PATH}/platform/service/sleeptimer/src/sl_sleeptimer_hal_rtcc.c"
    "${SDK_PATH}/platform/service/sleeptimer/src/sl_sleeptimer_hal_timer.c"
    "${SDK_PATH}/platform/service/system/src/sl_system_init.c"
    "${SDK_PATH}/platform/service/system/src/sl_system_kernel.c"
    "${SDK_PATH}/util/silicon_labs/silabs_core/memory_manager/sl_malloc.c"
    "${SDK_PATH}/util/third_party/freertos/cmsis/Source/cmsis_os2.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/croutine.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/event_groups.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/list.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/portable/GCC/ARM_CM4F/port.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/portable/MemMang/heap_4.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/queue.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/stream_buffer.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/tasks.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/timers.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/aes.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/asn1parse.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/asn1write.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/base64.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/bignum.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/bignum_core.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/bignum_mod.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/bignum_mod_raw.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/cipher.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/cipher_wrap.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/constant_time.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/ctr_drbg.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/ecdsa.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/ecp.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/ecp_curves.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/ecp_curves_new.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/entropy.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/entropy_poll.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/hmac_drbg.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/md.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/oid.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/pem.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/pk.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/pk_wrap.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/pkcs5.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/pkparse.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/pkwrite.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/platform.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/platform_util.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/psa_crypto.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_aead.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_cipher.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_client.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_driver_wrappers_no_static.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_ecp.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_ffdh.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_hash.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_mac.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_pake.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_rsa.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_se.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_slot_management.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_storage.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/psa_util.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/sha256.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/threading.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/x509.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/x509_create.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/x509_crl.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/x509_crt.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/x509_csr.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/x509write.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/x509write_crt.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/x509write_csr.c"
    "${SDK_PATH}/util/third_party/segger/systemview/SEGGER/SEGGER_RTT.c"
    "../../../generator/app.cpp"
    "../../../generator/main.cpp"
    "../../../generator/nvm3.c"
    "../autogen/sl_device_init_clocks.c"
    "../autogen/sl_event_handler.c"
    "../autogen/sl_iostream_handles.c"
)

target_include_directories(slc_generator PUBLIC
   "../config"
   "../autogen"
   "../../../generator"
    "${SDK_PATH}/../../../examples"
    "${SDK_PATH}/../../../examples/platform/silabs"
    "${SDK_PATH}/../../../src"
    "${SDK_PATH}/../../../src/include"
    "${SDK_PATH}/../../../zzz_generated/app-common"
    "${SDK_PATH}/../../nlassert/repo/include"
    "${SDK_PATH}/../../nlio/repo/include"
    "${SDK_PATH}/platform/bootloader"
    "${SDK_PATH}/protocol/bluetooth/config"
    "${SDK_PATH}/platform/Device/SiliconLabs/EFR32MG12P/Include"
    "${SDK_PATH}/platform/common/inc"
    "${SDK_PATH}/platform/CMSIS/Core/Include"
    "${SDK_PATH}/platform/CMSIS/RTOS2/Include"
    "${SDK_PATH}/platform/service/device_init/inc"
    "${SDK_PATH}/platform/emdrv/common/inc"
    "${SDK_PATH}/platform/emlib/inc"
    "${SDK_PATH}/util/third_party/freertos/cmsis/Include"
    "${SDK_PATH}/util/third_party/freertos/kernel/include"
    "${SDK_PATH}/util/third_party/freertos/kernel/portable/GCC/ARM_CM4F"
    "${SDK_PATH}/platform/service/iostream/inc"
    "${SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/config"
    "${SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/config/preset"
    "${SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/inc"
    "${SDK_PATH}/util/third_party/mbedtls/include"
    "${SDK_PATH}/util/third_party/mbedtls/library"
    "${SDK_PATH}/platform/emdrv/nvm3/inc"
    "${SDK_PATH}/platform/security/sl_component/sl_psa_driver/inc"
    "${SDK_PATH}/util/third_party/segger/systemview/SEGGER"
    "${SDK_PATH}/util/silicon_labs/silabs_core/memory_manager"
    "${SDK_PATH}/platform/common/toolchain/inc"
    "${SDK_PATH}/platform/service/system/inc"
    "${SDK_PATH}/platform/service/sleeptimer/inc"
)

target_compile_definitions(slc_generator PUBLIC
    CHIP_CONFIG_SHA256_CONTEXT_SIZE=256
    CHIP_SYSTEM_CONFIG_USE_SOCKETS=1
    SILABS_PROVISION_PROTOCOL_V1=1
    SL_PROVISION_CHANNEL_ENABLED=1
    EFR32MG12P232F512GM68=1
    SL_APP_PROPERTIES=1
    configNUM_SDK_THREAD_LOCAL_STORAGE_POINTERS=2
    SL_COMPONENT_CATALOG_PRESENT=1
    MBEDTLS_CONFIG_FILE=<sl_mbedtls_config.h>
    MBEDTLS_PSA_CRYPTO_CONFIG_FILE=<psa_crypto_config.h>
    RTT_USE_ASM=0
    SEGGER_RTT_SECTION="SEGGER_RTT"
)

target_link_libraries(slc_generator PUBLIC
    "-Wl,--start-group"
    "stdc++"
    "gcc"
    "c"
    "m"
    "nosys"
   "${SDK_PATH}/platform/emdrv/nvm3/lib/libnvm3_CM4_gcc.a"
    "-Wl,--end-group"
)
target_compile_options(slc_generator PUBLIC
    $<$<COMPILE_LANGUAGE:C>:-mcpu=cortex-m4>
    $<$<COMPILE_LANGUAGE:C>:-mthumb>
    $<$<COMPILE_LANGUAGE:C>:-mfpu=fpv4-sp-d16>
    $<$<COMPILE_LANGUAGE:C>:-mfloat-abi=softfp>
    $<$<COMPILE_LANGUAGE:C>:-Wall>
    $<$<COMPILE_LANGUAGE:C>:-Wextra>
    $<$<COMPILE_LANGUAGE:C>:-Og>
    $<$<COMPILE_LANGUAGE:C>:-fdata-sections>
    $<$<COMPILE_LANGUAGE:C>:-ffunction-sections>
    $<$<COMPILE_LANGUAGE:C>:-fomit-frame-pointer>
    $<$<COMPILE_LANGUAGE:C>:-imacros sl_gcc_preinclude.h>
    $<$<COMPILE_LANGUAGE:C>:-Wno-unused-parameter>
    $<$<COMPILE_LANGUAGE:C>:--specs=nano.specs>
    $<$<COMPILE_LANGUAGE:C>:-g>
    $<$<COMPILE_LANGUAGE:CXX>:-mcpu=cortex-m4>
    $<$<COMPILE_LANGUAGE:CXX>:-mthumb>
    $<$<COMPILE_LANGUAGE:CXX>:-mfpu=fpv4-sp-d16>
    $<$<COMPILE_LANGUAGE:CXX>:-mfloat-abi=softfp>
    $<$<COMPILE_LANGUAGE:CXX>:-fno-rtti>
    $<$<COMPILE_LANGUAGE:CXX>:-fno-exceptions>
    $<$<COMPILE_LANGUAGE:CXX>:-Wall>
    $<$<COMPILE_LANGUAGE:CXX>:-Wextra>
    $<$<COMPILE_LANGUAGE:CXX>:-Og>
    $<$<COMPILE_LANGUAGE:CXX>:-fdata-sections>
    $<$<COMPILE_LANGUAGE:CXX>:-ffunction-sections>
    $<$<COMPILE_LANGUAGE:CXX>:-fomit-frame-pointer>
    $<$<COMPILE_LANGUAGE:CXX>:-imacros sl_gcc_preinclude.h>
    $<$<COMPILE_LANGUAGE:CXX>:-Wno-unused-parameter>
    $<$<COMPILE_LANGUAGE:CXX>:--specs=nano.specs>
    $<$<COMPILE_LANGUAGE:CXX>:-g>
    $<$<COMPILE_LANGUAGE:ASM>:-mcpu=cortex-m4>
    $<$<COMPILE_LANGUAGE:ASM>:-mthumb>
    $<$<COMPILE_LANGUAGE:ASM>:-mfpu=fpv4-sp-d16>
    $<$<COMPILE_LANGUAGE:ASM>:-mfloat-abi=softfp>
    $<$<COMPILE_LANGUAGE:ASM>:-imacros sl_gcc_preinclude.h>
    $<$<COMPILE_LANGUAGE:ASM>:-x assembler-with-cpp>
)
set_property(TARGET slc_generator PROPERTY C_STANDARD 99)
set_property(TARGET slc_generator PROPERTY CXX_STANDARD 17)
set_property(TARGET slc_generator PROPERTY CXX_EXTENSIONS OFF)

target_link_options(slc_generator INTERFACE
    -mcpu=cortex-m4
    -mthumb
    -mfpu=fpv4-sp-d16
    -mfloat-abi=softfp
    -T${CMAKE_CURRENT_LIST_DIR}/../autogen/linkerfile.ld
    --specs=nano.specs
    -Xlinker -Map=$<TARGET_FILE_DIR:generator>/generator.map
    -Wl,--gc-sections
    -Wl,--no-warn-rwx-segments
)

# BEGIN_SIMPLICITY_STUDIO_METADATA=eJztnQtv3Eaarv9KICwOds9aYtS2k4w3mYEjy452rEhQK5mds14QJbK6mxFvUyRlK4P576eKLJLFa93JHmAXs7G6m/V+z1c31r3+fnJ7d/Oflxf37t3Nzf3Jm5O/fzq5u/z49v7q10uX/enTyZtPJ2dnn07+cfKiCbO9+eXu4nKLg33/py9R+NUTRFmQxD98Ojk/+/rTyVcw9hI/iPf4i1/u359+9+nkT3/8FH+fouQ36OVf4SBx9iZKfBjiJw55nr5xnM+fP59lQQgesjMviZwsc7Z54QfJGfQSBLEoDp1ClD9vPfwvDkfVPp1g6a+++n6XhD5EX8UgIj96SbwL9vQ38msQwvq3LHQjGCXo2a2eOjtg9QIF+Cfy2Bvn1yQsIpg5dzBLCuThv/ZB7kQgzyFyshxkBwcbfwqIz05WpGmCcgfu0MtNtD/fOJWqM2bGGePZXn74cHnn3t3fuxf4SUs4I1ZGaeKn6KXrwx0owtxuBE1YGqVKM+B66DnNE7tMo3ZGiXDy+vAp8KAbxEHu+p7vWc9PMwZHGd8jCO/ub7YXNrmGRqbiKwshTPMggsh6TI2aGuUCaerSqiWAmV2wSVsiOQxGxaIZrGtvlBBGYfDgkvoZh3wo9nb5ZqxNxV/0AP08tJyqo3Z4RDSmlwIbmKv4vneq1+bYKxQUebKH8eQ7FGfmMPBAjhHc/DmFpp2g9p0JU6MRfHd/id9uUZrEMM4zW0RDK1Op7dVPuZgehInxlGYiadSWSMXihYn3iFtd1sjGjU2hwSfiwwHEfgiRxfga2BEDshdNAztTQEGS5QiCiD5rLZ9PmBLGshdVY6a4WGX+C2JsKPaWibShxQnIoPcGcamaPcg5i6KQOQJxtktQtALuqO1J8LJZv1jMjlubhXsogjAP4oUhp62OwoZB/AgR+eYs9O2Q9UyMYpx5qOn54D/tgAyM8BtMe+g9Jm7mP7qvzl6RcZAGvvNYGoKcZNzm98ET78r3JfP74IltgNtDSfwRPGSdxwYPXr6/e7m5/nC+ue09N5QsY2vwVD+/5gDlReo2EZaq1PL5IUC+m2KpZ6ca83GayHPq+HGqaHAYX53WHafidcaBHI4Xz1kOoyNyYoyn70Mn600m41XshYXPTcfW1OblZvf6fLOPvvlOpboxEQuU2ZmE4iRnG84FXpQejxsNjoQDvndM/BWNBP7OTXGD55hcaInk3MDvhWPzo0YSd8SLiiPygdJI4KPnpBzFOyYnWCYpV9I8OS4/KJCEE5lao9SWC1m3tcp3gAxFxLtjSgaGSMKNCOCAmYcCnITHVDiGYFJOIfi343KGAok7AY+qwoWyFS7Mo2PCr2jE8XdpAQ9H5EDDI+7CPsXdzSNyoeGRcSE4phq2xpFzwD2mfkQLJO5EsDmmbERpJPB9cFT8FEfcgRC/Po7IgRpHzgHXO6bqlCGScAPiVmKmND1py42WSNoN96FQWiFk15WaSt6d48pfHSh5Z7L8CJ2poGScObYeN0Mk40aBOY7KixpI3IkoO6Z3IKURx0+9+JhSoMaRcAAd0xAgpZHCP64KtgWScyIL9jEIjywtWCpxd9BRDRAg2QEClEQ5eAiPqTnFIkk4knvHVLfWOHIOuEfng6vkBoLH9J5gkcQdyY6qYGeyBfvYGn0KTT663vuYigSLJOEIipVWitpyguKIO1Bkx9X2bnjEXXg6rvGnJ+nxJxLCTdJjGoNikcQd+eyrrZu25ESNI+cA7nwcU0OcReI5EtEF3KvjsyDSK7xWhh8FElriNfLl4KvhF/3tkFGUxHMrCoPYG6wk7K6jBnkSBRarxIrRwSBOx5ozS+VFWZC5SbZxq/BL8Y3ZnSUNmCDwS+5iy4+4kbkPcL6w2O7qUHMZ5uMaxoXF2eFu/Na25olAlkGbDY1enmyscfLksjlRLP+52EJeWBxC6VK11py5imtQD2WIUw/N52Fr63ipdxiPW44Ga3cncu0yrIw1Tv54zjwQhkrbdlS4WHtyeSRPktA7gCCeX/s+zEpTBwFYd7khrp1v7Tq8l73Aq3rygAOSJxeoiVr3aOkfmB+0dMbTYSVQEcK957kpgkHVnluedGifm3Okm4kPSZKHCcDfzDUVu7vY52rr7pP2SlnL3dti7wwJZqsaXgRdXG+vtnNxc1GeVTJXeqc2aHQirnq9kB29geImWLGIK/1xCHTTURmani0Z1eP0AJgVQBnLs5z572Q3V47f1otCds0KxOTe5vDlZCzux0cou3zk4AUverUsHmN0li5KCxeg6OnbRfE6VuXr40HlQM5R2RirP3Dz1HZslMC9zETNziZXkrl54D0ui8cYlW91TeyP7HtFxnmIDWvvOtYxun2wa9Z8swD3H3gbUpkjHuazr0jjdeS8CGv5hPrmMDbrFtc4Bq+d2D+jaXX0GkIG3OouBkHuib0Lc9jxk80BSkHuGkK+ihHpsA6OAMvO7dU1Yx7TDuwEh2QmOwb6FkM6q62NXkMYaHnUZ5boD6nUSvZjp7ZURw1rmZeWzRktKLc4Escjra3bGQRq4sN6ldj4R+tD1rJUSqxGWls3UJSqqT79gkSnDElJt59DK2PM2CxrmpeE9PFHiGIYrsTaGrdTmNgosZ5LqYf1XErXtFxqrMPaGjdRoJrDPA0UqkZrgXza2Gryasc6NyHbQ0wPIKyWiK4K3cGQpD+COO9ycPiDXsAFClIffQzBUuXW5ssl3azrjI51iXRZAbZv3vxoC4x89DQ31jKymEc+0aGX2JzFKp1glwQ09gy8D8jB4Zrus2eP244FYquMg77R2ZxOHl6UTIjI3cMYIpujLGNxxhjlE1qtq8foRmvmCTJ3F2Jji/O1ZvmUZKRzWcDaooURs94dA6Q6cqszJu01RRgXyXt8HkEm1yxK3DErmGsWBawtyueaMHiYzzX4gdLExfWrcmoULOAXtumM2LXRvuj7L7cUGPfuvENgcUF1CVg1GlpTM2vXyFM25yu6PGOzEiM45QoKYLVt0aViDHLWIS8XX11r83FmeylvJ76EVvLi5x5sLpjtED0MF8uO5CvLC4u7eUpkXTF+DoFoV8RWW4QMFWNtHsv6kqQO1uQypGESIqvdrk4CorEe1wjQEq36Hth0m34AaPngzC7axKGY41ALV/J9m/OIVufwO2CjM/V9HLuHwnV4xg986wNZPVulwzN6bsoIzrLZqWuQU8dbPSyhW8GPHoTQB6qmGRZCao2JQC1cmQ6NzkNaHjjtsI2OkmrvAaItSoudTeIC6We2lgRe6gvxUFNC78yFkBpj/BfSMkRQJNHKt8QyPLUp/gtpGR5qSaDOX4ZnfEpxos5fBqk1JlKdLsM0OnWpsJrXw6j589wQEHudHGfOvb1jkF6mw7topnc170TUslc+Ac+DIUTl/X82p/yqeOncpecM/WtvV5wm5J1OwARNojhIETmr0eq6EnXfeoACrpGrpY43zcbohA5iEJp9GM6tYyKUpM/uASD/M7DZUBCODboyYoyMdxgIQonVVRwSHjQs3CxZBz8S8C4Qh572+oHN/ZNS9F0gMXroWbxiS4WeAnHoG4EDOBL8HhE/57cXmh+JBwMmwRfKkTnRh1J7g4ytU5muvdZ/jda75lsgTurhWsIFNpfYSKEzNLx6y4uOiJuh4XFHwDsmcAaHV84P4PyIyFkcPvnm9TfHxc4A8elfn2+Oi54B4tDvj6qc7oXLaX5AEPhBvD8i+gGTVOviOHwYMMm1Lo7FiT6UWEo8gbBQu9jcXkq0TKqHHY4NORFlHwVPgx0han30KrrLY26Xb1+2vnSaljWNQAamfRoSgiodhxvjXIIlsgpgffebXKL0oORcoQtqjs2ZFkvAnQzWS11cH6Yw9mHsWT3aScapGTixYYoIxGAPIzLSubpDo0gylQGIM8yCAzYJHaSHo6saZii1nD1YXTBtxtWaUctR3MM6dj8popabADdNj93PmlGstRbkmVvuuzkCrwZAZoezOg9hUyMP9eIoiLGzMdmuiYosh76b5QnCFeEKjVsmski7Fn905uiGiT+Sz4/bPR4h18VqZuYofGlQRgrleJ4Wa2Cv7tw0l1Kr9Cj8GcWSc2cHQV6gVXrB8w6xYBoN7aNwawZOuqG9ukOjSGptFbIzgSwpOJJk4hGqOZk/p8eSD+foVIebeOup+h+7jZsiD0KmddM/uLyNgbnVVzsEIcqT4dHK3XVU5LBN3vDXxKmVg1mj+txO021REh+dJ2rfqrNC6xMsOwBqbc+pc1F7rtb2rRyOyvO2Poi0D8EpiM3juDQk5je3S1M3GMaGdKvjgniZmYwtk4se+X2MDxcXE32MzmNv767JXtv3o8/2EoEYX7B4VDHi1C472COnxnVqlrGG+Ag27n8j83MbGuwN0GhPYrJZPt1e76TqNYyuQTy2wrQXNwcIUvfViolKSZ0WRLiXItwhF6kULV3txI0IiudMXfY0AMXZBovG5vvJwqgsAQcWN40R9ADpPPtwR+YMrDQNhdGneXiLPp9Iy2qPPU9XxO9TcKDfYxlySvZ6wCwBBzYMMvM9IWHQ2jpvNSTMMtxFch+K3c7CCIgw7pCDB54W5BKQPLHTdREHH3AIgH9GIE2hhXvopbBZCg50/XZbD5gl4MGi5DdcGa4YuywBB/ZvBSxWjNbGPG/cAEbpYcX6obXPA82B9+iWjdEVM0CfggO9JY9fr8zcg+DGc3nC8trvjQEGb40eyMwfhCZMW1vnQZI9gSvmhNa+8LDNWHt+8T4Ya3n2dLNOs3NxzL71WdSyHbc4Ym11Fq16dyzO1pidP1S2UzEsDjkwPwtL6oUVMmJjdh6uqg2Wp2vsGjhelq5mnR99D4MHBNDz/DmCNjbtDeKC4jqUyJnYmNcFy+JzHDpboEgO8FjTXMjPKMhXgmxMz0I+gAx+s8AYYp+wtTuLZ2nNHxdvehXfCF7Zu1yLsTE+3wqwsIGVCzixSbUP5noFelqjpunaFsR0Y/h5TdTaPgfXz8xv+RWgpGZn4SLzCyG5ZNHowsZuTRjs48L88Sz8mrCxK4Bn56gmQcaJw5vGQaNkhWTu2hbEdBFYoUQP7c/iJsEK0UmNzoKlFo404oKlY0cb9cEevez1Cmi1WQ7cGmQCWCu1qhnDHMCVWtSMYQ7gSq1BxvB806A6NGeFxkFrWATQTZPQ/F1sopSN9fnmf45cHz2Y33XJb/szlmcRD+QEg3UYO6bnB7DKDf/LE7Z255M5ibE1sjgziFaoegbm54ew6l3wy4N2TM/XknS17ArVJGNZCNElkutxNubnYTOwFidjeX40LMQNXisr5vmjYazp+U5B7EbFAitUB52Bxq7AYF2zt2kFziGAcKd1ediucdFO61qc1LZMp3VF1Nq+BC7ONk8gC57WywpjIMLju4tD94xzmihWdsEJtE2mtrlNt6DcIEpXqLvGGWSwV6t2pzm4g9bNPlgb5zQJDVv3CQSQ16om+tbF+6nLo/aszy+siJJ8gTU2fcbGLGc6gGyNW56utcvDW6f6ZwzPA6aZrU3QfMaObS6mnX31QpST++gHkKQPu8QyvzHK1jYXM0fAW6GK7Jie75MC38pVrPwuaWuYN1S73iu9Z1xoTHkNSKEqqB4cXwGwMSw0PrJmgo8hzEIjctB/mLsHGC6zgaKPPAIwP4ybha4PH4r9esijCFxoLwxWGZjq2uZiRoGFK9+EIGvLXEQc8Pzlii34cQZB7Ef4vFKW7dqfxf3y+us/LD/MW1vlorkebsOsMUHbMy4CusJwOWtZBHGB9fATiPw18dWD2QqrM1nLXMSVFgx0TItBrpfeHfOisGulfMc8t9lX3zpbvWZXmR8bIAhCr0krE7dWzraUidmpgysnM8NKq8pHEUSh6Tls9U5mN8ZGc5AH5o9PlfFjlkrUtSxMcpuHF8s4NMIi7AY9YnJV/JZBFHuVvQFD+6K4u51v/mRkGd4aQBTYylHOMsBT5zRPAds4klmGd+K85SncFDyuW+ZqAFFgtMbejKF94Wpt5RqNH7feASs3b9byqswVJmnHIaQaUauMSvYAJBtRayK3CMLQq6xEGgGQAV5tem+aQ7HRuqoLIyz6be8jcqhLJdP6W9MJal+q9bcmbw0g1fpbE7gGEAVeb/B+AkIYfI01LkP7Mq3sNXGpfalW9pq8NYBwKxvEfhKttNhwmkOmk7AqtsDaqG4rfU3aTCpr9Md4ViUfssiON62KP3Wtisix2VPH+wodaDOIGbDE2Zh1VDSHS9LPQOhATICCBUv1gJFa50Fm8fmKkNS6AOTCi47GSCeXH40fs7Maa2ufB1qdRrEeaGOfB1oEoY/bibsFToafhO0wcIA9/E8Yrln+WQIerLdiHqDGeYgHgP+3+XpFToZACDZNwue1cWsGLnA5mrnwWOoQuUvBg154SHKAOzke2QddtPM3wJzo+g33lKUgP92cfVkRtcPABSb5xAX+b0WWuyHcA+/Z1s3oEh7MQqm4tEO4P7nonhkhp1gsKbdId6IMXAkdi1sjWNJuZQUZmYX5Ebo2giblXpYtOK4y7w5FkcIvV7QeCX/NIubAMZR84WLOnFyyJnMXg4ddH66zHjFDwIEtdzusR9qY52KuODjjCw3O+IcV+zzUOAcRekvOfvUZa+t8yDVrqMY8F/O3Zec0hqC/Tc1pDHfFr4k5OkE7cazcepgtAA912V3IA9CZG71ZzP2aQzB7oSGYw6O/W4+xts6DbI6hW4+UReDghtGKL0pqnINIn159dGjIwQNfcIXdAHZ0cd0A8PWahK9FEGGUoGd624cLwjBZcSRrAobjQow7vVniPcIlF4z00XsQPOQAdxMfFzzxa4DbAnBQyaHRq2FS4xxEcnz0aojUOA9xwYMzBoQiF3eRc67PF7iCfBqyti8AumKt2pgXwPx2XcxvRTDr81PXI2UIBGFXHn8aYIhilwerro9dY/Cwk/D5/OXXa5Y1hoAHi4InkEMXeJhnxWbAkIMHXh+4ux4yQ8CBRQF+2/nn36w4Sd9B4OGuOW41seCyf1rJAay4OKu2zock56qviUnt80Ffror5Ugzy9ZotrdY+D3TNGUGxOcDyxCXgHVZsDXQQRHDLRSVZEeRrTqGMkYjAJ8ljsHZkNwwCwHlAuuTrArcMHOD2woXVeDsIPNwgWpe1sc8BfcK5PFhyw2WflAHgoK67jEFw4UJz6tWqoDWBGOyKdQBLIASbrTidxRIMNq5MXaHe2d6B+xO8rR1rLeLDaI74Wj26j75a0wMKsrk1Bg8hXGE8tAWf4pFyhq76eYTP2F6A3Pw5XaMxMvRqEkzFvew5TuLnNebfJh1jkY54QwThl9sMUTlLwuRBTA4WSJNsnRYuE/fjOHKupAi3MvLg6Uhc6eLIuUJKFa6nyQDVKq2hEXeGSGIuVevIV3WhRRBFXmd2vYMsuvGicyDF0seVjJAPSCQdiHP4Jc+OpV6ax1Jz7YgKNx9NzcUjqYrnscRcwwHRCmPTjBcNgRjwWvsdGGLxfQ30gInVpjYZaInZzeboA5rDVuXuUAiCB7+vXDIbAkHgHBXeuo2IFkEMef2OmmSP7AmExcrELYLQeMbIl2Nfdcc8MrjfQ9Qb9ug/85zlMHoK4GfeARnbyw8fLu94gyjVU+7d/b398xwr/5zWBaey7nQhOHmieth+ZuDQCuRexq21aWsIY5l3+EUvnwZhgBs3LuHu5MHhc/iJ8iTB+YxPV3VWh+L0C0l/zibEz5XrPq3kadY3h3HA6TI6HYzZ83vaJ61kFHngQVZRyBOdj90PrO8gTc+8NJX3O0XJU0BmRLC7MUQgT5DTiDlDQxEIYnOWWrURU/FT9FIl740ZqrVGzBBvFTLMVMQdRo28xSHLEyST+M9QqfEOv4AoDWG7eKzOpi3I0AiX5Hb7Vi01pXEaSyNMt3WYiwOIY6g0myUANGZGgKZ8o1qKo0lbc1yXsZcoXqQog8SYEaGxHkUdQ3NE11VNbDt+GDMiNNbjp2Nojgj/kSdeYr2YsXZEeH49tx9JfVtCXJsFuTZ8rq366YQySNv+AYSzNB/IW1Dt2GYFKMaaSExZT76OIQGiiyLLk2gxLtacAN07uANFmC+G17E3wvej8hl/GfLI2ZpOVqRpgnLnx95pfWNmlLyeMDTp0TNuG90nP0GlE6AGxjpq8+bMeNfTGzF58dPV7cdkv1dcl9a3GFZSTk92xPA9/JLfxOFz/ZQRh2vzo+IjENsyy18oTzQS+/3y09fkmVV2fNbwlMfa0d23yotikhMuynHF27cflfsxxHI1OumMC07UEy+/q5qjqombwbxI3RQ8hwnwnb4iz6iyqzNmWW+r6ekClZ23moDW0tgwTh8Ydr4hAycX5TR88BCEQf5Mhgq84gyg6Azu0MvNWbQ/31R/kr/SzcvN7vX5Zh998x0OnidJ6B1AEPc18G+Z/9j/1sPvsiqXnOFfz7B7Hv4vOXXrzauzV2dfn7mn59+9fPXd5tXrV6+bUa7vI+xm+MaHmYeClHj2x++d4XfVQEsnBvB335PX12/Qy/HfJy9OtlfXtx+vLq7u/+pu7395d3XjXt+8++Xj5fbkzcl//71aMpQH8eWXcgw8+3Ty5r//58WnEwSj5An6+OMOhBl80Ty4rRKNPFefRuW8RxDe3d9s2xL/ovmtHZB0yc/dH0GKkxglODryALKb+NtHYIRrt+rqkepS57GHyKAJ/rlM49EHOreYDH8ub4x+CjzoBnGQu77neyLPwaiYemx4LsHoz1Rt6qlqvG7i1yyEMCXbCRHzBEk7nFOKEOIU+nTyPc0Lb66vyy+/+hKFcfaGfvvDp0+fTg55nr5xnM+fP9c5FWdaJ8tI24c8dAbL0Vr85Fc0C5TBclRUXwZ++bnwziq7Z2XJPSs8mhuaQaezveeVIVI/6kj88VOZk8tpGNLWynAhJbVBZejs/5L/OuShJmvX7vyxjBKKhR0miv94oZuryTJJTO3c3V+6pEAnMYyrHfov2h/DIH6EiFRpZ6Hf+QUnDc7XYeCVJbKc/OqFLTckUF0XPwbwS3v4CJvTvDDxHjMyLth9Bj4RiQOI/bC6SXLu54GFIMlyBEFEnxjRHzwxrVFyBuUpa97Ig0GvSLj0J/6DOQJxVm5CnQ5Cyne7co+jX1YGg4eOqOTcw4i0MeA/YdkZjuy+mBzJfTHWVuh/eWi+qjspL9hu1othl+FFv9PyYqoJ9mLQ+H/Rax6+GB/yHfm6GQ99MTXiOPZDT6szMDb2Q+95dtxq7Pt67Gj0t83wt87gwNgPh9Gv2U77yM+dTvPI78wQyYuxnkH/y+q50Q7OC2aC6UUzY4L/aqbI3LLd1bbhL663V1vngkyPXdF1AF6UBdUCu6CtNuUFcJFVDsts/pENX17SFr1SCBqlhYubwU/fKoTNf68Xt4kFJs3FTc/pJNuoBE6ycrecTNCqyiIhyQw6CezNB35XvotJ/5LMrH4kvb7L93cvN9cfzje3Dclop4HHJSvtAi/i5mp5UZ+bWeU1d26KGwRWdBOUmxf2osK8JnpOyka6DWW6KcmsbAa59Y60KGnL0l0hZnUj4NZd4sR8FGN5BP9mXBZayGcwj4xr7tICHoyr7lMPma9s9mlgPnsRUdd8ZRtszPsf+MC8aIgLgBVR1zOfr3D3FMYZtKVLThi0pm0vOtyM2yJTkLbzRgthAZB53CgzXzJSLzYPmiLzbRqsaSN3Edks2McgNI+MLLweURLlZN+zeeGc381TEnVt6SJoPudmFpLMTh1DB8zNx22OmiEkc6JFZqNCfLLRViCibpKaby989hPzEUtEcSVuqmKM6Gi9GblqWb/b4urJ0tGOLMd5qUhZWa1Rj1p2AMtRfUiSnEzqQtSb/+t95OlUG3vJ7p1yyiXLIL+o9MLkSRRwS0I3TDNUxWwslgitEAbSyzDFQ5Cx9oL7Xu6ECRjH4JfczUH2iN8U+wAnLrcSpkrltH2TEmKpR8PgTOSBMBRN8yrUPLOYUjOfX8fdHr8hUwTpnjBBzwcq1cytXujSFeHM0orQKKUInGiAkY+e2KwAmVkXTigy616GKfcsyAepZ+xVgu47cwZSQQ8gVAzm7kKQcV8ZY4HJ9K1EOLKgC/9/GfTi+lU5lQCEQ5MM0FsRQZLXraasxXJEV6j1XSFw6Ts3HHG5zH+RYFXeCfLAr+46z3uHgPtS7QbgN3D7zzOnfYgHE3o/9IIggfLaCyBeftiAQgPOI0FUYkJgjLTzvMj4XyeAwKhA/3kVPxCIdkUsZ0qkT9kJULXBFIIo5QOhjlknhOB0ZhuGvNxlSh2pbOjzQjVN/TwpO1IBqiIgEwRKMpUZWSYAycgyz5e5SyYAzV0yQaoswgmRQa9AAdnGyqyHYlfH1WuamzVv7dogclZ6CFFzOowtO0kUB7g5mEH+cJ+KGbIUyYorpBABiOOJ37yS0vS8yLwmuRrLtOjeAig5+tyG6Ob1NzZkX59vzMs2X5uWbZfo2lBuD/QwqBzYgm5OVDaafu0OAhfwh1dUZMk9kSZlq3sSTSo23x2AUd1ynKa8fRJ3lpD/GfAbFrL6dbkzLMtkYbPKgQlpIlEdKlW9Kqp8Vp1gEem8lHvC5Oyf5lZOU4JBTFbi4r5zjgrchPLdrLOM0ogNEs+27ZRDbfQoJ7IYO8W5O85d0q8hjRb1alXMTnN8lHEbuIJtTywzpd5+JdidVxTfQZAXyGzMZLDuq7k+TGHsw9gLzJhgXhNM8TVQLzD1WJBnbn2AihnZ0QxJEwDgd/QylqpbN5axdRAY5jNjCTf7rRhqS7VB9WGptiNOttGYli6npg1qTtUSXBOonE9kNjbVTfSRvU7cKkdIjGzlMyQlMCIpqBQ/8UfcxqRoTTfYqpidq0T9iBrZ0GhMrPRSUKreRVbHVv1ZNJamwrsoF2gi9jSoLw2DrA+98CWDoEa7p7OZy22+EfVjoBHoidRTtK2GvDMDjXJKSWQkUlhMDy3oyQnHUzk22iRWNahe1uE6Ao+4OQ9lGdqp9IZBNDbGBCjDuIT6wYjmxMZjZ3BU5g5BiPIkqzYZNWts6q9d/KpLpqJaWmx6CxNPiq6maXdCzcTVqEyVXriJneBn4qnRB274asvwHqukUy90rgZdPNGcCyAdJT2dLTk24Rpg16aaBcJSs0t+hFWaSNbUwa0nBD1Auuw+3JEiO9OdFlbtJKGmVhhMrh8X1ohgluGySxbQ7ybfQOJqaUEWieXJ3LCAlNpnBNIUTq69FtYiY18za4zFdVDyG84O2jx/K2ChDZPBKD1oJ1p58Anp8BkowrRVZSY3kTVj2hqk0aDsVlnCFCvaOsc5Hy4unLd312Sx0PvyW/OKZeKpOtnIXsPoGsR75wBBigMrUlY5WzFwN/8oipB8o/x+pBlGMPTUrXtAvPablEDB1HptcY0sPjeh8RkFuXBtNSX0wB4Moa4S7KfX3IqrdC5D01HyQATDUD+pPE/bKe8A8P82X5vRSZNwapGshBIO2T0jSV2rGmfVVYkmt1eIa5QrzU43Z1/0laqTbqo7BasLcebnrPWkdyiJyKChWXEyClkqtzf6mBUvD2XLYG7FAL2Y3JxgfemuAUUzSUWOfcrLMRhtsRy5PnrQLsvlaXH6ItrvWP+gXelCz59adS6joZ/Q0PstBY/aSUyWiehKVIsttGVmpvyFRfb6r9XDoz+1uVxcgyyjM1Fywkg7048ef6iu5usrvNaWqMYhq26DKzUEOSUZ49dNlniPcPIsG3Ep3It0Hz/ryiSBdlSnkwvRxSWEu+TTCl52LjwUO6einW+IyNSJWuIidMjelI6RN3UjRkJoi+GuwPnLr/Wju7wzFJarqjPtYkVahia8QwEuFv75N9r9JqT/EiermA1obF5/Y0Blat+gjMZr/ZJuoIGekYUTuFOrXaxKobIjmhX1/b7aeknyGBghI6flTR4gIazULHDWFgoiAyrz+5OEZUz0yogG7p5rZ0eqo51SlU6m3Egma1T1R8Laqzn1Feo+NDn714UxGZZWbvQMVWmvmtxfnYIAzS5eVZfPnuMkflZvpzPC7bHJ7IXihkSH13gbEu5eoK0pOrutU05Ip7szd3e9Kb3R2+MNixtP9Pnb0zXFm0vNNXX0xg0nrv/WlOrcyK2rVV+UravTXF+tKWSqZp3dGjYpFAYPCKBnZ3onFT9oGOzjmU0sfIEsPse/ZMJToWMC1bybogCdb9MK3WxfUY0GOl2nClGGntsKLiWh5YMbJVM7CmQUtBlcBD7rc5QqRlhwFnkCGa7IlOViNyqUMxidYtR5xzdSczs5BEOXC5ZMSKj6oNQqaUOzk0WqXrAibhCl6mnbVdKsiprJK0W/qlka5cDKuQIHdb0CPam/zFoFN4bKlQdRaXYzTu99FtTRqzPqKSZVV+h24DQJZ1dRC2soutFOCylChFEiPz9RB46U32eRrzI1zYTWqeKiNFPsfLEKSrOLrAAZJJNvvLMKuG8zeSolV4DMBimmXgr8mTPP+MEnz5vhB31UD6ld/2MJnZdzHVzZOpmvUrat1ZVIH7U6EnVwVc/rPrOq+c5UlqoI77gDCYW5zcXSMqqRylyaqNVsHQoZIAqD6f3jUkIavbaejOYrg1GjI16yOxPEFd04KY+JndyiaUZbn1ujUdtT0WfZ7fyprfHSMvo0Mxv1pWX0aXRb26yUenOTUZk+XUBWRZ+lXDSnD6Oy9m5EBoHYTyKtXjOrpt5h7anos2g0XzoiBkjCJOefc6KjaICxvu3RmJIGk27Dizyk3XxH5DjGMHcPMNR57dLVMYrelOs1qtaNqv3yJAZyWbauI2S3dTB5UK5QePz5/KX266FVeoTPyv60y04U06Zc4aERFhcYCNR7Sc3iEL3wytVRsxhEI7xWN7ER0PWCioi7ksF9efxAeTjCUwA/05vt6T+iOZIj45bXCJuTqqgiEMTNnbj1+VhHc991c9rQtvz4z3bn9dHE40XZ+aQat0mW/0iWXf1vfKrGJ709AedKHGKf/W9EqkbkP32W/HRC1gpiaufMQ149A4z/PKJatPDq8IvH7v+cvDjZXl3ffry6uLr/q7u9/+Xd1Y17++56e/Lm5Ps/4Sj49OkrusT2h08n52dffzrB38DYS0hbDH/1y/370+8+nfwJ28RGqU38SAwi+MOYr/Qm+K6rRJReH/W89fC/OGitdVJK4wfw/77fJaEPUatfJWjnmfrJACds81x7NU+7CAD/SikgTpgqismX5WUr5JsyW1XxOSvevrVd4p1R7d5tMMbZO+OgxtXHjryzYKY+rejCigfM8WIW2Ls3py2QCLC838a4lfISiWosverA2vGE9ggsq9P40jPyvVPVVuxXdBHjLcgP+GOBAmI3L/wgeVNX2E5dp1VaTUVefvrKTqV8DyMyjwZNVcv0pStUL+MCEAZeueC4XBhKo7t5g7aRPUwBbpre3V/iOpn2UjKj0uxpqy7mB2GyN21g5HBVz6yF6sSxA4j9sJrcsydumLw5pLPSN564A31b/GXqBuVaNs+4G0GvxnRp0bRtpjw0upyXt2WwbLnY9YmYaDfZWDNV3e5HvjsLfTVd1XdNU1Ev9rKZHTNSfuH0htxGXzy9IPXCkZFnJ0JUl+pOPj8RirmDlxN0QqC9uFco/BRG2SmWUBgvFaM3EQ+yF04II1ccD4uOHO3YBccmYMd0xVlHCqtkYtLTa3VTs3Vg83Kze32+2UfffEerNuU4qk/WnRTXTFTmKnDgRal53EbWIGh1lL1pzkrVIObOTYM4s4HaKpvFTVBui7eWNgdML8U0zEpVDWKi56Q5ct40LKttFJnuMDfPS4UNwmZNA9IoKpU1B0q6n3Trv2FWRtkgbgSwcOahIM0TG5l3aMAoPIJ/swNNhc3BQisVGTRdkcE8soFZqZrD3KUFPFgAbXTNoe5TD9loyjS6JlEDGzVXLWsW1LXRjm2FzcEGGxvJT1UNYvrACieVNQca4urZAmgtaxbU9WxUU4yyQVxy8XcGbeC2ysZxyRmV9pBrdfPYdvJFR9w8dHU9iiXoStwktK0eGaNsErcAyE781sLmYKPMxruCqprDTL3YRozWsgZBkY0hGapqFNNOxdUKm4XNgn0MQktxy6qbw0ZWOorIdEcRJVFz/5NpVkbaIDC5f9ECLJU1C+paY3Wt4CJoo55lpc0BZ1YKWGa6gNlqvFhoutCVfjayLCttEBjFexuwVNYcaJHZaRM2uuZQn+yMHzwZHz8gim6S2hhDYKXNAX/2Exu5tZY1C4obxzYaiKy0LnBEFwkaw2QFja+/MAQ5KmxlAYbQo5yHeD8PNzWQ7WCy64yC2BNcXzRYgdvcrDufNhVXfeF1G0ok4kcWz9b3JTNnr8jYHwuvRBIwUvBL7pILInFDbR/gPCbQZulQcbXU4grSSw1l4qcOo2YRZBkUeVn38kQTSjFPqOUEvfQvT7wpBLrVXattqHmrYjVIvzRnSLE0z+dA7vo36mN1oTxXSytvybEwoRRT+TnzQBhmsnbZcDZSOk+S0DuAgFfha2aUqWiptsUJR0pDW0dPG14oWSTevKovuHlPy/wrUce0DtNyP5CRaHdMxb4mjC7F3vPcFEG6YFydZqhjLE8YbmI9JEkeJuSITtlmVne/nkod3VXgl7yW1ekGdYZKWhWUbCReXG+vtrLxd0G2SCvVdPKLnnsRX73MyAaEIBRp2ZX+OQS46XgMJZTLXSXF3F+kCMMoKLPkv9dXdCiBdINrxsheZOhtMjb2sqNrfYbyMMjolRoCE1iZIEoLF6Do6VslhE7opWrfiQJLtmRvVi3ruOEqGoslbC8z0eDKSZlk5aVraghMYNstK+m9QUM/yYgMoeW+zVhX6XaabvBjbTLg3ofK9i9mC69aUdBt9o7sIebmR+qrw4St23jjcjqtz/4JEcbwajFTcEKrngXZpNc6z6PFTyIDeIJstZjtake36zo4WiQ759c/Y3FAu7ITegazj0nCVs5oJjKFV4ut3Aapd9mvM7hSWxeP1TpEHaWsgk46N6cNoFxg5I1HU6sc+5BPE3vCVWPjMa0XWQVj8a9NU6usXLiqabh1ihadAiR1jXh+rgIxI7ushE7yUqlHiGIYavK0IsdevNgIFM7T1Od6FqUrYS4N9HhakbWLWHP42ErFrLEvkaubME3O7qhoJXJ7GNsBhNWCRSNgHTmDhAbjrqunwRj0RCUKSx9vTOroq602N6o4XtcUHRVDqaEB1Jc51nEUGPnoSXYURWhJjI3sAr1EZEasdIpdINCEW/n9Qc4PXSHa2GNLRWOPhCnjrh9YuWyVB6arWNe26pbnWomMyYz5zgTWoxCq28cIJGryWevuLqSXFCkxtMH1SOoLDeUh6pBHPRbWOySYVEJudagcv+HBOE3e6PNSpvKDElUnuIH8oARRh7SdH8LgQT0/4MAl7MX1q3JCFEh4isM6I+GPtzXBjylTS2Vxv9A7BAKLmEuoqhnQBlFYtUZCi8w5dO2JzyyMmitXNwCht3bXKhNQcR2uvL/dUGo+iy517firtdIVh38QWXDasfggsth0Ml0FF9Z201RnXS0Oj0C0K2KhNhBjlQmlZlZ4SU3HrOQymrEoRkIdhU4EI/E+wqhBmXZmz7BsK3MEQPDQta5pqQPVpowqVlL9sGoIQvPAHcMSs71Dc2IHGXXsyRxSNDQodB5Cx57EWQej5tSSsxtQsY4S2kjdraAkNkkPDVYDzJIm20A6RhUri2FgNQjBAa6ObcHRrEX3WND2hkD3gThCeg5tCI1Xi6Q9GkSrZpc02QRSr1blLEKdSC3rSDl7dRD1alXOHg2hUbPJ2ZOZ/pis2eRMtoF0KhU5m4JTKMbXD3oYMH+W7ayy94wozgG2F9tkRUrONdY5SH7yyi2ppGOvjACeB0NyC4BQq72OR4eNGGfoI71Hx5mzpLu/mZFOojhIETn9S2guXN2HniEDLpBrLuynwZgVK1u2p0qB1AjrRGS52E+UpM/uASD/MxB5LQvHFZ3vHbOge0gAQonQHLQEaaOpnQFrefNRyQhrUtKeIxDZryVF2RU2Qwk9gYsuVCipsCZlY+AADGP2lPVzZns7ovnM2dU2VI1bgu2LL1lvy81D8+oYc6+2egduK6yZhrgOcIHIdLkUIqOqW7t4kQU+RlWXLwKeDUBGVreUHsC5BUJWVp9w8/obO4yMsD7l6/ONHUpGWJNyb6W87I2Vl/yAICCXuFmgHGgbfRcbr8S72mbfxaZh++JmYvYJhAW08Hrsaq93RFft+3BohBD6KHgSXGE9JWSid1klbXnwonoLrvWn03irVQ1kbtobIIrUklnccX1DpbISFN43IhfJPXGzyHQ63hZ0K28AO4P1hLrrwxTGPow9ocNOZOBnjJjpSEcgBnsYkZE2Y+Cj0iYLJYizFCBy8XKdsEF6sFZEZ6xZdeogtIzQjEsH6TWHCg7hXsZS/lBTVt0BuPm3lD+1LTMtoSDP3HINuEH6gfDxD6D0b0vOgLTIaCwHcQ5RTDYyoSLLoe9meYJwVajR9GSim7Q68UdnzopsNpnM/cu4wrNkxJ1qNN8odyMpXSxlc/xkAo00JI25OK1vpdVnlHtU3iz2DoK8QFo9ynlw1oDFBqtR/BkjxhusxsBHpe20Hci6XzI1bDjaeZbsOJM/p6bzz5yV9YZWVNfJTP/Qb3wUeRBOtj6GB+oeAuS7OH7k19rsEIQoT0SP9eyvjCGHxukMIkmfwzaaH9uz66ZasCQ+HSaanNrv6ty7+ly2jtCSLVb50/9GI6L2avYYQF5c1Mfx9cU0K41GDpf4ZHqTpjRdI3d0Q63VkRo6xYOMK5OrtPR7Mx8uLpR7Mz2pt3fXZJ/ce0W90cxBHFUovFUMO3U0OdhLp8Zzak217sIkZgQ8ND3HocHaCCv2bxQ7Eap9j16uuIbRNYjlV0mOxvMBgtR9ZSBDUCqnFbTeNzMyfGHiZcC55IQbiRTDkbv2ZAYIZ29sNJ4eLRBGYpU0oXC3BEEPkCEGH+7IPMZsc1wYcVpXd2njE2kF73EMpAYw+2qacO+xGXLSrT4Yq6QJFQYzFx8LA9UqumsBYZbhbiW5mXo3MzojjDXU0wVMC3LEfp7Md+fEAQd6BgA/I5CmcObWXSk8Vk0Trn7z6IOxSrpQKPkNV0IGYotV0oT6WwELA9HUyOiOacAoPRgoj62OLlAOvEe3bBQaSLi+mibclshdG2LriWnHW3leqKn6dSCnuwYNZNMH8whT1Sq6MGRfmIEUbHWsDpqMtyaVewmsgvLpOp0GlDJKX0UZp2ylKGPUoZXNV7Wxsv0muPrhgp3iqgwykFEGIiVVI2M0wdUBqrKpTtCEX/lgP7reUm2kOgweEEC84fGZaJzbCDWIQ4rqUKuO9GanvvEsPsfKmUTRGiCwElogn1GQa4I0EsogDyCD30iMEPUp2vDKCJxVZlwElXVjowhl/0WXoxFRfxPObMLjQkhvtBsad70CPemU0q6GARQ3hp9N4NQ6Gkh+Nr31UICEBlcGiKaXxnGtR5JL3fo1RbAn9wKr1xRNeE2E+UNNBDmkjjmZg4kSjSTpahhAcRHQKClDHWWkJNCIFhpY2Xg6c5gI13gqfqjIuPFHL3utYb4OrgGgY13TtGbrihHQgNBsWTECGhCarQlGQP11VR0IofHCagV0Idw0CafvNxElaVTUm3o5cn30ML1Pit/OYxSUMQ5kb7AeR0dCvaNfbq9Vp2jDqydJEmc5IEvScBdZI136Mupd/XoPqjpMR0K9FqFr/TSqEUZBG8Ml5vRZGhl1oAzosjAK6r34EDeYZtfM8nvxrIR6AzB2o0JiLdig4deE1xxIaPYbaLAMhYx0GNSBuiImOgy6LFTDVIfBAE6tYwgJJ/8TyIIn/WQbEzQyTqQM1hPReG3O7u8QeF/Kb+CYe3O7QZRqlPtxLVNo2tXStJ7WAFezP2vuJA2hIa6+kiaWbvHrq5jpP6jj9FTUJwajJJeY6e1zNME1hgDJBg91gja8DoJeFcgIqEOkGW+LG5+jo6GFMr8PUohEYd/jCAjpd8gs2BgjaTW0UHIEPI0qpCOh3lcA/uwlTvyuQiugMxyk/wrqiWiPTemAaBffepBNA6IR0O5HmkicMSllMESOvA1z9wBDueWZfawRIfWhooxc1P5Q7PWxRqW0wLww0OqIdzW0UKJg5hoMIZBaQQsDi56/NNCSG9cygPYInzWzUFdHGenL66//oD6UVIfWMu96+J2rM2nRE9GF0RhaYxV0MSTW4E1g6K3Dq0QyjdUprIIWhuakVkdCH0Q/bToyJoB0U6kjo9WkqG+Lql4nWmPUAykDYCaITMXR7GlPMjEkf5TTTMJprkgblTIBRk8wqffZuHHiZjnIg+kDwGRYZ9VN4GdhkoscjScDPaJpBJUek2QEsdUygaa1PnCoYwJpt/Onz9STYaqFTEDNHvQnAyV/it801NxhfTJM0ifxTSOl4NFMPq+FTEAhnXWWQx0jVYKh2kAvjrwD9B7b+yjJJTkakxrjYsZe7FqjKT0hgy92E1itlBEwrRnqESFTUNpD7NN6FhpERjBHNO223SxAd9VNtTpMgFIdY60OE0y1kLFWhwmoWsgElP4g4ISYETid+dShjqlWmgkkqmOslWaCqRYy0koDsZ9Emgs/pvVMNSSNoGnOmXdbgCaIMmPJ2O9DG6EbaprslxtBlDsKWecIO/mjqLS27c7EJZA5i6aOvOaQF/oZGDmABqBAoWwOWKiKLkwWnxuAoSoGYBSnx8eIFCbKR7HoZl9tplZHF6jaU6gP1OjoAhVB6OMW0k7iZMNJqI6WJpiH/wlDE+WNVdKF8gykHRXRRTkA/L/N1wZ4GCUjUGkSPpvCqrW0wcpxI8XRpyFaV00XTnGQZ4ClMMIzDqTUnRjgSHcmxmGSKAX56ebsiwGkjpY2GEl/F/i/FVnuhnAPvGfeTXgSpLPiNtB3CPdklFbqCsGz8kbxSQO5FK8MmcYfkTeOnxVkDAzmFl0YMWHUjSxT6FHPY1NJo5jl2ifDnLWmGVCTJdBYcWP2qZpg68rp4tXbm/XJGCVNqHKtqD5RI6ONY6AT7RvpRPsHA21oKqKJAj2V8fg+S62iD2Oi5Dcy2ji/qY3gDoF+kx/BnUBSmNEZ4khO54yj0HMm9HFaIV0ktf08AyDlu8y6OHsTXeW9ka7y4dHf6bPUKrowzSEY+kSslCZWGBl4QVARTRSqZqy3PtTTBVRYJzKAklwiMgHy2gTJaxMoMErQMz031QVhmBgYQZgQ1USNcScoS7xHqDKN20fsiemiBbg78ahwvsEAqxXSRCJHm2njUBFNFHLQmTYKFdFFUdieOSAxcZA3OX3tXOLKr2mYWscAkIFaqZExgPOtGZxvTeDUpxvpEzFKhqAM9e8HcqbwyuOPzOHVcrp4Sfh8/vJrE3meUdKFQsETyKELPA9mBl5zQz1dwPo4K300RkkTCgX47eCff2NgUq0jpYtlYlxAejnQKEp2AAYWHdQq+jDkJD8TOFRHH+ilEZyXZmBem2gZtDq6QCZmCMzMCZR754F3MPC260iZwConcbMiyE0M2Y4pmoBMksfAVOQ1WgbA8oB0xcyAtVqaYO3RmtpcHSldrCAyw9ToaALRC+P1iRghTSQz04WGJgibcwqMANVKZqAMlDlWyQhUZmA4nFWSWA6sfRUsbtVqX46uuRQFIzjmVpzQvXHVjDkoyMaamNxyqDG61AJO6RqFpnPqj/AZ8wTIlbwmk08/acCGG9lznMTPOqP+kw6w0kewPJVwml2aWjlNNPMgJhsE0yTTa68xcTkuaxYZd+ejIA+eDCN3Zc0ik1KBa0gyDKHVRhjBHkqbQa9WGxpBbaVMoenNrXXQTC2D7WwMVd3GO0I4UDQMGufwS56Zrgfm5e24YKGQ8U3YccVwFTcvb8YFLIw0RvoY2kbJDJjuqlSGzNzqU7o5VHtChYEzOKfSbHmkOccIX0fNEGDwu6ES0igZAstR4Zl5ebZSZtDMNfwNt/CfQFgYImulrPR6Ld4Wm8H9Hn9Wuiw2e85yGD0F8LPOxtft5YcPl3e63fdKxb27vxc/xafy3WndcCoVpyummdsqMfFsxqEykP8Z90xR1WJHm/15Pw/ydhAGuPnihuCBtyd7LCwOVZ6Ho1aw6Equanu9WOEcTWhy1HC1Dmy2TLC+Ogy80+VwOnLKu/1bldnMJw8lmP2s5qaRH8a+6m0HT9MzL02Z2CC/v3F+TcIigplzB7OkQB7+ax/kTgTynPidg+zgpCh5CsjovbOHMUQgT5DTyDnTJiMQxCZttnozRuOn6GUnJ2qZrNVmDJKYOJiM1sOsubdYoTyVKYn/DJ/VLMMvIEpD2C68oXmfQRqaEWa63b5VTXVpsMbWDN1tHfbiAOIYhtbibMyQBFfZErAWb5PWRAgvYy/pXwhiBY4xJMO1QLR1TImwXVfvDvtxxhiS4VogzjqmRNjwH3niJQsUUdaSDNmv50tEXN+aFOFmUcKNOOF25NwlK3Db8UOZOFwfyFu4d5SiTTzGnkzsLZC4HVMSbBdFlifRgoSsQQnOd3AHijBfELRjcYb0x+HpSMJYGfLICWVOVqRpgnLnx9ETksYNKsbEhEmul8+4DXef/AS/GPK0oydm2JTHPcUZ4xc/Xd1+TPb7/govZdthJeb0hGcQ7uGX/CYOn+unDUVCDTIqP4OzLYvNxXDiU4qkXwr7qqIAGpExi8CLBQOJ0bcvmgAk51yUo8u3bz9q9NsIQzVK7YxLcmqgl99VzWv1TJDBvEjdFDyHCfCdvqaoeQ33ZwCGMUBH929BfjAybmBSvn672dDsZ1STNnAiGJarJ2FMyv7+++8uTTbok+Ge02oNhEkb7JB6HIIsg7iORjBNbDjUNRYksobYMdkmdzwkSU7KERTJ2R0F2i1xHsIC5ljlQM/dUSV5B58CD5IKnQwUfySV6+X7u5eb6w/nm1vnSs/NKulJZKkqXFxvr7bOBRmy1mSplO7ub7YbXSmc38pI88u4c4MY5xkNH2HkoycDcQUj0maRFxhMU+0QxCUqIcfpZUGmGFvTqo8QxTBULEJcWdJgI4txnQ8XF87bu2v34vrVe92UDpIsRxBEOsmTQQ//SmYBw2phVQzjvJx5oYdF1K1NvQItaQbXKBC/2q1bM5Ate0sHTMnRQ6/1Si+ZR7GSOchW02oBjokonJqAVtEVnFvUfHfgd1zoHUCgVTPWxbjy24hSCGFKNpuPJUsEPJS8gzvyYsDN2G53xL24+fn91Qd3+9PbzetvyKf7y/+6d7dX/++ybJqXq2Dws/hHKdntX7f3l9e1+i/bS3d7c/Hny/ttR/VcVHN79fHtj1v39u7m16vt1c3P5K/7m4ubj+6v54qKHxm1i5/e/vzz5Uf38ue3P368fKem2DZUNi8371+fbz5cf/OdBM7b21uCdHt5d391uRUNWNWbP/9y7W7f/dm9/+nu8u079+PNxduP7vb+5u7th0v39uYKp+pdN+o3EmQXN9e3Nz9f/nzvXry9f/vx5gPmvNziz6Ia1z9evrv/uK2zw/urj93c9X/C/D+YWrpeUP1HWX3cAXYv7v56e38za6pzwZGkqbv7+zI7v91ed3S/Fo7PZnGNu728uMfZr8v3tyLJ/6N9qPrcE6cviffdRRi57/37v88+KfbiIO02/P/kb9JccfeedwZECPCDIo8JPRSJPBQnuA7tPUiq6JuUxjn5cOXjJ9tvzwrvjLzTsBAqYz4pv5556ow8EQW/l7PgncQqD6e0b9/78oVcDRX7APkd+zi9z79VsN+8xuYBmsfOvLToGsaNKPjlNHq1hPFdz/gufXp1mvUHeeyYxt3i3AUPQQcgS3b5TsW+ZLrjxnDTuhwuSyKBPgZZ3hht8EJSZN029GBMzmkNyrpAxjeiB64PzWNH6UQYxI88D6pn6D9bDwVp3skE/5Ki5Dfo5Q7ZcrmHsVM9SUZyzkLffubYFbFHvnRxY538m3XoclT0uyQWGHyQA6P2JRImBjF+fbv4vbCG50kU5O4O4deQmyZBnNOAy0LEZJ+LB9O1kh/bR3keLJzw9XjuNUjL1sDyfnsTb+M//MG+7c8AxUG8z85AGK7gemO+3GC1JkAKfRDngddtGoAwWxICIOiW5wVnihgReITlKwOg6Iw0tHOA9jDvc0w8NmiXnUb4mx/kWmeaCPmhiB56EPQ7+8b7TcPTCH/zA20gnvrn/UELOxCjjUSMQr4/xd//INFgHBhpax0uT/voVBV1ijuJP4jWUzP6dOJWDIasXZ/qwVRAwt0Yw0hjL7DTXZycVt+uAjTxRi+x2N+Wy0t1bef2Xzmnfym/WTaa7NIoxcvwXXj6F/rdSnFjjUgmfiaHTU5vxAZNDMaMTRaZOJnuMZ3uyG+n7W/LRtBiYDKxNd/HPd3Vv68Wa4sDSpW/+T7q6Y48cFo+cNo8sHCxXB5RJgaPY+zKYHwfqUOTg4rTTx6rK+MDGROPTY8uqg8qahKVw2qDQbVT3J2CXvYD+fWs/HMJlnqkx60+uxFIu1T/RfU+fXV6DdIf/uVfb365v/3l3n13dfdvzr/86+3dzX9eXtz//Pb68t/OysA6VceAOsg8qax3+hfchC/iIoP+aQpInTaozrgSnHTghu83dtQy+yHJ8n+6uJHzFXt2Vi0jOQtwJZEFLzeVx35+Vq0l8csj9crJorN9XJwxVS25LbsfJYxg7+nqoTMSZ2dJfoAoxO4dW+xxw4+eHzDz/C6CWYaj8TSE8T4//NCfQLedWqTHLZNe7PP/m2LaKVYtQihTi06k9ROArmdN0m6HDe7Qy020P9+km5eb3evzzT4aLLPRexvJ113hi9PTvTfRyBcLjrMD6b2fos9fsM4+gnGuVX9JtLGk/f2CPzRyp5+D/HA63HRhvbaljQRO2ZWV8wLkFSFAPkxh7MPYe1ab5Dgej2L8svYHLTrxKQq1unW8bOlo/RMkTfts/YoI/V0I9mPHDS1dIWhFveALkvV8Qb+/d+grpPz01fd/+hKFRLc6BB8rn599XdJDskMsiPf4q1/u35/i18afKoH6FdSsLCu8syjxC1x/ljvNzi7K9b+31WO3uET9WMZVsyXsrFz7hsNjpRSi/Hnr4X9/IPcQ0Zcb60CKBcrI3uYw/SPG73xeyCW/2iS9hXlezmVK+OLYo9KJYotYhUfBVJO8fx4Y7eCPFZDujskzD3n1MlUPVRbpuc1NpYe/ana5jdeE7IFV3bx18uJke3V9+/Hq4ur+r+72/pd3VzfMOuSTNyd//3TCbH188wl/8Qk34MATxPk18R5/BSgge1wy8vUb8h/yAPk/XEekAX7Kf/yYeNXYO/3hTf3HHnqPiZv5j+6rs1c4mejXL+o/yE6Bm3QYbrwZSH/8R/UfrHJCjwL45+L+B06UCoGscMlwGvz3/5z84/8DAgaZfA===END_SIMPLICITY_STUDIO_METADATA
