# Copyright (c) 2024 Project CHIP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import("//build_overrides/chip.gni")
import("//build_overrides/efr32_sdk.gni")
import("${chip_root}/src/platform/silabs/multi-ota/args.gni")
import("${silabs_sdk_build_root}/silabs_board.gni")

declare_args() {
  sl_use_example_credentials = true
}

if (wifi_soc) {
  import("${silabs_sdk_build_root}/SiWx917_sdk.gni")
} else {
  import("${silabs_sdk_build_root}/efr32_sdk.gni")
}

# Separate import since matter_support_root is defined in the EFR32/SiWx917 SDK imports.
import("${matter_support_root}/provision/args.gni")
config("storage-config") {
  include_dirs = [ ".." ]
}

source_set("storage") {
  impl_folder = "default"
  if (use_provision_flash_storage) {
    impl_folder = "flash"
  }

  sources = [
    "${impl_folder}/ProvisionStorageReader.cpp",
    "ProvisionCrypto.h",
    "ProvisionStorageReader.h",
    "ProvisionStorageReaderCommon.cpp",
  ]

  if (use_provision_flash_storage) {
    sources += [
      "${impl_folder}/ProvisionStorageFlash.cpp",
      "${impl_folder}/ProvisionStorageFlash.h",
    ]
  }

  if (wifi_soc) {
    if (sl_si91x_crypto_flavor == "psa") {
      sources += [ "ProvisionCryptoPSA.cpp" ]
    } else {
      sources += [ "ProvisionCryptoMbed.cpp" ]
    }
  } else {
    sources += [ "ProvisionCryptoPSA.cpp" ]
  }

  if (sl_use_provision_channel || chip_enable_multi_ota_requestor) {
    sources += [
      "${impl_folder}/ProvisionStorageWriter.cpp",
      "ProvisionStorageWriter.h",
    ]
  }

  if (sl_use_provision_channel) {
    sources += [
      "ProvisionChannel.h",
      "ProvisionStorageCustom.cpp",
    ]

    if (wifi_soc) {
      sources += [ "ProvisionChannelSi917BLE.cpp" ]
    } else {
      sources += [ "ProvisionChannelEFR32BLE.cpp" ]
    }
  }

  defines =
      [ "SL_MATTER_ENABLE_EXAMPLE_CREDENTIALS=${sl_use_example_credentials}" ]

  # Require the provision library when provision channel or flash storage is used
  if (sl_use_provision_channel || use_provision_flash_storage) {
    _provision_abi = "m33-hard"
    if (wifi_soc) {
      _provision_abi = "m4-softfp"
    }

    if (is_clang) {
      _provision_abi += "-clang"
    }

    libs = [ "${sl_provision_root}/libs/libProvision-${_provision_abi}.a" ]
  }

  deps = [ "${chip_root}/src/lib" ]

  public_deps = [
    "${chip_root}/src/app:test-event-trigger",
    "${sl_provision_root}:headers",
  ]

  public_configs = [ ":storage-config" ]
  if (sl_enable_test_event_trigger) {
    public_configs += [ "${chip_root}/examples/platform/silabs/test-event-trigger:test-event-trigger-config" ]
  }
}
