exports.model = {
  3 : {
    name : "Identify",
    commands : {},
    attributes : {
      0 : "identify time",
      1 : "identify type",
      65528 : "GeneratedCommandList",
      65529 : "AcceptedCommandList",
      65531 : "AttributeList",
      65532 : "FeatureMap",
      65533 : "ClusterRevision",
    },
  },
  6 : {
    name : "On/Off",
    commands : {},
    attributes : {
      0 : "OnOff",
      16384 : "GlobalSceneControl",
      16385 : "OnTime",
      16386 : "OffWaitTime",
      16387 : "StartUpOnOff",
      65528 : "GeneratedCommandList",
      65529 : "AcceptedCommandList",
      65531 : "AttributeList",
      65532 : "FeatureMap",
      65533 : "ClusterRevision",
    },
  },
  8 : {
    name : "Level Control",
    commands : {},
    attributes : {
      0 : "CurrentLevel",
      1 : "RemainingTime",
      2 : "MinLevel",
      3 : "MaxLevel",
      4 : "CurrentFrequency",
      5 : "MinFrequency",
      6 : "MaxFrequency",
      15 : "Options",
      16 : "OnOffTransitionTime",
      17 : "OnLevel",
      18 : "OnTransitionTime",
      19 : "OffTransitionTime",
      20 : "DefaultMoveRate",
      16384 : "StartUpCurrentLevel",
      65528 : "GeneratedCommandList",
      65529 : "AcceptedCommandList",
      65531 : "AttributeList",
      65532 : "FeatureMap",
      65533 : "ClusterRevision",
    },
  },
  257 : {
    name : "Door Lock",
    commands : {
      12 : {
        name : "GetWeekDayScheduleResponse",
        arguments : [
          "weekDayIndex",
          "userIndex",
          "status",
          "daysMask",
          "startHour",
          "startMinute",
          "endHour",
          "endMinute",
        ],
      },
      15 : {
        name : "GetYearDayScheduleResponse",
        arguments : [
          "yearDayIndex",
          "userIndex",
          "status",
          "localStartTime",
          "localEndTime",
        ],
      },
      18 : {
        name : "GetHolidayScheduleResponse",
        arguments : [
          "holidayIndex",
          "status",
          "localStartTime",
          "localEndTime",
          "operatingMode",
        ],
      },
      28 : {
        name : "GetUserResponse",
        arguments : [
          "userIndex",
          "userName",
          "userUniqueId",
          "userStatus",
          "userType",
          "credentialRule",
          "credentials",
          "creatorFabricIndex",
          "lastModifiedFabricIndex",
          "nextUserIndex",
        ],
      },
      35 : {
        name : "SetCredentialResponse",
        arguments : [
          "status",
          "userIndex",
          "nextCredentialIndex",
        ],
      },
      37 : {
        name : "GetCredentialStatusResponse",
        arguments : [
          "credentialExists",
          "userIndex",
          "creatorFabricIndex",
          "lastModifiedFabricIndex",
          "nextCredentialIndex",
        ],
      },
    },
    attributes : {
      0 : "LockState",
      1 : "LockType",
      2 : "ActuatorEnabled",
      3 : "DoorState",
      4 : "DoorOpenEvents",
      5 : "DoorClosedEvents",
      6 : "OpenPeriod",
      17 : "NumberOfTotalUsersSupported",
      18 : "NumberOfPINUsersSupported",
      19 : "NumberOfRFIDUsersSupported",
      20 : "NumberOfWeekDaySchedulesSupportedPerUser",
      21 : "NumberOfYearDaySchedulesSupportedPerUser",
      22 : "NumberOfHolidaySchedulesSupported",
      23 : "MaxPINCodeLength",
      24 : "MinPINCodeLength",
      25 : "MaxRFIDCodeLength",
      26 : "MinRFIDCodeLength",
      27 : "CredentialRulesSupport",
      28 : "NumberOfCredentialsSupportedPerUser",
      33 : "Language",
      34 : "LEDSettings",
      35 : "AutoRelockTime",
      36 : "SoundVolume",
      37 : "OperatingMode",
      38 : "SupportedOperatingModes",
      39 : "DefaultConfigurationRegister",
      40 : "EnableLocalProgramming",
      41 : "EnableOneTouchLocking",
      42 : "EnableInsideStatusLED",
      43 : "EnablePrivacyModeButton",
      44 : "LocalProgrammingFeatures",
      48 : "WrongCodeEntryLimit",
      49 : "UserCodeTemporaryDisableTime",
      50 : "SendPINOverTheAir",
      51 : "RequirePINforRemoteOperation",
      53 : "ExpiringUserTimeout",
      65528 : "GeneratedCommandList",
      65529 : "AcceptedCommandList",
      65531 : "AttributeList",
      65532 : "FeatureMap",
      65533 : "ClusterRevision",
    },
  },
  259 : {
    name : "Barrier Control",
    commands : {},
    attributes : {
      1 : "barrier moving state",
      2 : "barrier safety status",
      3 : "barrier capabilities",
      4 : "barrier open events",
      5 : "barrier close events",
      6 : "barrier command open events",
      7 : "barrier command close events",
      8 : "barrier open period",
      9 : "barrier close period",
      10 : "barrier position",
      65528 : "GeneratedCommandList",
      65529 : "AcceptedCommandList",
      65531 : "AttributeList",
      65532 : "FeatureMap",
      65533 : "ClusterRevision",
    },
  },
  513 : {
    name : "Thermostat",
    commands : {
      0 : {
        name : "GetWeeklyScheduleResponse",
        arguments : [
          "NumberOfTransitionsForSequence",
          "DayOfWeekForSequence",
          "ModeForSequence",
          "Transitions",
        ],
      },
    },
    attributes : {
      0 : "LocalTemperature",
      1 : "OutdoorTemperature",
      2 : "Occupancy",
      3 : "AbsMinHeatSetpointLimit",
      4 : "AbsMaxHeatSetpointLimit",
      5 : "AbsMinCoolSetpointLimit",
      6 : "AbsMaxCoolSetpointLimit",
      7 : "PICoolingDemand",
      8 : "PIHeatingDemand",
      9 : "HVACSystemTypeConfiguration",
      16 : "LocalTemperatureCalibration",
      17 : "OccupiedCoolingSetpoint",
      18 : "OccupiedHeatingSetpoint",
      19 : "UnoccupiedCoolingSetpoint",
      20 : "UnoccupiedHeatingSetpoint",
      21 : "MinHeatSetpointLimit",
      22 : "MaxHeatSetpointLimit",
      23 : "MinCoolSetpointLimit",
      24 : "MaxCoolSetpointLimit",
      25 : "MinSetpointDeadBand",
      26 : "RemoteSensing",
      27 : "ControlSequenceOfOperation",
      28 : "SystemMode",
      30 : "ThermostatRunningMode",
      32 : "StartOfWeek",
      33 : "NumberOfWeeklyTransitions",
      34 : "NumberOfDailyTransitions",
      35 : "TemperatureSetpointHold",
      36 : "TemperatureSetpointHoldDuration",
      37 : "ThermostatProgrammingOperationMode",
      41 : "ThermostatRunningState",
      48 : "SetpointChangeSource",
      49 : "SetpointChangeAmount",
      50 : "SetpointChangeSourceTimestamp",
      52 : "OccupiedSetback",
      53 : "OccupiedSetbackMin",
      54 : "OccupiedSetbackMax",
      55 : "UnoccupiedSetback",
      56 : "UnoccupiedSetbackMin",
      57 : "UnoccupiedSetbackMax",
      58 : "EmergencyHeatDelta",
      64 : "ACType",
      65 : "ACCapacity",
      66 : "ACRefrigerantType",
      67 : "ACCompressorType",
      68 : "ACErrorCode",
      69 : "ACLouverPosition",
      70 : "ACCoilTemperature",
      71 : "ACCapacityformat",
      65528 : "GeneratedCommandList",
      65529 : "AcceptedCommandList",
      65531 : "AttributeList",
      65532 : "FeatureMap",
      65533 : "ClusterRevision",
    },
  },
  514 : {
    name : "Fan Control",
    commands : {},
    attributes : {
      0 : "fan mode",
      1 : "fan mode sequence",
      2 : "percent setting",
      3 : "percent current",
      4 : "speed max",
      5 : "speed setting",
      6 : "speed current",
      7 : "rock support",
      8 : "rock setting",
      9 : "wind support",
      10 : "wind setting",
      65528 : "GeneratedCommandList",
      65529 : "AcceptedCommandList",
      65531 : "AttributeList",
      65532 : "FeatureMap",
      65533 : "ClusterRevision",
    },
  },
  516 : {
    name : "Thermostat User Interface Configuration",
    commands : {},
    attributes : {
      0 : "temperature display mode",
      1 : "keypad lockout",
      2 : "schedule programming visibility",
      65528 : "GeneratedCommandList",
      65529 : "AcceptedCommandList",
      65531 : "AttributeList",
      65532 : "FeatureMap",
      65533 : "ClusterRevision",
    },
  },
  768 : {
    name : "Color Control",
    commands : {},
    attributes : {
      0 : "CurrentHue",
      1 : "CurrentSaturation",
      2 : "RemainingTime",
      3 : "CurrentX",
      4 : "CurrentY",
      5 : "DriftCompensation",
      6 : "CompensationText",
      7 : "ColorTemperatureMireds",
      8 : "ColorMode",
      15 : "Options",
      16 : "NumberOfPrimaries",
      17 : "Primary1X",
      18 : "Primary1Y",
      19 : "Primary1Intensity",
      21 : "Primary2X",
      22 : "Primary2Y",
      23 : "Primary2Intensity",
      25 : "Primary3X",
      26 : "Primary3Y",
      27 : "Primary3Intensity",
      32 : "Primary4X",
      33 : "Primary4Y",
      34 : "Primary4Intensity",
      36 : "Primary5X",
      37 : "Primary5Y",
      38 : "Primary5Intensity",
      40 : "Primary6X",
      41 : "Primary6Y",
      42 : "Primary6Intensity",
      48 : "WhitePointX",
      49 : "WhitePointY",
      50 : "ColorPointRX",
      51 : "ColorPointRY",
      52 : "ColorPointRIntensity",
      54 : "ColorPointGX",
      55 : "ColorPointGY",
      56 : "ColorPointGIntensity",
      58 : "ColorPointBX",
      59 : "ColorPointBY",
      60 : "ColorPointBIntensity",
      16384 : "EnhancedCurrentHue",
      16385 : "EnhancedColorMode",
      16386 : "ColorLoopActive",
      16387 : "ColorLoopDirection",
      16388 : "ColorLoopTime",
      16389 : "ColorLoopStartEnhancedHue",
      16390 : "ColorLoopStoredEnhancedHue",
      16394 : "ColorCapabilities",
      16395 : "ColorTempPhysicalMinMireds",
      16396 : "ColorTempPhysicalMaxMireds",
      16397 : "CoupleColorTempToLevelMinMireds",
      16400 : "StartUpColorTemperatureMireds",
      65528 : "GeneratedCommandList",
      65529 : "AcceptedCommandList",
      65531 : "AttributeList",
      65532 : "FeatureMap",
      65533 : "ClusterRevision",
    },
  },
  1024 : {
    name : "Illuminance Measurement",
    commands : {},
    attributes : {
      0 : "MeasuredValue",
      1 : "MinMeasuredValue",
      2 : "MaxMeasuredValue",
      3 : "Tolerance",
      4 : "LightSensorType",
      65528 : "GeneratedCommandList",
      65529 : "AcceptedCommandList",
      65531 : "AttributeList",
      65532 : "FeatureMap",
      65533 : "ClusterRevision",
    },
  },
  1026 : {
    name : "Temperature Measurement",
    commands : {},
    attributes : {
      0 : "MeasuredValue",
      1 : "MinMeasuredValue",
      2 : "MaxMeasuredValue",
      3 : "Tolerance",
      65528 : "GeneratedCommandList",
      65529 : "AcceptedCommandList",
      65531 : "AttributeList",
      65532 : "FeatureMap",
      65533 : "ClusterRevision",
    },
  },
  1027 : {
    name : "Pressure Measurement",
    commands : {},
    attributes : {
      0 : "MeasuredValue",
      1 : "MinMeasuredValue",
      2 : "MaxMeasuredValue",
      3 : "Tolerance",
      16 : "ScaledValue",
      17 : "MinScaledValue",
      18 : "MaxScaledValue",
      19 : "ScaledTolerance",
      20 : "Scale",
      65528 : "GeneratedCommandList",
      65529 : "AcceptedCommandList",
      65531 : "AttributeList",
      65532 : "FeatureMap",
      65533 : "ClusterRevision",
    },
  },
  1029 : {
    name : "Relative Humidity Measurement",
    commands : {},
    attributes : {
      0 : "measured value",
      1 : "min measured value",
      2 : "max measured value",
      3 : "tolerance",
      65528 : "GeneratedCommandList",
      65529 : "AcceptedCommandList",
      65531 : "AttributeList",
      65532 : "FeatureMap",
      65533 : "ClusterRevision",
    },
  },
  1030 : {
    name : "Occupancy Sensing",
    commands : {},
    attributes : {
      0 : "occupancy",
      1 : "occupancy sensor type",
      2 : "occupancy sensor type bitmap",
      16 : "PIR occupied to unoccupied delay",
      17 : "PIR unoccupied to occupied delay",
      18 : "PIR unoccupied to occupied threshold",
      32 : "ultrasonic occupied to unoccupied delay",
      33 : "ultrasonic unoccupied to occupied delay",
      34 : "ultrasonic unoccupied to occupied threshold",
      48 : "physical contact occupied to unoccupied delay",
      49 : "physical contact unoccupied to occupied delay",
      50 : "physical contact unoccupied to occupied threshold",
      65528 : "GeneratedCommandList",
      65529 : "AcceptedCommandList",
      65531 : "AttributeList",
      65532 : "FeatureMap",
      65533 : "ClusterRevision",
    },
  },
  2820 : {
    name : "Electrical Measurement",
    commands : {
      0 : {
        name : "GetProfileInfoResponseCommand",
        arguments : [
          "profileCount",
          "profileIntervalPeriod",
          "maxNumberOfIntervals",
          "listOfAttributes",
        ],
      },
      1 : {
        name : "GetMeasurementProfileResponseCommand",
        arguments : [
          "startTime",
          "status",
          "profileIntervalPeriod",
          "numberOfIntervalsDelivered",
          "attributeId",
          "intervals",
        ],
      },
    },
    attributes : {
      0 : "measurement type",
      256 : "dc voltage",
      257 : "dc voltage min",
      258 : "dc voltage max",
      259 : "dc current",
      260 : "dc current min",
      261 : "dc current max",
      262 : "dc power",
      263 : "dc power min",
      264 : "dc power max",
      512 : "dc voltage multiplier",
      513 : "dc voltage divisor",
      514 : "dc current multiplier",
      515 : "dc current divisor",
      516 : "dc power multiplier",
      517 : "dc power divisor",
      768 : "ac frequency",
      769 : "ac frequency min",
      770 : "ac frequency max",
      771 : "neutral current",
      772 : "total active power",
      773 : "total reactive power",
      774 : "total apparent power",
      775 : "measured 1st harmonic current",
      776 : "measured 3rd harmonic current",
      777 : "measured 5th harmonic current",
      778 : "measured 7th harmonic current",
      779 : "measured 9th harmonic current",
      780 : "measured 11th harmonic current",
      781 : "measured phase 1st harmonic current",
      782 : "measured phase 3rd harmonic current",
      783 : "measured phase 5th harmonic current",
      784 : "measured phase 7th harmonic current",
      785 : "measured phase 9th harmonic current",
      786 : "measured phase 11th harmonic current",
      1024 : "ac frequency multiplier",
      1025 : "ac frequency divisor",
      1026 : "power multiplier",
      1027 : "power divisor",
      1028 : "harmonic current multiplier",
      1029 : "phase harmonic current multiplier",
      1280 : "instantaneous voltage",
      1281 : "instantaneous line current",
      1282 : "instantaneous active current",
      1283 : "instantaneous reactive current",
      1284 : "instantaneous power",
      1285 : "rms voltage",
      1286 : "rms voltage min",
      1287 : "rms voltage max",
      1288 : "rms current",
      1289 : "rms current min",
      1290 : "rms current max",
      1291 : "active power",
      1292 : "active power min",
      1293 : "active power max",
      1294 : "reactive power",
      1295 : "apparent power",
      1296 : "power factor",
      1297 : "average rms voltage measurement period",
      1299 : "average rms under voltage counter",
      1300 : "rms extreme over voltage period",
      1301 : "rms extreme under voltage period",
      1302 : "rms voltage sag period",
      1303 : "rms voltage swell period",
      1536 : "ac voltage multiplier",
      1537 : "ac voltage divisor",
      1538 : "ac current multiplier",
      1539 : "ac current divisor",
      1540 : "ac power multiplier",
      1541 : "ac power divisor",
      1792 : "overload alarms mask",
      1793 : "voltage overload",
      1794 : "current overload",
      2048 : "ac overload alarms mask",
      2049 : "ac voltage overload",
      2050 : "ac current overload",
      2051 : "ac active power overload",
      2052 : "ac reactive power overload",
      2053 : "average rms over voltage",
      2054 : "average rms under voltage",
      2055 : "rms extreme over voltage",
      2056 : "rms extreme under voltage",
      2057 : "rms voltage sag",
      2058 : "rms voltage swell",
      2305 : "line current phase b",
      2306 : "active current phase b",
      2307 : "reactive current phase b",
      2309 : "rms voltage phase b",
      2310 : "rms voltage min phase b",
      2311 : "rms voltage max phase b",
      2312 : "rms current phase b",
      2313 : "rms current min phase b",
      2314 : "rms current max phase b",
      2315 : "active power phase b",
      2316 : "active power min phase b",
      2317 : "active power max phase b",
      2318 : "reactive power phase b",
      2319 : "apparent power phase b",
      2320 : "power factor phase b",
      2321 : "average rms voltage measurement period phase b",
      2322 : "average rms over voltage counter phase b",
      2323 : "average rms under voltage counter phase b",
      2324 : "rms extreme over voltage period phase b",
      2325 : "rms extreme under voltage period phase b",
      2326 : "rms voltage sag period phase b",
      2327 : "rms voltage swell period phase b",
      2561 : "line current phase c",
      2562 : "active current phase c",
      2563 : "reactive current phase c",
      2565 : "rms voltage phase c",
      2566 : "rms voltage min phase c",
      2567 : "rms voltage max phase c",
      2568 : "rms current phase c",
      2569 : "rms current min phase c",
      2570 : "rms current max phase c",
      2571 : "active power phase c",
      2572 : "active power min phase c",
      2573 : "active power max phase c",
      2574 : "reactive power phase c",
      2575 : "apparent power phase c",
      2576 : "power factor phase c",
      2577 : "average rms voltage measurement period phase c",
      2578 : "average rms over voltage counter phase c",
      2579 : "average rms under voltage counter phase c",
      2580 : "rms extreme over voltage period phase c",
      2581 : "rms extreme under voltage period phase c",
      2582 : "rms voltage sag period phase c",
      2583 : "rms voltage swell period phase c",
      65528 : "GeneratedCommandList",
      65529 : "AcceptedCommandList",
      65531 : "AttributeList",
      65532 : "FeatureMap",
      65533 : "ClusterRevision",
    },
  },

  enums : {
    "ActionErrorEnum" : [
      "unknown",
      "interrupted",
    ], //
    "ActionStateEnum" : [
      "Inactive",
      "Active",
      "Paused",
      "Disabled",
    ], //
    "ActionTypeEnum" : [
      "other",
      "scene",
      "sequence",
      "automation",
      "exception",
      "notification",
      "alarm",
    ], //
    "AmiRegistrationState" : [
      "Unregistered",
      "JoiningNetwork",
      "JoinedNetwork",
      "SubmittedRegistrationRequest",
      "RegistrationRejected",
      "Registered",
      "RegisterationNotPossible",
    ], //
    "AnonymousDataState" : [
      "NoSourceFound",
      "SourceFound",
    ], //
    "ApplicationLauncherStatusEnum" : [
      "Success",
      "AppNotAvailable",
      "SystemBusy",
    ], //
    "ApplicationStatusEnum" : [
      "Stopped",
      "ActiveVisibleFocus",
      "ActiveHidden",
      "ActiveVisibleNotFocus",
    ], //
    "AssociationFailureCause" : [
      "Unknown",
      "AssociationFailed",
      "AuthenticationFailed",
      "SsidNotFound",
    ], //
    "AttributeWritePermission" : [
      "DenyWrite",
      "AllowWriteNormal",
      "AllowWriteOfReadOnly",
      "UnsupportedAttribute",
      "InvalidValue",
      "ReadOnly",
      "InvalidDataType",
    ], //
    "AuthMode" : [
      "PASE",
      "CASE",
      "Group",
    ], //
    "BarrierControlBarrierPosition" : [
      "Closed",
      "Open",
      "Unknown",
    ], //
    "BarrierControlMovingState" : [
      "Stopped",
      "Closing",
      "Opening",
    ], //
    "BatChargeFault" : [
      "Unspecfied",
      "AmbientTooHot",
      "AmbientTooCold",
      "BatteryTooHot",
      "BatteryTooCold",
      "BatteryAbsent",
      "BatteryOverVoltage",
      "BatteryUnderVoltage",
      "ChargerOverVoltage",
      "ChargerUnderVoltage",
      "SafetyTimeout",
    ], //
    "BatChargeLevel" : [
      "Ok",
      "Warning",
      "Critical",
    ], //
    "BatChargeState" : [
      "Unknown",
      "IsCharging",
      "IsAtFullCharge",
      "IsNotCharging",
    ], //
    "BatFault" : [
      "Unspecfied",
      "OverTemp",
      "UnderTemp",
    ], //
    "BatReplaceability" : [
      "Unspecified",
      "NotReplaceable",
      "UserReplaceable",
      "FactoryReplaceable",
    ], //
    "BatterySize" : [
      "NoBattery",
      "BuiltIn",
      "Other",
      "AA",
      "AAA",
      "C",
      "D",
      "Unknown",
    ], //
    "BootReasonType" : [
      "Unspecified",
      "PowerOnReboot",
      "BrownOutReset",
      "SoftwareWatchdogReset",
      "HardwareWatchdogReset",
      "SoftwareUpdateCompleted",
      "SoftwareReset",
    ], //
    "CalendarType" : [
      "Buddhist",
      "Chinese",
      "Coptic",
      "Ethiopian",
      "Gregorian",
      "Hebrew",
      "Indian",
      "Islamic",
      "Japanese",
      "Korean",
      "Persian",
      "Taiwanese",
    ], //
    "CecKeyCode" : [
      "Select",
      "Up",
      "Down",
      "Left",
      "Right",
      "RightUp",
      "RightDown",
      "LeftUp",
      "LeftDown",
      "RootMenu",
      "SetupMenu",
      "ContentsMenu",
      "FavoriteMenu",
      "Exit",
      "MediaTopMenu",
      "MediaContextSensitiveMenu",
      "NumberEntryMode",
      "Number11",
      "Number12",
      "Number0OrNumber10",
      "Numbers1",
      "Numbers2",
      "Numbers3",
      "Numbers4",
      "Numbers5",
      "Numbers6",
      "Numbers7",
      "Numbers8",
      "Numbers9",
      "Dot",
      "Enter",
      "Clear",
      "NextFavorite",
      "ChannelUp",
      "ChannelDown",
      "PreviousChannel",
      "SoundSelect",
      "InputSelect",
      "DisplayInformation",
      "Help",
      "PageUp",
      "PageDown",
      "Power",
      "VolumeUp",
      "VolumeDown",
      "Mute",
      "Play",
      "Stop",
      "Pause",
      "Record",
      "Rewind",
      "FastForward",
      "Eject",
      "Forward",
      "Backward",
      "StopRecord",
      "PauseRecord",
      "Reserved",
      "Angle",
      "SubPicture",
      "VideoOnDemand",
      "ElectronicProgramGuide",
      "TimerProgramming",
      "InitialConfiguration",
      "SelectBroadcastType",
      "SelectSoundPresentation",
      "PlayFunction",
      "PausePlayFunction",
      "RecordFunction",
      "PauseRecordFunction",
      "StopFunction",
      "MuteFunction",
      "RestoreVolumeFunction",
      "TuneFunction",
      "SelectMediaFunction",
      "SelectAvInputFunction",
      "SelectAudioInputFunction",
      "PowerToggleFunction",
      "PowerOffFunction",
      "PowerOnFunction",
      "F1Blue",
      "F2Red",
      "F3Green",
      "F4Yellow",
      "F5",
      "Data",
    ], //
    "CecedSpecificationVersion" : [
      "CompliantWithV10NotCertified",
      "CompliantWithV10Certified",
    ], //
    "ChangeTypeEnum" : [
      "Changed",
      "Added",
      "Removed",
    ], //
    "ChannelStatusEnum" : [
      "Success",
      "MultipleMatches",
      "NoMatches",
    ], //
    "ColorControlOptions" : [
      "ExecuteIfOff",
    ], //
    "ColorLoopAction" : [
      "Deactivate",
      "ActivateFromColorLoopStartEnhancedHue",
      "ActivateFromEnhancedCurrentHue",
    ], //
    "ColorLoopDirection" : [
      "DecrementHue",
      "IncrementHue",
    ], //
    "ColorMode" : [
      "CurrentHueAndCurrentSaturation",
      "CurrentXAndCurrentY",
      "ColorTemperature",
    ], //
    "CommissioningError" : [
      "Ok",
      "ValueOutsideRange",
      "InvalidAuthentication",
      "NoFailSafe",
      "BusyWithOtherAdmin",
    ], //
    "CommissioningWindowStatus" : [
      "WindowNotOpen",
      "EnhancedWindowOpen",
      "BasicWindowOpen",
    ], //
    "ContentLaunchStatusEnum" : [
      "success",
      "urlNotAvailable",
      "authFailed",
    ], //
    "DataQualityId" : [
      "AllDataCertified",
      "OnlyInstantaneousPowerNotCertified",
      "OnlyCumulatedConsumptionNotCertified",
      "NotCertifiedData",
    ], //
    "DehumidifcationLockout" : [
      "notAllowed",
      "allowed",
    ], //
    "DeviceStatus2Structure" : [
      "IrisSymptomCode",
    ], //
    "DlAlarmCode" : [
      "LockJammed",
      "LockFactoryReset",
      "LockRadioPowerCycled",
      "WrongCodeEntryLimit",
      "FrontEsceutcheonRemoved",
      "DoorForcedOpen",
      "DoorAjar",
      "ForcedUser",
    ], //
    "DlCredentialRule" : [
      "Single",
      "Double",
      "Tri",
    ], //
    "DlCredentialType" : [
      "ProgrammingPIN",
      "PIN",
      "RFID",
      "Fingerprint",
      "FingerVein",
      "Face",
    ], //
    "DlDataOperationType" : [
      "Add",
      "Clear",
      "Modify",
    ], //
    "DlDoorState" : [
      "DoorOpen",
      "DoorClosed",
      "DoorJammed",
      "DoorForcedOpen",
      "DoorUnspecifiedError",
      "DoorAjar",
    ], //
    "DlLockDataType" : [
      "Unspecified",
      "ProgrammingCode",
      "UserIndex",
      "WeekDaySchedule",
      "YearDaySchedule",
      "HolidaySchedule",
      "PIN",
      "RFID",
      "Fingerprint",
    ], //
    "DlLockOperationType" : [
      "Lock",
      "Unlock",
      "NonAccessUserEvent",
      "ForcedUserEvent",
    ], //
    "DlLockState" : [
      "NotFullyLocked",
      "Locked",
      "Unlocked",
    ], //
    "DlLockType" : [
      "DeadBolt",
      "Magnetic",
      "Other",
      "Mortise",
      "Rim",
      "LatchBolt",
      "CylindricalLock",
      "TubularLock",
      "InterconnectedLock",
      "Dead Latch",
      "Door Furniture",
    ], //
    "DlOperatingMode" : [
      "Normal",
      "Vacation",
      "Privacy",
      "NoRemoteLockUnlock",
      "Passage",
    ], //
    "DlOperationError" : [
      "Unspecified",
      "InvalidCredential",
      "DisabledUserDenied",
      "Restricted",
      "InsufficientBattery",
    ], //
    "DlOperationSource" : [
      "Unspecified",
      "Manual",
      "ProprietaryRemote",
      "Keypad",
      "Auto",
      "Button",
      "Schedule",
      "Remote",
      "RFID",
      "Biometric",
    ], //
    "DlStatus" : [
      "Success",
      "Failure",
      "Duplicate",
      "Occupied",
      "InvalidField",
      "ResourceExhausted",
      "NotFound",
    ], //
    "DlUserStatus" : [
      "Available",
      "OccupiedEnabled",
      "OccupiedDisabled",
    ], //
    "DlUserType" : [
      "UnrestrictedUser",
      "YearDayScheduleUser",
      "WeekDayScheduleUser",
      "ProgrammingUser",
      "NonAccessUser",
      "ForcedUser",
      "DisposableUser",
      "ExpiringUser",
      "ScheduleRestrictedUser",
      "RemoteOnlyUser",
    ], //
    "DoorLockEventSource" : [
      "Keypad",
      "Rf",
      "Manual",
      "Rfid",
      "Indeterminate",
    ], //
    "DoorLockEventType" : [
      "Operation",
      "Programming",
      "Alarm",
    ], //
    "DoorLockOperatingMode" : [
      "NormalMode",
      "VacationMode",
      "PrivacyMode",
      "NoRfLockOrUnlock",
      "LocalProgrammingMode",
      "PassageMode",
    ], //
    "DoorLockOperationEventCode" : [
      "UnknownOrMfgSpecific",
      "Lock",
      "Unlock",
      "LockInvalidPinOrId",
      "LockInvalidSchedule",
      "UnlockInvalidPinOrId",
      "UnlockInvalidSchedule",
      "OneTouchLock",
      "KeyLock",
      "KeyUnlock",
      "AutoLock",
      "ScheduleLock",
      "ScheduleUnlock",
      "ManualLock",
      "ManualUnlock",
    ], //
    "DoorLockProgrammingEventCode" : [
      "UnknownOrMfgSpecific",
      "MasterCodeChanged",
      "PinAdded",
      "PinDeleted",
      "PinChanged",
      "IdAdded",
      "IdDeleted",
    ], //
    "DoorLockSecurityLevel" : [
      "NetworkSecurity",
      "ApsSecurity",
    ], //
    "DoorLockSetPinOrIdStatus" : [
      "Success",
      "GeneralFailure",
      "MemoryFull",
      "DuplicateCodeError",
    ], //
    "DoorLockSoundVolume" : [
      "Silent",
      "Low",
      "High",
    ], //
    "DoorLockState" : [
      "NotFullyLocked",
      "Locked",
      "Unlocked",
    ], //
    "DoorLockType" : [
      "DeadBolt",
      "Magnetic",
      "Mortise",
      "Rim",
      "LatchBolt",
      "Cylindrical",
      "Tubular",
      "Interconnected",
      "DeadLatch",
      "Other",
    ], //
    "DoorLockUserStatus" : [
      "Available",
      "OccupiedEnabled",
      "OccupiedDisabled",
      "NotSupported",
    ], //
    "DoorLockUserType" : [
      "Unrestricted",
      "YearDayScheduleUser",
      "WeekDayScheduleUser",
      "MasterUser",
      "NonAccessUser",
      "NotSupported",
    ], //
    "DoorState" : [
      "Open",
      "Closed",
      "ErrorJammed",
      "ErrorForcedOpen",
      "ErrorUnspecified",
    ], //
    "EndProductType" : [
      "RollerShade",
      "RomanShade",
      "BalloonShade",
      "WovenWood",
      "PleatedShade",
      "CellularShade",
      "LayeredShade",
      "LayeredShade2D",
      "SheerShade",
      "TiltOnlyInteriorBlind",
      "InteriorBlind",
      "VerticalBlindStripCurtain",
      "InteriorVenetianBlind",
      "ExteriorVenetianBlind",
      "LateralLeftCurtain",
      "LateralRightCurtain",
      "CentralCurtain",
      "RollerShutter",
      "ExteriorVerticalScreen",
      "AwningTerracePatio",
      "AwningVerticalScreen",
      "TiltOnlyPergola",
      "SwingingShutter",
      "SlidingShutter",
      "Unknown",
    ], //
    "EndpointListTypeEnum" : [
      "other",
      "room",
      "zone",
    ], //
    "EnhancedColorMode" : [
      "CurrentHueAndCurrentSaturation",
      "CurrentXAndCurrentY",
      "ColorTemperature",
      "EnhancedCurrentHueAndCurrentSaturation",
    ], //
    "FanMode" : [
      "off",
      "low",
      "medium",
      "high",
      "on",
      "auto",
      "smart",
    ], //
    "FanModeSequence" : [
      "LowMedHigh",
      "lowHigh",
      "LowMedHighAuto",
      "lowHighAuto",
      "onAuto",
    ], //
    "FanModeSequenceType" : [
      "Off/Low/Med/High",
      "Off/Low/High",
      "Off/Low/Med/High/Auto",
      "Off/Low/High/Auto",
      "Off/On/Auto",
      "Off/On",
    ], //
    "FanModeType" : [
      "Off",
      "Low",
      "Medium",
      "High",
      "On",
      "Auto",
      "Smart",
    ], //
    "FaultType" : [
      "Unspecified",
      "SystemFault",
      "InetFault",
      "ChipFault",
      "CertFault",
    ], //
    "GenericDeviceType" : [
      "Incandescent",
      "SpotlightHalogen",
      "HalogenBulb",
      "CFL",
      "LinearFlourescent",
      "LedBulb",
      "SpotlightLed",
      "LedStrip",
      "LedTube",
      "GenericIndoorFixture",
      "GenericOutdoorFixture",
      "PendantFixture",
      "FloorStandingFixture",
      "GenericController",
      "WallSwitch",
      "PortableRemoteController",
      "MotionOrLightSensor",
      "GenericActuator",
      "PluginUnit",
      "RetrofitActuator",
      "Unspecified",
    ], //
    "GranularityEnum" : [
      "NoTimeGranularity",
      "MinutesGranularity",
      "SecondsGranularity",
      "MillisecondsGranularity",
      "MicrosecondsGranularity",
    ], //
    "GroupKeySecurityPolicy" : [
      "TrustFirst",
      "CacheAndSync",
    ], //
    "HardwareFaultType" : [
      "Unspecified",
      "Radio",
      "Sensor",
      "ResettableOverTemp",
      "NonResettableOverTemp",
      "PowerSource",
      "VisualDisplayFault",
      "AudioOutputFault",
      "UserInterfaceFault",
      "NonVolatileMemoryError",
      "TamperDetected",
    ], //
    "HourFormat" : [
      "12hr",
      "24hr",
    ], //
    "HueDirection" : [
      "ShortestDistance",
      "LongestDistance",
      "Up",
      "Down",
    ], //
    "HueMoveMode" : [
      "stop",
      "Up",
      "Down",
    ], //
    "HueStepMode" : [
      "Up",
      "Down",
    ], //
    "IdentifyEffectIdentifier" : [
      "Blink",
      "Breathe",
      "Okay",
      "ChannelChange",
      "FinishEffect",
      "StopEffect",
    ], //
    "IdentifyEffectVariant" : [
      "Default",
    ], //
    "IdentifyIdentifyType" : [
      "None",
      "VisibleLight",
      "VisibleLED",
      "AudibleBeep",
      "Display",
      "Actuator",
    ], //
    "InputTypeEnum" : [
      "Internal",
      "Aux",
      "Coax",
      "Composite",
      "Hdmi",
      "Input",
      "Line",
      "Optical",
      "Video",
      "Scart",
      "Usb",
      "Other",
    ], //
    "InterfaceType" : [
      "Unspecified",
      "WiFi",
      "Ethernet",
      "Cellular",
      "Thread",
    ], //
    "KeypadInputStatusEnum" : [
      "Success",
      "UnsupportedKey",
      "InvalidKeyInCurrentState",
    ], //
    "KeypadLockout" : [
      "noLockout",
      "levelOneLockout",
      "levelTwoLockout",
      "levelThreeLockout",
      "levelFourLockout",
      "levelfiveLockout",
    ], //
    "LevelStatus" : [
      "OnTarget",
      "BelowTarget",
      "AboveTarget",
    ], //
    "LightSensorType" : [
      "Photodiode",
      "CMOS",
    ], //
    "LineupInfoTypeEnum" : [
      "Mso",
    ], //
    "LogsIntent" : [
      "EndUserSupport",
      "NetworkDiag",
      "CrashLogs",
    ], //
    "LogsStatus" : [
      "Success",
      "Exhausted",
      "NoLogs",
      "Busy",
      "Denied",
    ], //
    "LogsTransferProtocol" : [
      "ResponsePayload",
      "BDX",
    ], //
    "MediaPlaybackStatusEnum" : [
      "Success",
      "InvalidStateForCommand",
      "NotAllowed",
      "NotActive",
      "SpeedOutOfRange",
      "SeekOutOfRange",
    ], //
    "MeterTypeId" : [
      "UtilityPrimaryMeter",
      "UtilityProductionMeter",
      "UtilitySecondaryMeter",
      "PrivatePrimaryMeter",
      "PrivateProductionMeter",
      "PrivateSecondaryMeters",
      "GenericMeter",
    ], //
    "MetricTypeEnum" : [
      "PIXELS",
      "PERCENTAGE",
    ], //
    "MoveMode" : [
      "Up",
      "Down",
    ], //
    "NetworkCommissioningStatus" : [
      "Success",
      "OutOfRange",
      "BoundsExceeded",
      "NetworkIDNotFound",
      "DuplicateNetworkID",
      "NetworkNotFound",
      "RegulatoryError",
      "AuthFailure",
      "UnsupportedSecurity",
      "OtherConnectionFailure",
      "IPV6Failed",
      "IPBindFailed",
      "UnknownError",
    ], //
    "NetworkFault" : [
      "Unspecified",
      "LinkDown",
      "HardwareFailure",
      "NetworkJammed",
    ], //
    "NetworkFaultType" : [
      "Unspecified",
      "HardwareFailure",
      "NetworkJammed",
      "ConnectionFailed",
    ], //
    "OTAAnnouncementReason" : [
      "SimpleAnnouncement",
      "UpdateAvailable",
      "UrgentUpdateAvailable",
    ], //
    "OTAApplyUpdateAction" : [
      "Proceed",
      "AwaitNextAction",
      "Discontinue",
    ], //
    "OTAChangeReasonEnum" : [
      "Unknown",
      "Success",
      "Failure",
      "TimeOut",
      "DelayByProvider",
    ], //
    "OTADownloadProtocol" : [
      "BDXSynchronous",
      "BDXAsynchronous",
      "HTTPS",
      "VendorSpecific",
    ], //
    "OTAQueryStatus" : [
      "UpdateAvailable",
      "Busy",
      "NotAvailable",
      "DownloadProtocolNotSupported",
    ], //
    "OTAUpdateStateEnum" : [
      "Unknown",
      "Idle",
      "Querying",
      "DelayedOnQuery",
      "Downloading",
      "Applying",
      "DelayedOnApply",
      "RollingBack",
      "DelayedOnUserConsent",
    ], //
    "OccupancySensorType" : [
      "PIR",
      "Ultrasonic",
      "pirAndUltrasonic",
      "physicalContact",
    ], //
    "OnOffDelayedAllOffEffectVariant" : [
      "FadeToOffIn_0p8Seconds",
      "NoFade",
      "50PercentDimDownIn_0p8SecondsThenFadeToOffIn_12Seconds",
    ], //
    "OnOffDyingLightEffectVariant" : [
      "20PercenterDimUpIn_0p5SecondsThenFadeToOffIn_1Second",
    ], //
    "OnOffEffectIdentifier" : [
      "DelayedAllOff",
      "DyingLight",
    ], //
    "OnOffStartUpOnOff" : [
      "Off",
      "On",
      "TogglePreviousOnOff",
    ], //
    "OperatingMode" : [
      "normal",
      "configure",
    ], //
    "OperationalCertStatus" : [
      "SUCCESS",
      "InvalidPublicKey",
      "InvalidNodeOpId",
      "InvalidNOC",
      "MissingCsr",
      "TableFull",
      "InvalidAdminSubject",
      "FabricConflict",
      "LabelConflict",
      "InvalidFabricIndex",
    ], //
    "OutputTypeEnum" : [
      "Hdmi",
      "Bt",
      "Optical",
      "Headphone",
      "Internal",
      "Other",
    ], //
    "PHYRateType" : [
      "10M",
      "100M",
      "1000M",
      "2.5G",
      "5G",
      "10G",
      "40G",
      "100G",
      "200G",
      "400G",
    ], //
    "ParameterEnum" : [
      "actor",
      "channel",
      "character",
      "director",
      "event",
      "franchise",
      "genre",
      "league",
      "popularity",
      "provider",
      "sport",
      "sportsTeam",
      "type",
    ], //
    "PhysicalEnvironment" : [
      "Unspecified",
      "FirstProfileSpecifiedValue",
      "LastProfileSpecifiedValue",
      "Unknown",
    ], //
    "PlaybackStateEnum" : [
      "Playing",
      "Paused",
      "NotPlaying",
      "Buffering",
    ], //
    "PowerProfileState" : [
      "PowerProfileWaitingToStart",
      "PowerProfileStarted",
      "EnergyPhaseRunning",
      "EnergyPhaseEnded",
      "EnergyPhaseWaitingToStart",
      "EnergyPhaseStarted",
      "PowerProfileEnded",
      "ProfileReadyForScheduling",
      "PowerProfileScheduled",
    ], //
    "PowerSource" : [
      "Unknown",
      "SinglePhaseMains",
      "ThreePhaseMains",
      "Battery",
      "DcSource",
      "EmergencyMainsConstantPower",
      "EmergencyMainsTransferSwitch",
      "BatteryBackup",
    ], //
    "PowerSourceStatus" : [
      "Unspecfied",
      "Active",
      "Standby",
      "Unavailable",
    ], //
    "Privilege" : [
      "View",
      "ProxyView",
      "Operate",
      "Manage",
      "Administer",
    ], //
    "ProductCode" : [
      "ManufacturerDefined",
      "IternationalArticleNumber",
      "GlobalTradeItemNumber",
      "UniversalProductCode",
      "StockKeepingUnit",
    ], //
    "ProductTypeId" : [
      "WhiteGoods",
      "Dishwasher",
      "TumbleDryer",
      "WasherDryer",
      "WashingMachine",
      "Hobs",
      "InductionHobs",
      "Oven",
      "ElectricalOven",
      "RefrigeratorFreezer",
    ], //
    "PumpControlMode" : [
      "ConstantSpeed",
      "ConstantPressure",
      "ProportionalPressure",
      "ConstantFlow",
      "ConstantTemperature",
      "Automatic",
    ], //
    "PumpOperationMode" : [
      "Normal",
      "Minimum",
      "Maximum",
      "Local",
    ], //
    "RadioFaultType" : [
      "Unspecified",
      "WiFiFault",
      "CellularFault",
      "ThreadFault",
      "NFCFault",
      "BLEFault",
      "EthernetFault",
    ], //
    "RegulatoryLocationType" : [
      "Indoor",
      "Outdoor",
      "IndoorOutdoor",
    ], //
    "RelativeHumidityDisplay" : [
      "notDisplayed",
      "displayed",
    ], //
    "RelativeHumidityMode" : [
      "measureLocally",
      "updatedOverTheNetwork",
    ], //
    "RemoteEnableFlags" : [
      "Disabled",
      "TemporarilyLockedDisabled",
      "EnabledRemoteControl",
      "EnabledRemoteAndEnergyControl",
    ], //
    "RoutingRole" : [
      "Unspecified",
      "Unassigned",
      "SleepyEndDevice",
      "EndDevice",
      "REED",
      "Router",
      "Leader",
    ], //
    "SaturationMoveMode" : [
      "stop",
      "Up",
      "Down",
    ], //
    "SaturationStepMode" : [
      "Up",
      "Down",
    ], //
    "SecurityType" : [
      "Unspecified",
      "None",
      "WEP",
      "WPA",
      "WPA2",
      "WPA3",
    ], //
    "SetpointAdjustMode" : [
      "heatSetpoint",
      "coolSetpoint",
      "heatAndCoolSetpoints",
    ], //
    "SimpleEnum" : [
      "Unspecified",
      "ValueA",
      "ValueB",
      "ValueC",
    ], //
    "SquawkLevel" : [
      "lowLevel",
      "mediumLevel",
      "highLevel",
      "veryHighLevel",
    ], //
    "SquawkMode" : [
      "systemIsArmed",
      "systemIsDisarmed",
    ], //
    "SquawkStobe" : [
      "noStrobe",
      "useStrobe",
    ], //
    "StartOfWeek" : [
      "Sunday",
      "Monday",
      "Tuesday",
      "Wednesday",
      "Thursday",
      "Friday",
      "Saturday",
    ], //
    "StartUpOnOffValue" : [
      "SetToOff",
      "SetToOn",
      "SetToToggle",
    ], //
    "Status" : [
      "SUCCESS",
      "FAILURE",
      "NOT_AUTHORIZED",
      "MALFORMED_COMMAND",
      "UNSUP_COMMAND",
      "UNSUP_GENERAL_COMMAND",
      "UNSUP_MANUF_CLUSTER_COMMAND",
      "UNSUP_MANUF_GENERAL_COMMAND",
      "INVALID_FIELD",
      "UNSUPPORTED_ATTRIBUTE",
      "INVALID_VALUE",
      "READ_ONLY",
      "INSUFFICIENT_SPACE",
      "DUPLICATE_EXISTS",
      "NOT_FOUND",
      "UNREPORTABLE_ATTRIBUTE",
      "INVALID_DATA_TYPE",
      "INVALID_SELECTOR",
      "WRITE_ONLY",
      "INCONSISTENT_STARTUP_STATE",
      "DEFINED_OUT_OF_BAND",
      "ACTION_DENIED",
      "TIMEOUT",
      "ABORT",
      "INVALID_IMAGE",
      "WAIT_FOR_DATA",
      "NO_IMAGE_AVAILABLE",
      "REQUIRE_MORE_IMAGE",
      "NOTIFICATION_PENDING",
      "HARDWARE_FAILURE",
      "SOFTWARE_FAILURE",
      "UNSUPPORTED_CLUSTER",
      "LIMIT_REACHED",
    ], //
    "StatusCode" : [
      "Busy",
      "PAKEParameterError",
      "WindowNotOpen",
    ], //
    "StepMode" : [
      "Up",
      "Down",
    ], //
    "SwitchActions" : [
      "On",
      "Off",
      "Toggle",
    ], //
    "SwitchType" : [
      "Toggle",
      "Momentary",
      "MultiFunction",
    ], //
    "TargetNavigatorStatusEnum" : [
      "Success",
      "TargetNotFound",
      "NotAllowed",
    ], //
    "TempUnit" : [
      "Fahrenheit",
      "Celsius",
      "Kelvin",
    ], //
    "TemperatureDisplayMode" : [
      "celsius",
      "fahrenheit",
    ], //
    "TemperatureSetpointHold" : [
      "SetpointHoldOff",
      "SetpointHoldOn",
    ], //
    "ThermostatControlSequence" : [
      "coolingOnly",
      "coolingWithReheat",
      "heatingOnly",
      "heatingWithReheat",
      "coolingAndHeating",
      "coolingAndHeatingWithReheat",
    ], //
    "ThermostatRunningMode" : [
      "Off",
      "Cool",
      "Heat",
    ], //
    "ThermostatSystemMode" : [
      "off",
      "auto",
      "cool",
      "heat",
      "emergencyHeating",
      "precooling",
      "fanOnly",
    ], //
    "ThreadConnectionStatus" : [
      "Connected",
      "NotConnected",
    ], //
    "TimeEncoding" : [
      "Relative",
      "Absolute",
    ], //
    "TimeSourceEnum" : [
      "None",
      "Unknown",
      "Admin",
      "NodeTimeCluster",
      "NonFabricSntp",
      "NonFabricNtp",
      "FabricSntp",
      "FabricNtp",
      "MixedNtp",
      "NonFabricSntpNts",
      "NonFabricNtpNts",
      "FabricSntpNts",
      "FabricNtpNts",
      "MixedNtpNts",
      "CloudSource",
      "Ptp",
      "Gnss",
    ], //
    "Type" : [
      "RollerShade",
      "RollerShade2Motor",
      "RollerShadeExterior",
      "RollerShadeExterior2Motor",
      "Drapery",
      "Awning",
      "Shutter",
      "TiltBlindTiltOnly",
      "TiltBlindLiftAndTilt",
      "ProjectorScreen",
      "Unknown",
    ], //
    "WarningMode" : [
      "stop",
      "burglar",
      "fire",
      "emergency",
      "policePanic",
      "firePanic",
      "emergencyPanic",
    ], //
    "WarningStobe" : [
      "noStrobe",
      "useStrobe",
    ], //
    "WiFiBand" : [
      "2G4",
      "3G65",
      "5G",
      "6G",
      "60G",
    ], //
    "WiFiConnectionStatus" : [
      "Connected",
      "NotConnected",
    ], //
    "WiFiVersionType" : [
      "802.11a",
      "802.11b",
      "802.11g",
      "802.11n",
      "802.11ac",
      "802.11ax",
    ], //
    "WiredCurrentType" : [
      "AC",
      "DC",
    ], //
    "WiredFault" : [
      "Unspecfied",
      "OverVoltage",
      "UnderVoltage",
    ], //
  },

  bitmaps : {
    "AlarmMask" : {
      1 : "GeneralHwFault",
      2 : "GeneralSwFault",
    },
    "ApplicationLauncherFeature" : {
      1 : "ApplicationPlatform",
    },
    "AudioOutputFeature" : {
      1 : "NameUpdates",
    },
    "BallastStatus" : {
      1 : "NonOperational",
      2 : "LampNotInSocket",
    },
    "BarrierControlCapabilities" : {
      1 : "partialBarrier",
    },
    "BarrierControlSafetyStatus" : {
      1 : "remoteLockout",
      2 : "temperDetected",
      4 : "failedCommunication",
      8 : "positionFailure",
    },
    "BatteryAlarmMask" : {
      1 : "VoltageTooLow",
    },
    "Bitmap16MaskMap" : {
      1 : "MaskVal1",
      2 : "MaskVal2",
      4 : "MaskVal3",
      16384 : "MaskVal4",
    },
    "Bitmap32MaskMap" : {
      1 : "MaskVal1",
      2 : "MaskVal2",
      4 : "MaskVal3",
      1073741824 : "MaskVal4",
    },
    "Bitmap64MaskMap" : {
      1 : "MaskVal1",
      2 : "MaskVal2",
      4 : "MaskVal3",
      4611686018427388000 : "MaskVal4",
    },
    "Bitmap8MaskMap" : {
      1 : "MaskVal1",
      2 : "MaskVal2",
      4 : "MaskVal3",
      64 : "MaskVal4",
    },
    "ChannelFeature" : {
      1 : "ChannelList",
      2 : "LineupInfo",
    },
    "ColorCapabilities" : {
      1 : "HueSaturationSupported",
      2 : "EnhancedHueSupported",
      4 : "ColorLoopSupported",
      8 : "XYAttributesSupported",
      16 : "ColorTemperatureSupported",
    },
    "ColorControlFeature" : {
      1 : "HueAndSaturation",
      2 : "EnhancedHue",
      4 : "ColorLoop",
      8 : "XY",
      16 : "ColorTemperature",
    },
    "ColorLoopUpdateFlags" : {
      1 : "UpdateAction",
      2 : "UpdateDirection",
      4 : "UpdateTime",
      8 : "UpdateStartHue",
    },
    "CommandBits" : {
      1 : "InstantAction",
      2 : "InstantActionWithTransition",
      4 : "StartAction",
      8 : "StartActionWithDuration",
      16 : "StopAction",
      32 : "PauseAction",
      64 : "PauseActionWithDuration",
      128 : "ResumeAction",
      256 : "EnableAction",
      512 : "EnableActionWithDuration",
      1024 : "DisableAction",
      2048 : "DisableActionWithDuration",
    },
    "ConfigStatus" : {
      1 : "Operational",
      2 : "OnlineReserved",
      4 : "LiftMovementReversed",
      8 : "LiftPositionAware",
      16 : "TiltPositionAware",
      32 : "LiftEncoderControlled",
      64 : "TiltEncoderControlled",
    },
    "ContentLauncherFeature" : {
      1 : "ContentSearch",
      2 : "URLPlayback",
    },
    "DayOfWeek" : {
      1 : "Sunday",
      2 : "Monday",
      4 : "Tuesday",
      8 : "Wednesday",
      16 : "Thursday",
      32 : "Friday",
      64 : "Saturday",
      128 : "AwayOrVacation",
    },
    "DeviceTempAlarmMask" : {
      1 : "TooLow",
      2 : "TooHigh",
    },
    "DlCredentialRuleMask" : {
      1 : "Single",
      2 : "Dual",
      4 : "Tri",
    },
    "DlCredentialRulesSupport" : {
      1 : "Single",
      2 : "Dual",
      4 : "Tri",
    },
    "DlDaysMaskMap" : {
      1 : "Sunday",
      2 : "Monday",
      4 : "Tuesday",
      8 : "Wednesday",
      16 : "Thursday",
      32 : "Friday",
      64 : "Saturday",
    },
    "DlDefaultConfigurationRegister" : {
      1 : "EnableLocalProgrammingEnabled",
      2 : "KeypadInterfaceDefaultAccessEnabled",
      4 : "RemoteInterfaceDefaultAccessIsEnabled",
      32 : "SoundEnabled",
      64 : "AutoRelockTimeSet",
      128 : "LEDSettingsSet",
    },
    "DlKeypadOperationEventMask" : {
      1 : "Unknown",
      2 : "Lock",
      4 : "Unlock",
      8 : "LockInvalidPIN",
      16 : "LockInvalidSchedule",
      32 : "UnlockInvalidCode",
      64 : "UnlockInvalidSchedule",
      128 : "NonAccessUserOpEvent",
    },
    "DlKeypadProgrammingEventMask" : {
      1 : "Unknown",
      2 : "ProgrammingPINChanged",
      4 : "PINAdded",
      8 : "PINCleared",
      16 : "PINChanged",
    },
    "DlLocalProgrammingFeatures" : {
      1 : "AddUsersCredentialsSchedulesLocally",
      2 : "ModifyUsersCredentialsSchedulesLocally",
      4 : "ClearUsersCredentialsSchedulesLocally",
      8 : "AdjustLockSettingsLocally",
    },
    "DlManualOperationEventMask" : {
      1 : "Unknown",
      2 : "ThumbturnLock",
      4 : "ThumbturnUnlock",
      8 : "OneTouchLock",
      16 : "KeyLock",
      32 : "KeyUnlock",
      64 : "AutoLock",
      128 : "ScheduleLock",
      256 : "ScheduleUnlock",
      512 : "ManualLock",
      1024 : "ManualUnlock",
    },
    "DlRFIDOperationEventMask" : {
      1 : "Unknown",
      2 : "Lock",
      4 : "Unlock",
      8 : "LockInvalidRFID",
      16 : "LockInvalidSchedule",
      32 : "UnlockInvalidRFID",
      64 : "UnlockInvalidSchedule",
    },
    "DlRFIDProgrammingEventMask" : {
      1 : "Unknown",
      32 : "RFIDCodeAdded",
      64 : "RFIDCodeCleared",
    },
    "DlRemoteOperationEventMask" : {
      1 : "Unknown",
      2 : "Lock",
      4 : "Unlock",
      8 : "LockInvalidCode",
      16 : "LockInvalidSchedule",
      32 : "UnlockInvalidCode",
      64 : "UnlockInvalidSchedule",
    },
    "DlRemoteProgrammingEventMask" : {
      1 : "Unknown",
      2 : "ProgrammingPINChanged",
      4 : "PINAdded",
      8 : "PINCleared",
      16 : "PINChanged",
      32 : "RFIDCodeAdded",
      64 : "RFIDCodeCleared",
    },
    "DlSupportedOperatingModes" : {
      1 : "Normal",
      2 : "Vacation",
      4 : "Privacy",
      8 : "NoRemoteLockUnlock",
      16 : "Passage",
    },
    "DoorLockDayOfWeek" : {
      1 : "Sunday",
      2 : "Monday",
      4 : "Tuesday",
      8 : "Wednesday",
      16 : "Thursday",
      32 : "Friday",
      64 : "Saturday",
    },
    "DoorLockFeature" : {
      1 : "PINCredentials",
      2 : "RFIDCredentials",
      4 : "FingerCredentials",
      8 : "Logging",
      16 : "WeekDaySchedules",
      32 : "DoorPositionSensor",
      64 : "FaceCredentials",
      128 : "CredentialsOTA",
      256 : "UsersManagement",
      512 : "Notifications",
      1024 : "YearDaySchedules",
      2048 : "HolidaySchedules",
    },
    "EnergyFormatting" : {
      7 : "NumberOfDigitsToTheRightOfTheDecimalPoint",
      120 : "NumberOfDigitsToTheLeftOfTheDecimalPoint",
      128 : "SuppressLeadingZeros",
    },
    "EthernetNetworkDiagnosticsFeature" : {
      1 : "PacketCounts",
      2 : "ErrorCounts",
    },
    "FanControlFeature" : {
      1 : "MultiSpeed",
      2 : "Auto",
      4 : "Rocking",
      8 : "Wind",
    },
    "Feature" : {
      1 : "Lift",
      2 : "Tilt",
      4 : "PositionAwareLift",
      8 : "AbsolutePosition",
      16 : "PositionAwareTilt",
    },
    "GroupClusterFeature" : {
      1 : "GroupNames",
    },
    "IasZoneStatus" : {
      1 : "alarm1",
      2 : "alarm2",
      4 : "tamper",
      8 : "battery",
      16 : "supervisionReports",
      32 : "restoreReports",
      64 : "trouble",
      128 : "AC",
      256 : "test",
      512 : "batteryDefect",
    },
    "KeypadInputFeature" : {
      1 : "NavigationKeyCodes",
      2 : "LocationKeys",
      4 : "NumberKeys",
    },
    "LampAlarmMode" : {
      1 : "lampBurnHours",
    },
    "LevelControlFeature" : {
      1 : "OnOff",
      2 : "Lighting",
      4 : "Frequency",
    },
    "LevelControlOptions" : {
      1 : "ExecuteIfOff",
      2 : "CoupleColorTempToLevel",
    },
    "MainsAlarmMask" : {
      1 : "VoltageTooLow",
      2 : "VoltageTooHigh",
      4 : "MainsPowerSupplyLost",
    },
    "MediaInputFeature" : {
      1 : "NameUpdates",
    },
    "MediaPlaybackFeature" : {
      1 : "AdvancedSeek",
      2 : "VariableSpeed",
    },
    "Mode" : {
      1 : "MotorDirectionReversed",
      2 : "CalibrationMode",
      4 : "MaintenanceMode",
      8 : "LedFeedback",
    },
    "ModeForSequence" : {
      1 : "HeatSetpointFieldPresent",
      2 : "CoolSetpointFieldPresent",
    },
    "ModeSelectFeature" : {
      1 : "DEPONOFF",
    },
    "NetworkCommissioningFeature" : {
      1 : "WiFiNetworkInterface",
      2 : "ThreadNetworkInterface",
      4 : "EthernetNetworkInterface",
    },
    "Occupancy" : {
      1 : "occupied",
    },
    "OccupancySensorTypeBitmap" : {
      1 : "Pir",
      2 : "Ultrasonic",
      4 : "PhysicalContact",
    },
    "OnOffControl" : {
      1 : "AcceptOnlyWhenOn",
    },
    "OnOffFeature" : {
      1 : "Lighting",
    },
    "OperationalStatus" : {
      3 : "Global",
      12 : "Lift",
      48 : "Tilt",
    },
    "PowerSourceFeature" : {
      1 : "Wired",
      2 : "Battery",
      4 : "Rechargeable",
      8 : "Replaceable",
    },
    "PressureFeature" : {
      1 : "EXT",
    },
    "PumpStatus" : {
      1 : "DeviceFault",
      2 : "Supplyfault",
      4 : "SpeedLow",
      8 : "SpeedHigh",
      16 : "LocalOverride",
      32 : "Running",
      64 : "RemotePressure",
      128 : "RemoteFlow",
      256 : "remoteTemperature",
    },
    "RockSupportMask" : {
      1 : "RockLeftRight",
      2 : "RockUpDown",
      4 : "RockRound",
    },
    "SafetyStatus" : {
      1 : "RemoteLockout",
      2 : "TamperDetection",
      4 : "FailedCommunication",
      8 : "PositionFailure",
      16 : "ThermalProtection",
      32 : "ObstacleDetected",
      64 : "Power",
      128 : "StopInput",
      256 : "MotorJammed",
      512 : "HardwareFailure",
      1024 : "ManualOperation",
      2048 : "Protection",
    },
    "SceneFeatures" : {
      1 : "SceneNames",
    },
    "ScenesCopyMode" : {
      1 : "CopyAllScenes",
    },
    "ShadeClosureStatus" : {
      1 : "operational",
      2 : "adjusting",
      4 : "opening",
      8 : "motorOpening",
    },
    "SimpleBitmap" : {
      1 : "ValueA",
      2 : "ValueB",
      4 : "ValueC",
    },
    "SoftwareDiagnosticsFeature" : {
      1 : "WaterMarks",
    },
    "SquawkInfo" : {
      240 : "mode",
      8 : "strobe",
      3 : "level",
    },
    "StartTime" : {
      63 : "Minutes",
      192 : "TimeEncoding",
      65280 : "Hours",
    },
    "SupportedStreamingProtocol" : {
      1 : "DASH",
      2 : "HLS",
    },
    "SwitchFeature" : {
      1 : "LatchingSwitch",
      2 : "MomentarySwitch",
      4 : "MomentarySwitchRelease",
      8 : "MomentarySwitchLongPress",
      16 : "MomentarySwitchMultiPress",
    },
    "ThermostatAlarmMask" : {
      1 : "initializationFailure",
      2 : "hardwareFailure",
      4 : "selfcalibrationFailure",
    },
    "ThermostatFeature" : {
      1 : "Heating",
      2 : "Cooling",
      4 : "Occupancy",
      8 : "Schedule",
      16 : "Setback",
      32 : "Automode",
    },
    "ThermostatOccupancy" : {
      1 : "occupied",
    },
    "ThermostatRunningState" : {
      1 : "HeatStateOn",
      2 : "CoolStateOn",
      4 : "FanStateOn",
      8 : "HeatSecondStageStateOn",
      16 : "CoolSecondStageStateOn",
      32 : "FanSecondStageStateOn",
      64 : "FanThirdStageStateOn",
    },
    "ThermostatSensing" : {
      1 : "localTempSensedRemotely",
      2 : "outdoorTempSensedRemotely",
      4 : "occupancySensedRemotely",
    },
    "ThreadNetworkDiagnosticsFeature" : {
      1 : "PacketCounts",
      2 : "ErrorCounts",
      4 : "MLECounts",
      8 : "MACCounts",
    },
    "TimeStatusMask" : {
      1 : "MasterClock",
      2 : "Synchronized",
      4 : "MasterZoneDst",
      8 : "Superseding",
    },
    "UnitLocalizationFeature" : {
      1 : "TemperatureUnit",
    },
    "WarningInfo" : {
      240 : "mode",
      12 : "strobe",
      3 : "sirenLevel",
    },
    "WiFiNetworkDiagnosticsFeature" : {
      1 : "PacketCounts",
      2 : "ErrorCounts",
    },
    "WiFiSecurity" : {
      1 : "Unencrypted",
      2 : "WEP-PERSONAL",
      4 : "WPA-PERSONAL",
      8 : "WPA2-PERSONAL",
      16 : "WPA3-PERSONAL",
    },
    "WindSettingMask" : {
      1 : "SleepWind",
      2 : "NaturalWind",
    },
    "WindSupportMask" : {
      1 : "SleepWind",
      2 : "NaturalWind",
    },
    "bitmap16" : {},
    "bitmap24" : {},
    "bitmap32" : {},
    "bitmap64" : {},
    "bitmap8" : {},
  }
}
