/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP
// This file is generated from clusters-Attributes.ipp.zapt

#include <clusters/CameraAvSettingsUserLevelManagement/Attributes.h>

#include <app/data-model/Decode.h>
#include <app/data-model/WrappedStructEncoder.h>

namespace chip {
namespace app {
namespace Clusters {
namespace CameraAvSettingsUserLevelManagement {
namespace Attributes {
CHIP_ERROR TypeInfo::DecodableType::Decode(TLV::TLVReader & reader, const ConcreteAttributePath & path)
{
    switch (path.mAttributeId)
    {
    case Attributes::MPTZPosition::TypeInfo::GetAttributeId():
        return DataModel::Decode(reader, MPTZPosition, DataModel::DecodeContext::kRead);
    case Attributes::MaxPresets::TypeInfo::GetAttributeId():
        return DataModel::Decode(reader, maxPresets, DataModel::DecodeContext::kRead);
    case Attributes::MPTZPresets::TypeInfo::GetAttributeId():
        return DataModel::Decode(reader, MPTZPresets, DataModel::DecodeContext::kRead);
    case Attributes::DPTZStreams::TypeInfo::GetAttributeId():
        return DataModel::Decode(reader, DPTZStreams, DataModel::DecodeContext::kRead);
    case Attributes::ZoomMax::TypeInfo::GetAttributeId():
        return DataModel::Decode(reader, zoomMax, DataModel::DecodeContext::kRead);
    case Attributes::TiltMin::TypeInfo::GetAttributeId():
        return DataModel::Decode(reader, tiltMin, DataModel::DecodeContext::kRead);
    case Attributes::TiltMax::TypeInfo::GetAttributeId():
        return DataModel::Decode(reader, tiltMax, DataModel::DecodeContext::kRead);
    case Attributes::PanMin::TypeInfo::GetAttributeId():
        return DataModel::Decode(reader, panMin, DataModel::DecodeContext::kRead);
    case Attributes::PanMax::TypeInfo::GetAttributeId():
        return DataModel::Decode(reader, panMax, DataModel::DecodeContext::kRead);
    case Attributes::MovementState::TypeInfo::GetAttributeId():
        return DataModel::Decode(reader, movementState, DataModel::DecodeContext::kRead);
    case Attributes::GeneratedCommandList::TypeInfo::GetAttributeId():
        return DataModel::Decode(reader, generatedCommandList, DataModel::DecodeContext::kRead);
    case Attributes::AcceptedCommandList::TypeInfo::GetAttributeId():
        return DataModel::Decode(reader, acceptedCommandList, DataModel::DecodeContext::kRead);
    case Attributes::AttributeList::TypeInfo::GetAttributeId():
        return DataModel::Decode(reader, attributeList, DataModel::DecodeContext::kRead);
    case Attributes::FeatureMap::TypeInfo::GetAttributeId():
        return DataModel::Decode(reader, featureMap, DataModel::DecodeContext::kRead);
    case Attributes::ClusterRevision::TypeInfo::GetAttributeId():
        return DataModel::Decode(reader, clusterRevision, DataModel::DecodeContext::kRead);
    default:
        return CHIP_NO_ERROR;
    }
}
} // namespace Attributes
} // namespace CameraAvSettingsUserLevelManagement
} // namespace Clusters
} // namespace app
} // namespace chip
