set(SDK_PATH "/Volumes/Resources/git/matter/stash/third_party/silabs/gecko_sdk")
set(COPIED_SDK_PATH "gecko_sdk_4.4.0")

add_library(slc_generator OBJECT
    "${SDK_PATH}/../../../examples/platform/silabs/provision/AttestationKeyPSA.cpp"
    "${SDK_PATH}/../../../examples/platform/silabs/provision/ProvisionChannelRTT.cpp"
    "${SDK_PATH}/../../../examples/platform/silabs/provision/ProvisionEncoder.cpp"
    "${SDK_PATH}/../../../examples/platform/silabs/provision/ProvisionManager.cpp"
    "${SDK_PATH}/../../../examples/platform/silabs/provision/ProvisionProtocolV1.cpp"
    "${SDK_PATH}/../../../examples/platform/silabs/provision/ProvisionProtocolV2.cpp"
    "${SDK_PATH}/../../../examples/platform/silabs/provision/ProvisionStorage.cpp"
    "${SDK_PATH}/../../../examples/platform/silabs/provision/ProvisionStorageCustom.cpp"
    "${SDK_PATH}/../../../examples/platform/silabs/provision/ProvisionStorageDefault.cpp"
    "${SDK_PATH}/../../../src/crypto/CHIPCryptoPALPSA.cpp"
    "${SDK_PATH}/../../../src/lib/support/Base64.cpp"
    "${SDK_PATH}/../../../src/lib/support/BytesToHex.cpp"
    "${SDK_PATH}/../../../src/lib/support/logging/TextOnlyLogging.cpp"
    "${SDK_PATH}/../../../src/platform/silabs/Logging.cpp"
    "${SDK_PATH}/../../../src/platform/silabs/SilabsConfig.cpp"
    "${SDK_PATH}/../../../src/setup_payload/Base38Encode.cpp"
    "${SDK_PATH}/platform/bootloader/app_properties/app_properties.c"
    "${SDK_PATH}/platform/CMSIS/RTOS2/Source/os_systick.c"
    "${SDK_PATH}/platform/common/src/sl_assert.c"
    "${SDK_PATH}/platform/common/src/sl_syscalls.c"
    "${SDK_PATH}/platform/common/src/sli_cmsis_os2_ext_task_register.c"
    "${SDK_PATH}/platform/common/toolchain/src/sl_memory.c"
    "${SDK_PATH}/platform/Device/SiliconLabs/EFR32MG24/Source/startup_efr32mg24.c"
    "${SDK_PATH}/platform/Device/SiliconLabs/EFR32MG24/Source/system_efr32mg24.c"
    "${SDK_PATH}/platform/emdrv/nvm3/src/nvm3_default_common_linker.c"
    "${SDK_PATH}/platform/emdrv/nvm3/src/nvm3_hal_flash.c"
    "${SDK_PATH}/platform/emdrv/nvm3/src/nvm3_lock.c"
    "${SDK_PATH}/platform/emlib/src/em_burtc.c"
    "${SDK_PATH}/platform/emlib/src/em_cmu.c"
    "${SDK_PATH}/platform/emlib/src/em_core.c"
    "${SDK_PATH}/platform/emlib/src/em_emu.c"
    "${SDK_PATH}/platform/emlib/src/em_gpio.c"
    "${SDK_PATH}/platform/emlib/src/em_msc.c"
    "${SDK_PATH}/platform/emlib/src/em_prs.c"
    "${SDK_PATH}/platform/emlib/src/em_se.c"
    "${SDK_PATH}/platform/emlib/src/em_system.c"
    "${SDK_PATH}/platform/emlib/src/em_timer.c"
    "${SDK_PATH}/platform/peripheral/src/peripheral_sysrtc.c"
    "${SDK_PATH}/platform/security/sl_component/se_manager/src/sl_se_manager.c"
    "${SDK_PATH}/platform/security/sl_component/se_manager/src/sl_se_manager_attestation.c"
    "${SDK_PATH}/platform/security/sl_component/se_manager/src/sl_se_manager_cipher.c"
    "${SDK_PATH}/platform/security/sl_component/se_manager/src/sl_se_manager_entropy.c"
    "${SDK_PATH}/platform/security/sl_component/se_manager/src/sl_se_manager_hash.c"
    "${SDK_PATH}/platform/security/sl_component/se_manager/src/sl_se_manager_key_derivation.c"
    "${SDK_PATH}/platform/security/sl_component/se_manager/src/sl_se_manager_key_handling.c"
    "${SDK_PATH}/platform/security/sl_component/se_manager/src/sl_se_manager_signature.c"
    "${SDK_PATH}/platform/security/sl_component/se_manager/src/sl_se_manager_util.c"
    "${SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/src/error.c"
    "${SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/src/mbedtls_ecdsa_ecdh.c"
    "${SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/src/mbedtls_sha.c"
    "${SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/src/se_aes.c"
    "${SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/src/sl_entropy_hardware.c"
    "${SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/src/sl_mbedtls.c"
    "${SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/src/sl_psa_crypto.c"
    "${SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/src/sli_psa_crypto.c"
    "${SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sl_psa_its_nvm3.c"
    "${SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_psa_driver_common.c"
    "${SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_psa_driver_init.c"
    "${SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_psa_trng.c"
    "${SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_se_driver_aead.c"
    "${SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_se_driver_builtin_keys.c"
    "${SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_se_driver_cipher.c"
    "${SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_se_driver_key_derivation.c"
    "${SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_se_driver_key_management.c"
    "${SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_se_driver_mac.c"
    "${SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_se_driver_signature.c"
    "${SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_se_opaque_driver_aead.c"
    "${SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_se_opaque_driver_cipher.c"
    "${SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_se_opaque_driver_mac.c"
    "${SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_se_opaque_key_derivation.c"
    "${SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_se_transparent_driver_aead.c"
    "${SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_se_transparent_driver_cipher.c"
    "${SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_se_transparent_driver_hash.c"
    "${SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_se_transparent_driver_mac.c"
    "${SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_se_transparent_key_derivation.c"
    "${SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_se_version_dependencies.c"
    "${SDK_PATH}/platform/service/device_init/src/sl_device_init_dcdc_s2.c"
    "${SDK_PATH}/platform/service/device_init/src/sl_device_init_emu_s2.c"
    "${SDK_PATH}/platform/service/device_init/src/sl_device_init_nvic.c"
    "${SDK_PATH}/platform/service/iostream/src/sl_iostream.c"
    "${SDK_PATH}/platform/service/iostream/src/sl_iostream_rtt.c"
    "${SDK_PATH}/platform/service/sleeptimer/src/sl_sleeptimer.c"
    "${SDK_PATH}/platform/service/sleeptimer/src/sl_sleeptimer_hal_burtc.c"
    "${SDK_PATH}/platform/service/sleeptimer/src/sl_sleeptimer_hal_sysrtc.c"
    "${SDK_PATH}/platform/service/sleeptimer/src/sl_sleeptimer_hal_timer.c"
    "${SDK_PATH}/platform/service/system/src/sl_system_init.c"
    "${SDK_PATH}/platform/service/system/src/sl_system_kernel.c"
    "${SDK_PATH}/util/silicon_labs/silabs_core/memory_manager/sl_malloc.c"
    "${SDK_PATH}/util/third_party/freertos/cmsis/Source/cmsis_os2.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/croutine.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/event_groups.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/list.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/portable/GCC/ARM_CM33_NTZ/non_secure/port.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/portable/GCC/ARM_CM33_NTZ/non_secure/portasm.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/portable/MemMang/heap_4.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/queue.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/stream_buffer.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/tasks.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/timers.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/aes.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/asn1parse.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/asn1write.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/base64.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/bignum.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/bignum_core.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/bignum_mod.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/bignum_mod_raw.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/cipher.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/cipher_wrap.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/constant_time.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/ctr_drbg.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/ecdsa.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/ecp.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/ecp_curves.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/ecp_curves_new.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/entropy.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/entropy_poll.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/hmac_drbg.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/md.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/oid.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/pem.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/pk.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/pk_wrap.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/pkcs5.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/pkparse.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/pkwrite.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/platform.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/platform_util.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/psa_crypto.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_aead.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_cipher.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_client.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_driver_wrappers_no_static.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_ecp.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_ffdh.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_hash.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_mac.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_pake.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_rsa.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_se.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_slot_management.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_storage.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/psa_util.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/sha256.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/threading.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/x509.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/x509_create.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/x509_crl.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/x509_crt.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/x509_csr.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/x509write.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/x509write_crt.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/x509write_csr.c"
    "${SDK_PATH}/util/third_party/segger/systemview/SEGGER/SEGGER_RTT.c"
    "../../../generator/app.cpp"
    "../../../generator/main.cpp"
    "../../../generator/nvm3.c"
    "../autogen/sl_device_init_clocks.c"
    "../autogen/sl_event_handler.c"
    "../autogen/sl_iostream_handles.c"
)

target_include_directories(slc_generator PUBLIC
   "../config"
   "../autogen"
   "../../../generator"
    "${SDK_PATH}/../../../examples"
    "${SDK_PATH}/../../../examples/platform/silabs"
    "${SDK_PATH}/../../../src"
    "${SDK_PATH}/../../../src/include"
    "${SDK_PATH}/../../../zzz_generated/app-common"
    "${SDK_PATH}/../../nlassert/repo/include"
    "${SDK_PATH}/../../nlio/repo/include"
    "${SDK_PATH}/platform/bootloader"
    "${SDK_PATH}/protocol/bluetooth/config"
    "${SDK_PATH}/platform/Device/SiliconLabs/EFR32MG24/Include"
    "${SDK_PATH}/platform/common/inc"
    "${SDK_PATH}/platform/CMSIS/Core/Include"
    "${SDK_PATH}/platform/CMSIS/RTOS2/Include"
    "${SDK_PATH}/platform/service/device_init/inc"
    "${SDK_PATH}/platform/emdrv/common/inc"
    "${SDK_PATH}/platform/emlib/inc"
    "${SDK_PATH}/util/third_party/freertos/cmsis/Include"
    "${SDK_PATH}/util/third_party/freertos/kernel/include"
    "${SDK_PATH}/util/third_party/freertos/kernel/portable/GCC/ARM_CM33_NTZ/non_secure"
    "${SDK_PATH}/platform/service/iostream/inc"
    "${SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/config"
    "${SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/config/preset"
    "${SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/inc"
    "${SDK_PATH}/util/third_party/mbedtls/include"
    "${SDK_PATH}/util/third_party/mbedtls/library"
    "${SDK_PATH}/platform/emdrv/nvm3/inc"
    "${SDK_PATH}/platform/peripheral/inc"
    "${SDK_PATH}/platform/security/sl_component/sl_psa_driver/inc"
    "${SDK_PATH}/platform/security/sl_component/se_manager/inc"
    "${SDK_PATH}/platform/security/sl_component/se_manager/src"
    "${SDK_PATH}/util/third_party/segger/systemview/SEGGER"
    "${SDK_PATH}/util/silicon_labs/silabs_core/memory_manager"
    "${SDK_PATH}/platform/common/toolchain/inc"
    "${SDK_PATH}/platform/service/system/inc"
    "${SDK_PATH}/platform/service/sleeptimer/inc"
)

target_compile_definitions(slc_generator PUBLIC
    CHIP_CONFIG_SHA256_CONTEXT_SIZE=256
    CHIP_SYSTEM_CONFIG_USE_SOCKETS=1
    SILABS_PROVISION_PROTOCOL_V1=1
    SL_PROVISION_CHANNEL_ENABLED=1
    EFR32MG24A010F1024IM48=1
    SL_APP_PROPERTIES=1
    configNUM_SDK_THREAD_LOCAL_STORAGE_POINTERS=2
    SL_COMPONENT_CATALOG_PRESENT=1
    MBEDTLS_CONFIG_FILE=<sl_mbedtls_config.h>
    MBEDTLS_PSA_CRYPTO_CONFIG_FILE=<psa_crypto_config.h>
    RTT_USE_ASM=0
    SEGGER_RTT_SECTION="SEGGER_RTT"
)

target_link_libraries(slc_generator PUBLIC
    "-Wl,--start-group"
    "stdc++"
    "gcc"
    "c"
    "m"
    "nosys"
   "${SDK_PATH}/platform/emdrv/nvm3/lib/libnvm3_CM33_gcc.a"
    "-Wl,--end-group"
)
target_compile_options(slc_generator PUBLIC
    $<$<COMPILE_LANGUAGE:C>:-mcpu=cortex-m33>
    $<$<COMPILE_LANGUAGE:C>:-mthumb>
    $<$<COMPILE_LANGUAGE:C>:-mfpu=fpv5-sp-d16>
    $<$<COMPILE_LANGUAGE:C>:-mfloat-abi=hard>
    $<$<COMPILE_LANGUAGE:C>:-Wall>
    $<$<COMPILE_LANGUAGE:C>:-Wextra>
    $<$<COMPILE_LANGUAGE:C>:-Og>
    $<$<COMPILE_LANGUAGE:C>:-fdata-sections>
    $<$<COMPILE_LANGUAGE:C>:-ffunction-sections>
    $<$<COMPILE_LANGUAGE:C>:-fomit-frame-pointer>
    $<$<COMPILE_LANGUAGE:C>:-imacros sl_gcc_preinclude.h>
    $<$<COMPILE_LANGUAGE:C>:-Wno-unused-parameter>
    $<$<COMPILE_LANGUAGE:C>:-mcmse>
    $<$<COMPILE_LANGUAGE:C>:--specs=nano.specs>
    $<$<COMPILE_LANGUAGE:C>:-g>
    $<$<COMPILE_LANGUAGE:CXX>:-mcpu=cortex-m33>
    $<$<COMPILE_LANGUAGE:CXX>:-mthumb>
    $<$<COMPILE_LANGUAGE:CXX>:-mfpu=fpv5-sp-d16>
    $<$<COMPILE_LANGUAGE:CXX>:-mfloat-abi=hard>
    $<$<COMPILE_LANGUAGE:CXX>:-fno-rtti>
    $<$<COMPILE_LANGUAGE:CXX>:-fno-exceptions>
    $<$<COMPILE_LANGUAGE:CXX>:-Wall>
    $<$<COMPILE_LANGUAGE:CXX>:-Wextra>
    $<$<COMPILE_LANGUAGE:CXX>:-Og>
    $<$<COMPILE_LANGUAGE:CXX>:-fdata-sections>
    $<$<COMPILE_LANGUAGE:CXX>:-ffunction-sections>
    $<$<COMPILE_LANGUAGE:CXX>:-fomit-frame-pointer>
    $<$<COMPILE_LANGUAGE:CXX>:-imacros sl_gcc_preinclude.h>
    $<$<COMPILE_LANGUAGE:CXX>:-Wno-unused-parameter>
    $<$<COMPILE_LANGUAGE:CXX>:-mcmse>
    $<$<COMPILE_LANGUAGE:CXX>:--specs=nano.specs>
    $<$<COMPILE_LANGUAGE:CXX>:-g>
    $<$<COMPILE_LANGUAGE:ASM>:-mcpu=cortex-m33>
    $<$<COMPILE_LANGUAGE:ASM>:-mthumb>
    $<$<COMPILE_LANGUAGE:ASM>:-mfpu=fpv5-sp-d16>
    $<$<COMPILE_LANGUAGE:ASM>:-mfloat-abi=hard>
    $<$<COMPILE_LANGUAGE:ASM>:-imacros sl_gcc_preinclude.h>
    $<$<COMPILE_LANGUAGE:ASM>:-x assembler-with-cpp>
)
set_property(TARGET slc_generator PROPERTY C_STANDARD 99)
set_property(TARGET slc_generator PROPERTY CXX_STANDARD 17)
set_property(TARGET slc_generator PROPERTY CXX_EXTENSIONS OFF)

target_link_options(slc_generator INTERFACE
    -mcpu=cortex-m33
    -mthumb
    -mfpu=fpv5-sp-d16
    -mfloat-abi=hard
    -T${CMAKE_CURRENT_LIST_DIR}/../autogen/linkerfile.ld
    --specs=nano.specs
    -Xlinker -Map=$<TARGET_FILE_DIR:generator>/generator.map
    -Wl,--gc-sections
    -Wl,--no-warn-rwx-segments
)

# BEGIN_SIMPLICITY_STUDIO_METADATA=eJztnQlz3EZ697+KipV6K3kjDnhKtmLvlkzRWmZFU8Whnewut1BNoGcGJq7FwcNb/u5vN84G0EDfA6TepDYWZwb9f35PX+i7/3nw9fbmPy8v7uzbm5u7gw8H/7w/uL388vHu6pdLm/zp/uDD/cFqdX/w+8HbJsz65ufbi8s1CvbdH18C/80TTFIvCr+/PzheHd0fvIGhE7leuEVf/Hz34+E39wd//MN9+F2cRL9CJ3uDgoTphyByoY+e2GVZ/MGynp+fV6nng4d05USBlabWOstdL1pBJ0ogEkWhY5hkr2sH/YvCVWr3B0j6zZvvNpHvwuRNCAL8oxOFG29b/YZ/9XxY/5b6dgCDKHm1y6dWO6SeJx76CT/2wfol8vMAptYtTKM8cdBfWy+zApBlMLHSDKQ7Cxl/8rDPVprHcZRkFtwkpyfB9uTMKlUtmhmLxrO+/Pz58ta+vbuzL9CThnAoVqg04VNwartwA3I/MxtBI5aoVHEKbCd5jbPILBPVDpUIJa8LnzwH2l7oZbbruI7x/DRhkMr4YwLh7d3N+sIk19DIWHylPoRx5gUwMR5TVFNULhDHdlW1eDA1CzZqiyeHwSDfawbr2qMSwsD3HmxcP6OQD/nWLN+EtbH4Cx6gm/mGU5Vqh0VUxfS+wAbmSr7vrPK1SXuFgjyLtjAcfYeizOx7DsgQgp29xlC3E5V9a8QUNYJv7y7R2y2IoxCGWWqKaGhlLLWd+ikb0QM/0p7SRCRRbfFULI4fOY+o1WWMjG5sDA0+YR92IHR9mBiMr4EdPiBz0TSwMwbkRWmWQBBUzxrL5yOmuLHMRRXNFBOryH9eiAyFzn4ibWhxBNLrvUHsSs0c5JRFXsgsAWG6iZJgBlyq7VHwolm/t5ilW5uEe8g9P/PCPUOOW6XC+l74CBP8zcp3zZD1TFAxVk7S9HzQn2ZABkbYDaYtdB4jO3Uf7bPVGR4HaeA7j8U+yHDGbX4fPPGpeF8Svw+eWHuoPRSFX8BD2nls8ODlj7enJ9efT856jw0Vi8gaPNXPrq9pBgO7iS6ZKj7beYlrxyDJXq1ywMdqYs6qI8cq48AiHLUaX6wS1qLRWAwHMmQ3jxfjAQ2n70Inz40m4FXo+LnLTMHGEjg6PtocH52cecHZNzIVjYZYqJitcShGcjYBbeAE8VK8aGD46eXaI2bguy0VJvtDnoBgMfQNjQh/5iyJv6Th5neCfDH0FQs3Ox7EXAx8DcNPj/TDTbQcB1oefh8CgMKlTuLFWSTV3TbjygCL36PY95fjRwXDTQ8XVJqhYGmGeYoAloPf4HB7sEkTZznluaHh5t/GqK+yGP6GRoDfW0701zBC9DbuTy7KhYaI24/dZkmloKER4H9ZEv6LGL13spwSXLHws4MFtedqGH56Bzg7qXksM/wNDrcHj/A1dYDUuKERFwgebh981PZbjAM1jBD9ywNYTkuaBBL2Ai/P8cIFDU7QwPi9gsWKkOU40/Lw+7Cod7Mv/G72l/Ru9kXfzQHw/IfoZTEOEDz8PsRg97CkITsSiN+LdDkNjYqFn/1pOUPVFQs3e+yEy+ne1DD89MlyXmUViwi7nXrbEPiL8oFk4vYldRKQObsYuItxpYvE7wlc2juhQ8Tvx4LGHVPBcccUdTI2UkvrzOA3OCIeLGkSqsXh9mBZLWvxdnW+rIZ1Lt6yXtbgu/jY+5MLllMCahhu+mdXbnGvEfoahkUfVEtz5wYnOVgLePprfuZFp+Fwrd+hfDn4avhFf5NbEETh1DoxL3QG68O6q2NBFgWewXJXMloIxOpYsyapnCD1UjtKT+wy/L74aHYnST0iCHzJbGT50U7g1kPZwuDrsEPNZJiOaxjmBscCuvFb25omAmkKTb7KenmyscbIk/vNiXz5z0YWstxgh7BL1VqzpiquQT2UJox6aDoPG1ujWXmH8JjlaLAwcyTX7oeVsMbIH3gCxvelNmPIcJH2xPJIFkW+swNeOL2ieZiVxrZ3G3e5Ia6db+1arJc9x6t6dNs6zpN7qIla96rSPzA/aOnQ02EmUB7CrePYcQK9sjm3f9KhfWbOEW4mPkRR5kcAfTPVVOzuTZ6qrbtPmitlLXdv47Q1JJisalgRdHG9vlpPxc1FcQLFVOkdW33fibjy9YL3aXqSWxv5Iq7wx8LQTT9laHqyZJSPV8d6zABKWJ7kzH7De3Qy9LbeK2TXLEdMomI+QyxWVqf58HZ6Jzg93S8faXWSL4hzGyTBk8EtKhS+jlXxGnlQPeDzMU601SCogWo6NgrgXnaqzE4mV5Tamec87hePMCre7hrZ+Nb3Cg/0YBvG3nakY9XusK5Z/Q0D1INgbTQktu5PZ1+e5ivlHABj+aTyzSJs1m0uOgarpdg/e2d29LHtKowzZGbnHtlVMIUdPpkcouTkriHEqxieLuvgaCdU2Rqra2geV13YEQ7BTLYE+hZDOKvNjV5DaGh51GdRqA+q1ErmY6e2VEcNaZmVls3ZG0lmcCyORVpbNzMM1MSH8Sqx8a+qD0nLQikxG2ltXUNRKuf61AtSNWeIS7r5HFoaI0ZnSdOsJKwef4RJCP2ZWFvjZgoTGSXGc2nlYT2b0jUtlhrzsLbGdRSo5pBGDYWq0dpDPm1sNXm1Y52ZkO3hlDvg16utZsXugQh6UB5aML8DDYcg/wLyTZeDwe/1Au6hMuij0xAMVdBt2dqnm3W917EukC4zwPbN6x8xgoGbPE2NF1GWJIknOnQik3NxhRPkwobGnoZ3Gj7UWtF98lxs07GAbRVx0Dc6mdPxw3sl4yKytzCEicmRIlqcEUbZhEbrahodtWYeIbM3PjK2d77WLJsSj9buF7C2aGDUr3f+Pa6O7PL8Q3NNEcJF/B6fRhDJNXsl7pjlzDV7Bawtiuca33uYzjXogcLExfXpaTHDC/bgGDJq0QybaGH0Y0BsKSHqoxrujRSERVKTtiZW4aHH8Llo+wGqLDFwogTui6cyNQ0E9xY/kCd+ipN/9sNTm5oGwjuM98NTWZrGwVtX94NTWZrGSfeVmVOOrFwOlO0LqDE2DWV4gKPDRB3E4Jiomt6q0tS1Blt/2ImiPxiMHcM5qEh3nsGt/B2i2hT7RbMnHto0PgWnWHQIjHZku1SEQcbWnf3FV9fadJyZ3v3SiS+uzS9FeTC4VqdX8ijLcYYNGLN7cbp5imcrDnouAcEmD/dVQxHWprGMr+LtYI2u3KW2QfeVgAlteI8CtI8hpB7Y+AASrZG8Hy7qEi1qI3k/PPSTOGmN5P3wUA/8oeDs993XNchuwe+HinrMDaUFvx+alKMiMH2cSBdo5LCQkW7F3qAqYzxQe640h0Z5+j77YaNOvUmsy3YQavY6OQxGXPjGWD3R3gJYXXfDugumd3nuSNSSlzIBx4E+TIob+kxOfJbx0rntzhr6195/OE7IOmaCCBoFoRcnMIUmTz5T8a0HyOEavvxpuWlGo+M6VINrDma4wgARJVH8au9A4j4Dk0Oj3LFRrQ+hkbEOdUmSyOhaFgEPGhZmlqyDLwS8C8Sih8WdOQshb2AY1HVg6LiouKH/GpzDE/KADsbpTboDC3OjImKXgPbq8YV4MGDifLEszIk+lNybhLZqZ7wWm/91Wp+E0AIxUg/VGjYwueBICJ2gYXA7TrAgboKGxR0AZ0ngBA77fReAEGxhsIwWcZHV+0wsH3bgeEGxT+KwyU/O3y2LnQBi058fnyyLngBi0G8XVddsuesa6Pwag0e4IPYeEYM/2yUQuF64XZAHAyahFt4yfBgwibXwluJEH4ovJZ6An5u82UQmJVom2UNEacN/WNlNvKfBPiu58ZIyurMk3M7Qxm996TTvaxrODFwqGN+CKeZDD0rMlWqSemnOtFgc7qBGXDV9bLswhqELQ8foCWMiTk3A8blWxchD7vmZFxZXYy3GsxE2IcdQILINvjDXhnTCzqF60nsqB6QX6FyXTsg5gBoyS3OpZhJyBPVhl+ZHhSTkRnGjSpbPMhEx6UwHTMglx4t3ZrfYyvjTUvE5kyUgTBEK0l6oY5OE0k7ujO7wUXex5pN2cFE14ASftINLqhnH8cTdW+h7eRqRz80oBv/IF/lqo5IJObXQZBulk0mxhb0ZxuBkXFtUdUlH4xsD8rLULvaXL8CZAZDeicrOQ8gU5aFeHHkhcjbEx5IkeZpB106zKEEdqBmGzIjIwqNl6KM1RTdMfEquXrZ7LEKmi+Xam0X40qBQCiU9T3ONdc3u2yiW2NDdBhZ9qjmGoqcdIsEUhu8W4dYEnPhYyVI86jHJ9MgX5kpLpTI8tzCnhnQqA6sLdE5s6cVgfGxhHgVcVz92W594Kx5O3OXUdjQwIZey13hBlXcfSnyoYHlJNEon7tyyEotKpm9Gu17rpWc622719t4NbCw3B0J2WNid2PZ5O888o2f0ijrQAAl5MdOoyZQfAmMlZLBq78aiXCGYhHyZZQJgyhHuEX8y0MyjjlP+SAw59oPvQOj63gyLclh+kWBCXs03DzrlktgkKBkS4yG4xWW+Hhdf66MOHKVmzx/m8oZKJO5HdQFskhm9YUvWpz6dyY0sRDtkvnioj2DusAiVOBduvHCGhvGEDySTkC/zNPGnPOHvjA2ahUtyowYSqy9mG7XtuzJKJZQqzVxDsfZvbp8mycTSqQ4+u0+jVGL9ox0CsMvN8rO7NAUm5tUC/ZH0ZJ5h9UlP+MfUaX3FJblCMIn3X5fkSA2k0n9dkj8SUxyj3cSl+UWCSfZfl+RSh0q6/7okj3pcsgPNwuc0xSjD46oV+AoHlrcixi+Cak0VXUyqZa2H9g4tGMs2hG/FshOa5YlzwgbPGz+6jwU8cpQfK5P2P3bTC3d1iATr/UqAT2XoTQIhHoSYPnasGKxgTdCsizhkjUe014/rLho4PjpP1L6VV57XF3F3AOSGXcaud++5Wts3csc7y9v6PvU+BOMl0TyOKutIfz9LmLrB0DbjWN56yMrMeDMvePDpadx58vPFxcjyy85jH2+vy9s2frr7K/X5QYgwCu3iBUqDoCQdRt5joSrj0aojykLxYJFOWi2/VaPRFjpS/QCp/lP39blS0XF7EwAn0b/DXp8/DZ9Q+izXn4qO7s3oKtWpBazjK1s7RfYaBtcgpJ222YvDHQSxfTZjFq9IrRaEez0v99QEzzsSZFFg4LRZZkRUeFZrn3XEUxIh0VB/948blSRgwLowTqAD8DLzYobCM7NWiht9nId12M0TXna0RZ7HM+L3KRjQPyKZ27ub9XzAJAED1vdS/R0jbtDaOutESJimYAvth3yzMTAgy4075GCBx7kdJ1EWmZnw4wcfcHCAPycgRl3ZmbFJCgZ0/XabD5gkYMEm0a+oMpwxdkkCBuw/cpjPGK2NeeZphkG8m7F+aO2zQDPgPNpFu3vGDNCnYECv8ePXMzP3IJjxnEAQzP7eGGCwzsgDqf6rcblpa+ssSHw/wow5obXPPYpHa8/vvQ9GWh6QjzZ+947Ztz6JWrTj9o5YW51EK98de2drzE7CdSuGvUMOzE/C4nphhozYmJ2GK2uD/dM1dnszUhxzkoNBk+o0yenJGN97SEDyShnBJsdVDBy1N4iLCteqiKyRywq6YGl4jEIbuOaVjUeaZkI+J142E2RjehLyAaTw3R7GEPuErd1JPEObf5h44zt8KHhF73Iuxsb4dCvAmQGwMsoCs508eZqjpuna5sS0Q/g8J2ptfxI30H8YDxMxoJ6y061svG2Y72FOblDZNHY58JoL6udgbIzzgAbRDMnctc2JaSdghkIztD+JG3kzRGdldBIsNnB7PBMspt0i3wd7dNLzGdBqs4wq2031X/3EUVNXZhkxN0e0cWDN1KomDDMAZ2pRE4YZgDO1BgnD08XC0CZ0dsEY32lOA7TjyNd/egEvZWN9uvmfJbabPOjfYM1u+xOWJxF3+BaneRg7pqcHsIoLg/ZP2NqdTuYoRNbwySVeMEPVMzA/PYRV30Kzf9CO6elaslrzPEM1SVjmQjRzigo35+iZKV3YFMzFSVieHg3zUWvcyHFl7NEw0vR0jyW0g3wPC5YHPZXGLsdgnbkNrJyjdpN7VUd71PuH7Rrn7VHPxVnZFulRz4ha2xfARdnmCaTe03xZgQbCPb67d+iecUYTxcgBuBxtk7ETbsdbULYXxDPUXXQGEezZqt1xDuagdXNWgol7ErmGrfsEHMhzVRN96/z91P2j9qxPL6wIomwPa2z6jI1ZxlwFPjNy/3StXRbePNU/YXgaME5NnX/OZuzYZmKaOYGei3L0xPkBJO7D7mOZH42ytc3EzBLgzFBFdkxP90mB60fOHlYgDrqkrWHWUO18r/Seca4x5TkguaqgenB8BsDGMNf4yJwJTkOYhE5QCNRmsnfQ388Gij4yBWB6GDf1bRc+5Nv5kKkITGjH92YZmOraZmIGXrqHTY40yNoyExEFPD6dsQVPZ+DENnLQnQDy2HF2HdyX86Nv9z/MW1tlotkOasPMMUHbM84DOsNwOWmZB3EP6+FHENlr4ssH0xlWZ5KWmYgzLRjomOaDnC+9O+Z5YedK+Y55ZrPPSV7jLKpfs7PMjw0QOKHnpBWJWyOXP4rE7NgVj6OZYaZV5VQEXujqLqJ6J7MdIqP4iDv9x8OJ+DFJxeta6kcZeWXUnA5RWLjdqC5jnBW/ZeDFnmVvwNA+L+5m4+q/eUSEtwbgBTZyVYoI8NjVKGPAJm6WFuEduT96DDcGj/OWuRqAFziZY13y0D53tTZzjcaO2+qk8erNaubkcPYkLR1CqBE1y6hkD0CwETUn8vg55qPQs6xEogCIAM82vTfOIdlondUFCot623tBDnWpRFp/czpR2Rdq/c3JWwMItf7mBB67WGAMeL7B+xEIbvA51rgM7Yu0sufEHbnUeLKVPSdvDcDdygahGwUzLTYc5xDpJMyKzbE2qttKn5M2Fcoa/TGeWcmHLKLjTbPitwzMo2sGh9CMHe/LdaDNIGbAPs7GrKOiOVyy+gy4DsQEibfHUj1grKyzINPweEbIyjoH5J4XHdFIR5cf0Y/ZmY21tc8CLY/KmA+0sc8CzT3fRe3EzR7OxB+F7TAwgB30j+/PWf5JAhasM2MeqIyzEHcA/e/kaEZOgoALNo58/bfnCeLWDExgaO5WSQFkKHKF5L6HJAe4vPcqOnvt/A0wR7p+wz1lMcgOT1YvM6J2GJjAOJ/YwP01TzPbh1vgvNbLGWb0YBJKxqVNgvqTe90zw+UUiSXkFu5OFIFLoaW4RcESdivN8cgszBboGgVNyL003eO4yrQ7FYoQfrGidSH8NQufA0so+dzFnDi5ZE7mLgYLuz5cZz5igoABW+x2mI+0Mc/EnHFwxuUanHF3M/Z5KuMMROjsc/arz1hbZ0POWUM15pmYv+53TmMI+uvYnMZwV/ycmNQJ2pFj5ebD5L4Ifs+7kAegYzuRe5jbOYdgtlxDMLtHdzMfY22dBdkcQzcfKYnAwPWDGV+UlXEGYvX07KNDQw4W+B5X2A1gqYvrBoDncxKe8yDCIEpeq9s+bOD70YwjWSMwDBdC1OlNI+cR7nPBSB+9B8FC9lA38XGPJ34NcFsABio+0Xo2zMo4AxGfbT0bYmWchbjHgzMGhDwXd+FDuI/3cCP9OGRtnwN0xlq1Mc+B+X5ezPc8mPX5qfOREgScsDOPPw0weLGLg1Xnx64xWNiR/3p8ejRnWSMIWLCJ9wQyaAMH8czYDBhysMDrA3fnQyYIGLCJh9527vG7GSfpOwgs3DnHrUYWXPZPK9mBGRdn1dbZkPhc9TkxK/ts0NNZMU/5IM/nbGm19lmgc84I8s0BFicuAWc3Y2ugg8CDWywqSXMvm3MKhUbCAx9Fj97ckd0wcABnHu6SzwvcMjCA2wsXZuPtILBwvWBe1sY+A/QJ5XJvnxsu+6QEAAN13mUMnAsXmlOvZgWtCfhgZ6wDSAIu2HTG6SySYLBxZewK9c72DtSfYG3tmGsRH0Kz+NfqVfvoyzU9IMebW0Pw4MMZxkNb8DEeIWeqVT+P8BXZ8xI7e43naIwMvRoFk3EvfQ2j8HWO+bdRx0ikBW+IwPximyFKZ3GYzAvxwQJxlM7TwiXino4j5kqcoFZG5j0txJUujpgruFShehoPUM3SGqK4M0Tic6lcRz6rCy0CL/I8s+sdZN6NF50DKfZ9XAmFfEAi6ECYwZcsXUq9NI0l59qCCjcbTc7FhVTF01h8rqGAyQxj04QXDQEf8Fz7HQhi/n0N1QETs01tEtACs5vN0QdVDpuVu0PBCe79NnPJbAg4gbMkd+ZtRLQIfMjzd9QEe2RPwM9nJm4RuMYzKF/SvuqOeaRwu4VJb9ij/8xrmsHgyYPPrAMy1pefP1/esgZRyqfs27s78+c5lv5ZrQtWad3qQjDyRPmw+czAoOXIvYRbc9PWENoy7/CLXj71fA81bmzM3cmDw+fQE8VJgtMZv1rVWR6K0y8k/TkbHz1XrPs0kqdJ3yzCAavLaHUwJs/vaZ80klHEgQdZRSJPdD52P5C+gzheOXEs7necRE8enhFB7oYwAVmUWI2YNTQUAC/UZ6lVo5gKn4JTmbxHM1RrUcxgbyUyzFjE7ahGPqKQxQmSUfhnKNV4hy8giH3YLh6rs2kLMjTCJPm6/iiXmsI4jSUK09c6zMUOhCGUms3iAKKZ4aAp3qiG4mjU1hTXZehEkhcpiiARZnhojEdRx9AU0XVZE5uOH8IMD43x+OkYmiJCf2SRExkvZqQdHp5fjs1HUt8WF9fJHrlO2Fxr+dMJRZDW/QMIJ2k+47eg3LHNElCENZ6YMp58HUMcRBd5mkXB3rhIcxx0n+AG5H62N7yOPQrfD9Jn/KWJg8/WtNI8jqMks37ondZHMyPl9YihUY9eUdvoLvoTlDoBamCsozZtTo93PT2KyYs/XX39Em23kuvS+hb9UsrqyVIM38GX7Cb0X+untDhcm6eKUyDWRZa/kJ5oxPb75aevyTIr7fik4TGPlaO7b5UVxTgnXBTjil8/fpHux2DL5eikRRccqSdOvymbo7KJm8Isj+0YvPoRcK2+IsuotKsTZklvy+npPCk6bzVBVUsjwyh9oN/5Bg+cXBTT8N6D53vZKx4qcPIVSIIV3CSnJ6tge3JW/on/AkfHR5vjo5MzLzj7BoXPosh3dsAL+yLot9R97H/roJdZmU1W6NcV8s9B/8XHbn04W52tjlb24fE3p2ffnJydn503w1zfBchP/4MLUyfxYuzaH76zht+VIy2dKEDffYffX79CJ0N/H7w9WF9df/1ydXF19xd7fffzp6sb+/rm089fLtcHHw7+9s/7gwQG0RN07w8+bICfwrflKqLMCy9fimHxFP3yt7+3X6/LVMPf1sdRWT8mEN7e3azbIv+2+a0dkbTxz90fQYzSOIlQdGQeJHfxt4/AAFVv5d0j5a3OtIfwqAn6uUhk6gOda0yGPxdXRj95DrS90Mts13EdnudgkI89NjyYgPpzpTb2VDlgN/Jr6kMY4/2ECfEETimUU3IfohS6P/iuygsfrq+LL9+8BH6Yfqi+/f7+/v5gl2XxB8t6fn6ucyrKtFaa4sYPfmgFi+Fa9OSbKgsUwbIkL7/03OJz7qxKu6ui6K5yp8oNzajTaus4RYjYDToSf7gvcnIxD4MbWykqpbg6KA2t/i/+r4UfarJ27c4fiiipsJDDWPH3t6q5Gq+TRNTW7d2ljQt0FMKw3KL/tv3R98JHmOA6beW7nV9Q0qB87XtOUSKL2a9e2GJHQqVro8cAemsPHyFzmuNHzmOKBwa7z8AnLLEDoeuXV0lO/Tyw4EVplkAQVE9Q9AdPjGsUnF5xzJpDedDrFQm7+on9YJaAMC12oY4HweW7XbrH0C8qg8FDCyo5dzDAjQz4P7DsDId2344O5b6lNRb6X+6ar+peyluyn/V22Gd42++1vB1rg70dtP7f9tqHb+ljvpSvmwHRt2NDjrQfelqdkTHaD73nyYEr2vf14BH1t5Phb53RAdoPO+rXZK+d8nOn10z5nRgjeUvrGvS/LJ+j9nDeEjNMb5spE/RXM0dmF+2uthF/cb2+WlsXeH7sqloI4ASpV66w89pqU1wAFVnpsMTuH9HwxS1twempRNggzm3UEH76RiJs9lu9vI0vMG4vnvS8jtITmcBRWuyXEwla1lk4JJ5Dx4Gd6cCfipcx7mHiudUvuN93+ePt6cn155OzBqTpNdjACZg5T1SyeanqUnxAnYZAv2bGzPaCmk6Qa1bEDXzdkujxauODTtUA2HWXL2JWRaLise9rloTakwrmKUiYdYqg6CZNHN1JtY2dRHem2saefkwvsvFQoWbd3UZ/lO42L7olvRPdaeQB7XWJ1xwOoFH0Eb6mDmA2KQRVfVRDGZB8eQC6a7taFo8TeaH2l6kPi6EY3aoGSpWvv1QFwPMfohfdqjHYPehvogSp7vIaPOlu7MVOqLuCjhPdWR4p2qm3DYGvWxk1eEDm7OLyOnKdwtBMVk21t3tQv8TZbPWL6m+em6j3chMVn4mW5JMLdMfnsxtpTvfOJJYe6aAantaiVq5jtxteJdGqa59mKLHzmBBV6eHXon1QhuZDFGV4AhMmvamu3keWTrmJFe9UKWYX0hSyM3IvTBYFHjOndsM0gzLEJlqB0BJhYHXxI38IPKycM18/nTAe4Rh8yewMpI92ArceSltmPVYpFVPUTUrwpV4VBlfswPd507wMNc3Mp9RMXddxt3UclAdhtf+J0/OBSjlJqRa6cIU7s7QiVZRWCIxogIGbPJFZARITDIxQeIK5CFOszxcPUk9OywTddobHhYLuAHOAZySYvfFBupMJjGcqBcLhxUvo/4ugF9enp8WwOeAOjnNAb/Yfp69dTs/yZYmuUOu8RODCeWY47HORAQPOurwThGuItReCWUN2nnd2HrND0w3Abv72nycOw+APxvVK6QVJOIp4LwB/kSMCcgx9dp7nGdvrBODot/afl4lkjn5i53nUQd/koRhaKpYmfH2hfpAMMtsSlCBSac/VBeqE4Jzga8PgNoBIScNVUlNZcNVIVQhsQeh5XMJEAkBBA0VBEQmAC4rI8zjHizyfivlbZUWRIGV+YoRAfYfiNFbgFxmk/cjZzWeF56w8CJlidewAg+FGCp088fBuVmJVFPq22adat/Sbb1hE4oo2aFeoGFDv32GtW765c1q3sCliziF4CWXiDjjNyjuO9rCErBfi1VqotOD5GQP6w5OUDBgoVge2S6h0yhcDzFnObsVJaDcHk2jWra9G0CDrkbobWMSELmSPlg+Vtethjra6Vn0BDBQ71bV+9ao+1S9cV076lXcc/VUJ2V7lYcZAU3nol28rD/3aRSHXI9spiFGqrRAOdKtRxCTjWGk3YqPdu1BvOWt2JLQrt/FVNj5MVF45XHaiIPRiVCFC9mypjBm8UNyIK7j+BRDFE3tEUEjTcQL9mvjmUt2i1cXH2nW3BiKgKUOBzmxWKO/AsX7c4uYbE7Lnxyf6ZZuvdcu2W75MKLcnxGlU9kxBN1d0aE2/YrCiuMpa7jVIV6y/Ky5xt4sL503Io/ysVRfVEoA9kSsm6dctRtRGStxnIN2OGdWvy55mWSIb61X2dEhjifKk0nLgKwXtjey6BJtufZbkaQZdO+3soNFiA0eHaTt1lA9O0zYgrti9pco3h9Ki0sleTSanrDT+xtDWMnzDYUNDC2fSRsBeJiUoHMXgHzm08dwTjhrduaaSVxkiGpMuNrTGqDYPM2P4pA0TPlTzVyhvxjB0Yeh4ekwQLxAvS+36OEQ9srSqzIw43gytWzpLpMdIqJq9qtGIMnFph3wjY9KC0mAdQ1vL8BeHDaLyNWIDV75GhFXH18bkq8rXXPbsGjCSh7om9CdBpW80j5JvEXOJQbFiJEUodhTGzQWs6E980ojRHEB9zzNNJMVSauIAk3rohHKmCbPRwCXGs6OXU4pjIRenUvjEXkdEk6oaQYMjidITmainqOGDi7SJFV5yStWnxdSxVX/mjaWx8HaScXRcehqVLw2DqA+98AUDp0Z7dlMzfdx8w+vHQMNTE6mnuFoNcWcGGsVyWq5FaNxqvMuKOOXUXPV6ctzxXiwKaxK/XHpY9BpUBB5h0p5QwyvR7ktoGHhjgyZQMdAl5G9U0CdGj53BHRubBEI8UVqeTdLsVaq/ttGrMxqLamGx8flYllS1M6k9QGUirqgyZXpZThKhZ8KxljwzfHnU2BapxGMNBKZGtROlOU9QOEp6Omt83OI1QK6NNTO4pSb3T3GrNJGsqINaYwl0AB7vLZbSeVNDSNyqnSRU1PK9dKwq49YIYJqisoteH5vN6BuNXy3O8Y67LJoaDhNSe05AHMPR5fLcWnh+A1/KrKyTRL+i7KDMg7qVuTJMCoN4p5xoxYGpuP+koQhXrTQ9uQlvwFPWwI0GabeKEiZZ0dY5zvp8cWF9vL0ud179dPdXK0Sv0qKLWGZL4wZAOtbu1mtDMpK5bRRZVNnKNQyuQbi1dhDE9tjuYqZcWX4lA3dLiaQILh3SrYCqWHCG7t/iV38ePy6NXyLxxs624ddIw2MdGs+Jl3HXyWNCD+SxmfIq3nZ8mza/SueueBUlBwTQ99WTynGUnXJ2AP3v5EiPThz5YxsZBJQga+sJv9bUPDe/yvhUML9GsTPp8GQ1do6LgFJ5DrD7a55m1X3B0yuw1KQ3SRTgoVa94njstlBuLzzWK14cWZ/CzIiBNOXuR/MJvpwffatJUU9S4UOxs2KkSVksS2w3eVAuy8VZ+uoiyu9Yd6dc6RZLBNU11BO6WtSsLjO2+Z5fYnIXHL/MxKo4bpGt+mt19+hulDXwMnYdJccPlDM99XIIebWxZW0CCufKEuVoa9ltsIUGWsckQ/S6SSPnEWbKER6ivrL9+KwqE3nKUR2PHkrAL8E98DCu4KTH3APOUyrK+QaLvFcWqSYmdOloeVM3YhO7QfnFUFfg+PRIPbqLZQKw2NWUKhcr3DLU4V3ioWLhHr9T7jcl6i9xvCdHg8bJ+TsNKmNHTYlonKuXdA0N9BQvN5k41VhMqOiIprmXqTdAC70oevS0kOGrBCD3xMeYUrNdR1nICzSoTJ9Vwy2jo1eGNVD3XDk7VjrKKVXqpNKNZLyNQ30kDKuojVm0CnUfGt+MZMMQD0tLN3qGqlWvGi9Zi4E3fQKDvHz6Gkbhq3w7nRBuL5UK4ihVqXAoolybO2SE0Ws+8DLvSQvt5DFAYkIq3R1CiGczkpRecX9Nqjex++LaE71vQGviI8VEuk1F6KiNGxJCqm19QqpZx65Dy/tNS3ynWZI7Ogqbrpp1cqPzqJDvPSQgebXGt8Syg/reNpzYkMYWSMNj9MvoaW1cAuW8m6RANd+mFJp1MA9bppyuk4UoQk8d8ickoeSDHURjWw9EFJQZ7AQ8q3MUKlpYUBZ5AimqyKTlQjvIpTNYNcWo8o5vpKa2fXCGLpZl6ZCQ9UGqVdKGJieLZL0gRWwviOXTtqukWBU1k1eSfpWzNNKBpXMFCmo7efIk/zJrFewQSlceWKXZ8D9+kgenjlqdMX2WGW9wO478ybXi3BqSbrTTQpIQfhCJz0/UgQPp91ngykxNE6FVqrggTiU7X6SC1OwiKYAHycQb76QC6tuMXmHCFMCzQZKpFwN34ph8dvDR44TZQR/lQyrX/0hC5eVcB5e2juerpG0rdSXiR6WORB1c1vO6zyxrvjOVJSvCOrhHQGFqF7KwjGyktjJqzdahkAYi3xs/TUBISKHX1pNRfGUQatWIl+j+C35FO4yKm4VGN7bq0VbnVmjU9lTUWTab0aPahGXUaSZ29gvLqNOotrZJKfnmJqEyfiSBqIo6S7FoTh1GZu0dRSYBoRsFSr1mUk2+w9pTUWdRaL50RDSQ+FHGPvVGRVEDY3WQnga2ySP5uJRUG174IeXme4KPQ/Yzewd9lddutTpG0ptivUbZupG1X5xf8ZBvlR3Be8q90VuZuMKjz8enyq+HVmniFgmmSrvsRDJtihUeCmFRgYFAvpfULA5RCy9dHTWLQRTCK3UTGwFVLyoRfldSuC0OWSiOgHjy4LO1vvz8+fK2+oc3RzJk7Nu7O01EhVRJFQAvXDlxXHyoDxz8O/4hcnMf3h98uD/4Du+thk724fq6+PLNS+CH6Yfq2+/v7+8PdlkWf7Cs5+fnVXkMxQr1d1DJtL6WD60g7gThJ99UyzSKYFmSl196bvE5d1al3VUKszxeNWc0rYuPxe1kAL1QVlvHKcLFbtAR+sP9ffjmzXfFVC5etpW+ifF1GUlpbvV/8X8t/NB3Vs+pPxQxUMEht7Hi72//eX+QwCB6gi76agP8FLYPXb4U88Up+uVvf2+/Ls+kaL5dRDxeFJ3PSuNrlGY/4GVX/xufsvFZ3beJciUKsU3/NyJlI/J/fJa8P8BrBRG1tXISp54BRn8uqBbNnTr83mP37wdvD9ZX11+/XF1c3f3FXt/9/Onqxv766Xp98OHguz+iKLi/f1Mtsf3+/uB4dXR/gL6BoRPhthj66ue7Hw+/uT/4I7KJjFY20SMhCOD3NF8vyiTouopFqxvHX9cO+hcFrbUOCmn0APrfd5vId2HS6pcJ2nmmftJDCds8lza3ObeLANCvFQVECVNGMf6yuJ4Xf1PktjI+J8Xbt7aNvdOq3bs/WDt7ZxxUuzrtoEADZuozmS6MeEAcomaAHcSxXWV9D6Z7SARY3G+s3UpxR2g5ll52YM14UvUIDKtX8aVm5DurrK3Ir6pFjF9BtkMf88TDdrPc9aIPdYVt1XVaqdVU5MWnN2Yq5TsY4Hk0qKtarl66XPUyKgC+5xQLjouFoVV0N2/QNrKHKcBM09u7S1QnV72UVKs0eUatjfiBH211G6AcSevotVCeq1Zcc1dO7pkT10zeHG1a6mtP3IG+Kf4idb1iLZuj3Q2vV2PaVdE0baY4BLqYlzdlsGi5mPUJm2g32RgzVbxEEvzdynfldGXfNU1FvbeXzeSYkfQLpzfkRn3x9ILUC0coz46E+FTUxqPPj4Ral4fAfkH9RUbQEYHLH29PT64/n5xxBR+jKPrEAgr0QlEeows3yelJsD05q+rEbt5CqdAex1vGmUVEgtX4U58PS1MdFhox0AwkKHtpJ6XJ8qNSSqlgMlaH86qmY8MPjo6PNsdHJ2decPZNVanJxlF9cPC4uGKiNsI2cIJYN20jqo+yeZtrhCw1tTE+5El5wr1WykZVJ2fmmOAsVbVxOuUFDVopK01tjPV9FFoha1F9lMh+te9cL2irq481AEg3dRIvzqJEP/JAXh95XO5P0MtbiWqjhAZKFdRcqmCegvLQBr2Yjaw20k2aOPrLVaOqjXMbO4n+iqpR1cjp6Y/OWlQrpV2cm20CtVHWxrvbmMiljapGzhcTmC96Kb0T/SWp0tTHCAy0S2pRfZTNUVF6ORtZbaR4vZ0DQu2ohK42Vh+1cbSD1qJaKV8egP4WHimsnba8h8VAZ5RmQB89bC4L0wvd6upjNfKu8rW/q3wT7ypf97sqAJ7/EL1oByV09bHGYPdgYgiFFNZHm+p/wVaa+hif9A/tVZraGGMn1N+MrkX1USb6q/xKUydjeVOzb4SV1NbGnDoJyJxdXO7P1YrcldZHDE3VqR1lfbwGxntSzeM9KWoEb7b6MRtZnaQmBs9bWW2kZlp8+tt7uZkGX66/xWdmUFL/mOSTC/Tn0FpUG+WzG+kv8bWoKmVQLRfTBUjqqU7H92f49SDSZI3MxnM9yniI9fNwaTveFCS62sQLHc5VJoN1mM0tstMpU3LVlzu3oXginrKEsr4bmDiBQ8Q+LbwUiUdIwZfMxtcE2gnceiiLcbySOlRMLbm4gtXVdiLxU4eRswjSFPK8Pnp5ogklmSfkcoJa+hfnnuQcnZCu1TbUtFW+GqRfmtNEsjRP50DmWqjKx/oaeYaWUt4SYyFCSaYyHrr2/VTULhnOREpnUeQ7O+CxKnzFjDIWLeXmKO5IaWjr6GnDcyWLwJtX9gU37WmRfwXqmNbhqtwPZATaHWOxrwijSrF1HDtOYLVsWJ5mqKMtT2huYj1EUeZH+KBG0WZWd9eWTB3dVWCXvJbV6ga1hkpKFZRoJF5cr6/WovF3gTfKStV04itgexFfvszwMnTP52nZFf5ZGLjpdwwlpMtdKUXcYiMJQyhIs2S/1Rc1SIF0gyvGCKpEFGKjCi3PUBwJGJyeyjGQoaUZgji3QRI8cSzLpjB0Qu+r/h0psnhr7smspR01XXljsYDtZacquHRSRmlx+ZYcAhHYdNtKeJPI0E88JINpme8z0tVqd0U3+FIbDaj/IbMNiNjKKVcUVBu+lL2kzPxY+WoRYetWHl1Opf3ZPylAG5740nTmDnptbMKrkKfRwieeITxOtlrMdLWj2nkdHDGBqmtm/UOLg6ozO6KnMfvoJGzltGYiXXi12MxtkHq39TzDK7V1/litQ9RRSiqopHOz6zzJOMbeWDS1ytIHfZrY464aG4+repFU0Bb/yjS1ysyFq5yHm6doVXOAuK7hz89lIGJsl5RQSd5K6hEmIfQVeVqRpRcvMgK583Tlcz2P0pXQlwZqPK3I3EWsOYRqpmLW2BfI1U2YJmd3VJQSuT2Uawf8ei2SFrSeoEbKcruxPshGTyOjxjTu6ikwej1RgULdx6NJLb56bUuNjON1jdZR0ZQaCkB9maWO98DATZ5ER3u4Fu+YyC7QiXjm7gqnyKUMTbiZ33P4vMsZoo08ZpM39nCYIu76gaXLVnHAt4x1Zat2cQ4Tz9gRzXcisBoFV91OIxCoySet2xu/ulRHiqENrkZSX8AnDlGHXPSYXe9QW1wJ2eUhaOyGB+E0fqNPS+nKD1JUneAa8oMURB3SdH7wvQf5/IACF7AX16enxdwtEHAVBbZoAsttT7DjStdCQNSD5exzFFRFtiHDSKyxQ8HxeUViBqsQkuaq+99F7FVB5AxCYf+gin/FSSBi9uogcgbxjk4xe1UIOXN4S6GYuSqEnLlUNLOkClmlHEYSNdgEkjPK2YXv2OTspktOvshtSmhqIo6WEHal6McEYoe6UaqTncexAbljsQ4iX10K2uOfNKaaK5auAa6OTtcqEVByk4W4v91Qcj7z7mPo+Ku0jaHIhxwrLHo5l3sRBe01yLdropumKpsmUPgEBJs8FC2hRCg5s9zrJTtmBddIjrQ0RCM44R9WoRoU6Zr3DIt2zOlNHTG7AgtaRpo6YvZEzkmjN3XE7Akcd0E1J1f3dgPKt7PErAoc9kBtZ4lZSxUKCu9m/K5Boa32o407YaNVIBWjkpXCMLBKC1PMNudAv/bVmg4CzF6FO9zE7R6SM67tdTJpHuPjEVXObx+96Eoo6ciLGoDjQB+fvc/1Iq3j0SIjxhr6WN1eY01ZUt1MTkhHQejFCUwhz3k8Kj70DGlwAV8uYT4NaFaMbJEfKwVC48QjkWUjP5MofrV3IHGfAc9wD3dcVbPWNAuqBzIkScQ1ky5A2mgqZ8BaXn9UEsKqlLA4714zYSOqSFeLQ8dFhQz9l2OeQIiUbkATdboDhnArZfUc2t5NqD+TdrU1VeeGYPvi+6y/xWbVWXWNvldcvfO5FVZMQ1Qn2IBn8l8IkVBV5HOcwAAfoarKFwDHBCAhq/42CUAItjDQ21ossmJfW5V1B44NxCYpq054cv7ODCMhrE55fnxihpIQVqTcGinbW21lGzq/xuARGmDsKStyZrsEAnwtnQHSgbbW9o32F2NXW2/7RjdsX1xPzD4BP+c581wmZlvt+Y6bq30fDjthQjfxnjj3CowJ6ei5l0mbJeFWoVXc+tNpENeqmjJ3aYF7I5EYa09cL3I1iWcKupXXgI0aStU0nO3CGIYuDB2u829E4CeM6HGhipn6blh8IYZ2D0ZsaHUAiZLtVkMuDK1odwLVXN5TOcBp0ImuFa1OANS4MIVea2sFRv0yU7yVtFbc4hz4LFcaOp6E7hjQiu548Y5vS5YMd6uuB7q4+DsGCb753awDk5aMObPjWg+u7spOeOG4oCNGapwJO8YcMVETjZvR74bh99e0KT3uRDH4R2701UC1oBXecDKMWjGRAoZq3DEjJlwwUj3RTegZb/Cy1C724mmEHggvf+qnJ4IcEBahxrIXZjAJ8YbyJE8z6NppFiWoS6EwwENENx7bQR+tKSui2WQ0r+/HFZYlLe6U6xG0cjeSwsVSNMePJtBw8EObh6PyeoeENrDoi6gMf06DkwYMDgtpxZ8wor8vr5u8p22ih2kIuVU3OexjCH5oxeQAnEEn9E5PD8ZrDJEHWi5w6rb+8NYTnJj6axeaAa3o2WtsoFLsi+vv4pqL8lEr+p0wE/lUC8ubVazXt8w/pWi3LNJdrUahObSqo6neIWz17DzzuE4CFAVthLXSKo4cTPFqHC8gZauV20aQCW2tzEqDyFPA2kaNSVFNI2NT3AaGxfryOxC6vqewEIHFTxrQSq8+dzWFrnfiilQGWQbx/WimMk1PX88bvxaPUr5zBrmoqcr6eauL2pKM674LWfa+leWPSU60INRjqT5esaOptRy5cOOFCk3PCVZSWyuzWmN5ilhfN2XQmDKBWwvrLe3K43t95FF1rbHcjEcXq5lMRPfAgt54r+XNxDuprrdVv4POo11uCzUS7X0DeukNchsiVhtQnSTWN5pK6+mYQCa09feiTADvhA/x5KDVNF49xW1gsHq0k2OKnzRgqBdlAr2jbqwXZYK8pz/f0KPmkz9iVBBwVQn8PR222Rrkvo6gDVJ0tqgKCzqQb8jHzJCEh8UEP01B4gyagQ73sUosIO5jlmSz6/gP/VTCXYfRZBreIL7zEteOQSJ+2M0mgRB35+UOuimGA1SmBYSvnaRmifaqzrFih+PTIqLJqv0ur/msr6HsCO1zcEP8slNqRNReTd56yoqL+vbRvpjiq62RQ6+maLwXJUzXyC1u5qy8QUileODNh+DBl8kXPaXPFxfSi/F6Uh9vr8vTtn+6+6uk5ohyGIV20YwRd5iZ/XBUSlQPZRpadUJYKB4tMgKsltmqTcgtr2Owg3T8LGF9+JUVIx4EwEnGdxDr86GxYywdzPtQWVHxQHJNpFJg6XWYvYrgGgbXIBQ/846aajsIYvtMQ+GpqKxW0Pg6VS3TJjpaFiCLgokzJ5mRWGFYrY7qoTNJhIyG4116biRSSRHKhXECHYCXWxezK970yiduxHFd1eM9nvDioy2KgVgDZl9NEe5HZAbfEq8ORiopQvleOt7V5AaqVVRPdINpCrbQfsg3m4lBZ26soZ4qYJzbcRJl0fSkID/gQE8D4HMC4hhOHJEshEeqKcLVbx51MFJJFSqJfkWVkIbYIpUUof6Rw1xDNDUyyueNBfFOQ3lsdVSBMuA82kXLWEPC9dUU4dZY7loTW09MOd6Ku7Z11a8DOdVTr0A6flkcN1WtogqDT/nWkIKtjtEROHprUrqXQCoIcE80x6RR+irSOEUrRRqjDi1tvqyNpe03waUBusVVGmQgIw2ES6pCxmiCywOUZVOeoAnPNfNj7rLZ6oQ3uWkP33tIQMKaa5mIxqmjrQdxWKFalVVL+AjrvvE0PEbKE5ehsRFICSWQ58TLFEEaCWmQB5DCdwIjRH2KNrw0AmPzBRNBZocFFaHov6hyNCLyb0JHAaIKrGLcdvLkSaWUdjU0oNghfNaBU+tIIwXjh3MwMQLBUzf6BdXbhrnAPMigoDbhFRGmbx7l5BC6i3QKJogUkqSroQHFToBCRh3qSCNFnkK0VIGljccTd38yjcf8d4DSjT866bmC+Tq4QrXlpuOXTHDUVlVwhRhQcV/RtGLrihBQgFBsWRECChCKrQlCQD4rMjaJsjOjzE5QOoQdR/74jmBekkZFvqmXJbabPIxviGS38wgFaYwdvuFBjaMjId/RLy4ekKdow8snSRSmGcAnAaAuskK69GXku/r1qffyMB0J+VqkWr+pUI0QCsoY07v6uVkk9vD3gVKgykIoyPfifdRimzzCht2LJyXkW6ChHeQCCwsHLc8mvOJAAnurGOeIguSusIkeizxQV0RHj0WVpdLQ1WPRgFPraEJCyf8EUu9JPdloglrGiaTBeiIKr83JQ/o43pfip/BNvbltL4gVyj1dSxeacrU0rqc0wNXs3J26u4driKuvpIilWvz6Knr6D/I4PRX5icEgygRmevscTXCFMUh8ppY8QRteBUGtCiQE5CHilHVOKZujo6GEMn0mLBeJxBmwFBDc7xBZsEEjaTWUULIEOApVSEdCvq8AXD9yBNaKDLoKrYDKcJD6K6gnojw2pQKiXHzrQTYFiEZAuR+pI3FoUtJgCb7A3M/sHfTFlmf2sShC8kNFqW+78CHfqmNRpZTAHN9T6oh3NZRQAi8V2C5AA6kVlDCQ6PGphpYcXUsD2uRxOAJY4ofe9JBezo++lR9KqkMrmbcd9M5VmbToiajCKAytkQqqGAJr8EYw1NbhlSKpwuoUUkEJQ3FSqyOhDqKeNh0ZHUCqqdSRUWpSlJe61q8TpTHqgZQGMB1EuuJo8sIbkRgSv9ZmIuEUV6RRpXSAVefD1/ts7DCyi0Nsxg9dEWGdVNeBn/pRxnPzpgg0RVMLanVljBbEVksHmtL6wKGODqTNxh0/2VmEqRbSATV53LQIlPjx0uNQU7fEiTAJ3wU3joSvotfCVAvpgEpU1lANdbRUCZpqA7U4qs6crN4u02dEsic16GLaXuxKoyk9IY0vdh1YMidSToApzVBThHRBKQ+xj+sZaBBpwaRomm27GYDuqutqdegArXS0tTp0MNVC2lodOqDEj2Mdh1IfBBwR0wKnMp861NHVStOBJHyRF6OVpoOpFtLSSgOhGwWKCz/G9XQ1JLWgKc6Zd1uAOohSbcnY70NroRtq6uyXa0EUuxZW5TxE8aOolLbtTsQlEDmLpo685pCX6jPQcgANSDyJsjlgqVRUYdLwWANMpaIBRnJ6nEYkMVFOxao2+yoztTqqQOWmRnWgRkcVKPd8F7WQNgKnPY5CdbQUwRz0j+/rKG+kkiqUoyHtKhFVlB1A/zs50sBDKGmBiiN//IYKQaxaSxmM42YVATSt16jIDvIMsHTdOeJIdScGOHpuBS4Pej88Wb1oQOpoKYPh9LeB+2ueZrYPt8B5rScbNZBOiptA3ySoJyO1UpcLnpTXio8byIV4aUg3PkVeO36a4zEwmBl0gWJCqxtpKtGjnsauJLViFmufNHPWmnpAdZZAbcWN2Keqg60rp4pXb29WJyOUFKGKtaLqRI2MMo6GTrSrpRPt7jS0oSsRRRToyIzH91lqFXUYHSW/kVHG+VVuBHcI9Kv4CO4IksSMzhBHcDqHjsK4h48fR9ule5L7eQZA4nt6qDhbHV3lrZau8u7R3aiz1CqqMM0hGOpEpJQilh9oeEFUIooolZq23vpQTxVQYp3IAEpwicgIyLkOknMdKDCIktfq3FQb+H6kYQRhRFQRNUSdoDRyHqHMNG4fsSemiuah7sSjxPkGA6xWSBEJn62mjFOJKKLgk9aUUSoRVRSJ7ZkDEh0HeePj344F7o8bh6l1NABpqJUaGQ047/XgvNeBU59upE5EKGmC0tS/H8jpwiuOP9KHV8up4kX+6/HpkY48TyipQhW3S0MbOA5MNbzmhnqqgPVxVupohJIiVOKht4N7/E7DpFpHShVLx7iA8HIgKkq6AxoWHdQq6jD4JD8dOJWOOtCpFpxTPTDnOloGrY4qkI4ZAj1zAsXeeeDsNLztOlI6sIpJ3DT3Mh1DtjRFHZBR9OjpirxGSwNY5uGumB6wVksRrD1aU5mrI6WK5QV6mBodRaAnlEs9ma0bfSJCSBFJz3ShpgnC5pwCLUC1kh4oDWWOVNIClWoYDieVBJYDK18Fi1q1qgtnVZeiIARL34qTam9cOWMOcryxJsS3HCqMLrWAY7paoas59Uf4ini8xBa8JpNNP2rAhBvpaxiFryqj/qMOkNILWJ6KOfUuTS2dxpqZF+INgnGUqrXXiLiky+pFRt35wMu8J83IXVm9yLhUoBoSD0MotREo2ENpPejlakMtqK2ULjS1ubUOmq5lsJ2NobLbeCmEA0XNoGEGX7JUdz0wLW/GBQOFjG3CjCuaq7hpeT0uIOFEYaSPoG2U9ICprkolyPStPq02hypPqBBwGudUmi2PVc7RwtdR0wTo/aaphDRKmsCyJHf0vDxbKT1o+hr+mlv4T8DPNZG1UkZ6vQZvi03hdos+S10Wm76mGQyePPissvF1ffn58+Wtave9VLFv7+74T/EpfbdaN6xSxeqKKea2Uow/mzGoNOR/wj1dVLXYYrM/6+dB3vZ8DzVfbB88sPZk08KiUMV5OHIFq1rJVW6v5yuc1ITGRw2X68AmywTpq0XAW10OqyMnvdu/VZnMfOJQnNnPaG6i/ED7qrcdPI5XThwTsYF//2D9Evl5AFPrFqZRnjjor62XWQHIMux3BtKdFSfRk4dH760tDGECsiixGjlr3GQAvFCnzVZvwmj4FJx2cqKSyVptwiCOiZ3OaN1NmvuIFIpTmaLwz/BVzjJ8AUHsw3bhTZX3CaShGW6mr+uPsqkuDNbYmqD7Woe92IEwhL6xOKMZEuAqWgLG4m3UGg/hZehE/QtBjMARhkS49hBtHVM8bNflu8N8nBGGRLj2EGcdUzxs6I8scqI9FFHSkgjZL8f7iLi+NSHCk70SnvATrinnLhmBW9MPZWJwfcZv4d5RiibxCHsisbeHxO2YEmC7yNMsCvZISBoU4PwENyD3sz2CdixOkP4wPB2JGytNHHxCmZXmcRwlmfUD9YQkukHJmBgxyfTyFbXh7qI/wRdNnnb0+Azr8rinOGH84k9XX79E221/hZe0bb8Us3rCEwh38CW7Cf3X+mlNkVCDUOUncNZFsbkYTnwKkfRLYV+VF0AhMiYRWLGgITH69nkTAOeci2J0+evHLwr9NsxQjlJbdElGDXT6Tdm8ls8EKczy2I7Bqx8B1+pr8ppXcH8CYBgD1ej+V5DttIwb6JSv324mNPsZVacNlAia5epJGJ2yv/32m10lG3TxcM9huQZCpw1ySD30QZpCVEcnMI5MONQ15kWihsgx2SZ3PERRhssR5MnZHYWqW2I9+DnMkMquOndHluQTfPIciCt0PFD8BVeulz/enp5cfz45s67UvCxTHseVrMLF9fpqbV3gEWtFllLp9u5mfaIqhbJbEWduEXW2F6Iso+AjDNzkSUNcwQA3WcQFBrNUmwSiAhXh0/RSL5WMrXHVR5iE0JcsQUxZ3F7Da3GtzxcX1sfba/vi+vTU/unur1YYhXYKnTxRTngvSrMEgkAltQoSD88J+uUyqxCGWTEPUx0dUbc91Yq3oBlUv0D0ojduTUMu7S0k0CVXHYGtVpjxrIpK5ohhUmygAr6RLIa3r5aLegzIw2ZS0aQ2X2NIajJeRpdznlXxRYre976zA57Sa6KuxEq/tSj5EMZ44z0tyQPgJNEnuMFvSdSk73bN7Iubn368+myv//Tx5Pwd/nR3+d939vrqr5dFN6VYEYSeRT8Kya7/sr67vK7Vf15f2uubiz9f3q07qse8muurLx9/WNtfb29+uVpf3fyE/7q7ubj5Yv9yLKn4hVC7+NPHn366/GJf/vTxhy+Xn+QUm0bbx6Pjox+Pj07Orq7PvhHg+fj1K2b6enl7d3W55g1YvjZ++vnaXn/6s333p9vLj5/sLzcXH7/Y67ub24+fL+2vN1coWW+7cX8iQHZxc/315qfLn+7si493H7/cfEacl2v0mVfj+ofLT3df1nV++PHqSzd7/R8/+w/iJVWvLv+DqP7X9Uf74vYvX+9uJk11bnsSNHV7d1fk54/r647uEXd8NiuN7PXlxR3Kf12+f+RR9h/tQ+Xnnnj1jvyxuyIlc51///fJJ/nem7gVi/4f/1023raOswI8COhBnse4Hgp4HgojVIv2HsSV9E1cRTr+cOWiJ9tvV7mzwq80JJQUUR8VX088tcJPBN5vxZqATmoVR3Wat++8vOCLskIXJG7HPkrw4/cS9psX2TRA89jKifOuYdSIhC+HwenpPqxvetY38dP5Ydof8zJj2o9AZoMHrwOwKxLCdLKjvkDTuB6u0cKBvnhp1hit4VBNigqi3YYeDFBarUFRF/BgT/DA9KF5bJFO+F74yPKgfKb6Z+2g/kDWyQL/EifRr9DJLLz/dAtDq3wSD2ut/D1kjk0eOvhL3KXG/6YduizJ+z0yAwwuyIBW+wIJE4IQvb5t9FqYw/Mo8DJ7k6C3kB1HXphVAfcLEeJNPw6M50p+ZD/JMm/PCV8Pbl+DuGgM7N9vZ+Rl/O235m0/gyT0wm26Ar4/g+uN+WK32ZwAMXRBmHlOt2EA/HSfECCBdnF4ciqJEYBHWLwyQBKscDs7A8kWZn2OkccGzbLDAH3zvWDjTJEh2+XBQ4+i+s688X7L8DBA33xftQ8P3eP+sIUZCGobEaHg7w/R999ztxcHJtpKh0nTPjpWQx2iPuL3vNXUhH41ic0Hg9fxj/VfSiDuToxmJNr763ATRoflt7MAjbzQCyzyt/3lpbqys/tvnMP/Kr7ZbzSZpZGKl+Gr8PC/qu9mihtjRCLxMzpocnjDN2SiMWZMsojEyXiH6XCDfztsf9tvBO0NTCS2pru4h5v699libe+AQuVvuot6uMEPHBYPHDYP7LlY7h9RJAaXMXSlMb4X6tDomOL4k0t1hT6OMfLY+OCi/JiiIlExqjYYUztEnSnopN/jX1fFn/tgqQd67PKzHYC4S/Xfld79m8NrEH//L/968/Pd15/v7E9Xt/9m/cu/fr29+c/Li7ufPl5f/tuqCKxSdQyovdQRynqH/4Wa8HmYp9A9jAGu0wbVGVMicIL+wAIzDCPtmOH7DSS5ArKL0mx58cnK10K+Is9W5dKTlYcqltQ7PSk9drNVuf7ELY4kLGaXVtswXxHVM75tvB8lhGDv6fKhFY6zVZTtYOIj9/6/yI3UMxsmnt8EME1R1B/6MNxmu+/78/SmUxj37EXSmHz+f1N5llQu10cUKVzN8fUTrVp4HMXdziTcJKcnwfbkDBwdH23wEiAvGCwBotv0QLKCz3Hx1hmrIa8ucRf+ph4BEkqPYRqKxQnmw2z4i2pFQJ1Ln85XZ6vjPuxEgCpbA9ctlsYA/+cUJvO4xdtCEX83+W8PD7fOSMePLzgqunhE5zB5fkE62wCGmdL7SaDdLezvC/rQyB0+e9nucLgpyfjbtGo4MupZUTnHS5zcB4kLYxi6MHRe5ea9luNRiBpj7qCVzz9rJfcepJctFa3/AUnTPlvXe7678cFWsKYzUiEoRT1nY4b0fI9+f2dVr+7i05vv/vgS+Fi3vCQCKR+vjgp6iHdQeuEWffXz3Y+H6G39x1KgfvU3aw1zZxVEbo7qz2In5uqiWBP+tXzsKypRPxRx1WyZXBWrIVF4pBTDJHtdO+jf7/E9XVWjgnQgRgJFZK8zGP8B4Xc+78kltzxEYA2zrJjeFvDFMkelEsUGsXKnApNN8v55edWgD62AdHcUr5zEqVcuO0lpsTrXvKn00FfNLlB6TUge6NbNWwdvD9ZX11+/XF1c3f3FXt/9/OnqhliafvDh4J/3B8TW4A/36It71HAGTxDl18h5/AUkHt4EluKvP+D/4Afw/6E6IvbQU+7jl8gp52OqHz7Uf2yh8xjZqfton6GW5VH99dv6D7x75CYehhtpfle//l7+B8kcVGdl/A8D/x0lS8mAlz2lKBX+1iYDdJEeTuS3TWYr9o9gF6udZXiBfbkZpj29HT0dJd7WQ43w6vEw9/23zbU86Ivjt4VChipd9Onbb7795vTb86N3v78VNU7s1rRdx3VUMA7Pz89P3337/ltRDhDHdlU4PZiqIJy9O3t3/v7bk1PxmBheTi0eAcfvTt+/P3///t2JvP0qRZQwjk9RfngvkBD10Pbt3aV9Ue8sS6WsHx+fnZ6cnpy//0bUeC87Oj4q+imeHJKIgbOTd+dnx+dH3AlRQwyqcWHjJ0cn3x4fvf/m/bvf/37w+/8DgDs58g===END_SIMPLICITY_STUDIO_METADATA
