/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP
// This file is generated from clusters-Commands.ipp.zapt

#include <clusters/Groupcast/Commands.h>

#include <app/data-model/Decode.h>
#include <app/data-model/RequiredFieldSet.h>
#include <app/data-model/StructDecodeIterator.h>
#include <app/data-model/WrappedStructEncoder.h>

namespace chip {
namespace app {
namespace Clusters {
namespace Groupcast {
namespace Commands {
namespace JoinGroup {

CHIP_ERROR Type::Encode(TLV::TLVWriter & aWriter, TLV::Tag aTag) const
{
    DataModel::WrappedStructEncoder encoder{ aWriter, aTag };
    encoder.Encode(to_underlying(Fields::kGroupID), groupID);
    encoder.Encode(to_underlying(Fields::kEndpoints), endpoints);
    encoder.Encode(to_underlying(Fields::kKeySetID), keySetID);
    encoder.Encode(to_underlying(Fields::kKey), key);
    encoder.Encode(to_underlying(Fields::kUseAuxiliaryACL), useAuxiliaryACL);
    encoder.Encode(to_underlying(Fields::kReplaceEndpoints), replaceEndpoints);
    encoder.Encode(to_underlying(Fields::kMcastAddrPolicy), mcastAddrPolicy);
    return encoder.Finalize();
}

CHIP_ERROR DecodableType::Decode(TLV::TLVReader & reader, FabricIndex aAccessingFabricIndex)
{
    enum class RequiredFields : uint16_t
    {
        kFieldGroupID,
        kFieldEndpoints,
        kFieldKeySetID,
        kCount,
    };
    DataModel::RequiredFieldSet<to_underlying(RequiredFields::kCount)> __required_fields;
    detail::StructDecodeIterator __iterator(reader);
    while (true)
    {
        uint8_t __context_tag = 0;
        CHIP_ERROR err        = __iterator.Next(__context_tag);
        if (err == CHIP_ERROR_END_OF_TLV)
        {
            return __required_fields.Check();
        }
        ReturnErrorOnFailure(err);

        if (__context_tag == to_underlying(Fields::kGroupID))
        {
            err = DataModel::Decode(reader, groupID, DataModel::DecodeContext::kWrite);
            __required_fields.MarkPresent(to_underlying(RequiredFields::kFieldGroupID));
        }
        else if (__context_tag == to_underlying(Fields::kEndpoints))
        {
            err = DataModel::Decode(reader, endpoints, DataModel::DecodeContext::kWrite);
            __required_fields.MarkPresent(to_underlying(RequiredFields::kFieldEndpoints));
        }
        else if (__context_tag == to_underlying(Fields::kKeySetID))
        {
            err = DataModel::Decode(reader, keySetID, DataModel::DecodeContext::kWrite);
            __required_fields.MarkPresent(to_underlying(RequiredFields::kFieldKeySetID));
        }
        else if (__context_tag == to_underlying(Fields::kKey))
        {
            err = DataModel::Decode(reader, key, DataModel::DecodeContext::kWrite);
        }
        else if (__context_tag == to_underlying(Fields::kUseAuxiliaryACL))
        {
            err = DataModel::Decode(reader, useAuxiliaryACL, DataModel::DecodeContext::kWrite);
        }
        else if (__context_tag == to_underlying(Fields::kReplaceEndpoints))
        {
            err = DataModel::Decode(reader, replaceEndpoints, DataModel::DecodeContext::kWrite);
        }
        else if (__context_tag == to_underlying(Fields::kMcastAddrPolicy))
        {
            err = DataModel::Decode(reader, mcastAddrPolicy, DataModel::DecodeContext::kWrite);
        }

        ReturnErrorOnFailure(err);
    }
}
} // namespace JoinGroup
namespace LeaveGroup {

CHIP_ERROR Type::Encode(TLV::TLVWriter & aWriter, TLV::Tag aTag) const
{
    DataModel::WrappedStructEncoder encoder{ aWriter, aTag };
    encoder.Encode(to_underlying(Fields::kGroupID), groupID);
    encoder.Encode(to_underlying(Fields::kEndpoints), endpoints);
    return encoder.Finalize();
}

CHIP_ERROR DecodableType::Decode(TLV::TLVReader & reader, FabricIndex aAccessingFabricIndex)
{
    enum class RequiredFields : uint16_t
    {
        kFieldGroupID,
        kCount,
    };
    DataModel::RequiredFieldSet<to_underlying(RequiredFields::kCount)> __required_fields;
    detail::StructDecodeIterator __iterator(reader);
    while (true)
    {
        uint8_t __context_tag = 0;
        CHIP_ERROR err        = __iterator.Next(__context_tag);
        if (err == CHIP_ERROR_END_OF_TLV)
        {
            return __required_fields.Check();
        }
        ReturnErrorOnFailure(err);

        if (__context_tag == to_underlying(Fields::kGroupID))
        {
            err = DataModel::Decode(reader, groupID, DataModel::DecodeContext::kWrite);
            __required_fields.MarkPresent(to_underlying(RequiredFields::kFieldGroupID));
        }
        else if (__context_tag == to_underlying(Fields::kEndpoints))
        {
            err = DataModel::Decode(reader, endpoints, DataModel::DecodeContext::kWrite);
        }

        ReturnErrorOnFailure(err);
    }
}
} // namespace LeaveGroup
namespace LeaveGroupResponse {

CHIP_ERROR Type::Encode(DataModel::FabricAwareTLVWriter & aWriter, TLV::Tag aTag) const
{
    DataModel::WrappedStructEncoder encoder{ aWriter, aTag };
    encoder.Encode(to_underlying(Fields::kGroupID), groupID);
    encoder.Encode(to_underlying(Fields::kEndpoints), endpoints);
    return encoder.Finalize();
}

CHIP_ERROR DecodableType::Decode(TLV::TLVReader & reader)
{
    enum class RequiredFields : uint16_t
    {
        kFieldGroupID,
        kFieldEndpoints,
        kCount,
    };
    DataModel::RequiredFieldSet<to_underlying(RequiredFields::kCount)> __required_fields;
    detail::StructDecodeIterator __iterator(reader);
    while (true)
    {
        uint8_t __context_tag = 0;
        CHIP_ERROR err        = __iterator.Next(__context_tag);
        if (err == CHIP_ERROR_END_OF_TLV)
        {
            return __required_fields.Check();
        }
        ReturnErrorOnFailure(err);

        if (__context_tag == to_underlying(Fields::kGroupID))
        {
            err = DataModel::Decode(reader, groupID, DataModel::DecodeContext::kRead);
            __required_fields.MarkPresent(to_underlying(RequiredFields::kFieldGroupID));
        }
        else if (__context_tag == to_underlying(Fields::kEndpoints))
        {
            err = DataModel::Decode(reader, endpoints, DataModel::DecodeContext::kRead);
            __required_fields.MarkPresent(to_underlying(RequiredFields::kFieldEndpoints));
        }

        ReturnErrorOnFailure(err);
    }
}
} // namespace LeaveGroupResponse
namespace UpdateGroupKey {

CHIP_ERROR Type::Encode(TLV::TLVWriter & aWriter, TLV::Tag aTag) const
{
    DataModel::WrappedStructEncoder encoder{ aWriter, aTag };
    encoder.Encode(to_underlying(Fields::kGroupID), groupID);
    encoder.Encode(to_underlying(Fields::kKeySetID), keySetID);
    encoder.Encode(to_underlying(Fields::kKey), key);
    return encoder.Finalize();
}

CHIP_ERROR DecodableType::Decode(TLV::TLVReader & reader, FabricIndex aAccessingFabricIndex)
{
    enum class RequiredFields : uint16_t
    {
        kFieldGroupID,
        kFieldKeySetID,
        kCount,
    };
    DataModel::RequiredFieldSet<to_underlying(RequiredFields::kCount)> __required_fields;
    detail::StructDecodeIterator __iterator(reader);
    while (true)
    {
        uint8_t __context_tag = 0;
        CHIP_ERROR err        = __iterator.Next(__context_tag);
        if (err == CHIP_ERROR_END_OF_TLV)
        {
            return __required_fields.Check();
        }
        ReturnErrorOnFailure(err);

        if (__context_tag == to_underlying(Fields::kGroupID))
        {
            err = DataModel::Decode(reader, groupID, DataModel::DecodeContext::kWrite);
            __required_fields.MarkPresent(to_underlying(RequiredFields::kFieldGroupID));
        }
        else if (__context_tag == to_underlying(Fields::kKeySetID))
        {
            err = DataModel::Decode(reader, keySetID, DataModel::DecodeContext::kWrite);
            __required_fields.MarkPresent(to_underlying(RequiredFields::kFieldKeySetID));
        }
        else if (__context_tag == to_underlying(Fields::kKey))
        {
            err = DataModel::Decode(reader, key, DataModel::DecodeContext::kWrite);
        }

        ReturnErrorOnFailure(err);
    }
}
} // namespace UpdateGroupKey
namespace ConfigureAuxiliaryACL {

CHIP_ERROR Type::Encode(TLV::TLVWriter & aWriter, TLV::Tag aTag) const
{
    DataModel::WrappedStructEncoder encoder{ aWriter, aTag };
    encoder.Encode(to_underlying(Fields::kGroupID), groupID);
    encoder.Encode(to_underlying(Fields::kUseAuxiliaryACL), useAuxiliaryACL);
    return encoder.Finalize();
}

CHIP_ERROR DecodableType::Decode(TLV::TLVReader & reader, FabricIndex aAccessingFabricIndex)
{
    enum class RequiredFields : uint16_t
    {
        kFieldGroupID,
        kFieldUseAuxiliaryACL,
        kCount,
    };
    DataModel::RequiredFieldSet<to_underlying(RequiredFields::kCount)> __required_fields;
    detail::StructDecodeIterator __iterator(reader);
    while (true)
    {
        uint8_t __context_tag = 0;
        CHIP_ERROR err        = __iterator.Next(__context_tag);
        if (err == CHIP_ERROR_END_OF_TLV)
        {
            return __required_fields.Check();
        }
        ReturnErrorOnFailure(err);

        if (__context_tag == to_underlying(Fields::kGroupID))
        {
            err = DataModel::Decode(reader, groupID, DataModel::DecodeContext::kWrite);
            __required_fields.MarkPresent(to_underlying(RequiredFields::kFieldGroupID));
        }
        else if (__context_tag == to_underlying(Fields::kUseAuxiliaryACL))
        {
            err = DataModel::Decode(reader, useAuxiliaryACL, DataModel::DecodeContext::kWrite);
            __required_fields.MarkPresent(to_underlying(RequiredFields::kFieldUseAuxiliaryACL));
        }

        ReturnErrorOnFailure(err);
    }
}
} // namespace ConfigureAuxiliaryACL
namespace GroupcastTesting {

CHIP_ERROR Type::Encode(TLV::TLVWriter & aWriter, TLV::Tag aTag) const
{
    DataModel::WrappedStructEncoder encoder{ aWriter, aTag };
    encoder.Encode(to_underlying(Fields::kTestOperation), testOperation);
    encoder.Encode(to_underlying(Fields::kDurationSeconds), durationSeconds);
    return encoder.Finalize();
}

CHIP_ERROR DecodableType::Decode(TLV::TLVReader & reader, FabricIndex aAccessingFabricIndex)
{
    enum class RequiredFields : uint16_t
    {
        kFieldTestOperation,
        kCount,
    };
    DataModel::RequiredFieldSet<to_underlying(RequiredFields::kCount)> __required_fields;
    detail::StructDecodeIterator __iterator(reader);
    while (true)
    {
        uint8_t __context_tag = 0;
        CHIP_ERROR err        = __iterator.Next(__context_tag);
        if (err == CHIP_ERROR_END_OF_TLV)
        {
            return __required_fields.Check();
        }
        ReturnErrorOnFailure(err);

        if (__context_tag == to_underlying(Fields::kTestOperation))
        {
            err = DataModel::Decode(reader, testOperation, DataModel::DecodeContext::kWrite);
            __required_fields.MarkPresent(to_underlying(RequiredFields::kFieldTestOperation));
        }
        else if (__context_tag == to_underlying(Fields::kDurationSeconds))
        {
            err = DataModel::Decode(reader, durationSeconds, DataModel::DecodeContext::kWrite);
        }

        ReturnErrorOnFailure(err);
    }
}
} // namespace GroupcastTesting
} // namespace Commands
} // namespace Groupcast
} // namespace Clusters
} // namespace app
} // namespace chip
