set(SDK_PATH "/Volumes/Resources/git/gsdk")
set(COPIED_SDK_PATH "gecko_sdk_4.4.1")

add_library(slc_generator OBJECT
    "${SDK_PATH}/../wiseconnect/components/board/silabs/src/rsi_board.c"
    "${SDK_PATH}/../wiseconnect/components/common/src/sl_utility.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/core/chip/src/iPMU_prog/iPMU_dotc/ipmu_apis.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/core/chip/src/iPMU_prog/iPMU_dotc/rsi_system_config_917.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/core/chip/src/rsi_deepsleep_soc.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/core/chip/src/rsi_ps_ram_func.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/core/chip/src/startup_si91x.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/core/chip/src/system_si91x.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/core/config/src/rsi_nvic_priorities_config.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/cmsis_driver/UDMA.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/cmsis_driver/USART.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/clock_update.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_crc.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_egpio.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_timers.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_udma.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_udma_wrapper.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_usart.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/service/nvm3/src/sl_si91x_common_flash_intf.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/service/nvm3/src/sl_si91x_nvm3_hal_flash.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_ipmu.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_pll.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_power_save.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_rtc.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_temp_sensor.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_time_period.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_ulpss_clk.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_wwdt.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/ahb_interface/src/rsi_hal_mcu_m4_ram.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/ahb_interface/src/rsi_hal_mcu_m4_rom.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/ahb_interface/src/sl_platform.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/ahb_interface/src/sl_platform_wireless.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/ahb_interface/src/sl_si91x_bus.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/ahb_interface/src/sl_si91x_timer.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/ahb_interface/src/sli_siwx917_soc.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/errno/src/sl_si91x_errno.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/firmware_upgrade/firmware_upgradation.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/host_mcu/si91x/siwx917_soc_ncp_host.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/icmp/sl_net_ping.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/memory/malloc_buffers.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/sl_net/src/sl_net_rsi_utility.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/sl_net/src/sl_net_si91x_integration_handler.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/sl_net/src/sl_si91x_net_credentials.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/sl_net/src/sl_si91x_net_internal_stack.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/src/sl_rsi_utility.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/src/sl_si91x_callback_framework.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/src/sl_si91x_driver.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/threading/sli_si91x_multithreaded.c"
    "${SDK_PATH}/../wiseconnect/components/protocol/wifi/si91x/sl_wifi.c"
    "${SDK_PATH}/../wiseconnect/components/protocol/wifi/src/sl_wifi_callback_framework.c"
    "${SDK_PATH}/../wiseconnect/components/service/network_manager/si91x/sl_net_si91x.c"
    "${SDK_PATH}/../wiseconnect/components/service/network_manager/src/sl_net.c"
    "${SDK_PATH}/../wiseconnect/components/service/network_manager/src/sl_net_basic_certificate_store.c"
    "${SDK_PATH}/../wiseconnect/components/service/network_manager/src/sl_net_basic_credentials.c"
    "${SDK_PATH}/../wiseconnect/components/service/network_manager/src/sl_net_basic_profiles.c"
    "${SDK_PATH}/platform/CMSIS/RTOS2/Source/os_systick.c"
    "${SDK_PATH}/platform/common/src/sl_assert.c"
    "${SDK_PATH}/platform/common/src/sl_slist.c"
    "${SDK_PATH}/platform/common/src/sl_string.c"
    "${SDK_PATH}/platform/common/src/sli_cmsis_os2_ext_task_register.c"
    "${SDK_PATH}/platform/emdrv/nvm3/src/nvm3_default_common_linker.c"
    "${SDK_PATH}/platform/emdrv/nvm3/src/nvm3_lock.c"
    "${SDK_PATH}/platform/emlib/src/em_core.c"
    "${SDK_PATH}/platform/service/device_init/src/sl_device_init_nvic.c"
    "${SDK_PATH}/platform/service/iostream/src/sl_iostream.c"
    "${SDK_PATH}/platform/service/iostream/src/sl_iostream_rtt.c"
    "${SDK_PATH}/platform/service/system/src/sl_system_init.c"
    "${SDK_PATH}/platform/service/system/src/sl_system_kernel.c"
    "${SDK_PATH}/util/third_party/freertos/cmsis/Source/cmsis_os2.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/croutine.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/event_groups.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/list.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/portable/GCC/ARM_CM4F/port.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/portable/MemMang/heap_4.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/queue.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/stream_buffer.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/tasks.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/timers.c"
    "${SDK_PATH}/util/third_party/segger/systemview/SEGGER/SEGGER_RTT.c"
    "../../../../examples/platform/silabs/provision/AttestationKeyMbed.cpp"
    "../../../../examples/platform/silabs/provision/ProvisionChannelRTT.cpp"
    "../../../../examples/platform/silabs/provision/ProvisionEncoder.cpp"
    "../../../../examples/platform/silabs/provision/ProvisionManager.cpp"
    "../../../../examples/platform/silabs/provision/ProvisionProtocol.cpp"
    "../../../../examples/platform/silabs/provision/ProvisionProtocol2.cpp"
    "../../../../examples/platform/silabs/provision/ProvisionStorage.cpp"
    "../../../../examples/platform/silabs/provision/ProvisionStorageCustom.cpp"
    "../../../../examples/platform/silabs/provision/ProvisionStorageDefault.cpp"
    "../../../../examples/platform/silabs/syscalls_stubs.cpp"
    "../../../../src/lib/support/Base64.cpp"
    "../../../../src/lib/support/BytesToHex.cpp"
    "../../../../src/lib/support/CHIPMem-Malloc.cpp"
    "../../../../src/lib/support/CHIPMem.cpp"
    "../../../../src/lib/support/CHIPPlatformMemory.cpp"
    "../../../../src/lib/support/logging/TextOnlyLogging.cpp"
    "../../../../src/platform/silabs/Logging.cpp"
    "../../../../src/platform/silabs/SilabsConfig.cpp"
    "../../../../src/platform/silabs/SiWx917/CHIPCryptoPALTinyCrypt.cpp"
    "../../../../src/setup_payload/Base38Encode.cpp"
    "../../../../third_party/mbedtls/repo/library/aes.c"
    "../../../../third_party/mbedtls/repo/library/asn1parse.c"
    "../../../../third_party/mbedtls/repo/library/asn1write.c"
    "../../../../third_party/mbedtls/repo/library/base64.c"
    "../../../../third_party/mbedtls/repo/library/bignum.c"
    "../../../../third_party/mbedtls/repo/library/ccm.c"
    "../../../../third_party/mbedtls/repo/library/cipher.c"
    "../../../../third_party/mbedtls/repo/library/cipher_wrap.c"
    "../../../../third_party/mbedtls/repo/library/constant_time.c"
    "../../../../third_party/mbedtls/repo/library/ctr_drbg.c"
    "../../../../third_party/mbedtls/repo/library/ecdh.c"
    "../../../../third_party/mbedtls/repo/library/ecdsa.c"
    "../../../../third_party/mbedtls/repo/library/ecp.c"
    "../../../../third_party/mbedtls/repo/library/ecp_curves.c"
    "../../../../third_party/mbedtls/repo/library/entropy.c"
    "../../../../third_party/mbedtls/repo/library/hkdf.c"
    "../../../../third_party/mbedtls/repo/library/hmac_drbg.c"
    "../../../../third_party/mbedtls/repo/library/md.c"
    "../../../../third_party/mbedtls/repo/library/pem.c"
    "../../../../third_party/mbedtls/repo/library/pkcs5.c"
    "../../../../third_party/mbedtls/repo/library/platform.c"
    "../../../../third_party/mbedtls/repo/library/sha256.c"
    "../../../../third_party/mbedtls/repo/library/sha512.c"
    "../../../../third_party/mbedtls/repo/library/x509.c"
    "../../../../third_party/mbedtls/repo/library/x509_create.c"
    "../../../../third_party/silabs/matter_support/matter/mbedtls/tinycrypt/src/ecc.c"
    "../../../../third_party/silabs/matter_support/matter/mbedtls/tinycrypt/src/ecc_dh.c"
    "../../../../third_party/silabs/matter_support/matter/mbedtls/tinycrypt/src/ecc_dsa.c"
    "../../../../third_party/silabs/matter_support/matter/mbedtls/tinycrypt/src/error.c"
    "../../../../third_party/silabs/matter_support/matter/mbedtls/tinycrypt/src/oid.c"
    "../../../../third_party/silabs/matter_support/matter/mbedtls/tinycrypt/src/pk.c"
    "../../../../third_party/silabs/matter_support/matter/mbedtls/tinycrypt/src/pk_wrap.c"
    "../../../../third_party/silabs/matter_support/matter/mbedtls/tinycrypt/src/pkparse.c"
    "../../../../third_party/silabs/matter_support/matter/mbedtls/tinycrypt/src/pkwrite.c"
    "../../../../third_party/silabs/matter_support/matter/mbedtls/tinycrypt/src/platform_util.c"
    "../../../../third_party/silabs/matter_support/matter/mbedtls/tinycrypt/src/x509_crt.c"
    "../../../../third_party/silabs/matter_support/matter/mbedtls/tinycrypt/src/x509write_csr.c"
    "../../../generator/app.cpp"
    "../../../generator/main.cpp"
    "../../../generator/nvm3_si917.c"
    "../autogen/sl_event_handler.c"
    "../autogen/sl_iostream_handles.c"
)

target_include_directories(slc_generator PUBLIC
   "../config"
   "../autogen"
   "../../../generator"
   "../../../../examples"
   "../../../../examples/platform/silabs"
   "../../../../src"
   "../../../../src/platform/silabs/SiWx917"
   "../../../../src/include"
   "../../../../zzz_generated/app-common"
   "../../../../third_party/nlassert/repo/include"
   "../../../../third_party/nlio/repo/include"
   "../../../../third_party/silabs/matter_support/matter/mbedtls/tinycrypt/inc"
   "../../../../third_party/mbedtls/repo/library"
   "../../../../third_party/mbedtls/repo/include"
   "../../../../src/lib/support"
   "../../../../src/platform/silabs"
   "../../../../third_party/silabs/matter_support/matter/si91x/siwx917/BRD4338A/support/inc"
    "${SDK_PATH}/../wiseconnect/components/service/bsd_socket/inc"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/cmsis_driver/CMSIS/Driver/Include"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/cmsis_driver/config"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/cmsis_driver"
    "${SDK_PATH}/../wiseconnect/components/service/network_manager/inc"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/rom_driver/inc"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/core/chip/inc"
    "${SDK_PATH}/../wiseconnect/components/board/silabs/inc"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/inc"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/core/config"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/service/nvm3/inc"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/errno/inc"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/icmp"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/firmware_upgrade"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/inc"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/sl_net/inc"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/ahb_interface/inc"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/systemlevel/inc"
    "${SDK_PATH}/../wiseconnect/components/protocol/wifi/inc"
    "${SDK_PATH}/../wiseconnect/resources/certificates"
    "${SDK_PATH}/../wiseconnect/resources/other"
    "${SDK_PATH}/../wiseconnect/components/common/inc"
    "${SDK_PATH}/platform/common/inc"
    "${SDK_PATH}/platform/CMSIS/Core/Include"
    "${SDK_PATH}/platform/CMSIS/RTOS2/Include"
    "${SDK_PATH}/platform/service/device_init/inc"
    "${SDK_PATH}/platform/emdrv/common/inc"
    "${SDK_PATH}/platform/emlib/inc"
    "${SDK_PATH}/util/third_party/freertos/cmsis/Include"
    "${SDK_PATH}/util/third_party/freertos/kernel/include"
    "${SDK_PATH}/util/third_party/freertos/kernel/portable/GCC/ARM_CM4F"
    "${SDK_PATH}/platform/service/iostream/inc"
    "${SDK_PATH}/platform/emdrv/nvm3/inc"
    "${SDK_PATH}/util/third_party/segger/systemview/SEGGER"
    "${SDK_PATH}/platform/service/system/inc"
)

target_compile_definitions(slc_generator PUBLIC
    CHIP_SYSTEM_CONFIG_USE_SOCKETS=1
    EXT_IRQ_COUNT=75
    FLASH_PAGE_SIZE=1
    MBEDTLS_CONFIG_FILE="siwx917-chip-mbedtls-config.h"
    OPTIMIZE_TINYCRYPT_ASM=1
    PROVISION_CHANNEL_ENABLED=1
    SIWX_917=1
    SRAM_SIZE=0x2fc00UL
    TINYCRYPT_PRIMITIVES=1
    SIWG917M111MGTBA=1
    SLI_SI917=1
    SLI_SI917B0=1
    SLI_SI91X_MCU_ENABLE_FLASH_BASED_EXECUTION=1
    SLI_SI91X_MCU_COMMON_FLASH_MODE=1
    SLI_SI91X_MCU_CONFIG_RADIO_BOARD_BASE_VER=1
    SLI_SI91X_MCU_CONFIG_RADIO_BOARD_VER2=1
    SL_BOARD_NAME="BRD4338A"
    SL_BOARD_REV="A02"
    SL_NET_COMPONENT_INCLUDED=1
    __STATIC_INLINE=static inline
    SRAM_BASE=0x0cUL
    SLI_SI91X_MCU_ENABLE_IPMU_APIS=1
    SL_SI91X_SI917_RAM_MEM_CONFIG=1
    SLI_SI91X_OFFLOAD_NETWORK_STACK=1
    SI917=1
    SLI_SI91X_ENABLE_OS=1
    SLI_SI91X_MCU_INTERFACE=1
    TA_DEEP_SLEEP_COMMON_FLASH=1
    SL_WIFI_COMPONENT_INCLUDED=1
    configNUM_SDK_THREAD_LOCAL_STORAGE_POINTERS=2
    SL_COMPONENT_CATALOG_PRESENT=1
    RTT_USE_ASM=0
    SEGGER_RTT_SECTION="SEGGER_RTT"
)

target_link_libraries(slc_generator PUBLIC
    "-Wl,--start-group"
    "gcc"
    "nosys"
    "stdc++"
    "c"
    "m"
   "${SDK_PATH}/platform/emdrv/nvm3/lib/libnvm3_CM4_gcc.a"
    "-Wl,--end-group"
)
target_compile_options(slc_generator PUBLIC
    $<$<COMPILE_LANGUAGE:C>:-mcpu=cortex-m4>
    $<$<COMPILE_LANGUAGE:C>:-mthumb>
    $<$<COMPILE_LANGUAGE:C>:-mfpu=fpv4-sp-d16>
    $<$<COMPILE_LANGUAGE:C>:-mfloat-abi=softfp>
    $<$<COMPILE_LANGUAGE:C>:-Wall>
    $<$<COMPILE_LANGUAGE:C>:-Wextra>
    $<$<COMPILE_LANGUAGE:C>:-Os>
    $<$<COMPILE_LANGUAGE:C>:-fdata-sections>
    $<$<COMPILE_LANGUAGE:C>:-ffunction-sections>
    $<$<COMPILE_LANGUAGE:C>:-fomit-frame-pointer>
    $<$<COMPILE_LANGUAGE:C>:-Wno-unused-parameter>
    $<$<COMPILE_LANGUAGE:C>:--specs=nano.specs>
    $<$<COMPILE_LANGUAGE:C>:-g>
    $<$<COMPILE_LANGUAGE:CXX>:-mcpu=cortex-m4>
    $<$<COMPILE_LANGUAGE:CXX>:-mthumb>
    $<$<COMPILE_LANGUAGE:CXX>:-mfpu=fpv4-sp-d16>
    $<$<COMPILE_LANGUAGE:CXX>:-mfloat-abi=softfp>
    $<$<COMPILE_LANGUAGE:CXX>:-fno-rtti>
    $<$<COMPILE_LANGUAGE:CXX>:-fno-exceptions>
    $<$<COMPILE_LANGUAGE:CXX>:-Wall>
    $<$<COMPILE_LANGUAGE:CXX>:-Wextra>
    $<$<COMPILE_LANGUAGE:CXX>:-Os>
    $<$<COMPILE_LANGUAGE:CXX>:-fdata-sections>
    $<$<COMPILE_LANGUAGE:CXX>:-ffunction-sections>
    $<$<COMPILE_LANGUAGE:CXX>:-fomit-frame-pointer>
    $<$<COMPILE_LANGUAGE:CXX>:-Wno-unused-parameter>
    $<$<COMPILE_LANGUAGE:CXX>:--specs=nano.specs>
    $<$<COMPILE_LANGUAGE:CXX>:-g>
    $<$<COMPILE_LANGUAGE:ASM>:-mcpu=cortex-m4>
    $<$<COMPILE_LANGUAGE:ASM>:-mthumb>
    $<$<COMPILE_LANGUAGE:ASM>:-mfpu=fpv4-sp-d16>
    $<$<COMPILE_LANGUAGE:ASM>:-mfloat-abi=softfp>
    $<$<COMPILE_LANGUAGE:ASM>:-x assembler-with-cpp>
)
set_property(TARGET slc_generator PROPERTY C_STANDARD 99)
set_property(TARGET slc_generator PROPERTY CXX_STANDARD 17)
set_property(TARGET slc_generator PROPERTY CXX_EXTENSIONS OFF)

target_link_options(slc_generator INTERFACE
    -mcpu=cortex-m4
    -mthumb
    -mfpu=fpv4-sp-d16
    -mfloat-abi=softfp
    -T${CMAKE_CURRENT_LIST_DIR}/../autogen/linkerfile_SoC.ld
    --specs=nano.specs
    -Xlinker -Map=$<TARGET_FILE_DIR:generator>/generator.map
    -u _printf_float
    -Wl,--gc-sections
    -Wl,--no-warn-rwx-segments
)

# BEGIN_SIMPLICITY_STUDIO_METADATA=eJztfQlz3DiW5l+pUExszOykkpIsH/JWdYeckl2atiytMl3dtaMJBpNEZnLEq3joqI7+74uTyQMkARIgVR3TM2U7SeJ933u4Hq6Hvx/c3t38x+ViZd7d3KwOPh78/f7g7vLr+erql0uz+Or+4OP9wXx+f/CPg1meZnnz/W5xuYTJfvzzs+/98AjixA2Dn+4PjudH9wc/gMAOHTfYwgffV58PP9wf/PlP98GPURz+N7DTH2CSIPnohw7w4Be7NI0+GsbT09M8cT1rnczt0DeSxFimmeOGc2CHMYBCYeoIxOnL0oZ/w3RU2v0BFP3DDz9uQs8B8Q+B5aOXdhhs3C19h966HmDvlpdfvlzemXerlbmAn813UHgWu/AN+uqj8UvoZT5IjDuQhFlsw39t3dTwrTQFsREDD1gJMCD6o4uUNpIsisI4NRL37Pi9QYANDobB45J4ZgBS0wEbK/NS89HyMpBoYdSIxOX1OQbgbnWzXODEWgjVIbhM7laX5gV4dG1gwsRamNQhmvJqHVqxY5JkWWylUKSuzGqA6mSWxqGnnRMD4bKJ3IDy1sKjLJ7LAPieuzZRuwHL+zrb6qTTgkW4/WiQponXTFlZGm5BwG+nPDd4ADF6Yi7DxdxzVLKnyAYHpLEaLkI/CgMQpIpbKMaljtFU2m32lWlbqeWFirOWEWpCaqIFHtGHOytwPBBro1RDEaNjj0LHbqbjhkkaA8un32oqRA1AwqR0mYkH1EnKDdwU/pGkVmCPYbA6Hpfi3I5t1s7Bf+pgVYPobkyf3AT6ikEAncI3ZuI8mG/mx/M3hba14iGyhib/ovaNg52CwvvaF8RjLX3B+ebs+LnySe0j385qn3A4x4DzVf27nRtxv6tzQ6blflj71L29/m7CbNs2JuAnccK0GYMkKhQtOJAwk5ckBT7NfeySiRWxQgEw9tlrkFw0SFbhYvZsQHMbyJoGMpUBrWDk6hk5a6ORjCGqjhv5mWlFrmi7olyFEoFm2qV6Jf+61H4Rg2GSY2hdxWtSskwyteI0i0ZkWQUUookKYJSYMWyaN1lgj0GUAylM1QEgSjz4h5mEo5GtgfLpthbharsVtLWKFaVBHIeizl5vZSEjowQmlCdr2NOa6Usk7DoM4ldGEyLoQJ96PIJlNCGCd8vjZ/i/MdgVoIQrnG1HaITiC09DDC6AZURxolDGaBQpVq8WdiSOFUhhqiVvZCyyNVAhujAFgRiDZglMlN54NacEJkrPShIQpyPR24PJVJtxy2EJUMzNK/qGI7Cs4omRRF+PWFeqeBIk/cdRWvESmLQ71/aqdZWo9dv2kXKlagRQSzgSc8PYTV2QF1uNHjGdo6c+cTN+L+eY43VksLkYofoTtRpAG3QRzIxRWDdj88g3ZkPzi8qEVeyitVihOSI/cROTJBCrAYvr5dVSdLbook0w5/urwPYyhz+7xc1ZAoDWC7T14dSaRtFUBraCQdANytqokRGeIGIpz7+9Fh0IE1kFLlc/vxIFKJMeCpjX54vXowRj00eR259/fUWKUDayinz2rGT3StTIucgqcXXyWooUZSKrwPXi6pUoQJnIKvDt/NvFK9GAUZFVYXn+WvKAMpFW4PbVKHDbS4Hvy/O71StRIecir8SnV6PCp54KvJaqzKj0UOG1OEqMip5VQZn1ltZxuIqNSCpMWdgsyN+k1ElbehujYtr8PY5S2fYKBmCCY60S18txPfvLVte9xOzLuF3jl9b+r8RsXM+11Tst8RrXIW11Oku84CjH/Hr+7cP705PzEQlWYQWYjutOtrqMZV6jVgXxmvD94nrMHGVwIsxGdks7XM8KtzG9zVaPsp6bWmbim3OzeeK9npsjUmN4UnPRNe8tDn2peWSp3TVIuO09aHb09irki41FYOElUZQIbCM3nIRujiy+hGvZD26gaS2khW0BV8q2dqxph0ZXQYjltmngNJqW7ruoyi3i43KzyRJNK89dJZYhS/HduP4kbCmuFNdt5PjWJGxzZCm+UfgEB1eJ9ThNgSjDyzF/mqZUUFwprr8lkTsJWQYsxTaeoIco4EpxTa21B0yt2zY7WNcY9OCvccOSEHu5DUx5WtcXPvammDVDluKbTdU0Z31aZpTIfIqtKJrIyFUCcuy9KEmQQz0N9SK6xg1l0DJutAOx5VEW/K04/TeX2V5oP5hZ5Fgp0DtSrKuCd5dVCYjvAI81nQjpIFzAFuZKBlJTsc3Rhfni5k/TETMBwnt4Yca4BZyKLwOXYpu3fFOyLpIQZ59YcTodbYY+4rGsUiOltb/hKI76nSoBqVZyCsIFbMlWciq2cpNdVvZsxmADYhDYwHwMvVTrNuAO/q1shO1vOdOVFYotcVBN83i3rVzbckNehGrFVqrrVKcI5RIFceaapxzbGMtNO9q6t260UpWb1Hes6eoZxRZvk/VP5ba1ydLTuSDYoVAjjv453TbaFRLC7KckLct1hInoFrbyk9Fb7VOkbXRlp0ndk+naCIotwXW6tpdii3Odrg925freMLJ8TYcjBcjm6OJLv7qXS1rYyi6Z/AamawootjjXKdst6eUdlACFDEqnG8iVKYhPKutelGqhLL0wNWnfG0v3vYnjhppPXrXwzdEl+PpgutYsRxfnO+G8SSK5RSjx3QmLAgUXZzth4yvb9iaTkpVm+5LE6XRO7h5ekrG5A5aDliemZV6kIbuuMxXzPbzcus5UfKWX1cdbUu9g3WtZnaysTEaboQvzfbScydhSbGGuT1msef9NC1kGLhaYx9MaKKqDbgldlC8N73NqRtO0bXUKGreEQOM8VoMIN34cPPpvRCOstO0ZabI5CUJmblA0A9MN0o3eZWGqu4HUIlFQW4m0HETlaoPEmjuYuVjMVKrUWTTWg64ousKr3RWLYArsZo8x1jVL1kBVqoGBbI7Wi8W4arQT6ZWvahoRHFfOA4/A03DGZh1q7pgL9PNOjoKKr8IlY+wv5TEtIotPXEd+Nj5Vhio+C+yJXhajkCUFFSc5hSmlLTnSwQku136nJqI4hGSSECYFQaJ7uwOXOIeB+Kwq2Oqf7+GxLgBLkE0hnvh9UUrpFqDFCeue7OFSlZzigQKiyQpvBVxqVsdEQ5Mput0KuPhkwzj793mUBTbv80bwT47mITGPK0MdvtlVKt4s7vf1jn8KyrKtvQxVytsYnSUF7dORj8+1hC3VVo/OlYL2aqtHJ1sB79VWj0+6DN6jrR6dcglarq0enStDVTf51/Ci6XH1+jJ0N1rCOzFWvSsM+GH80hDkuWBa3/K80DbX2Waj5XgQY2wQQkYdr25a0UjWII6DUCSOdXM/yZ9iwoI12gLLL88Q5pDD4qw0z+mUNCVoyj2fioL42giGpCWWObmwWEcRQPcgu0EK4sCCj1LL1tBQ5uYialSmjLkEBCIE0UuccUubup6bvozGnIMrTpiojVTekquMJW8lVUO/lYWYMvv8s2PgoGG15elsWZtKTwV9lIaFUwj0tTJUcTopz8FVUfjGpN/KQlKZ8Ylra+Vd2+dfVcpTPkIxo/RVNsTFqEBxlW6ipi9batS4+SFq9I0b+09WDMwsgoWx4daNkpaVFOQ6en05USVYfZDjd2YPN6G+fBIjPijzmrwdfldFBkA6e6hi17RHE6k3I7kxhKCA79KwJg1HNWvoopmbGL55CmOt3mJpkwQXuX/JSXcxsBzYeoiUH5ftkcm81CUpgYY5kFzznJzRgt1f912YpKbPvWS7XsMQuJBH5D49nx2/RxfPmoEdmQhEo4mYDvR5E7qWftrarcmQZWM1bGbqNyhD1RJtnoFqoe1YsKBrNGBJiXweqA4v5o5FnpVuwnhcwhVcOaYmEzwV5RIBmRHXOhudcwlYiCtqtvIqOTLdGrYA42rhD6ete6FEiSaZQ7blTFIucuhRht40JoSWixYatC2EohC/Z4GELNB3p3cHV5ELvut8ic86OtccVpCnfzo6RwIpyC8cP79DmXyOHqDztPU1bAroYFkEFuSKLjodnScDFeSIgFHTvbNiB49wE5BmGk7Ad7BupiGqh2cFbL+vrr3TXTpwKcjwd8DGDSZocavgPfykMSlzsCUZa9qDLMi5Yx9y1UsiSCOz7bhZfPiMcYPL1Da7pHFiNqjNLjUp3nDiIUhSK9ARDqvKkQMowxPNYWINXa3tTIVsFVWcsXa/rsS03Z3jM8TzOXn1GYtpHVWcsRumqN18ADq9qBLbMqI4UxxQxA497SOREts6qjhjFAZl9NagBirBN7XSbDyiOZo4w1GzXirHn9yNq793pvwqYMJz6NzHnIe1R/UH3UdiqwdhQYrWO0zfCqxt7WIpgalm3hrt2kpcW93Gjfz0YJlrcccJF7GaAc1UYXOC3o3FswgnTtIGcQpLmG2lcOyVwg57LKvycAVo66ZXp8GvSCJrTs07QPQoQdaVKjjyyvBcdJ4qirq7JnUKm1ha+zgeNSfQT4piiNBxIxW9mQCnIpAIsXFYSVHC/d04vMpQIo2PZkZ1GiIddq0CrxOHet3tPW9nRYeUnLUapfecSMQBJrnV6vArl+y21UWiIF6EyTv47TudXHKA9tIIPcSh0cIbeOxFtzNQMIxsYtA4XiwzeFHUQFThX7pbg2xoBMAG7IwX3U+Fz74Ordhp89jJEGSgo04CQ0CkYf4NFpEPimIWcILK1eDP7OUPytQS732gDCq3tUDlX9IFhCxWsNWxmU8dpavzQ9d1aLFRTXYXE/fE1kWkJLqLR/Tk6+JREt3FI9GXMYlMvtBAibqoVKSrbyLZ5F9bK4kcxuGTGdjtVL0vldE3kHQ2nm1B0jXGRZBKNWGDWiZYz3i2yVKDCnJZk+J8Hh+pq4qRpGpG3S3cZAbbOIXKlZBmXt0rH1xyCoaSzZyEB4+49Oohoac5JPsZWl3GWlNXVVrJ6QBChLVoDWcAusfE9UagFofTcVzkDpFDnYMXRyhvFmaTJ9xo5WP7iZuoWQMvc6kJ7uChpsGpcGhuZGoOHwDgw9GJiopc5lAT3MFDySRehULjfF1TXVII3lACupqK6s9yPYsZj0JtqzYt+6n/pNLAFHS2nlAkChfyLq4VzCPgz+1e4XJzZkaRgNGNYwhQjGL3ES1lPIAXnBT9rYNiA04rRVjR4o0LPDjss3AipcR40pvp/J7FwFxbXur6aHOIckKN8hsp2RaSoJZGWWYzNM5TDfA1uR0UWGlSzKAgtpEAmgkDsXob1OV2UFBug5rYRgLIi8Pbd5XiV6U2649H2sVGULEhGuULUlKfNU3iGwn5Lw54fHDTahehjFILQCcp5fbhCO7KKmeLJChv0JukG8IDmTDdVXaglOi7gQOe57vU7xNJd08aoxhlYY0cSz/LP8rct8B+CM3EeTBP56fz41yL6tQVPZ/X4nJ1juYExkdp6LuiG763kLTBeFXHQrmgdpd37Yq6eW1oVIrIWCtMTuTOabXh8kS2knALScBzaqZW8oCC1bpJKrwRtoVQp/h2C4EgE63WbVZhYtrBpK7EaC1qDbdb1Me4qnJdLK+h1xyLhxxpA9wL6gD0YEarwGNyuvSTmEFp1483W9I939M5O9VeH8SmrLjE2YneDvFCNWAwjYIgoQI5HHAvSKRAKsBjcmTmMGrFZXG9vFq29Y8LOJxsX/q5Cmwv40TjKY+3cKFAUzKueAirsvqYqoH4GBTSqEttnY8mn6PImuJrzIIcCkJbKaS/oynAFNYMVfhliQL6b+1+zkyj7lRgOzSelRA+DNyNXJDXCuxHmWnF/uN7VcglgQo2rd2tbpYnymoYbHYHKIq5VHKXSmw1cojuGrFFVw27kQvy5Jc9lxiq3VgQAMXWdYVjaDZzJnBGWaL6dSmB0wfksITpBm7H/keRxfqCMDOA/+xlJ7bdqyCMdV88+XqWuGtIfUopT5PSwdGyfAXtghtCjwJY/vCsZJIGZSETwvKvKLRz6xL91ozTfp5PFwkmWE8BylUdUnBy6mwFrCBUyn46SDDBCootCVk+vNASObhWDSoyRE7uNJelCuztQp8/gDgAondASNDYy9VTcIvaDik2lPx+S1pRqpwNldPYy1Xf5wLfiR/belzO9KJ8RgE7dEQ3D5UNg/kV5w1yUQoqMudST+ljFIXrFQcoyL2usfvkAvxYFagQmLkFAYh7+hc8TQvyusF3Vr/KxQOmsoRA6f2hCqH3ErsJeGHPUQcPmwnrsUW0q0OrXDSKQ+Z4bvDQc8atwB71KO3SBa2oigcTJm9Fz123WxF+gCEW16d40sEaRhmKMzgidfQjVdXkJm1hN2eLn1Cu6ovURLlTkKJ0CyGT268aIna469pLaZk/pV8NbGormE0N7bANYWiXWfPCZLpzY8eMrDh9aSsYmxiAOA07DijhiRpO1RGZFmmcRZIobEhVo6CRwWiTKSQ2RVKSXWuVhG4bapoJq2jB8GWnw7oUYfNTVfmc4BRcOn4UhlLdtDShHEHIviKtMnGwu0pXFMaptfb4OVP68stiIRKI+fzuGjXKn0XijCJwNeWVKGswbQxI1mBMDAYjEMUMfepbdix6XHIorRxLS+yya+BfWyLx13fAisxTPVlBSRh7jGEhYXjdnEjbIr8dpFNHimw0bRCpcYCZnaFj01pYFIV38HBAFAO0Yckh0RTxVn+p1W9hVs1QHRzBI9rrtoVKRXqYVQE6+HyGYtDKgRYuReEdPGT3RQhz4G+UqOFDmMTaAnrvnhYmdYguTlFGgqHJHHiQ5FSDEOD0FFtRhC4n1MWoCNDBhzXIWrgUhXfxiMP/hi2BHpsUhXfw+C0DmR5j5JI7GCTAj3Z6atBedBcHdB2gid0QPTlSBejgs0SfX+ujU5HfaR28yqKxqashdDBC27K0EGGCu/BRSGA9WbMXLTzG5LlWKp3YotDW6biSL6GSQVVwKwvZHWqd6Lytag0NqUrYXGL7GlWp6qjEr0lu3xoGa47aTM8ltuOS+qIUOBepYkUZbLtjaeLFwEcXPHVOg11++XJ51zXII1+Zd6vVILsQ6saenUEEG2X5XX0Z/nhQW9lBRKRD3TPWSITJ7zt7JTVlWzmBUhzjR9HcjiIhPX0rTaFGKHitlWDP8dFFW0ENPKsMh/SxkYsz6lC+5QYqsfbyOGB4qQNFFnkvWKwFAMsyOaCWcCTYClqx3Phr4KReAt9FIVq0ia34xbCKQV/LmElwDBMmov2JNHJRfgP+U+ymOvFz+Rz8NZTyTnQiThZ8L5yH7G7RURdNyLlwDrJt64KlknmYbrQTdhqkYXPhjch44K4VPkfgcaDBLPAFH7pYVDF4PNLYdOK16CkOaQoF8Rx0YDs7TchMNB81sfTBEtlcXF3ljUrmY5p2Fj9q60jKADwGQRqHkWhEH2n4vXQO9u7B2WgCZqJ5qL5l66xUJfk8v0g0mKYssO80IOLIJ1ogqWQe5oOdvNWFymTzcOUugZWGrt31Wh5x76yTt+80Ye+F85HfHovubeiBTIVzkJ/fHp1pwmWiG1DRRQ6WNk+0gsBtvUUPj7Rg06iY5AszySK0UsASMGKpG7zY8UtEDplQXD4jU0Wf3Y+U2dKnw5cqevW+xJp7/TgOFbi5fXgxZA6r0FXQSfTgRHG57fkkhKKHRj6KRgi9SLWNHaIHRePzXszaxu7Rg6KRey9mbaP6/D5yNK02Db8qg+Y+R3QFQS3BIngDN2xh006mac9qDDgsFz9f3S5QivD2/OsKJsc/+s4SFvONMV66f0U3cxptSA3ErpEz258J3o1MDVUS1wB3S5nD78L4RSUyT3KzzofXluehO+qVql6SyptHjESvJhacht5xYc5hWhRwBH7/F+EAjhVE8Gz5kQffVcvankodppPLNaxEfW0uzWgPxuF1yxItdlYgfpRNnhMPSIAPXkvSZqhGtDZmlwE6jya64WEAqQKQCJ8RzFSCauN0TS5D0m+jApAInxFsVIJq43RLQ4DrN1IRSYjRCGYqY4mwOhmT1kk3ryXsfWBO68++ApAAny9Sh4iG0/pSPWbUbq0R8rAEJcBpkSVp2Nv968GsCCjA74KeDR6PYAmRN+H4kqA7L1C46GydKCfGE89h8Yms2PYq6FXPdS+rGUiRk1yUxgN7gc7bKvwZhR5VAleS1w6oSsOKxIbxx9dwuxUPm9iB6RFhRkUwB3oFntObwHthXylSmhHgiufQWOKyvsBXd/U3QX0IXJbaBax09F2VywFXYPQqbpehUX1784G4rv0NnYA0i8zIevFCyzGqMrtgB6jbAiwxw6CkjvHl8vsHFMWE7J/qBS08H0VvlHKf8MzPp7uL0zdvPpznlOkdkCU2lHDp1jzGnPZ8kDLEBF7pCb6ubBH6EUyxxpdtwNfr2EGI1sejOfq/86OTH9Cjo6OT/aM3MDFSpZrWt7O5Ffvzp40/hxpsIT//+PjY36ZrFAQgDUPP3lluUE0H3yXOQ/WpHSIpyFRz+HaOjxbMoR1A/BHHm56bZ2/eH529e3t2tA897cNy5H10QGLHboQM8acfjfozsq+wZDD47Ed8oATYKfz3wexgeXV9+/VqcbX61Vyuvl9c3ZjXNxffv14uDz4e/Off0V0ifvgInPuDjxvLS8AM2i5zvdQNLp/xFvcEvvnP/9o/Juer8VO8KQdi5yfB9g3cLH93t7o0L0jUMprR+3f7fZgmSlp+iY/OkzPzDlhnW3qfYvmjyA24z1FMav4ljPxv0piMw0pv8QXUNNLFo+Vl5AgVsgXMiwydP/54f/AjtfbH62v88Idn3wuSj/TpT/f39we7NI0+GsbT0xMrCbBQGEmCHDz00RwgLdGXP1Aj42RpnJGHroN/Z/ac4M5x4zPPbGrvfNZtvrVtnCJy/JKIP93jsoJPLSCHMoEFH9VTAjT/3+hPA32UFx6mzp+wTSgtqDCS+I/Z0HJjZWkIWePCscivzqEZwF6SqCKodTKX4WLuOaW3JA40SWnaVmrBnr4iAIXCxkcRdlbgeGR3W9vrWuo8ZBn5IqkLqH3RLAPH7HPxBjP71ZWkFfBRBw7+gGWpPtE7a57YnfE8gOrDXf6IDQhmxWHNrO6cz6oDhFn7wsqs5mrP+JP/s8o6yKx5oYL/ioguOWMz/vwy53E+8TprmtjkvajIKs288V5Uvi9PQXHfNKQ4qScpTTrwXuy4j4tTAZzXpYE4531h8mXG8+yrD8l33CHKLN/TPiscFZjlqzWzyv7zWWU/+Ky4P3tW3DI9y3cxz4p7i2e17b4zzubbWXkj7CzfeTMr7niZlbaZzPbbV2eFPaWzfJ/nrLr7clbaDDkrbA2Z1e7tkIzd3UsADT7dK20haLds+kL4acmkpfjRkmnLsb67E7fEc5ZNXAjJLJqUhv0pR0ZuS9x0h4VEmjyChngaelGKeALeDScSqXukYbeHiKfIr6uQSJLfOCGTJt53lmJpOu9jEZBUu+NBPE1+bYJEkvxmB+E0nbdgtElqDuvZnaoWtlIySTG8pmzSbamLlUpKI072SLaPFimbmIV7FEzXEC1QMHV3mEZZQSzOYns6Tng9qQTimcoJM9iWQDKguqyolijzIqLaonUPSc8CbUvJ4ERcH5KeBUsXkdEa+bm3gH3MZgkR/AjevQXsY29zRPQPu6dCWLOH1ifQopQYTryKPumr0Sb6yOCFtBoipxKxZYioVi+zV5y1IXKaI6MNkVqNajZEVosvOiCW1yBptShcQ6UVI2gNkVWMgDVITiGC1RA5eRCqIUL2YaQGSamEgBomqxIvaYgwFvNokIw8alEfKS2DmoHBTtVKzOOUDhJbDwXaR1weHahP4lponz5C8vg8vRLnMXZEUgsEgFEghgW0USWKsGKnlGeVU8mzYvSUGTsyPKuGOZnlB8Vm+SHfGTuqNSudkZoVTuTOSmeUZqVzQbPyCdoZ52jOrHjMdVY8eTrj7wqb1TcDzNAV6fmty2+wNd/Mj+dvjHyZLTHweilb+Ud+dpy4ZBFVgQjuWm0PgdDv3kZuOJQXGsWc2AqkRE++AimJEo1grsfpIKXQyGaf67agiMrMqeNgx9GqTATKyiFjD1QL3PSlrwy6tNGXgwsA+HB0YhadO2kZ0aDkPQ1Ax6gstWhWkmmOvDjgjT6+neFlCsPeuRGmdbc8fob/E+YkJhUtZUmaSkywY6WWFsGwiS2tLSiUW5rcVyiXfKhYLmoybLS4p4M0Fg5/aBBLVhzVy42S8r4lxbJj6C9ussDWIJ06DlrY4+d6CiAR7T+qLiQFP0pla4caZ/f2+juaOdiSfzlhCp9FfmZakZsobK+bsGq5be69XFW4CMMBIEo8+IeZhLYG+cX6oFY69BxitA+Y5L5i2cWCpUY02dnImuIMdktqq/FePlr/gMXJDeEoxgWK2zq6QZPmbgPUUIs5sYu2bND5bfKL7ji4ID/YXDr5aS7Ovw3WTx5UTXcqjXu5+nkSUPP6fDEN8O3Pv44P/Lmw3jwi7NXJBEa+XlyND/rt/NvF+KjL8wlUXd5OAPp9eX63mgL20ySgE5QliKqpKR6hi7nU1px/0VbctTWO2hpA2HWZX8+/fXh/enKuB0Fbg6YtF79fXJ/r8RGxZD2ccWOqh7S+dlpbW1w4YFY7Q6QPqnaWbThUBGK8497yTPYIzSxY2bMZgw2IQQABH0O8kU/JMKoD2Ebb/cwsctCBIM1YaARnOcPnqQRgbNsdBQYdACVHqMZAi8ex3fD5ayEUdfW3BcaxRrEZ2GTJKPUHoOXOUYCCHTq86Jgb1x8DbySYbeT41ihASTRKE+SejFLA3ZNRqqs7SkMaRpY/fG1AACh6GqVQ/wZGKWq/jVSkEQ7ZRTkGWhxod7IwzFgNT+K4obp5xFYgH4xSvJNxerzEd8ex2zi1KBkLB28zGg/J3AHL2W9p1YpY2jyrFSkbqXVAOGxP+Sh4iaVgP4wA0KMlvsltAMxTFg9f+u/AqZ5R1glEt0qcmpHWYo4WcEtTDapmthqw2HB5BBgyIhsBqLQxWysSboxGwskbozHwcGOkCigOfTZnmPv7lv3gKvQnORDoke09qKutTRgKJ5uaINQ1cA0IaqdlmkCUTsk0gKicHmmAUDs10gAShU8ogqD1qD1bVI69GyCUDogbMFQOTxsg8OEnU9UubiEwNVsou6BQh6kbRKnj3oKh3GlvwvKiJEE9jDIgdlyeGw9E9TJXDSz3ccludBLWw3SDdKMHk0UDaMBU5Xw0Y1YCmCgDxFtUPfBIzpbSc0Hqxlw8+U6iuA7zQNAua60Akefpla+bv/oumwsThzZIkhBCgSBRuKLKA4vBVuk8HB8jhWlljjf2QlE498aTDx9EY+QIqugmGrtpblM09G8clKcnR93gpgjAhrK41dLRtucHKTxPr/x9q6ITBlUPnfKL1UMrTqF66MTZVw+dKLh6DAF4clGY+iQxrN0aOVYg3ljwm8K+nKH7WDsQFB0i7ULBNtSJkIca1SI91Gqd6CE1/a0/rKHtwEAHp3TKR0JhbYEOe+w8WTEcGeMo3ToRPStgAxMFgy8RNBw+Sl9NyePx6QNAi9D4fgt8bHEEmOHjngYg1gSjESIqeP4pOjCpozHmIYXakFDwjXLoFJ0QJvtMIxYZzq8z/RiksGlDKVceJTAgjoOQBDFA/1JTUYjQkmWIdCWUN27s4xY+i7axheIylh+QSDgjQimx2S5MUlS76fNCRpuBHZnotRqdXNuP2EUt0T5ssmqpSoxCOyXsP0jGaxGRy+YWZYPZyMhGZQVTd1X12yUAlY5tSTAuj3kDpAHADVNUuh+AIrezJDyit1uoHFmUANDOSp0FRzLEk7hg9QZ5cjeuUr/Rx7ewGD6+0oVG8FPUd5MWijFHjZXytqUOMXyNrks4rqhbEgOucjOTGkDal1cNpjJPChDNOmkApIs9ENaOgYMmmi1PbWmrAeFmlQZys4dNEO2x4lpXqVIu7c5glVyjGK8bONQBT2GslnypS1MiON3FwHLQXabEe8Z79DIvdckLID4HyHoUAzV3xaZPuJ41SuCZVYFQ6d6pWVZPZ6BZoFwvVJZDHWRq/X75Rwtck/VFhbLF43XiUF+GrMuD1FkLa9csxIX/vYN2f6dIFhQ1VFIC65XEdrMmKXJ+X5OUF/Ei1CAik9hwlu8UACkqJKZPrmIrdMYKRfWovgJCnUCpOOkQnAIylQvs0d40Sc1bnr1XJ9tS1ETmXo9CUebaSlzbtEGcQuXRzQPQ09hf+aISoofLJCwcNtnoItMOyXF+93JB38SwntDqmwvQRaf753McXrrrQEC3yAj6KMisD+AFi3wAHaOHFpEoHt7GBZ4DeyIsrJeg37MYQLtB18bHV9/1F2Vb6Gf/5NhCCkQw2/aR4L9At/DBTatZP0TWED6ozIN4kFGIiEEksItcrBWKRCkg5WzR0yHFFrXzeJFRQkCY7nBn4aALaFOfbS97fnt0Rhsd9E/Uyu2P2tAnaeEnDjtv2gketLyaC4rzJneJf/7RLil+NXZc4CVeKuMWjoQ+wcTO/9izrz3/x5KqLEm3fsP6DVNskz+cIfd3vkOfzM6D0MavqRXNbJZ+dOv+18HsYHl1ffv1anG1+tVcrr5fXN2YtxfXy4OPBz/+GZrg/v4HtDUMQv10f3A8P7o/gE8AulIclgf46Pvq8+GH+4M/Q0wISjHhJ4Hlg594ui5IFpRVRUJh2gj2ti9LG/4NkzJZB1g0/AD+/4+b0HNAvJdPMrT0DfsS+vX77/YXypiIAOqF4UtKAsB8IRZGD/F1nOgJLmzEnK2y2ciXnpJ4tLyMjASVIbD77xb5HiBlouux01TapeECGS0QaRx6SoVHbnHXlTKx+JpUsmzrgHW2HYjxo0HqRPGRS2KR3lrpDv7MYheZKs0cN/zImgWD1RwiK28u8K8f9FT9FfDRphygqvLTpr279pMbdtEzcxku5p6DMfM2em/ouvWFKtAin3qguahGNLkpnEiG45bU8sKtagByx2NhQU+fcFut8PwuWyJfuelr8nXxxzcTu3gu1u6vRt92IK9EozUEraPG3o0BfyTObRtqPgSrvZyvG9KQJcHG7xtSEa+xI1Vj2rPjZ6GkDQJ8O5NI3miruEtrcVk7N+opq8lGyK8fILBBbH4JiwLhbRDodhdlEAyo1Ow0Xh1zz5oH9P1H45fQy3yQGHf5PNbWTY1CFRM5VTLgJpt6+6nQCKW7eqZRvERBlbKcHmBqQZVOr3J1jn7bVxGHm7qqUvWmoRF0qkIqV4pzOZN+tTigWhSr3Wo1jmo12CHKKaig9R4oUNN31gyeX9Wn19B5MGQGp7z0lG+51K9NGU+5OuVjkfrVKeMpV6cQE0e/LgUwLY1U+UrOcSpOGVOPWvQy0JEUomja+8fRNKqAalGsdo/oOKrVYJUrV7pCV79SJTgdyozZPpTgdCizD6I6ijJ7OF2Nw9j1pwSpfphTuU1Xv05VRPUqkZMAI7YIVURNKtG7lMfSh8JNNpwZllh4PXmATFWzkrVmpvmKXX2ZL3rJ7+TDW65PXblbWbeZGmAH2Ua4GIykXzN6PzV7Zn7fZLWFHRIKSdkaR+G6OrWtCr58VMdqx8Vwsq3yr8iipN6FDqJE4ZLUew1VgYXN6nEtuNYFDoZGbj5/HZoTLmOoTe9AfxVqUy4jqc1uYX8tqjM+Y6lP74J/NepTPmOon99I/yqUz9mMoTq9+PlVKE65jKE2vZb6VahNuYyh9rfzbxevRm9GZgzF6V3er0JvymUUtW9fkdq3o6mdX/z9KhTP2Yyj+qdXpPinEdV+PQ0bIzOS4q/HYWdk/hn3ZOnYNaJgvpRbNri76scpHnRuq85A/ZYF3tmb0ZUsM3hd87bTTeMonbGpaHU59jj9UsFAvKLDl7Edsy8KvK+KDmOPHBWMDisajD0IVDDQq2hw+/Ov5tfzbx/en56cj6pKFVihTmMP1RQMx6oajFy51dft7xfX45YnBqhSh9EHgUoGejUtxh3PKRiz8cqSplX15rI0dBGdV5ZGVYIhjroOzJSvjFP2NyiqXYXVtmu+eHewzizruLZYy/a40k28EyiXY+vZ/Le/WHpk3QrI2vKN3jU9RZGM9W163l9xPYVi+jaili7WnqKmMWxt2tHLtifQjSJr0yy/43sC3XJsbdqVbyqdQMUyAX16Pk1VPimyNs3YjeoTqMagtekWT9J/F5C1aVa7QH4CHWscNGur9diCkK76jjHkOOwSuil0ZNjatMum6woz3T0hAjCfYiuKJsvAKgV9uhZvdJ5C0SL+P8mRFXTTcLQDseVRjftuXm+Qr+X4iu2F9oOZRQ6NeqyzLNQNhM+vVCnoOfEca4sx0aFeAV2LZmQSZTrdcnwt2uEuTVuAIAH19gS06Id7tem0Y/DadMt7s2l1LNLQo2tikTjxUynJ8CffNzLGxHypy9DswXCMjjyZKgVtvdY06hXQNfZa0+mmb+nByp7NGGxADAIbmI+hl2o+CNqhbSsfLXlrOVOWWoquKRyQ9pm2tvpo65tsQwwtEv11QgVLJPToqX1xqU0/fQtMtv7Nua2K6VukdqwpWxOKrqcPHGNBsK0P1LooCIIdiqPtjLEy2KZkhYYWXadVUadmoyx+tuimdwF0O8LSWZtyOpfP3JMp202KrkmzKfs6iq5Hsym9L1ef1xVGlq8tGJaAajm+no1m+rcWtOimc3vBb2DK5pGi69Fs2pZf68YJJNzEl6BPrOGehJ6FTP2bQ1oU1LpBZGKvK9bqdSWOG2qPkdKiXY6vSTsfTNkf5Ph6tJt01jbRuF088d1JCyWF16PbpJ2dzr4umVg1rbq9JHE65SBuT0CjfuYOWA5aYp9azyIRnXsZptNzT0DfXobptNO6QXDMzYEdOmrfIEj2EkyoJMPXot2j5UyoG0XXotlTFmvfXd2iGoNXH07d03wtQYdyJXwd2tEA7qdmNFXvUCfxT7IpF2bbY/cFoZJCg0efd6HpcLJKdvi2lzJyfYi5QZFBTTdIN7o3rdEcMJDRyL15rVSUBfxq0B/RMHew+GPY6ZSv81DQsqi7L1LLLj5uzmBDOGBjZaPtlCrlCmr+GjjoLov1CjC24u1UXkWJfE2dCb4LxwOPwPuDRK9Yh9qd3YJRcleQwurZD5SMc8aOp1cRW88CcORnUyjGcPWsj3reFDpRWD0qTZNNWnNptEAAXM30RwGI4hAST0IIA4JE/0ZXrpocDnpWEMF2jFl/no4FaE2qpZCbqz8OKV+5Arge9fRP+XMV0zjRD8GiCStdBV7b3L6JJlemcbgq8Hqmhcc6M85TUNmB8Ub1np4c7ROMPM0Y7ms7uKfttkTsa+qedykYmh2RZLjafNwJdKKwuh3CKTQroWvraSfQjMJq72knUK0Cr72nnULFMrzmnnYCBUvg+nraCTRjuH/Upa2yIQuBdHUashDAR95y0grLJ6i6LU9uDDw4xJb2XWqSfOCH8UvvC2hLueVbnhfa5jrbbDSFM2F6G4S2UUfUnnkNdgRxHISq7vEd6pU2LcVgklrzBSOU1wBz0NcQmXvoGkTFskQ3DeOpikHRMCrH+kPedA2LQwDS115BIEW0LgjiwIKPUsvW4pzkmUuMUlky51JQGJufgJrYC0pdz01fRtSRg6xeNWJIZMRtbKFpTHNnBY6nJz5Ti6KtPNSqvS87dgwcNHlreXp74KayW8H/J2z0OcVYZw9ADU03MnCQx6xA4yraykOT2lOo+Ift1V3bj9SMHag5InSjhM5mCzE2KmA9Td+sgM4iVFOgR9lRlf0bN/afrBiYWQQrqNN3A2rFkhWpuOJrLRNVNaoPcgZKCgpXuM4SI6behMWovzff5AiRuRy9/k/R8dnjqWpLRnPPiRpKfPLGHaCW563hQMbcxPDNUxhrHlWVtl9zsacq6ekuBpYDW21V5d1lJxoyL3WJdKBlxSC3bq6C0YI+lX13YZKavp0pm2dA6ikdO7hPz2fH780ktM3AjkxEWGt2MYvQ5034f0jv09qtyVTJxup9+EX31BJqWNEBCJgF6NgRbIS0ZnfJJPmaUJ2A2sFT5FnpJozHVq2CrEcnkxGYTrkSBR3zRutsAu1K0Eq1Qt1S3syNrlgNXaFu1cocTt2ahBpqHikY5AjCRKUyB/8nnL6kMYh9zaPOsnULwY/94duKuQF0U8tMXyKg5XBxh1ZlcNWakbHlBFrlwIo18k8n0IaAKtYknKK0hTpKWfQAhwlbX8vm4A59itCKtcqSSWoOg1WsDSKIOt6dFTt4/i4BaaYl4miHfs1EVGvsWQE7tavv1HSXtlwSOjR1wMYNJunBqvAa/fFxleOga9JN23ldQe2UnNmte+OE0eh6FXD/kHNT/Z329rUArUuLQW0toL/5G6NBBElqBXou8qhqwoFUrQ1aRcO2cjW32xWVqrhq9RphzFHSZ+hQo0kPPPudNy3j6VPHVauXG6aoN3sAev31kk5lTLX64BDaduiNMIIv6VTHVasXCg8+QYtXg1WsVWql2Zjq5Hhq9Ri5sCkvY0/uxh3DP6NaVOBe0zEZoU87Pup63S/oXj2sHkjRLgTTtwJri841iag3bJGSv1NtbSWurXK7cB53q6xhcUc0F1O8ILUpApty9HY8LYqAalSwQZzCOmZbKYBtHnTxxssRHvJApfSTFyUp05AM3QHStrNYl0HIzo4Kkm7DyA1w+WZR5ho1maaw0bqnP8Qn7gRjUKYoQ8m6kRpPR4BxEWoo7bE4KyOM/aOxWJfBhjbV2vmKklThyDU0WOvEoePXfj7XoAYPmsBZqzLzXhMS15XJ7l0KoASXnDvUR7EAMJTnOyjnnV6mOUT/mgXHTsPvYW5guRfen5+S6aMmfj3miar8XpQ1o1VyL8PazGz47VANzDLxm5+mGPGuQyt2ZMe7ZEphgmEuCdELGQ/1u7GQfGokZsF/qeRX7WfvmQ4ssCUb7AMgU8m9q1IuhS6sZ7GS41DNbOs4Q1ynbeSGmuxbkz6Ep3ti66NZEj6EZfTk62NZEj6EZaIzyxNVOU4v+9JHtCL/tXZZbIFHttdCw6tppmbxwE79iTlmCAPJZ3NoLVivf14NkVdsFTaRxkS/6r69Jf8GVviyVYqrP3ysIQ0VEatqHrCFuarpPyxN7b6CZtZD9hE0UFcyQdXMWMmUFK5/uii+5u6K7DKVHmIJdjl1Qys6YU5os15F+Bx5v3k80UaTc7+e47jI7SeBtRRsYaB6s+vzeOKFSlqNqe0nbqJqz1+ZZU10T4aqmuwKO9lmmjPYAQB8ODpR09CV2dVE92SoaEGmQk5y7aW5NVBKS7ik9W1Km19UW46YsW9sP+oN8n5hvGsOq2JP6wnFF3ahRYqr6/MI+HO75yWfOX+jSMvoRuowfCPxKHYf0ZaAB/CCxaG/9RBvQJImDhuPeOMCz4GuKhakmC5PvhzJ37MYmGvLS10fbeLVQLMRQYqobSGpqsmVpcoRwiVFC6ma5B7EWMlVzqsgWIoWWmMAsQ571SX3IKbBXjXBUrTQ2AAf3FPMqipXzlZ41q3YvCs3WiPCAKI6MrcJQIqm/+KAxwc3rXaUCom2QPSiqsGWHNF9MtvZIqkaurAm+U0kZYfZYbrr3HlbUdkNHPA836V+v1se94pibKMsTlovzgveo6reW2A/hGbiPJin89P5MccC9Ql0GoNGwmXuNYcxYFSfhr5bPlaapJnjhh8NqKnBFKgO1vNU/cZKazeVhaRJhswIhMkJL3aHADgvfS8mbkEUeE7N1Eoe0G2IbpJWTox1s+qU1c9WIMh8WfuwNP0QrSQBsXSB2KfqOwfTqyQMy384BIqrMW4FUPepeqJ6sFBIg7JEfTWtTRIKaSo299dv9rP3XG97XbMFdWQhrjpkDapFclwKqQaVZ0nUfaoh5VkWlCXSM5PWUOQW18urpWx/vghjsZCMtZRXge1lUrGkq+NxXDbRhKRbDVnPtTHWz0CEDYpt1EX0Xs4iotAtU9WNTXJkChJ6c0l/RxPsKayyvYiUkw+0yNYW8NkarUFT9+eAZ8YqgaiEKRQS92bgR5lpxf7j+14USqkn3lh/t7pZnkxa12E/JGpFTLZSmGjy3lkZJmbq2g/9KBQS695ussRD0P7GhlTRjYNu5VakTlUJrlFO/lqX4Hse6yXnok03cHseLxm6b6xAwAzgP7uziG1CL6RkjgZP2GvfDFXj3FkdeQYoRR8qC5u4mXVD6HMCq3kmRmvxYujixYqlYGWqKGHQZmYqx4xTAQe6iw2T8tpLd2494VKda8z2BxQkKLP/YDZMysSVi9ykO03VIti4rREvzyRRPjAsixi4cxyJegBxALyBfPZCXnv1KhpQuExTnfdb4osi1OXBMD57Ia/V4wK+Ez/K+ltCqww6CguwQwd05wlWqjgzmKebuKULHv03UxyAhrAowKiVeQI1jFgPpSGHciuJ+x8ghoJ6oQ9GNbcgALGIV8rTvZB4GIudJdCe8BjQhIPRzY1nJbveHPbJhzHxQpHxOo8ES6n9gMwQr6JYYVjoYs8NHkRm+gtKo968XZSCXOhFiKXUnQueu+6fCzAxJru4PsUTlpaEpjCtwUn/evvwbkupWsuCTo1dDY7VYE5kRVRmCkle0ZEExkqgHUKKYC9in6THuhNNLdMXVYDFeyL927nRznLxbSnpzo0dM7Li9EW2nG5iAOI07BnEAM8xSzUiQ6dtuXm/n+puqjfInkbBTAbTm0yTs2nckiCJ9l86/OPwxQKuIZhWrasGXbZgs/dVYdJBMRu4+VEYNntq0uxycVrya0gHS4anQ6pHFMaptfb6lIuKpC+LhapbBM/vrlG3/VnlxU1I0R6Vl1jYYGYyoJYGo2cwmQrvDEAifcuOwx7Ft5NrLvgPeSnANfCvLVWXv+6AFZmnCgoEZWXsBb6m0L4NpnTVdAYdm0c7jUhpGHLbSVsIweKdoQhkwykVJQ0k5YAoBmhrtkPuiMHHXJs3xglTbJY7kDB4RIcEttACkQKaVWkDyX2GMGhhfDixoqSBpFq3VwoTktlv2ULGB0libYG5zjablh1cwrTq8oYSjDJyd0D9HG8/gjV5Cgg+xVYUgVgRvaK0geRYzzOcWFHSUFJx+N+wEVJgraKkgaR+y0CmwEy5mIF0EuBHOwX1cS9nKKEUBaPBTqGCjKtKG0huicRdK+JWETbYbnjtXVX7WhM3kB7aTz6cFZMylAy6V01BDu7laJ004XuTvUcJRQm9J/tLDlRvKlUpvem0br3vpCG2B78FnrTGvfHz5P13GJSqa28iNTH996XDmjqgYOTJ+xMgdbM/gzz91PuYwLb/pTJ4w8ijC54GzVZffvlyeTd0XE6kmHerlXimEN2NvRoGkWKUhQ3t1bEw8e6gg5UKP2OvnipWTNh008UKl4+4J6PLs0BRNLejSPBct2+lKbQduhzLSrC7/+iiozkGXhuz0jA2coFGM6hvuYFa1L3EFli8oowiXb4XjvomAF2W2gJvSdzQVMEtll9/DZzUS+C7KETr5LEVvxhW/TKmKnoSHEMBifjNStIciggdTJ5iN9XLJEdoYbKG0t6daqOxF9/Gwd2i89faOOTiWzjYtj4CVHYbuhvtKs6YUgK5+E4OeKZHM5Eco40NDQWIL7bWx6eK0sYojU0nXm/1kSkAtPAAtrPTxoEJb8dPLJ0EiPRWBvpKKJXdjm7aWfyosSsrQ7RxCdI4jMQjuEoT2ctvYbF7cDbaKDDhbfi+ZeutmiWENq9O/LoRWQp+7b6R6hQ20NeDUdlt6A928lYfPpPexoBuW9NHogDQwiPZWSdv32ljsRffzuHt8YlODlR8C4fnt0dn2hgw4R346LJZS6OXXcFo7TVsFSzoPRzkCzPJIrQGxhIwiqkbvNjxS0QO9FLkdm6mGp+iHz1TwOeAH6nxOvpS7PZK4jhU4sL3YciwW/iFrpLOqQc7itzae0xELaqdI6gxUzYi6kVPZKwUPSib1ejFUWTGI3pQNt/Ri6PIXAjr4HHU8qmYVjl093Did22rpVqE72CJrW/ayVTtY41DC9/Fz1e3C5QyvD3/uoJi8I/+c7XFXGXcl+5fn8+O3xttWB0Ur5FLPoQTPh1DjVcS2AF8S3WB34fxi1oOPNnddji8tjwvtJWboyS3bTY3ioTDwgouH+xaAc+hDBRoEKb7i0RQ/go2eLb8yIPvqqVzT6oOJMzqGlbE/jkizW0P18LwliVe7KygerheLTselAQzvFqp0XiNeCIcLwN0mj0ew3oFKBlmo5iuBCbC7ppcjD6G3QpQMsxGsVsJTITdLb3MawzDFbGkuI1iujKaDL+TcQmeiDNcwj4PlocxMrcAJcHsC+e8rF6CX/jHbLssOEoOl8Ak2C2yJA0HuKw9OBYhJZhe0FAjY1ItYbZN7L4k6BZOdBVRtk40UOQBtPD5RNb3e1aNqt+9l9YNqczZL8prg32B7uYq/Bld3KAIuCRRDFqd1hWZHaOsr+F2W437PgDdI+KMiugWEivwnN4E3gv7WpkhGBUuQAuhJa4vC3yh/BCz1KcGynJFKSien6hKbqGhJEuqDESzAdXeNx+IKz4kGxKQZpEZWS9eaDlGVaoogUEmaKHQY15GUU3lS27voVDgObIbsCcJ4dk+eme3+4Rn0z7dXZy+efPhPCePY+FV+JSo09MZt1a6UzR7oxaAddN6pFYrnVoUHN9HscCmiVT1QPkJc5WCf//9d5OWFOCgeb5DFshQJUqx9gQeuSCDLFtrUaoM54YjQUmuAuAgTbq48PYGjISmxc6VTkB7NZ6olHT3HgOJNVyRzCK2rhPHTEL7AWjEIqHM89Ed1ti3M8OJXXSnCI3nRH7RsP0X5MeVkpKlgpaN/dDpiegtDQFIn8IYnUDG06PTFYk49JnlR+eAoswZ9s6N9EGvQyt2GPJkRo5AjPfCW57JHk1k7AkrV170aYzV8Vg8uai3SBK0cyoIJ8J2bb86rBsDduPG/pMVAzOLtrE1Zgu/13wSeyeeGYzd1+bg1m5tugF0OzYWuhBhqnaHDIc98EhiE+ghEdFVIHz7tWIY/qXBWgDoRcE6LLQPDS8gv+Payb4S6heLDZNUutmqr6iGW3n6iqsG4u8vh4bClRQgGKtTmdRy1BHVYrmRGYfmdPFumGHZLOFG9DoeP1TT/Q0dFUk46NBFHgPvvjSvay5/Xa4uoa1vvn2++mJ+X16ay5vFXy5XS1Epl39bmVd3/xdK+P5thWdkHy0vQ2/evxWV8fnr+fJn8/b8C0S/+n+XJSmnR2fvROVcf7q8WH1dMm0+X30ty7q//1+/ZWH6f+io/BCNBQ7pjMehzVZF6EeioDe3q6tryNpcXX37dXH36+3KPF9ei6a+vbv55Wp5dfPNXPx8/u3b5Vfz8tv5p6+XFyXix6Lilld//ZtZn7Ns/v7u/Lpu86Pno6OjU/jf0fevopL22t/eQXusrn65FC5DkPUXSPr6+Pj4+svq07lwuq9XkDxWt5exWPJPR8ME/M28XnynGWeSwvzpfHl5YV7+7XLxfQVzV4X8xc31NSwnRP71zcWlGqG4qtydX1zdmJ9uzu8uMHXzF9QiaREPJZ/0FU1FfDu/LitPaiybZJOrv7nUu8tfOELPj06k5X27XKHcur35dvkNto7fFl+/X6AaLSbANJer89XVAib8evWtrCjek2rDB27guUG1D26v5ihfq9XcFq/gTU3FycaWaSe4debq9vq7eX57Jd5ifKVCcP01EbXrvBvrV7pqnZCsPjefP3+9Ob9Auf/Xm7u/oFxc/EW8CZRptXNMar8bCcMVzX/1bXV59/l8Iazt6ty8uLyEbsNX9GexRerRZgtn9V+vPl8NqFCkZ//2HRbfi7+Yq5/vLmEufb1ZnMNCtLq5Qzl+e4NNsSwVnRMJint2i/PV+debL7AbvFxeIpdITMbdaoXdL+w7FCuYMIk8vJK5vFzUOh3SiO0/4jZqdHnpc2nRfWtXXUruZ0EIXVCRD5PUsf/931u/FPPGBS6y4TMQ0sevfJSGoXcTUZujH1cO/Gr/dJ7Zc3atO7Z8iB+3fDW3n59NFCLEsWKnlFnQPrUKIoKPftk7yw3aCeSfze0oKwPDQRh4PvRPxwDfVMA30ePpYVKdtdQD7YVWalprt9y7hpt00wef3FrVDk5vtiJ/Le3YjdIS+L+g4L5oJsfK0nALAoN8ieZ/zGW4mHuO/gK5yQIbPTQTgP9OSgzTOKt6HBo4OFZqKcWXyJzACkLTNmF7MIXmoe+m5iaGzY8ZhXg6dwIS0ADg2QbRVNkP8eM0dUfOeLZx5tqKcC8wvt52Q09wdqYf+8mKAzfYJnPL8yZQPYcHz2lsTUkgAo4VoAFWqVuyvGRMEmj1DMdcSKaggb7w3d/x0cdy5+j+LgbvWw8A9VpQEX+OfLLUircgreI3fFZzSQ59+OQnOcdkIIV0l/nrCgn6TD941Ss69OGTn6hvdOgcV2dD9ZDg+keQCnp+CJ//JOEr1UD2jV4nn/2nTS3kIRxP/CTaTLbIp7urxcigIKxNzjshJOzBK6bE6z8PN0F4SJ5OQqjBocC0iu/GK0ussTWrPd7hX/GTcc2kl00vu9S74sO/0mcT2UYbIxn7NPaOhzeDy6+sZXRykbFJ84DtcIPeHe7fjWug0YjJWKt9iH24Ye8ns9roBKXqX/sQ+XCDPjjEHxzmH4xcLceiyB/eNnzWPO80bLppICs84VKbbjmEni6wk5/Q2zn+5xhc2BwAvYPe9K2ozOpvVN79D4fXVvTTv/zrzffV7feVeXF192/Gv/zr7d3Nf1wuVmhx8t/mOPGQgldj7SY25+oLLParm6S56H3vCL2rLMgS4BxGFiputZLWKaIjHzrTV7f+GnsjSJhmFybpH842crpCzeZkW+XcdQD855sTorGTzsmefWeduZ6Dp7Dn2yCbF1odFAe/apKCwMrX5KM5stkcb0JEtw69Nut1pufettLy/YZe1HjogWCb7n6qLqvpzi00GJLJr+L3/5Njg3OMLCXi3KLLLNUMoHtCw6g66/W0PTt+7x8fH/vbdN1zsNHQEUk3Wxn8YUYxdBo2Jp6KkbTpX73Z4eHWbnDdxJLDkoTGZIfx0zOUs/XRlmO1zfxI1tLfQlPHQqh9Rt+ymu45G8/aJhOUDdWZ26+llLAb/ZpZ7p/FbrUWBJ209tdKfJ9n+CMXd/jkprvDegiIV1I3ZMXZbmxnnhU7IAKBAwL7pd9y0uvRKICtolMbIYkvBg2pgQrU2Ndmiaz50aCdNP71w49/fvY99CmIUTwM+PHxnOzYBSiCiRts4aPvq8+HH+4P/kwEsE4+382T2XM/dDJYo3AklPkCn9q4JZ/dQht/wsTzUBtzvOsJpoeSIhCnL0sb/v0TucwZuw9F00dQANZ8mYLoT5B+6fdIKg1RxtBHyyHRx5YgTfHy5utgldnUXH2zvHo5JZ1G4TXF5Rg2czu2TXrYwI4JIior0Dp5NYCP8lAe/GarePFguWwdzA6WV9e3X68WV6tfzeXqO9p6fXt3c3t5t7q6XB58PPj7/UEhpMzHe/jgHnq61iOA5TW0H36xYhedxEnQ44/oD/QB+h9sASIXfuU8fA1tMvFMX3xk/9gC+yE0E+fBPJ2fzo/Z4xn7BzoFcxPV09Ucbfr8H+QPKOCAxrH7w1D+B8wKgo72lCTQ8v+5Nz1woCSUsbO8gOHDPkg5UjoKF2aaKFoWCjAEPw5jd+sGlke/DjLPg09p3YAPjmdYQApdEPjr8Pjd0dnRyen70w//mEmhkwOtJq2+Jm6nk14cjj+8PT16e/T++EySwucYAHTwbx+wTF7/k+Pjdx9O3py8fSsJfre6NC/IoJBGd+pj/OPTt2/evTt7J298HEqANhRZjEtuLxJnx0fvTj8cvX0zgEIak6C1fcx/9Ob47dnpybEkfOQGpj0g349P3h8dfXj//kRWb3wa00ThC2DZX2fbQSzef/hwcnL85r0oh5bJ+B7V7vT47cnZm/fC1Y6ho6K/yM8T96vzx6dvUK17L9zsMHBY7vKzzCZssS0v7FsEzt68hcY//SBc9gocyJXwOytwPBLqWhr/zdu3707O3p1IZ34N3e6TAUfvT07ensH/esCzY7OUQc8icHp6cnZ6fHR0ooJBPxucHsHO+exIuA3gMUAnLeAfaK+P3dsUH87ef4DlUZpIzVvsUQ3eH304+3D69v3bf/zXwT/+P+8NLUM==END_SIMPLICITY_STUDIO_METADATA
