set(SDK_PATH "/home/thiru/matter/stash_slc/matter/third_party/silabs/gecko_sdk")
set(COPIED_SDK_PATH "gecko_sdk_4.4.0")

add_library(slc_generator OBJECT
    "${SDK_PATH}/../wifi_sdk/components/board/silabs/src/rsi_board.c"
    "${SDK_PATH}/../wifi_sdk/components/common/src/sl_utility.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/core/chip/src/iPMU_prog/iPMU_dotc/ipmu_apis.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/core/chip/src/iPMU_prog/iPMU_dotc/rsi_system_config_917.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/core/chip/src/rsi_deepsleep_soc.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/core/chip/src/rsi_ps_ram_func.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/core/chip/src/system_si91x.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/core/config/src/rsi_nvic_priorities_config.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/cmsis_driver/UDMA.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/cmsis_driver/USART.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/clock_update.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_crc.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_egpio.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_timers.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_udma.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_udma_wrapper.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_usart.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/service/nvm3/src/sl_si91x_common_flash_intf.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/service/nvm3/src/sl_si91x_nvm3_hal_flash.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_ipmu.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_pll.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_power_save.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_rtc.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_temp_sensor.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_time_period.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_ulpss_clk.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_wwdt.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/ahb_interface/src/rsi_hal_mcu_m4_ram.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/ahb_interface/src/rsi_hal_mcu_m4_rom.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/ahb_interface/src/sl_platform.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/ahb_interface/src/sl_platform_wireless.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/ahb_interface/src/sl_si91x_bus.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/ahb_interface/src/sl_si91x_timer.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/ahb_interface/src/sli_siwx917_soc.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/errno/src/sl_si91x_errno.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/firmware_upgrade/firmware_upgradation.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/host_mcu/si91x/siwx917_soc_ncp_host.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/icmp/sl_net_ping.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/memory/malloc_buffers.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/sl_net/src/sl_net_rsi_utility.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/sl_net/src/sl_net_si91x_integration_handler.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/sl_net/src/sl_si91x_net_credentials.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/sl_net/src/sl_si91x_net_internal_stack.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/src/sl_rsi_utility.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/src/sl_si91x_callback_framework.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/src/sl_si91x_driver.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/threading/sli_si91x_multithreaded.c"
    "${SDK_PATH}/../wifi_sdk/components/protocol/wifi/si91x/sl_wifi.c"
    "${SDK_PATH}/../wifi_sdk/components/protocol/wifi/src/sl_wifi_callback_framework.c"
    "${SDK_PATH}/../wifi_sdk/components/service/network_manager/si91x/sl_net_si91x.c"
    "${SDK_PATH}/../wifi_sdk/components/service/network_manager/src/sl_net.c"
    "${SDK_PATH}/../wifi_sdk/components/service/network_manager/src/sl_net_basic_certificate_store.c"
    "${SDK_PATH}/../wifi_sdk/components/service/network_manager/src/sl_net_basic_credentials.c"
    "${SDK_PATH}/../wifi_sdk/components/service/network_manager/src/sl_net_basic_profiles.c"
    "${SDK_PATH}/platform/CMSIS/RTOS2/Source/os_systick.c"
    "${SDK_PATH}/platform/common/src/sl_assert.c"
    "${SDK_PATH}/platform/common/src/sl_slist.c"
    "${SDK_PATH}/platform/common/src/sl_string.c"
    "${SDK_PATH}/platform/common/src/sli_cmsis_os2_ext_task_register.c"
    "${SDK_PATH}/platform/emdrv/nvm3/src/nvm3_lock.c"
    "${SDK_PATH}/platform/emlib/src/em_core.c"
    "${SDK_PATH}/platform/service/device_init/src/sl_device_init_nvic.c"
    "${SDK_PATH}/platform/service/iostream/src/sl_iostream.c"
    "${SDK_PATH}/platform/service/iostream/src/sl_iostream_rtt.c"
    "${SDK_PATH}/platform/service/system/src/sl_system_init.c"
    "${SDK_PATH}/platform/service/system/src/sl_system_kernel.c"
    "${SDK_PATH}/util/third_party/freertos/cmsis/Source/cmsis_os2.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/croutine.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/event_groups.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/list.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/portable/GCC/ARM_CM4F/port.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/portable/MemMang/heap_4.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/queue.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/stream_buffer.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/tasks.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/timers.c"
    "${SDK_PATH}/util/third_party/segger/systemview/SEGGER/SEGGER_RTT.c"
    "../../../../examples/platform/silabs/provision/AttestationKeyMbed.cpp"
    "../../../../examples/platform/silabs/provision/ProvisionCommands.cpp"
    "../../../../examples/platform/silabs/provision/ProvisionEncoder.cpp"
    "../../../../examples/platform/silabs/provision/ProvisionManager.cpp"
    "../../../../examples/platform/silabs/provision/ProvisionStorage.cpp"
    "../../../../examples/platform/silabs/provision/ProvisionStorageDefault.cpp"
    "../../../../examples/platform/silabs/provision/RttStreamChannel.cpp"
    "../../../../examples/platform/silabs/syscalls_stubs.cpp"
    "../../../../src/lib/support/Base64.cpp"
    "../../../../src/lib/support/CHIPMem-Malloc.cpp"
    "../../../../src/lib/support/CHIPMem.cpp"
    "../../../../src/lib/support/CHIPPlatformMemory.cpp"
    "../../../../src/lib/support/logging/TextOnlyLogging.cpp"
    "../../../../src/platform/silabs/Logging.cpp"
    "../../../../src/platform/silabs/SilabsConfig.cpp"
    "../../../../src/platform/silabs/SiWx917/CHIPCryptoPALTinyCrypt.cpp"
    "../../../../src/setup_payload/Base38Encode.cpp"
    "../../../../third_party/mbedtls/repo/library/aes.c"
    "../../../../third_party/mbedtls/repo/library/asn1parse.c"
    "../../../../third_party/mbedtls/repo/library/asn1write.c"
    "../../../../third_party/mbedtls/repo/library/base64.c"
    "../../../../third_party/mbedtls/repo/library/bignum.c"
    "../../../../third_party/mbedtls/repo/library/ccm.c"
    "../../../../third_party/mbedtls/repo/library/cipher.c"
    "../../../../third_party/mbedtls/repo/library/cipher_wrap.c"
    "../../../../third_party/mbedtls/repo/library/constant_time.c"
    "../../../../third_party/mbedtls/repo/library/ctr_drbg.c"
    "../../../../third_party/mbedtls/repo/library/ecdh.c"
    "../../../../third_party/mbedtls/repo/library/ecdsa.c"
    "../../../../third_party/mbedtls/repo/library/ecp.c"
    "../../../../third_party/mbedtls/repo/library/ecp_curves.c"
    "../../../../third_party/mbedtls/repo/library/entropy.c"
    "../../../../third_party/mbedtls/repo/library/hkdf.c"
    "../../../../third_party/mbedtls/repo/library/hmac_drbg.c"
    "../../../../third_party/mbedtls/repo/library/md.c"
    "../../../../third_party/mbedtls/repo/library/pem.c"
    "../../../../third_party/mbedtls/repo/library/pkcs5.c"
    "../../../../third_party/mbedtls/repo/library/platform.c"
    "../../../../third_party/mbedtls/repo/library/sha256.c"
    "../../../../third_party/mbedtls/repo/library/sha512.c"
    "../../../../third_party/mbedtls/repo/library/x509.c"
    "../../../../third_party/mbedtls/repo/library/x509_create.c"
    "../../../../third_party/silabs/matter_support/matter/mbedtls/tinycrypt/src/ecc.c"
    "../../../../third_party/silabs/matter_support/matter/mbedtls/tinycrypt/src/ecc_dh.c"
    "../../../../third_party/silabs/matter_support/matter/mbedtls/tinycrypt/src/ecc_dsa.c"
    "../../../../third_party/silabs/matter_support/matter/mbedtls/tinycrypt/src/error.c"
    "../../../../third_party/silabs/matter_support/matter/mbedtls/tinycrypt/src/oid.c"
    "../../../../third_party/silabs/matter_support/matter/mbedtls/tinycrypt/src/pk.c"
    "../../../../third_party/silabs/matter_support/matter/mbedtls/tinycrypt/src/pk_wrap.c"
    "../../../../third_party/silabs/matter_support/matter/mbedtls/tinycrypt/src/pkparse.c"
    "../../../../third_party/silabs/matter_support/matter/mbedtls/tinycrypt/src/pkwrite.c"
    "../../../../third_party/silabs/matter_support/matter/mbedtls/tinycrypt/src/platform_util.c"
    "../../../../third_party/silabs/matter_support/matter/mbedtls/tinycrypt/src/x509_crt.c"
    "../../../../third_party/silabs/matter_support/matter/mbedtls/tinycrypt/src/x509write_csr.c"
    "../../../../third_party/silabs/matter_support/matter/si91x/siwx917/BRD4338A/support/src/startup_common_RS1xxxx.c"
    "../../../generator/app.cpp"
    "../../../generator/main.cpp"
    "../../../generator/nvm3_si917.c"
    "../autogen/sl_event_handler.c"
    "../autogen/sl_iostream_handles.c"
)

target_include_directories(slc_generator PUBLIC
   "../config"
   "../autogen"
   "../../../generator"
   "../../../../examples"
   "../../../../examples/platform/silabs"
   "../../../../src"
   "../../../../src/platform/silabs/SiWx917"
   "../../../../src/include"
   "../../../../zzz_generated/app-common"
   "../../../../third_party/nlassert/repo/include"
   "../../../../third_party/nlio/repo/include"
   "../../../../third_party/silabs/matter_support/matter/mbedtls/tinycrypt/inc"
   "../../../../third_party/mbedtls/repo/library"
   "../../../../third_party/mbedtls/repo/include"
   "../../../../src/lib/support"
   "../../../../src/platform/silabs"
   "../../../../third_party/silabs/matter_support/matter/si91x/siwx917/BRD4338A/support/inc"
    "${SDK_PATH}/../wifi_sdk/components/service/bsd_socket/inc"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/cmsis_driver/CMSIS/Driver/Include"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/cmsis_driver/config"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/cmsis_driver"
    "${SDK_PATH}/../wifi_sdk/components/service/network_manager/inc"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/rom_driver/inc"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/core/chip/inc"
    "${SDK_PATH}/../wifi_sdk/components/board/silabs/inc"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/inc"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/core/config"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/service/nvm3/inc"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/errno/inc"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/icmp"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/firmware_upgrade"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/inc"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/sl_net/inc"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/ahb_interface/inc"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/systemlevel/inc"
    "${SDK_PATH}/../wifi_sdk/components/protocol/wifi/inc"
    "${SDK_PATH}/../wifi_sdk/resources/certificates"
    "${SDK_PATH}/../wifi_sdk/resources/other"
    "${SDK_PATH}/../wifi_sdk/components/common/inc"
    "${SDK_PATH}/platform/common/inc"
    "${SDK_PATH}/platform/CMSIS/Core/Include"
    "${SDK_PATH}/platform/CMSIS/RTOS2/Include"
    "${SDK_PATH}/platform/service/device_init/inc"
    "${SDK_PATH}/platform/emdrv/common/inc"
    "${SDK_PATH}/platform/emlib/inc"
    "${SDK_PATH}/util/third_party/freertos/cmsis/Include"
    "${SDK_PATH}/util/third_party/freertos/kernel/include"
    "${SDK_PATH}/util/third_party/freertos/kernel/portable/GCC/ARM_CM4F"
    "${SDK_PATH}/platform/service/iostream/inc"
    "${SDK_PATH}/platform/emdrv/nvm3/inc"
    "${SDK_PATH}/util/third_party/segger/systemview/SEGGER"
    "${SDK_PATH}/platform/service/system/inc"
)

target_compile_definitions(slc_generator PUBLIC
    CHIP_SYSTEM_CONFIG_USE_SOCKETS=1
    EXT_IRQ_COUNT=75
    FLASH_PAGE_SIZE=4096
    MBEDTLS_CONFIG_FILE="siwx917-chip-mbedtls-config.h"
    OPTIMIZE_TINYCRYPT_ASM=1
    PROVISION_CHANNEL_ENABLED=1
    SIWX_917=1
    SRAM_SIZE=0x2fc00UL
    TINYCRYPT_PRIMITIVES=1
    SIWG917M111MGTBA=1
    SLI_SI917=1
    SLI_SI917B0=1
    SLI_SI91X_MCU_ENABLE_FLASH_BASED_EXECUTION=1
    SLI_SI91X_MCU_COMMON_FLASH_MODE=1
    SLI_SI91X_MCU_CONFIG_RADIO_BOARD_BASE_VER=1
    SLI_SI91X_MCU_CONFIG_RADIO_BOARD_VER2=1
    SL_BOARD_NAME="BRD4338A"
    SL_BOARD_REV="A02"
    SL_NET_COMPONENT_INCLUDED=1
    __STATIC_INLINE=static inline
    SRAM_BASE=0x0cUL
    SLI_SI91X_MCU_ENABLE_IPMU_APIS=1
    SL_SI91X_SI917_RAM_MEM_CONFIG=1
    configUSE_POSIX_ERRNO=1
    SLI_SI91X_OFFLOAD_NETWORK_STACK=1
    SI917=1
    SLI_SI91X_ENABLE_OS=1
    SLI_SI91X_MCU_INTERFACE=1
    TA_DEEP_SLEEP_COMMON_FLASH=1
    SL_WIFI_COMPONENT_INCLUDED=1
    configNUM_SDK_THREAD_LOCAL_STORAGE_POINTERS=2
    SL_COMPONENT_CATALOG_PRESENT=1
    RTT_USE_ASM=0
    SEGGER_RTT_SECTION="SEGGER_RTT"
)

target_link_libraries(slc_generator PUBLIC
    "-Wl,--start-group"
    "gcc"
    "nosys"
    "stdc++"
    "c"
    "m"
   "${SDK_PATH}/platform/emdrv/nvm3/lib/libnvm3_CM4_gcc.a"
    "-Wl,--end-group"
)
target_compile_options(slc_generator PUBLIC
    $<$<COMPILE_LANGUAGE:C>:-mcpu=cortex-m4>
    $<$<COMPILE_LANGUAGE:C>:-mthumb>
    $<$<COMPILE_LANGUAGE:C>:-mfpu=fpv4-sp-d16>
    $<$<COMPILE_LANGUAGE:C>:-mfloat-abi=softfp>
    $<$<COMPILE_LANGUAGE:C>:-Wall>
    $<$<COMPILE_LANGUAGE:C>:-Wextra>
    $<$<COMPILE_LANGUAGE:C>:-Os>
    $<$<COMPILE_LANGUAGE:C>:-fdata-sections>
    $<$<COMPILE_LANGUAGE:C>:-ffunction-sections>
    $<$<COMPILE_LANGUAGE:C>:-fomit-frame-pointer>
    $<$<COMPILE_LANGUAGE:C>:--specs=nano.specs>
    $<$<COMPILE_LANGUAGE:C>:-g>
    $<$<COMPILE_LANGUAGE:CXX>:-mcpu=cortex-m4>
    $<$<COMPILE_LANGUAGE:CXX>:-mthumb>
    $<$<COMPILE_LANGUAGE:CXX>:-mfpu=fpv4-sp-d16>
    $<$<COMPILE_LANGUAGE:CXX>:-mfloat-abi=softfp>
    $<$<COMPILE_LANGUAGE:CXX>:-fno-rtti>
    $<$<COMPILE_LANGUAGE:CXX>:-fno-exceptions>
    $<$<COMPILE_LANGUAGE:CXX>:-Wall>
    $<$<COMPILE_LANGUAGE:CXX>:-Wextra>
    $<$<COMPILE_LANGUAGE:CXX>:-Os>
    $<$<COMPILE_LANGUAGE:CXX>:-fdata-sections>
    $<$<COMPILE_LANGUAGE:CXX>:-ffunction-sections>
    $<$<COMPILE_LANGUAGE:CXX>:-fomit-frame-pointer>
    $<$<COMPILE_LANGUAGE:CXX>:--specs=nano.specs>
    $<$<COMPILE_LANGUAGE:CXX>:-g>
    $<$<COMPILE_LANGUAGE:ASM>:-mcpu=cortex-m4>
    $<$<COMPILE_LANGUAGE:ASM>:-mthumb>
    $<$<COMPILE_LANGUAGE:ASM>:-mfpu=fpv4-sp-d16>
    $<$<COMPILE_LANGUAGE:ASM>:-mfloat-abi=softfp>
    $<$<COMPILE_LANGUAGE:ASM>:-x assembler-with-cpp>
)
set_property(TARGET slc_generator PROPERTY C_STANDARD 99)
set_property(TARGET slc_generator PROPERTY CXX_STANDARD 17)
set_property(TARGET slc_generator PROPERTY CXX_EXTENSIONS ON)

target_link_options(slc_generator INTERFACE
    -mcpu=cortex-m4
    -mthumb
    -mfpu=fpv4-sp-d16
    -mfloat-abi=softfp
    -T${CMAKE_CURRENT_LIST_DIR}/../autogen/linkerfile_SoC.ld
    --specs=nano.specs
    -Xlinker -Map=$<TARGET_FILE_DIR:generator>/generator.map
    -u _printf_float
    -Wl,--gc-sections
    -Wl,--no-warn-rwx-segments
)

# BEGIN_SIMPLICITY_STUDIO_METADATA=eJztfQtz47iV7l+Zcm3d2r2RxbbbM/24M0m5ZXePN3bb11JnMjdOsSgSkhjzNXxY9qTy3y8AEhQfIAmQAAmndnbT3SKJc77v4A0cHPzz6O7+9r8vFyv9/vZ2dfTx6J8PR/eX1+erq79c6sVXD0cfH47m84ejfx3N8jTL22/3i8slTPbjn55d57snEEa27/30cHQyf/Nw9B3wTN+yvS188G31+fj9w9Gf/vjg/RiE/j+AGX8Hk3jRR9e3gAO/2MVx8FHT9vv9PLIdYx3NTd/Vokhbxoll+3Ng+iGAQmHqAITxy9KEf8N0mbSHIyj6u+9+3PiOBcLvPMNFL03f29jb7B16azuAvFtefvlyea/fr1b6An4230HhSWjDN+irj9rOd4EW7+ww0VwjjkGoRbER7fTI3ZIHUPeTjShrURIEfhhrkf3h5J2WqtUoGjQaksjRPRDrFtgYiRPrT4aTgEgCnkY9VFT3q0v9AjzZJtChDAlw6gqarLP2jdDS02RJaMRQpBzzNCjqxBWHviMZEVFBxfI5BOB+dbtc4HQSkNQVUHEA17HXOqqpsJStk21mSgmAWjSlyH7U0qaA1iwYSexvgUdvFxzbewQheqIv/cXcscRhz/RqFBWNVXDhu4HvAS8W2iIQJHUNTWXdJF/pphEbji80UwmcJj1NoMAT+nBneJYDQkmAajrYwJgjgDGbwdh+FIfAcLNvpRSeBjXMkOSYiKamE5Lt2TH8A+rzTPnGqmujApyboUnaNfhP8ZhqCrqbzr0dwZGY58Eh11s9sh71t/OT+UmhJa2Mv0jTkn9R+8bCQ4DC+9oX6Xiw9AXlmw8nz5VPah+5ZlL7hII5BJSv6t/t7ID6XR0bMi31w9qn9t3NNx1m27YxAT2J5cfNOtJEhYIFh+l69BLFwM1yHw/AmAuYY5IH6K2lBwYcj2tpLml7e2OjgqEd8l5Ls5h8gbNKg3mhIVNryI4aNJGWc9dySlojUo2Vqx24iW4ENkdzMyK/ErpmTqUayf+61Oql1sQgJzdJFUyTBWqlN4j0EDakm8QzJydBwcPMwwIgiBz4hx75ajCpIaJzaS1y1RbKa2v/KhYBYehzDOUkWALC1UpImHJzbURAj18CntGDJPBlKEzoLTjWVgR9GQoT+vvlyTP8b3LoBRzMLYBpBmjO4/IsaUgs9GU47CygDDXwZ0B69SQqEKjgYeZRGiUpwaSGiIkLTJGqmJxDCQkrdkWqcgkJK3YjikAYq4D9gISnHitU9ktomDiUhsJTU6iCYWOAvlal8lbBcDBwn6bvykpIuEfgba9aN8hav21fxqhURw+yhJNd2w/t2AZ5bZhqhpPtp2RznGZwvSY7lBFdAtuvqdujlHMDogaijNk4PaVmYDRmjRnY/KKySBnaaHebaV3QjexITxOwVazFzfJqybpCeNEmmPL9lWc6iUVf0aRme6oA7QpNM5DJTK0V7ahhE2kpNC2jpNWQMi8KkpTnX18FwRQmL7vL1c+vgV0Gswc7/eZ88UoYEqh9WN79/OtrYZlB5WX52YHYXwPHHCgvw6vTV1FSM5i87G4WV6+BXQaTl93X868Xr4EewcnLb3n+KnIvg8nN7u51sLvrxe7b8vx+9Rr45UD5GX56Hfw+9WT3KtoWgrMHv1cxCCU45WzB82yWtq7ICPIPlGvngnsv3bWwk1Mft+PRONFdlrkyXPXZNuPEukTkUqHJ2GXrbKsE+4tC44MvrYOAEmyF5hOtc4YSaIWmCa1TgRJoOKXVr8+/vn93dnquCvoqJgYaCg3yWwfyZdDq1E32qvnt4kaZgkKwsMBWaSbRMVuoAFdmgtA6CagXkvE3w5oLSfPeV72QqIKbgOHa8akNuEPf5dqt4fJmRMJN53HKsfmBX+6dUETF7GCBEoFtYPvqcclhsXuLGOaj7U2xkdlCpQCKK1fMcArXta7yFfL5r+E0UzgfdfHgc0PCxXGTRFN4wHTVEgKLi8zGdtWjkoHiIrINLNdQj0oOi4tM4O/hBD0ynhQsZ2VsfLT2Cha2DBQXkd+iwFaPCUHFRSVUrZssgOIiEhtrB+jTnRXooFSD14PcVN6jTNT4vEnztLbLc7R7NEoEFheZRMkuKOnTA6FE+j40gkDF7Kmi46PmBFGEJkgK8ipCk+gXDM1mBzsQGk6Ggu762N9H2HR881FPAsuIwYQLCnWe2Em4io79HFQ4xSnODjYFYMxE0im1klRyaMxkcGM9xQFwBjYHbMx0cHutJBmCjItK3k4rS6mIkJ1aBFEpyolAG/Fsd6lJna5fpVgF9a9VdFwNvnJsCsA4G3wlqfAt7xrJsx6CDQiBZwL9yXfi6U6tdJBrhcqcc4alaBHMgHEchZ9yzaStLpl8yyZIqxEa8SSBLFj4lPCx05pyeb6NDt8SvTmpq1wrD74dOctQtOJnwNj7nok3TNr6Hu5NE+DtUFg3a+KdkzZOFYTM1JRlxEtk6r2gFir8+0Hbafca2rjw7jfYp4q2aBkwDiKK9jEZMHYiig5hbL6hix8Y7hRRHRiY5NDYnVcm3SVtocK7U/obULThyoCxE1G2Cebe8kUJUJTKWNHFgDI+9n2dSXexW/hw72SrO3QJuYcukWX7Ux78biGTQ+Mg4wJFG+YcGjsZVRcDI05Pz8i1VS1hGTJ2Kqp2Mrx9TKQuE24qL1EYKzppOWDjpKPvgGGhXUmFaRUx8m4EK0nrgI1vI1hJMtwuRYq4E3VQ6uVSlO62qsmJQGMm82RYalLJgDET2SfhlJ6SLUwIMraQlc50YVs7uJSgsZKZLH5uNxnOgLowRRbF80wPFOxz6vgk+hPCYvBUveWl8WPvyX3LGg6xzeGwKUPSjNQ3KJiXbnvxZkIvncwwGuKcXonRirIlPgmVKhKr72DOYzFK8qxDbKxeXdecMHsmVcyFIZBrESd3FimZCtXUBni8ZaFeoBTi2I6yV4kQ03DhSNgOeAKOhOPBa3/K0VSBWz74yBCx+yBEk5/QoNEowmLf6wrcRDEeBBL73pDDcRHpKBQyROwMlMsE7jxQ4XAmlUi/k5lB6JsginyYFHjRpE5tVFYUeOzbKWA78boqjVIBFQeTGOrjuhp5JC4FXOxsJl1UpfLgXEqFAgI1K0wFGdfqqY5mk8qNWirI2JfmFDjpR+PDcMyPtqS1t6ZcBqIRIZCGHzThun0ED5smnOwWLEHO3BBIXCM5tShkiPqMgxQjUgLG1SepRSRD1KtPUotJBVmvPkkxRmVkPfoktfiUcPH1SWoRIZDELXc3vGh6XL1RPQQOnL9030zuAtcPXxruICrY3TUcxzf1dbLZjH/smdDRUrRaHUzd7qy3MIEw9HyWO5iaBwv0pVEseCpDYeXlNfEcz7DQhs1rkSUzpNrGHThW2ON7HwkMKTd4Qdt6IJZReKBYtFANQs+Aj2LDHLvlzm2Zcqxsr1DRMcT6TIXpuOmPbceOX9SgRQHFzia1CbLHNjTQooS+MzzLGT34QAu3VohsTA85b4bAQqsvhjNZP9BUKCvQRmnpKMVnomYvs0q29UUBJaJMK8OtFSInU8VYSeuwbNMNusd6GZQAxY2dqIIjoFoFB9UiTbgnytAabmpOsmbXxg7dvRECPQlgGW+4cLNkgkoKXC+mysMq+uqDHFxnxlITTpTDbKwGZXvTYJHeJafT0sl64mIXfIDCUldVGAWm6BmGfg3uL3AiuobDX30Twjd7P5xumF5y86LC6l8g410IDAs2ZyzF0iYugIkT22lKMPY6Wm6WHLnWAqy/YXZ+FOuumTBNAZFypgGlvX/+cPJOj3xT98xAR0qmsh8hmD1vgiZlsGLs1uksc2M0eHn2m2Sj2o58AyEt5KcKq8hU1i0xzNcS69jYRrOBY8QbP1SITQUUHw2dCFaSTwkdzwx6nahFqISKiQhqR/NmQCUuNWAMdKoVzleo+tCx8RS21F9RGUJ1XKOs0GThycY/A9JgikLINPa7ENMYWLGhxy8BGPvoRweRMi5WMulkQS0iOSZGEu6ZWgRSPIzgfcWKkc9TfIJHODDdumM7J3VQKKJiJJJEqtUCgoiRwN6OAOqidkZo4YWQCMTJ2IGROig1Y2Ql6RgeOUcyyWmeLoJUfDzkLLCxPdV6liqyHgNUZfhQgHHSmeJUDCOhjpMx1eFpqkklKgVIcrZeGsaqbauiU21ieLVV0SarNBwK9CAub/SQuFUCFDQ8JNCSPqZvT9cqVphUIbHTmXa0XaLRPsimw8frkHmVVYJGHRI7HduPURfwCCYbvpaolOGw08Ah80zfmXZOWqJSh8ROB0UBVKvtqiHiIBMbcaIIixwKO3x1ShRXQcKqph3cZOArSJj3uKiPKQ9rj+oPusN1VIN0gBhtVuqu4Rnb2t3ZDLs9NHeQtRHZ5khOa3kIgjKRoiseFU41d5p5wPYNvVOCRBELOwMThDHUahoxnIXHcEijAhUqKAZOk2KvY6RXXpZ96GbXuAkYpnvNFRD8TGlTLhrPMfr8Jq4F17/Wjp6G2/ImRpwBYMFqB9K7dAbARRQsqBWAzIUX61AAdBkHSzs6Jdw6RpbxTq25WUdWNotqH7h0NksQkrUewSIHwGlIKKK2Nb/gV3Z6/mMShAXdLDB/gN/+MBnQXHt7DYDjdqnXYDWAPOhthyd7naIJXuOCRBneyxhtXRXbS3fDlkiNdt4ALKFFMhcxe1v7Rmi1zd1SrAOnbGm0MKhJ4qgTy8/nziEJUZYplTDKPMiXVxxKpA5x1zKlreU0/zLbN0xC2f71zWDrELrGDugaz/GtW1PcBdM+NSdBWdLbBTLYu5OALOntAhlNlN8RT3Zn4eQnwVlRLb4rIEvsbb0BQjt8+Q5zHvWMBeGGX5KllhYYspZfkMrxaJL1FqJVzlJLkxnl1Y8yzeLCOB1GV7VOk46wWtQCnGeRCKcYbeu0GXT3VikVueyFjGbAzEsXuMZMgFBOy576j7WO8mutdtUi8k/0pShJ49xwbq97uabeZNUuQbAsG41D0yAXcndTM1LkjgOaZq0VrOlGdjSC51AZaE1rB8gR2s4KwOb2sjZGBwC8f3MqvdkpA6xp7QApfx29gq9xybyp5o+FrKHUdbV61Z/lViEEkZ+EJiiuZFRbycNeYVRpKwsGMfYosJkNcRc3F+cBcOem+JtVcthaEZ3WDUJjwB+E9hPaGH0ELzgp+nt0/A0gWvFDCOHGBo4Fx3s40Xioaaqbsf6ehEBfG05su8jHb1y0jcob8ZoGkjAixrLCZly4qIyNraa0Ax8pwWPCK+hsRIeWlEE4svXqSjvwjWu9ms5GdEgSPjgzHriqSo15oO/Hu4p7VYmL7Vngeb6LXeH3PhyYYAhaWVMjgdLP8o8ysS0wH32kST+bn83f5BSrS1jZKe6WTr5zKsQwf4h91xZ1ACVnphHw1TlDrq19mLa2RY0+OiFlqlgmLn50KvaMbic4mt5WpHYhCXiOdQjiEd2qYEexMM/6LtSdGNptDbxEVOPUaV+iqx2R0IsGu+tIw92B9XnqqCWRrfzBMWUoLrRZJ6qDtg5UDix8o4EiyrosJXC5hsFStCWa7hWozsW09touZoWtmR0JqtGBgal+j4O1oI2pJo2E6qCNpSaNBYoo41k7qRXhxc3yatk2SlrAKWX7RuCVZzoJJbZheeaEyyBaCrLFBSGl2Ajz0RBoLcOl1VW3bgqkn6NA8eKcKHiAFjS34ox/R2ujMazSo4Isq2Ww5NaUOIJutGKmtR0fXi0RFgGEEV5BaSs6N0h0I3Sf3o0Kr6RVgE/t/ep2eSqs/YB9mGxrYMCVwpSpbc0uH10uaYraDGeEV1DKv+W/xBP5drNDBei2DFtY+PoOYikmraxW/D4pw1G29OSdbnt2hzc4ix9MQZjuwX/KMyZxKy1oJAMGGgg5jiI1TdIqBY1uKRxEGYSABs324WgQGO7wQkEkyS8MRBMpCUXNnY6P2bd6GEsc2nYhJdrllNfcHtLLac6PbM4WNHPlxGRIiXYBVSm9h2l4RUrl4Jouv4SmyvJJWFk1g1sp+vwRhB4QdZEfL9aDcjmVqWgS6aU0Y3hwnS2q5suNabAelIsf5QDXCp/axjiUPRL+LAemb4nySqRYD5Mortfl+gS0QN6T+3Zg+4NE6I4vc4CcmgApwlW5pFFCHUbyZecnJoMP2mXK2s8CIsZb4IFQ5liSgqyotBvhzpDYitDQZQqZkOkbB+odHd9BbTdKXKZHBUg08tcix1631yL4AVaxuDnDi1HGCLygTo2iV0bPUuXPtzMCOz5TXOAQqlGQLVBrWVAl1L2YyJVYXhEF3OMdVLXsP2RfjdFOVoA1tZLDHDmRd2ize0cBals53IQAhLHfcawVr/JRqjPLclnjOqXoso3sUfqCcEsXKcnSWQlArc1luny2aUG2QpXol7Iq28WWrIBWQVDCZFExu4Hvi++tuVHnMJhyiqVjSicUXYU58MPYWDv0PC59+WWxYLm65fz+BnU5n1nC+SPlI1aP1CIaoaxBRhqBqxEsDFFv0aeuYYaiogIIwZ4DkhLz9ga4NwbLrVE7YAT62YSZmiHVDkCGBcyjDQdYGkVJLoOdhsjgaU1OhDWgsNgkKMbJdFCLCDrAWiAIAfKZtdJY4vhslXj3IGbozXg6iIAndBRiC5kHE8KvougA/RmKQdtz0wEuIugAK8WZjRko3butBtIFUWRsgb5ONhsJ3jDMcOs4uoAHSRqhV+QZtj7AazgYgO9DIwhAODHsIooO0KR3mw5wEUEX2ND/B2wMJ7RuEUEH2N8SkExo1lx9B8wIuMFuwvbhoL8LaIxiMeDB6IQFoIqiA/QSfX4zMeYKiE474z3YqfuNGowO2MjneDq0RHsXSHQDyoQl4aCfedmGNp4ffQ5W1Ny6yF8ado4Os6q9FaoUR+5OiDSP7oaua3Rsudr2XfVSwzA6yJr6dg9q2C5MUBBzte3g0tZgfHS5XhEePmDbfQ0AdoR4ssG+cwX+8suXy/uuFZj0K/1+tZJvvJSfdqCgpdq1MoiucQj+WH7H04GWZcR0oDU1WgKi78I51+ZU5cRycb0vCOZmELAaw92SB3Cy8mSjgx4a3j0zYj/UcmFaXZFr2J44TQdpFFV4/xjFlHvHXoPa1ZUlUlQaPBdiHHQVy4u7BlbsRFoIAh/tgodG+KIZxcstyhoj7wQmjDi6Uh69RekN2vehHcvTnkunaF8bEfiBY7WeQ/VBNE2vvUVniqXozUVT9JqmHKWZXJpGO9jxDIB4lOaiG/XiNSaJynP5NARZvC58oaQcDFUNNBRxqFvhmuOEKA+AgnCKbmBaOyl6iWC6zsiQpTSVTNUqp5RlcukadTMJnyR1F2XxNP1eHPoBR3BEHuUH2RTNu0drI0UtEUzT6RqmvGpUkk4b8XAEkedQ61oN+nBQNQkKM7k0jY9m9L0cnUQyTWvmyCVHcUE4RXe0M06//0GK5oNout7vTzh8svj0ZqIpep+/f/NBilYiuEEnup/OkDS6rMinttIcJxzpmrP5YfpGj5IA7USRDwms2PZezPAlSI84ZlrpePThfXI/SHpLnw1fDu+1+8Jq7tXD0B88dO2DiuilYPLtwZ1BD0SZVmrLPQGc4LERjZARfy9IbXOB4FHIDLsXrrbZd/AoZO7dC1fbvJx0njgy7hToqvqbexeO3RFh8IqqG5Bh6+pmNEX7VdNPwbj4+epugVL4d+fXK5gc/+i3rlfMMYJ3af/y/OHkndampwHWDRqm9sWBT1tkRioJa1B2l+GG3/nhizi9NLnNfI9vDMfxTaG0SzJpI9EYlq8kyGLG6ffLk2f4n9Timl0PYu9x0fh0f3H29u378xw4Ph7ciIq2eBkE7Mv/3SveO6qSO/L1TXrdY79MAs+GGzggqlWUAxi6IhZEPWzQB0+HfRY7w+M6v9wPTUENBc19HC/x3iv5TFZu0RWxIJJjH5qa1tyCFczwrEh+cS5rYsIkuwgV9LThufTQEe8RanxJEQsiyQYqqGlDs4QtJ2wZ5NunpIgFkWT7FNQwoLkAGyNxeg6uesAq6ePAN47RCtoo2M6hWKgFHWP4M8/lEFyQ6ko6kdzAkba0DGxSxYZqDBsRRbRx5EuE7kBDF1Uka9HdCU04BcOndLO3hyWqg+eDpGY1QkbpRVkNE4Nrf7vlCtPcrM1JRWkVsRTFK/Ac33rOC/lKCFminiqcAmKJc3+Br3DtS78+Iy3L7FIrcCpclUpRPdjcVa1dJkbl7+37tKPva+IIoKlaYLw4vmFpVYldSntTbVHLMdUXUKvoUultJIqxlDoe9VAsaoad3ThewpLBLd2XTHBnfTUEDHUCp/QE3wsLR9IBTLHG92fB1+vQOnvz5tT4+GaO/u/8zdvv0CMIIn90cgITIyrVtK6ZzI3Qne837hwy2EJ87snJibuN1yhmSez7jrkzbK+aDr6LrMfqU9NHUpCp5vDtHJ/ImEM7gPAjvtBjrp+8ffvuww9n788OYWF/dGEhcj5aIDJDO0CW+OOPWv1Z6olXshh89iM+9wPMGP77aHa0vLq5u75aXK1+1ZerbxdXt/rN7cW368vl0cejv/0T3Q/m+k/Aejj6uDGcCMyg8RLbiW3v8hm74Ufwzd/+fni8JLeJffwbdm6BuvPjiIdWbZa/u19d6hdp6Mkspw/vDp6LOkpafonDaqTxNCywTrbZVdrlj9CdHPR7tunfxGEaXqD01gMxOraKCpT+ZDhJeoAOcYY2T1BQgI8PRz9mVv14c4MffvfsOl70MXv608PDw9EujoOPmrbf70mWw9zXogiNPdFHc4DYoC+/y4yJk8Vhkj60Lfw7Meep3jluYeaJmdk1Xyaab00TpwgstyTijw+4TOATFGj4FMESjipkqmj+v9GfGvooLySEzh+xTTJYkDCS+K/Z0PJhJLEPUeNCsMivvcsygLx0bO8RhKgR0pf+Yu5YpbfpdRJpSt00YgN24hUB6G4OfJhhB2fTTuoL1va6ljqP5Zh+EdUF1L5oloEDrNrYJctUriStgIt6aPAKy1J9tjRrnh3RX6Vp6j119eHhOzI0nhUH97P2fYtZbdg8o6+wzyobDbPmvQD6q1R0aYg1o6+EzhqX3KhvKilK60K0F5XvSyvHtBeV70vrKrQX9O9LCwwt79PU9JVS2ov0+/p4ufow/Y46mZjlLtyzgk/8LN8rmFUcrmcVF+hZ0Sl5VvQUnuXuu7OiW+2s5us6o/iezsqeoLPcNWVWdAqZlXwxZgcPzlnBsXKWuzvOqm6Is5Jf4KzgQTGrXWjGeVNFLwHZ3Qe90hZun+BNX7jYgDNp6dIBzrTl+yi6E7fE9+dNXIi+z5qUGt++LXHT9VccafKIMOxpsnvf2BPQ7mLjSN0jDbmdjD1FfvUUR5L8YiieNOGhG2RL03kpHIOk2gVK7Gnym4Q4kuQ3IjGn6byHqk1ScxTg7lS1WLOcSYrhDXmTZhFaeyQ7BE7lTUyCmjKmawgaypi6FpC4PR0lpCVXAva8oMT/bEvAeZEEr6iWKzhYRLVdGzAkPQnmzyWDconEkPTkagcWGa3h3nsLOMRg5xBBvwCgt4BDVH6KiP5hJUUIax4d9QlJyiWGEmGiT/pq6Ic+MmihyIbIqcR9GSKqdYTXKxzfEDnNsfGGSK2GrBsiq2UcOCBy2iBptXBmQ6UVo4wNkVUMADZITiE21xA5eeSsIUIOYa0GSalEmxomqxJQaYgwEu9okIw8GFEfKS0TioFxesVKzKPnDhJbjz3bR1weYKdP4lrgmz5C8sA0vRLncWNYUjOEIhEghsRfESUqRUUOzM4qB2RnxSAdM3J+dVaNpzHLTzPN8jOnM3KiaFY6zDMrHBGdlY7TzEqHWGblQ50zykmSWfHs5ax4IHLW5pM+ozsazep76/DR3o7gtNzzgBm/xaZ+Oz+Zn2j5dlak4X1JspWOBuFhZKeblQJEUPdEewiEg/JtYPtDcaEpzqkpQEqwdwVIiYQwgrkexoNIoWnPIddNRhGVJU3LwqNKo7JCxysnnZigKmLHL31lZHsOfTHYAID3b0714siPW0YwKHlPA2QTWJKaNSvTNZC8OGDPGddM8P6BZu7sAMMibRArJjapaI+J01Rsgi0jNqQIhk1sadFfoNzSqrtAuemHguWiJsM0AzmgsXD4Q4LYdCtQvNwgKvsHCZYdwsHkJvFMCdKzgYMU9Pi5nAKYinafRBeSwjhKZGuHGmf77uYbWlbYpv+y/Bg+C9xENwI7EtheN+mq5bZ+GAKL0ot0WAAEkQP/0CPflCC/WB/ESi9lvhjRqZcfaS4T2HWIrWoH+WgDA2a57cNpiA0Et0eZs2KWAw2qhlrMCm3k75AtUKe/su36i/QHWQxPf+qL86+D+fErFdPlceu9XP08iVL95nwxjeK7n38dX/Hnwj7viGqvTicw8s3ianylX8+/XoyvdXk+AdXl3QRKvy3P71dTqP00idIJyhLUKqkpHqGLuZTWnH+RVtylNY7SGkDYdenX51/fvzs7PZejQVqDJi0Xv13cnMsZI2LJcjDjxlQOaHnttLS2uHCoqnaeRp6q2vmt4aoCEGJ3dcPRySM0+zeSZz0EGxACDyp88p1Y1DSqQ7GJ/PX0JLDQ4RjJutAMzrCGryUxqDFNexQ16NRjepxoDG3hOLYbvsbMpEVc/W1RYxmj2AxskmiU+gPQluQoirwdOshn6RvbHUPfSGq2geUaoyiKglGaIPt0lAJun45SXe1RGlI/MNzh6/cMioL9KIX6NzBKUfttpCKN9KRukGNoCz3pgyysZqyGJ7JsX9w6YqsiF4xSvKNxerzItcex2zi1KBpLD3YFGk+TvgOGdfBJlaqx5P0qVVMyUuuA9BCn8FH0RYYAnxUGRU8GuyPaADX7JBy+Pd+hp3rAV6YiQX403Yoyv4kzPZBan9BOcWlNQ9QSWoMuMi8fQU069RtBUcmFW6om3OqNpCdv9cbQh1s9UYpC3yWLk/nEwjAfbYEDV4oK9Mh0HsXV1iYdAle1mlSIa0kbNIhd/2lSInTtp0GJyHWYBhVi12AalAT+HsXnM56kZ4vISX6DCqEz7wYdIufBDSrwMSldlEs3kzIx/pRdqlCHKVuJ0BlCiw7hs4MmXU4QRaiHEaaIHKwvh8EgEQ4F76fVlOVj3HRIncbt0G0v3sjRSeIGNOgUNfho1lmJUCJMIfaFdcBTego1OyQkbnJHk29FguswTQlyuZaqIHAcufJl4xffZVPVhL4JosiHqoAXCdy6pSkLwVbogh9dRwzT8px17KVF4CIfTT58EIyRI6ii62juJrlNkdC/UbTs95a4yU1RAZnK4lZLRtuen6pwHLnyD62KTDWoesiUX6weUvUUqodMPYfqIVMLrh5DFOztEDiwt9CM3RoNrEC4MeA3BQegocunHRoEnSjt0oJtKFNDHhBUinRfqnWCx1h3t+6whrZDBzqhJVM+EgprCxywh9beCOHMGIfGlqnRMTwyMREw+WLRhgNNyaspeeQ+eQrQbje+PQKfYRxBzfB5T4Mi0gSjGSIqeO4ZOj0pozGmafKlaUKROMpBVmSq0MlnEnWl0/l1Il9HWtikaSlXHiFqQBh6fhrRAP1LTEVJhZYsk0oXAnljhy5u4ZNgGxoogmP5QRoWZ0RVQmy286MY1e7seSGjdc8MdPRaDCfbdANyO0pwCG4sWqoQo2SdEh4/cAZvYZFL1hZ5I9vwyEZlBUO3RfXbJQUiB7Ylwbg85g2QBAW2H6PS/QgEDTtLwrF3pek7ImcWJQXIhVNmweGM98QuWLxB9vbGFjpudPEtKJqLr1TJYv0J6rvTFoogR42V8LalrmL4Hl2XcFxRt2lAuMp1SGIUZn151WAi86SgopmTBIXZZg9Ua4bAQgvNhiO2tNUU4WY1i+pmDlsgOugKa12lSLlZdwar5BpFg93AqQ7Y+6FY8KUuTYjgeBcCw0J3g6ajZ+yjlzixnb4A7GuApEfRUHNXbPqY61mjBJpZBQjl7p2aZfUcDDQL5OuFynKyAXJm/X75lxW4JuuzCiWbx+vIysYy6b48iK01M7tmITb83w/Q7j8IkgVFDZUUwXrF4W7WJIVv3Nck5YW9CDWISDgcznJPARCjQqK76aVnhc5YoKge1ZdBqOUJFccdj5NBpnCBPdqbJql5y3MY1fG2FDWR+ahHoCh9bUS2qZsgjCF5dEcBHGkcLocRqaLHkIlZOGyy0e2hHZJDEKXXSWoFvpFm7NHumw3Q7aKH53MciLrr5EG3yACOUZBZH8ELFvkIOmYPLSJRVOqNDRwL9kRYWC9BvychgHaDQxsXX1DXX5RpoJ/9k2MLCRBBbNtHAipjIBwEIhUxBARqefC2F4cAP97h5ssCcMYYu8Th6fn7Nx+yaoD+ierd4fBH9iQu/MQh03UzwsNoZe6pzRuBJf752u6qVcaOC7zpmMm4g2PzTzCx9T/27GvPzIUWlkqYYhv9jyH7GvLVF8nD1d9wlGDm8VdDlVrRxCTpR7fu349mR8urm7vrq8XV6ld9ufp2cXWr313cLI8+Hv34J2iCh4fvkLMSVPXTw9HJ/M3DEXwC0HXSsGbBR99Wn4/fPxz9CeqESjOd8BMPTr1/onFdpFlQpoqEwrQB7G1flib8GyYlso6waPgB/P8fN75jgfAgP83Q0jfkSzjSPHx3uAxFRwBQLwxfZiAAzJfUwughvuYePcGFLTVnq2wyF8v89p8MJ0nnJsI01GN7iQTfcAmJFBVx6DtChZNr7Ra5w44w0fguznTHzwLrZFtwCuqj40ctLbzFR3YaL/POiHfwZxLayFxxYtn+R1J/NVLEU1l5vca/vpNTR1fARf4cQFQtzdrg7mqK7ReiZ/rSX8wdC+vMG9ODoevWZ6pEi3zWmuWiGNHpufRUMpypxYbjb0UrSC8SLOwFyRNuihWeX5iayhdu+pp8Wfjx9bc2XsYz+9Po2w7klWi0hqB1ete7MaBPmaltQ62zJ7WX8nVDmnQ3qfH7hlTp8K4jVWPaDyfPTEkbBLhmwpG80VZhF2t2WTs76CmryUZoAD5AYIPY/DIPAcLbVKBbQoSpIIpKzU7jFSQPpHlA33/Udr4L8HWAiebiiQC63TPa6ZFjkgelywLTTVW8hA6rHstphQHXpdQbV4EWKl0Io6BVSvhEWYLSd0wtqNJdVi6GmThjqnCG5wOlnlau2ZmYMgWRFNa1y4sU4F3DNIS5gCpS7z08Mf1eLTfy69omzIU8Ei/BIrzcla9BnJhqGYxwruVzdBNzLYMRzrUQYWViogUkUlrN8lWQClTWMiA5nLMbKlVgm0GRPg5Qg24FkRTWtWsxFeBdwySceem62IkZl7DIYKpMg1XCIoPpIYzp9EwPWGS1VkrV2RIe4Yyrt9VOTLgKRzzf1PNelSaqCkcS3+yWYyXIZlgmm4EOS8y8zz5ApqhF4FrT1nzr7kQlg/VS4MmXK6jzlcpdzJPasAHTIMMxFyAVyDdD62eDnsWmb7La9lwaC0nYTlXhYjyxjRW+5lTGntXFcLCt8q/SrWW521UpicJ1rA9j1xMSVKvH7eRSt6mItvQC9ldglhToGDbJ7mlX3yYZ0JFsQq6RfxV2IWDHsk120/3rsE0GdgzbfMYhjV+FZXKoY9gluxBbfatkQMewSXaXt/o2yYCOYZOv518vXodRCNIxrJJdna6+UTKgo9jk7rXY5G40m+Q3tKtvlRzqOHb59Fqs8mlEm7ySlpYgHckqr2QyRJD+O7o0ynD5ErByTi041OMsCpSdbK2yDk+81xDtVJxaFijDU2t5X9E1O6HLcxXKl0otrVwKWDupEPyi1Oj0i4AhaIWgUvN5AXP2Cj2lpuYCpt8Venc//6pfn399/+7s9FwdnlVUAgkrNYEWMEmu0lOptRHf2Hy7uFGomBI0IgmqNW8XMjevUVRoCi5gmk0rolM4tjQX0aF+LLQiqg5DAmdUbwtimcrU8nBRqVhfB2mnlIpXdE+Wnx1Xh0txti3dhq0a8xyYHD/jw83vKhEvwJKW49lN8SrRLsCSR3saB/ou1vJc6XEl2iTRNJ7WXbWbAJNGfWO7KhLPYEmjvQ2yC85VI54Dk0a9fPGxavzL6OQZYa9ksc9gSaP9W3Y7tGq8CS5pxEP1BjEFWNJox8baAfqUJ7Q7DFADKNkU050hYzKEvDNluR5yA6dyBiDApFFPFO3yE9k9PlKg70MjCNTM+io+eYbIrwFX0QpFcP8mJw/R1e7BDoSGkzHue1ioQb6UU4im45uPehJYWVD/yQpK3Xr4GGIVn5y4H+E0caE6uBegSaGdLqcpSjwHJ4U67oCnCcjHwP2ATgp53AcrSp1gk0Y873sVNkARoxxDREZ6aYuSFiDgJvdCG2O3qdTBTTlSo+QIGrFV8UnrgBXkXoAmsQNWlLi8zTYjedZDsAEh8EygP/lOPGXcgg5TtIKVUioMS9nKkEGTFHBw2tXatjbAlLdgixAaabB6VdmXEMoxwrQbsW3k5W3GmhMfhmhlLc/DxDKUbd4yaHL6+sm33dv6eqlb78DboXtIrMn339ssUMEoxRAK85dJe3r/gxbicn0QtlPvQbcxl7kPbZ8q28pn0CTRVrZPz6DJoa3s4NWWN2j1A8OdJoonA+8cnBxX2Yk9ilqIy/Qq+g0o25hn0OTQVrgTk+pMhYSj25JiZRfpygjl+BJM7E3Wwl6qR5nKg9ZQ6qA1smx/2hBtLdRzcJKou0DZri0HJ4e6ulsRkcRTP5Frq1vWM2xyiKvbqcvs0yOVeUsl/hKFsbKT8gM6ieT1HTAs5FmjtBGKKGU6PylqhAM6ec5PilKX6hytjGN0hwGkO0en/kWqWoCAk0L9ybBUJZ5Bk0J7n4TTnoNp4U2wib9oyJnykrAO5iVwMqhPeBNcN3WJV8NB6dmtTmd6oGQfX0f4b3L+AxZnZBCxhz68J/etjMtcxBwmaS+CaTHXNyiMvm578WZSj+MsezRk0fTK9VacwqLGNhgHwdB3sG5gtYpapg5SQIMlLIyuHP9sarZhQ1hgYyRqOKuWsgy1qg0AZZfietVRyirtOJUoyyp1YPiuTwc8AeeVhOla+9POZwoWywf0GSY5vpORAmfaaaSLwOR4mARuohxrAkqOj4XjKEc4wySHr4IZLDV/1QhNRKUtPy5REPomiCIfqgFeNPHhB6oNKADlOBqA7eR7cTQDFHBJ4h1DbPbEizR05gVkcrhPvBFHZS1x+w0qC1St6BVs0nbcdLQepuB4tYJNzpaLErFoaOyFBaJp5L7fW9MuwdNoE1CqHbGXEuMmH6pPushWyAUS6YCAkjZ/UI1whkn2eFo52iVo0kYUqtHOMEkfUajGu4JN+ohCOf5lbJJHFKqxLyGTN6JQjTYB9Vo3c8tWLtxXMZmVC6ET+c3KbQ3+BNWx294OgQMi/qiHNUkucP3wpedAsJKVruE4vqmvk81miohvxChaykmrw5Gesw1GBmHo+b1tLHjc3rS/iEFOl2lYfXlLPEekwr06QzfWKmZPuY09V61YG01RcyCjGllUzYJlxQOx6lULQkQ74SD0DPgoNszxh1J5zqcWq/ieUPEJvLArVarjMVtsO3b8oooBKLDE806tjCy8DQ202q3vDM9yJoiM2WKFVpBibXIodWYILLQBYDgTjheaqkQF3L9hL0SpAJN1SVkuZL5EFFhj1kuFrNAKUpJNlOP/agcotukGYmZXmTkCdEHdZE0loqNVkPTMl2Z2kxW+GrsepU5UwdnYobs3QqAnAaz3Vl9f94qZK1JxezJdaapyrD7I4QkpYlThk5U1Nu4TFsD+k6GmAV+6wjbhOK84wDuAEdV+qTG7STkKmdI0eqIbjrOGk0R9E8I3ez+ccjpbOl1CBTZVBYp3ITAs2I2IqkY2Oc2VOLGdSgfjb0nlps/5aS3QpjL+zo9i3TUTYUtDiJ7QqZe9f/5w8k6PfFP3zEBHgKfLS2Ku7HkTuFc5BDd263R1a2P0PjIoe6kQtdfo8BfMAnRYEzZf05WFkr3yTcc6OrFzz8Ax4o0fKsW7AksOYZ0AUJR5CZ+MdcB1ohr1Ei6hlFE/mTetarGuQRNIvNqA+EpVczo6GUU9PbilEPU6sn/DVe7sZo0pglQ0mL5w34eA6BTUmx9iQ49fAjB+XIoOymVkommnk3rVKOeoBNN1z1SjmiISTNNXrhD7Mgpv8AinYFt3/BMMHWSLuARTTiL1aivBJJjq3o4AGmDsjNDCy7wRiJPxY9p3kG9GKdocjuGRUBETBfnoMgUVoQwzWGBje+r11FVsEidCCjGnQJNEfJrwEozUhYSYqE+DUkRqkS6AepXrm/1nS+17WNNtw3u1Paz+edMYTcmD2L0J7gWs0qTgEU0VbSpjQ9pT9jIVvlVQYklPPRMskR06AWwiiXdt8uZMEbJ1UGJJ236MOuZHMOFEqUS4DEgsWXzfjOk7U6/llAjXQYkljS7aUa19rmESTDk24kQZrjkYsSRVKsPCiy6GM/XwNqNYwaLSgUamTzs+6nrdL1pwPR4wiJELke4anrFFx1NZ6A3zE6A7xa6NyDZHOyqRR/Ys0y8eFaECYi9lbSxh34LeKkKxiEYMPxOEMURkGjGA7SwcBKtBlAprIOOJmbEy4Gm8hnqFtR25mMRaqbdXBYZsq/EtWNBtNs74sMluheMpPQeFdFaWNzmfDMJQJnYwwnCPgU4Rx1BOShASxgbrV4JSGcnQXmdaMqwMRIyDG5rXdWRl6xH9hqyDmmdoAms9Sh4caKZR+Yni3uUHSrDTk/AT4S9oH0riByjnhwlp5Pr712Y4ozXHqc0VCgfN/cHLX59sAt9jIbIK/mWcHqGK/GVY859IvlS3AXbCfmHuFGsfa98ILd6Vj9QKEyx4pJc6QMRSZ0NYQ76CFpK7JDK1Ss9+DkhlFvWSgQ6XbWRqe9fQXErmT5OE8s/gNlOpgxgy8twGtj9FztRUDyFhn5oTcShpHkIh2LsTUShpHkIhmqwkRaIKUna78kQsKspV7ZrJNipv74zsMM1mBM6BkU9/Eyvhl2R5twWI+ku+CPyYJiNrvESv0gOclsyV2Y6UTVbcRqUDGdI4pmJHWb9uoSVq2RpLG9ERqZnSEMejBl7yl0eb6QhZEMV1fhL8Kve8qVc/96yYsfes58IYUWFSTqSDZI790m+JmbWJp9yTblk2mm+lgUZl+zxlRiHXoNN0M5XRGg3TjexoFE/pMoWa3p7wR+l9KtB5exzK/BQA8P7N6QjNchl6TW9P+GPsiVaQc25/Nrdd42FmLt19e4XmF9V2LgSRn4QmaF4LrfctB0+arhXUirGNPbrLwoYWKbrjzAPgzs1QwmZCTk4rYta6YXTkSiOrILSfkIPRI3jB4tDfE7BqgMHNCsIKNzZwLDhHwILG5EJTzsfg9yQE+tpwYttFZzHG5tConouFaSCpoyIvq+RDiwvg+IhranugJrVlXNAFrVyY0WYdCEe3dF1tD9RjW7qmlQszko6PzI8Juaq0CTHvxNCPd52O3hX+tmeB5/kudiVcIX5gj4FpZV3cpCkvaI+qRtkC89FHePSz+dn8DcU89aXtLHYYx7Cp15R8wDw09l27fPA8ihPL9j9qyPKEQHUGmafqN5he2zGvyizJkGmqH53S4h8xKKel74XELogCz7EOa8EjuvbajuLKKc1uVJ2y+tkKeInLax+Spp9GI4pAyF0gDqn6zv17lYRh+Q/Hq2E1tDuD1kOqnlodWCi4lZJEfZnWlrWYmLItSPVbr+u9dNle10xGjiTAYIesQbWID0sh1aDyzKn1kGpIeeZVShLJWU1pKHKLm+XVkrc/X8CpYL+t7SvPdBKuWxKqsxxcNtGilF29AIZqY8xPQ4C1TLdWF9F76yYVhe6mrDpI8YEpSOiNJf4drd3GsMr2AlJOPtAiW5NhzNZojSx1fwx4paISdY8ZQiFxbwRukOhG6D696wWhlHriUwr3q9vl6aR1HfZDrFbEYCuFKUveOyv9SI9t87EfhEJi2e4cSzwF7W9sCBVdYmxXLj3spJrq1crJVd1R7nnEPD2jr9ue3fOszlCPrgIA3YP/7M4i4gZfSEkGGjRhqjsb1TB3VkeaAUqBxMrCJm5mbR+OOYHRvBIjtXgR7ezFiqQgZaooYZBrcyZHD2OGAXQXGiJF9dKdW4+5VOeMyQZyQYIw+w9GQ6RMXLlQxwQmqlqpbtzWsJfnNFE+MSyLGOjwjUQ9gtADzkA8ByGqV6+iAZnLdMb54KxeFCEuD4bhOQhRdcQFXCt84h1vMe0yyCgswPQt0J0nmFRxZTBPN3FL5z25bydo55Ba3fFZpg6p6VAC3JyUUirdjiCkrCUD08PHrLNE/c+JI/tsgQdCljEvRXsx8TAUO4OhtaIhyBIO1q5vHCPa9cZwSD4MCS6tvUCQlLLLuWOv+5dzmBiDXdyc4YU4g4MpTKtR0qvbN3VbStQeDeyszWoYsQZzIiuitrGQRCHncIKKoQYgIrh3PCTpsZ+SpeZpBSuK2dtA+a6qyGuW3d2i4HXCW043IQBh7PcMD4DXTrkakaHLkdS8PyzhNtUbZM+Scw7hnS7/kuXJkiCO9p87xObwRXCqIQir1tXwLluQVemqMO7Aow3Y3MD3m8cI3OhycVLya0gHm067hlSPwA9jY+30KRcVSV8WC1GXpZ7f36Bu+7PIS90Q0R6VN7WwRsykQZYagacRmQLvvEAiXcMM/R7FtxNrLvhV3ltxA9wbQ9Tt2DtgBPqZgAKRodIOAlUKn9xgSltMZ9DhFNlpxAyGxucm2QIIFu8ExRMbDqkoaSAoCwQhQH7IVno7Ej5T2OzwxQyxWe5AwOAJHXvZQgsEAmBWpQ0E9xmqQRu+w4EVJQ0E1eo2yAyIx4+wBYwLosjYAn2dbDYtnknMsOryhgIMkvROiPrpxn4Aa/IEANyHRhCAUBC8orSB4EjPMxxYUdJQUKH/D9gICbBWUdJAUL8lIBFgplzMQDgRcIOdgPp4kDMUUIzilOBBoYCMq0obCG6JxN0IwlYRNthueE9ZVPtaEzcQHvKTHo6KSBkKBt0LKCAHD3KkLprQR5O9ZwlFCb0X+0sDqN5QqlJ6w2l1Ke+EweZb3qI+bY1768+T9985L1XX3kBqYvr7W8OaOqBg5Mn7A0jrZn8Eefqp/XPAtv/FPdgR4skG+0Gr1ZdfvlzeD52Xp1L0+9WKPVNS7tqBhpZK0crChvbqWBh7d9CBSsQ440BPFCoibLrlYoHbR9QTv+VVoCCYm0HAfpjZ3ZIHcLD/ZKMDJxreGTNiP9RycVqzStewPZE6D/JalOLdZBQd8R1PYK52xWWZLcoNviuuDlqL5dZdAyt2Ii0EgY/2x0MjfNGM+nVVVd2RdwIFRFx3T/EgKMrvwLEP7Vgmjlx+C461EYEfziSBOAhvQ2Bv0UliSQhy4S0ITFOW+kxym2472FWGXgLV58I7EeBVHakwcg1tWLI4afgKdlloqjra8MShboXrrSwoBfEtKIBp7SQhIKLbtUeGPPWp7Fb9ssplJrldt24m4ZO0DqusoA2JF4d+wBVGkwfGQXoLht2jtZEEgIhu0+4apszKWJLfNl7juqCDA4Bbu4KjujANZPVTmeQ23Y9m9L0s7UR2m/7MEU0WhIL4FhTRzjj9/gdJGA7C2xF8f3IqD0EmvAXB8/dvPkjST0R3aEe37xrSRs4VDa29gzkcQxb3Kn2jR0mAdrLIhwRgbHsvZvgSpMdNM73tyHQRY4Z+4HSGMQX8SMSooi/A7lFHGPoChuV98BHNLeh8W0An1ANbpre1n5gEWFA761LDJWiG0wscy9wneBS0LtELIcuaRfAoaMWiF0KW1QzSjeM4ytPgrCLo7su4LgsXBrSovAMjtrxuRtO0hzUELWgXP1/dLVBK/+78egXF4B99V1eL+UmQL+1fnj+cvNPaNHUAvEGD7f6I8EmWzHAlcR1q7zIm8Hs/fBGJgCa52wbHN4bj+KZgU5Skto2jY1gekyCL7affL0+e4X+SC3h2HZG9x0Xo0/3F2du3789zCvgoeCOutsXkIOAJwNq9Z7FrVXdHUt2kV0D3zULwbLiBA6JaJTvAoqviwdbLLn2QMdpssTO86hl1KbgKilpw3cfxEu/ek8/l5SVdFQ82WTajKWLKS1hJDc+KxqgAZV1c6OQXtYImFmSXHjraP0q7UVLFg0260QqKWHAtYdsM25kxbFZSxYNNus0KijhwXYCNkTi9h4E9AJY09kA6liEL+lpQnkPxKEYvTPdnvmtLuMDV1TBjuoEzB4nZ26SMD984diOq2sa+LxG62RFdpJKsxXdeNPEtaD6lTgK9rFOdBBxkdSsUNO8oSuuY9Fz72201EHhvvU4qTKsIboGwAs/xree8kK8FGYAAoYpvgbPEpWWBLyLvb5L6/LwslRWA0CWCqtwWEAIyo6qfNQNQyX37Ph2G9M+ACKDpamC8OL5haVWZrOoH0G8B0GNZREjdpMttb5FR5LHUea4XBFFrEDgUWgVNCXh2iOHOiHdC1htEiiddkgyZ1WomUgcOfyNUXNO6pWg1+eFrcWJ///13PSsdwEKrUcckcp04HcXa4jnpfQjpLrAEQmVltj+KIs6Fdhy3SA4S2ib7KLokWLjS0EuutJOUje7+YTgs7ktSSbzOdWTpkW8+gqmApFGu85kOtpVrJpoV2ui6iSwkUvori+h+kf64ElUa5WI28bBVcZQTlkAPxHs/RGeD8aq/osUw9F2SoWoBRJHjNHNnBxPhWvtGaJEP1DINybsAhNhf3nB08kgtoGkeqtpO5BU1ixKqCMS9HQI4i4iQe5fnqwjMNt3qbHlyTBs7dPdGCPQk2IaGMr3nwWbqZWPk6J5Sw6McmbFb67YHpW0MdL2BMgBLrQde+nDAUxquYQKEOPiP6Tv45ZgY6NcNj6/dT+8hHt3wh8jzDMo7brXsK6F+b9kwSaWLs/qKarj0p6+4apz//nKyiMScAhhDpgqTWg7+IlosNUDm0JwuXj0zLJs5RmG9ohQMZXq4AKQiCcd+ushDET6U9gz05a/L1SW09e3Xz1df9G/LS315u/jz5WrJKuXyryv96v7/Qgnfvq7wev+T4STozbvvWWV8vj5f/qzfnX+B2q/+32VJytmbDz+wyrn5dHmxul4SNp+vrsuyHh7+12+JH/+fbE3oGE3fjrOVtmOT7LRlH7Eqvb1bXd1A1Prq6uuvi/tf71b6+fKGNfXd/e1frpZXt1/1xc/nX79eXuuXX88/XV9esApYXv3yV72+Ht78/f35Td3Kb57fvHlzBv/35ts1q6QD37t7aIHV1V8umUsNRP0Fgr45OTm5+bL6dM6c7voKgsd0C+hPuJN/ejNMwF/1m8W3LKv0tPh+Ol9eXuiXf71cfFvB/BQhf3F7cwNLRir/5vbiUoxQXDnuzy+ubvVPt+f3Fxi6/hfUBkkRDyWf9hWdifh6flMmn9ZRsqjLV2NzqfeXf6EIPX9zyi3v6+UK5dbd7dfLr7A9/Lq4/nbBXod1fbk6X10tYMLrq69lotgfxoQPbM+xvWqv217NUb5Wq7nJXsGbmorTjcnTTlDrzNXdzTf9/O6KvcW4zoTg+qsjaDd5x9WvdKUtPurz7m6XV3/VL+/vv94OrQO3nz9f355foBLxy+39n1HOLv7M3izytOS5zsymtxzGLGbJ1dfV5f3n88Ulc8t/rl9cXsLBwzX6s9hK9WjHmbP/l6vPVwMqWZrbX7/BIn3xZ3318/0lzKXr28U5LFir23s0+Li7xaZYlsrAKQfEA7rF+er8+vYL7Bovl5doYMQm4361woMwPIIoVjpmEHmsK315uah1RGnDdviI2tBlW5ufS44dW7M6sKR+5vlwIMryYRRb5h/+0Pol25ic4VYhOgImPm7lo9j3ndsgszn6cWXBrw5P54k5R7/MnWF72PQ+ft722dwMklIumXAqBJ6P3bMxlG8qyjfB09lxVF1AlaPa8Y1YN9Z2ucfzN/Gmj37YPz6iBZc25ek32V9LM7SDuKT8P1CkY2DGmpHE/hZ4WvolWqLRl/5i7lg9gKG1GSigAxr5ar5JPBM91COA/45KCOMwqY4CJGCwjNgQqp8jczzD83VTh/VxCua+a8f6JoTVXw98vMo7AQhoAPBsgmCq7If6wzi2R8544ix1YwS4FR6ft6mjiFqWEVrlBvnDhxF0Pz83aP/DH06qI1EJ+vdG6NneNpobjjOB6XP14DkOjSkBBMAyPDTpKnWLhhONCQLtFeIAGtEUMNAXrv07PopR7pzt39nUu8YjQL0mJOLO0ZgsNsItiKv6Gz6rDYmOXfjkJ76B0UAI8S5x1xUQ2TP5yqujsmMXPvkpG5sdWyfVNVE5IKjjMwgFPT+Gz3/iGKvVlBwavk48h0+bWuhjOJ/4ibWZbpGfee+zgUExcZsa7RQQc8stGBKt/z7eeP5x+nQSQA0DGgyr+G68skQaW73a4x3/gp+Maya5aHrZpd4VH/+SPZvINtIQ8dinsXc8vh1cfnktIxMLj02aJ4zHG/Tu+PBuXAONBozHWu1T/OMNeT+Z1UYHyFX/2qfoxxv0wTH+4Dj/YORqORZE+vS64bPmda9hy10DUeEFn9pyzzEc6QIz+gm9neN/joGFrEHo6W/dNYIyqr9m8h6+O74xgp/+4z9vv63uvq30i6v7/9L+4z/v7m//+3KxQhuW/zXHiYUXPDsyKXeRYNHXdhTn4ktD0a2XwMFodb9FO+DhQLnzo1hdmBDUPPWOm9sWgP98e5qCteJ5etjBWie2Y+GF6DlUmA5SCRUU6r/KpSCy9n362RzRnWOPP3SZkiDinSk7qkhneurdMS3fb7JrJ48d4G3j3U/VfSmujEp3dnAmZavuVbtnjnp+UF2E2G8/nLxzT05O3G287jn2a2gXuIttAn/oQQjb8I2OZ8acNv3FmR0fb82GnpQtOZxCoSHycbh/hnK2LvIDFVvVR7KW9KpO2nmWao6/JRXcsTaOsY0mKBuiM7dfA8lht+xrYrl/F7s19tLDa8XQdrx6fklQvy6dmPzqztWvC+3VX3XfXCvrKLSAuxZSJp7hj1zc8d6Od8f1+CaK9AO84kw7NBPHCC0QAM8CnvnSbydLHUYebBSs2uSMfR9qSG8jgMah5+LImh+1bECKf33345+eXQd9CkIU8gV+fDJPHYgBCs9je1v46Nvq8/H7h6M/pQLIgDZ3JErMuetbCaxROMzPfIGPjdyln91BG3/CwPNoMnPscAXTQ0kBCOOXpQn//im91BsPlYumD6AAzHwZg+CPEH7p90iUrDQG3xLEMd7C5OCiyUM1xMQSYSVmBqxvllcvKc1WcGhNcTlE09wMTT077WCGqUZUVmCm5dUAPsoj19CbreIFlOWydTQ7Wl7d3F1fLa5Wv+rL1TfkCX53f3t3eb+6ulwefTz658NRIWrSxwf44AHO6ownAMurbz7+xQhtdBQoQo8/oj/QB+g/2AIENvzKerz2zXTNO3vxkfxjC8xHHx2J08/mZzCbsscz8g90DOc2qKerTSqz5/9K/4ACjrIgk68G8r9gVqTakTtNBC3/t4PpgQUloYyd5QUMnzZC5FpWA+HXfmhvbc9wss+9xHHg06xywAcnM+xtG8PxNvx1fPLDmw8nZ2cn797/6+9H//r/ilhoSQ===END_SIMPLICITY_STUDIO_METADATA
