set(SDK_PATH "/Volumes/Resources/git/gsdk")
set(COPIED_SDK_PATH "gecko_sdk_4.4.1")

add_library(slc_generator OBJECT
    "${SDK_PATH}/../wiseconnect/components/board/silabs/src/rsi_board.c"
    "${SDK_PATH}/../wiseconnect/components/common/src/sl_utility.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/core/chip/src/iPMU_prog/iPMU_dotc/ipmu_apis.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/core/chip/src/iPMU_prog/iPMU_dotc/rsi_system_config_917.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/core/chip/src/rsi_deepsleep_soc.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/core/chip/src/rsi_ps_ram_func.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/core/chip/src/startup_si91x.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/core/chip/src/system_si91x.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/core/config/src/rsi_nvic_priorities_config.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/cmsis_driver/UDMA.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/cmsis_driver/USART.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/clock_update.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_crc.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_egpio.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_timers.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_udma.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_udma_wrapper.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_usart.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/service/nvm3/src/sl_si91x_common_flash_intf.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/service/nvm3/src/sl_si91x_nvm3_hal_flash.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_ipmu.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_pll.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_power_save.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_rtc.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_temp_sensor.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_time_period.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_ulpss_clk.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_wwdt.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/ahb_interface/src/rsi_hal_mcu_m4_ram.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/ahb_interface/src/rsi_hal_mcu_m4_rom.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/ahb_interface/src/sl_platform.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/ahb_interface/src/sl_platform_wireless.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/ahb_interface/src/sl_si91x_bus.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/ahb_interface/src/sl_si91x_timer.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/ahb_interface/src/sli_siwx917_soc.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/errno/src/sl_si91x_errno.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/firmware_upgrade/firmware_upgradation.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/host_mcu/si91x/siwx917_soc_ncp_host.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/icmp/sl_net_ping.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/memory/malloc_buffers.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/sl_net/src/sl_net_rsi_utility.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/sl_net/src/sl_net_si91x_integration_handler.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/sl_net/src/sl_si91x_net_credentials.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/sl_net/src/sl_si91x_net_internal_stack.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/src/sl_rsi_utility.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/src/sl_si91x_callback_framework.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/src/sl_si91x_driver.c"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/threading/sli_si91x_multithreaded.c"
    "${SDK_PATH}/../wiseconnect/components/protocol/wifi/si91x/sl_wifi.c"
    "${SDK_PATH}/../wiseconnect/components/protocol/wifi/src/sl_wifi_callback_framework.c"
    "${SDK_PATH}/../wiseconnect/components/service/network_manager/si91x/sl_net_si91x.c"
    "${SDK_PATH}/../wiseconnect/components/service/network_manager/src/sl_net.c"
    "${SDK_PATH}/../wiseconnect/components/service/network_manager/src/sl_net_basic_certificate_store.c"
    "${SDK_PATH}/../wiseconnect/components/service/network_manager/src/sl_net_basic_credentials.c"
    "${SDK_PATH}/../wiseconnect/components/service/network_manager/src/sl_net_basic_profiles.c"
    "${SDK_PATH}/platform/CMSIS/RTOS2/Source/os_systick.c"
    "${SDK_PATH}/platform/common/src/sl_assert.c"
    "${SDK_PATH}/platform/common/src/sl_slist.c"
    "${SDK_PATH}/platform/common/src/sl_string.c"
    "${SDK_PATH}/platform/common/src/sli_cmsis_os2_ext_task_register.c"
    "${SDK_PATH}/platform/emdrv/nvm3/src/nvm3_default_common_linker.c"
    "${SDK_PATH}/platform/emdrv/nvm3/src/nvm3_lock.c"
    "${SDK_PATH}/platform/emlib/src/em_core.c"
    "${SDK_PATH}/platform/service/device_init/src/sl_device_init_nvic.c"
    "${SDK_PATH}/platform/service/iostream/src/sl_iostream.c"
    "${SDK_PATH}/platform/service/iostream/src/sl_iostream_rtt.c"
    "${SDK_PATH}/platform/service/system/src/sl_system_init.c"
    "${SDK_PATH}/platform/service/system/src/sl_system_kernel.c"
    "${SDK_PATH}/util/third_party/freertos/cmsis/Source/cmsis_os2.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/croutine.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/event_groups.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/list.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/portable/GCC/ARM_CM4F/port.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/portable/MemMang/heap_4.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/queue.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/stream_buffer.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/tasks.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/timers.c"
    "${SDK_PATH}/util/third_party/segger/systemview/SEGGER/SEGGER_RTT.c"
    "../../../../examples/platform/silabs/provision/AttestationKeyMbed.cpp"
    "../../../../examples/platform/silabs/provision/ProvisionCommands.cpp"
    "../../../../examples/platform/silabs/provision/ProvisionEncoder.cpp"
    "../../../../examples/platform/silabs/provision/ProvisionManager.cpp"
    "../../../../examples/platform/silabs/provision/ProvisionStorage.cpp"
    "../../../../examples/platform/silabs/provision/ProvisionStorageDefault.cpp"
    "../../../../examples/platform/silabs/provision/RttStreamChannel.cpp"
    "../../../../examples/platform/silabs/syscalls_stubs.cpp"
    "../../../../src/lib/support/Base64.cpp"
    "../../../../src/lib/support/BytesToHex.cpp"
    "../../../../src/lib/support/CHIPMem-Malloc.cpp"
    "../../../../src/lib/support/CHIPMem.cpp"
    "../../../../src/lib/support/CHIPPlatformMemory.cpp"
    "../../../../src/lib/support/logging/TextOnlyLogging.cpp"
    "../../../../src/platform/silabs/Logging.cpp"
    "../../../../src/platform/silabs/SilabsConfig.cpp"
    "../../../../src/platform/silabs/SiWx917/CHIPCryptoPALTinyCrypt.cpp"
    "../../../../src/setup_payload/Base38Encode.cpp"
    "../../../../third_party/mbedtls/repo/library/aes.c"
    "../../../../third_party/mbedtls/repo/library/asn1parse.c"
    "../../../../third_party/mbedtls/repo/library/asn1write.c"
    "../../../../third_party/mbedtls/repo/library/base64.c"
    "../../../../third_party/mbedtls/repo/library/bignum.c"
    "../../../../third_party/mbedtls/repo/library/ccm.c"
    "../../../../third_party/mbedtls/repo/library/cipher.c"
    "../../../../third_party/mbedtls/repo/library/cipher_wrap.c"
    "../../../../third_party/mbedtls/repo/library/constant_time.c"
    "../../../../third_party/mbedtls/repo/library/ctr_drbg.c"
    "../../../../third_party/mbedtls/repo/library/ecdh.c"
    "../../../../third_party/mbedtls/repo/library/ecdsa.c"
    "../../../../third_party/mbedtls/repo/library/ecp.c"
    "../../../../third_party/mbedtls/repo/library/ecp_curves.c"
    "../../../../third_party/mbedtls/repo/library/entropy.c"
    "../../../../third_party/mbedtls/repo/library/hkdf.c"
    "../../../../third_party/mbedtls/repo/library/hmac_drbg.c"
    "../../../../third_party/mbedtls/repo/library/md.c"
    "../../../../third_party/mbedtls/repo/library/pem.c"
    "../../../../third_party/mbedtls/repo/library/pkcs5.c"
    "../../../../third_party/mbedtls/repo/library/platform.c"
    "../../../../third_party/mbedtls/repo/library/sha256.c"
    "../../../../third_party/mbedtls/repo/library/sha512.c"
    "../../../../third_party/mbedtls/repo/library/x509.c"
    "../../../../third_party/mbedtls/repo/library/x509_create.c"
    "../../../../third_party/silabs/matter_support/matter/mbedtls/tinycrypt/src/ecc.c"
    "../../../../third_party/silabs/matter_support/matter/mbedtls/tinycrypt/src/ecc_dh.c"
    "../../../../third_party/silabs/matter_support/matter/mbedtls/tinycrypt/src/ecc_dsa.c"
    "../../../../third_party/silabs/matter_support/matter/mbedtls/tinycrypt/src/error.c"
    "../../../../third_party/silabs/matter_support/matter/mbedtls/tinycrypt/src/oid.c"
    "../../../../third_party/silabs/matter_support/matter/mbedtls/tinycrypt/src/pk.c"
    "../../../../third_party/silabs/matter_support/matter/mbedtls/tinycrypt/src/pk_wrap.c"
    "../../../../third_party/silabs/matter_support/matter/mbedtls/tinycrypt/src/pkparse.c"
    "../../../../third_party/silabs/matter_support/matter/mbedtls/tinycrypt/src/pkwrite.c"
    "../../../../third_party/silabs/matter_support/matter/mbedtls/tinycrypt/src/platform_util.c"
    "../../../../third_party/silabs/matter_support/matter/mbedtls/tinycrypt/src/x509_crt.c"
    "../../../../third_party/silabs/matter_support/matter/mbedtls/tinycrypt/src/x509write_csr.c"
    "../../../../third_party/silabs/matter_support/matter/si91x/siwx917/BRD4338A/support/src/startup_common_RS1xxxx.c"
    "../../../generator/app.cpp"
    "../../../generator/main.cpp"
    "../../../generator/nvm3_si917.c"
    "../autogen/sl_event_handler.c"
    "../autogen/sl_iostream_handles.c"
)

target_include_directories(slc_generator PUBLIC
   "../config"
   "../autogen"
   "../../../generator"
   "../../../../examples"
   "../../../../examples/platform/silabs"
   "../../../../src"
   "../../../../src/platform/silabs/SiWx917"
   "../../../../src/include"
   "../../../../zzz_generated/app-common"
   "../../../../third_party/nlassert/repo/include"
   "../../../../third_party/nlio/repo/include"
   "../../../../third_party/silabs/matter_support/matter/mbedtls/tinycrypt/inc"
   "../../../../third_party/mbedtls/repo/library"
   "../../../../third_party/mbedtls/repo/include"
   "../../../../src/lib/support"
   "../../../../src/platform/silabs"
   "../../../../third_party/silabs/matter_support/matter/si91x/siwx917/BRD4338A/support/inc"
    "${SDK_PATH}/../wiseconnect/components/service/bsd_socket/inc"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/cmsis_driver/CMSIS/Driver/Include"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/cmsis_driver/config"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/cmsis_driver"
    "${SDK_PATH}/../wiseconnect/components/service/network_manager/inc"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/rom_driver/inc"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/core/chip/inc"
    "${SDK_PATH}/../wiseconnect/components/board/silabs/inc"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/inc"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/core/config"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/service/nvm3/inc"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/errno/inc"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/icmp"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/firmware_upgrade"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/inc"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/sl_net/inc"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/wireless/ahb_interface/inc"
    "${SDK_PATH}/../wiseconnect/components/device/silabs/si91x/mcu/drivers/systemlevel/inc"
    "${SDK_PATH}/../wiseconnect/components/protocol/wifi/inc"
    "${SDK_PATH}/../wiseconnect/resources/certificates"
    "${SDK_PATH}/../wiseconnect/resources/other"
    "${SDK_PATH}/../wiseconnect/components/common/inc"
    "${SDK_PATH}/platform/common/inc"
    "${SDK_PATH}/platform/CMSIS/Core/Include"
    "${SDK_PATH}/platform/CMSIS/RTOS2/Include"
    "${SDK_PATH}/platform/service/device_init/inc"
    "${SDK_PATH}/platform/emdrv/common/inc"
    "${SDK_PATH}/platform/emlib/inc"
    "${SDK_PATH}/util/third_party/freertos/cmsis/Include"
    "${SDK_PATH}/util/third_party/freertos/kernel/include"
    "${SDK_PATH}/util/third_party/freertos/kernel/portable/GCC/ARM_CM4F"
    "${SDK_PATH}/platform/service/iostream/inc"
    "${SDK_PATH}/platform/emdrv/nvm3/inc"
    "${SDK_PATH}/util/third_party/segger/systemview/SEGGER"
    "${SDK_PATH}/platform/service/system/inc"
)

target_compile_definitions(slc_generator PUBLIC
    CHIP_SYSTEM_CONFIG_USE_SOCKETS=1
    EXT_IRQ_COUNT=75
    FLASH_PAGE_SIZE=1
    MBEDTLS_CONFIG_FILE="siwx917-chip-mbedtls-config.h"
    OPTIMIZE_TINYCRYPT_ASM=1
    PROVISION_CHANNEL_ENABLED=1
    SIWX_917=1
    SRAM_SIZE=0x2fc00UL
    TINYCRYPT_PRIMITIVES=1
    SIWG917M111MGTBA=1
    SLI_SI917=1
    SLI_SI917B0=1
    SLI_SI91X_MCU_ENABLE_FLASH_BASED_EXECUTION=1
    SLI_SI91X_MCU_COMMON_FLASH_MODE=1
    SLI_SI91X_MCU_CONFIG_RADIO_BOARD_BASE_VER=1
    SLI_SI91X_MCU_CONFIG_RADIO_BOARD_VER2=1
    SL_BOARD_NAME="BRD4338A"
    SL_BOARD_REV="A02"
    SL_NET_COMPONENT_INCLUDED=1
    __STATIC_INLINE=static inline
    SRAM_BASE=0x0cUL
    SLI_SI91X_MCU_ENABLE_IPMU_APIS=1
    SL_SI91X_SI917_RAM_MEM_CONFIG=1
    SLI_SI91X_OFFLOAD_NETWORK_STACK=1
    SI917=1
    SLI_SI91X_ENABLE_OS=1
    SLI_SI91X_MCU_INTERFACE=1
    TA_DEEP_SLEEP_COMMON_FLASH=1
    SL_WIFI_COMPONENT_INCLUDED=1
    configNUM_SDK_THREAD_LOCAL_STORAGE_POINTERS=2
    SL_COMPONENT_CATALOG_PRESENT=1
    RTT_USE_ASM=0
    SEGGER_RTT_SECTION="SEGGER_RTT"
)

target_link_libraries(slc_generator PUBLIC
    "-Wl,--start-group"
    "gcc"
    "nosys"
    "stdc++"
    "c"
    "m"
   "${SDK_PATH}/platform/emdrv/nvm3/lib/libnvm3_CM4_gcc.a"
    "-Wl,--end-group"
)
target_compile_options(slc_generator PUBLIC
    $<$<COMPILE_LANGUAGE:C>:-mcpu=cortex-m4>
    $<$<COMPILE_LANGUAGE:C>:-mthumb>
    $<$<COMPILE_LANGUAGE:C>:-mfpu=fpv4-sp-d16>
    $<$<COMPILE_LANGUAGE:C>:-mfloat-abi=softfp>
    $<$<COMPILE_LANGUAGE:C>:-Wall>
    $<$<COMPILE_LANGUAGE:C>:-Wextra>
    $<$<COMPILE_LANGUAGE:C>:-Os>
    $<$<COMPILE_LANGUAGE:C>:-fdata-sections>
    $<$<COMPILE_LANGUAGE:C>:-ffunction-sections>
    $<$<COMPILE_LANGUAGE:C>:-fomit-frame-pointer>
    $<$<COMPILE_LANGUAGE:C>:-Wno-unused-parameter>
    $<$<COMPILE_LANGUAGE:C>:--specs=nano.specs>
    $<$<COMPILE_LANGUAGE:C>:-g>
    $<$<COMPILE_LANGUAGE:CXX>:-mcpu=cortex-m4>
    $<$<COMPILE_LANGUAGE:CXX>:-mthumb>
    $<$<COMPILE_LANGUAGE:CXX>:-mfpu=fpv4-sp-d16>
    $<$<COMPILE_LANGUAGE:CXX>:-mfloat-abi=softfp>
    $<$<COMPILE_LANGUAGE:CXX>:-fno-rtti>
    $<$<COMPILE_LANGUAGE:CXX>:-fno-exceptions>
    $<$<COMPILE_LANGUAGE:CXX>:-Wall>
    $<$<COMPILE_LANGUAGE:CXX>:-Wextra>
    $<$<COMPILE_LANGUAGE:CXX>:-Os>
    $<$<COMPILE_LANGUAGE:CXX>:-fdata-sections>
    $<$<COMPILE_LANGUAGE:CXX>:-ffunction-sections>
    $<$<COMPILE_LANGUAGE:CXX>:-fomit-frame-pointer>
    $<$<COMPILE_LANGUAGE:CXX>:-Wno-unused-parameter>
    $<$<COMPILE_LANGUAGE:CXX>:--specs=nano.specs>
    $<$<COMPILE_LANGUAGE:CXX>:-g>
    $<$<COMPILE_LANGUAGE:ASM>:-mcpu=cortex-m4>
    $<$<COMPILE_LANGUAGE:ASM>:-mthumb>
    $<$<COMPILE_LANGUAGE:ASM>:-mfpu=fpv4-sp-d16>
    $<$<COMPILE_LANGUAGE:ASM>:-mfloat-abi=softfp>
    $<$<COMPILE_LANGUAGE:ASM>:-x assembler-with-cpp>
)
set_property(TARGET slc_generator PROPERTY C_STANDARD 99)
set_property(TARGET slc_generator PROPERTY CXX_STANDARD 17)
set_property(TARGET slc_generator PROPERTY CXX_EXTENSIONS OFF)

target_link_options(slc_generator INTERFACE
    -mcpu=cortex-m4
    -mthumb
    -mfpu=fpv4-sp-d16
    -mfloat-abi=softfp
    -T${CMAKE_CURRENT_LIST_DIR}/../autogen/linkerfile_SoC.ld
    --specs=nano.specs
    -Xlinker -Map=$<TARGET_FILE_DIR:generator>/generator.map
    -u _printf_float
    -Wl,--gc-sections
    -Wl,--no-warn-rwx-segments
)

# BEGIN_SIMPLICITY_STUDIO_METADATA=eJztfQlz3DiW5l+pUExszOykkpbtOuyt6g5Zkl2atiytMl3dtaMJBpNEZnLEq3joqI7+74uDYPIASYDEI1UdUzNtO0nifd97uIGHh78f3dxe/8fF2dq8vb5eH70/+vvd0e3F59P15S8XZvnV3dH7u6Pl8u7oH0eLIs3q+uvt2cUKJ/vxz0++980DihM3DH66OzpZvro7+gYFdui4wQ4/+Lr+ePzD3dGf/3QX/BjF4X8jO/0GJwmS937oIA9/sU/T6L1hPD4+LhPXszbJ0g59I0mMVZo5brhEdhgjLBSnjlCcPq9s/DdOl0u7O8Kiv/nmx23oOSj+JrB88tIOg627y9+Rt66H+LvVxadPF7fm7XptnuHPlnssPItd/IZ89d74JfQyHyXGLUrCLLbxv3ZuavhWmqLYiJGHrAQZGP3BJUobSRZFYZwaifvu5HuDARsCDEPEJfHMAKWmg7ZW5qXmg+VlKAFh1Iok5PUxRuh2fb06o4lBCDUhhExu1xfmOXpwbWTixCBMmhBtebUJrdgxWbIstlIsEiqzWqB6maVx6IFz4iBCNpEb5LxBeFTFCxkg33M3Jmk3cHnfZDtIOh1YjNuPBmuaRM2UlaXhDgXidspzg3sUkyfmKjxbeo5O9jmyIQBprYZnoR+FAQpSzS0U59LEaCvtNv/KtK3U8kLNWcsJtSG10UIP5MO9FTgeisEoNVDk6NiT0LHb6bhhksbI8vNvgQpRC5A0KSgziYB6SbmBm+I/ktQK7CkM1sQTUlzasc3bOfxPCFYNiP7G9NFN8FgxCPCg8I2ZOPfmm+XJ8k2pba2NEHlDU3zR+Mahg4LS+8YXbMRa+ULwzbuTp9onjY98O2t8IuAcI8FXze/2biT8rsmNmFb4YeNT9+bqq4mzbdeaQJzECdN2DJaoVLTwRMJMnpMU+Xnu0yGZXBErFQDjkL0Gy0WDZRUtZk8GNrdBrGkQUxnYCkahnlGwNlrJGLLquJGfmVbkyrYr2lWoEGinXalX6q8r7RczGCU5hdZ1vDYlqyRTK06zaEKWdUApmqQARokZ46Z5mwX2FEQFkNJUHYSixMN/mEk4GdkGqJhuZxGut1tBV6tYUxrFcSg72BusLGZkVMCk8mSDe1ozfY6khw6j+FXRpAg6eEw9HcEqmhTB29XJE/5vCnYlKOkKZ9sRmaH40ssQowtgFVGeKJYxGcUca1ALOxHHGqQ01cpoZCqyDVApujgFg5iCZgVMlt50NacCJkvPShIUpxPRO4CpVJtpy2EFUG6YVx4bTsCyjidHknw9YV2p4ymQ9B8macUrYMrDua5XnbtEnd92z5RrVSPAWuKZmBvGbuqiotgCjojzNfp8TNyOP2hwLBh1ZLi5mKD6M7VaQFt0kcyMSVi3Y4vIt2ZD+4vaglXskr1YqTUiP3ETkyWQqwFnV6vLlexq0XmXYMH3l4HtZY54dUuYswyA7BeA9eG5NY2yqQxqBYOhGzlro0FGeoGIpzz98lJ0YExUFbhY//xCFMiZDFDAvDo9ezlKcDZDFLn5+dcXpEjORlWRj56V7F+IGgUXVSUuX7+UIpUzUVXg6uzyhSiQM1FV4Mvpl/MXogGnoqrC6vSl5EHORFmBmxejwM0gBb6uTm/XL0SFgou6Eh9ejAofBirwUqoypzJAhZcyUOJUYHYFVfZbOufhOhyRdJiy5CwodlLqpa3sxqiZttjHUSnbXsAETHKuVeF6Me3I/qJz6F5h9mnarvFTZ/9XYTbtyLVzdFrhNe2AtHPQWeGFZznm59MvP3z/9vXphATrsBJMpx1Odg4Zq7wmrQryNeHr+dWUOcrhZJhNPCztGXrWuE052uwcUTZzE2Qlvj032xfem7k5ITWOp7QW3Ri9xaGvtI6s5F1DhNvePfBA76BCsdlYBpbeEiWJ0C5yw1noFsjyW7iWfe8GQHshHWxLuEq2tWMgD42+ghCruWnQNEBb931U1TbxabnZZgnQznNfieXISny3rj8L2xxXiesucnxrFrYFshLfKHzEk6vEepinQFTh1Zg/zlMqclwlrr8lkTsLWQ6sxDaeoYco4SpxTa2Nh0xQt80e1g0GA/gDOixJsVdzYCrSur70sTfNrDmyEt9srqY5G9Iyk0TmY2xF0UxGrhNQY+9FSUIG1PNQL6MDOpRhy7jRHsWWl7MQu+IMdy6zvdC+N7PIsVIEO1NsqkK9y+oE5D3AY6ATIT2ES9jSXNlEai62Bbo0X9r8AR0xkyB8gJdmTFvAufhycCW2Rcs3J+syCXn2iRWn89Hm6BMey6o0UqD9jUBx0u/UCSi1knMQLmErtpJzsVVb7LKyJzNGWxSjwEbmQ+iloG7APfw72Ujb33LmKys5tsJBNeD5ble5ttWmvATViq0U6lSnDOUKBXnmwEuOXYzVlh1taNeNTqpqi/qONV89y7Hl22T4pdyuNll5ORcFexJqxIFf0+2iXSMhzX5O0qpcJ1iI7mCrvhi9A18i7aKrukzqvp6vjcixFbjO1/bm2PJc5+uDXbW+N4wsH+hwpATZAl1+6xd6u6SDreqWyW9ovqYgx5bnOme7pby9QxKQkEHpfBO5KgX5RWXoTakOysobU7P2vbFy35s4bgh88qqDb4GuwNdH87VmBbo83xnXTRJFF6HEd2csCjm4PNsZG1/VtjeZlawy2+ckTucb5B7gFRmbe2Q5ZHtiXuZlGqr7OnMxP8Cr7evMxVd5W326LfUe1oO21dnOymy0Obo03wfLmY1tji3N9TGLgf1vOshycLnAPB5ooKgeuhV0Wb55eJ+3ZjRP29akAOgSgo3zUA8i3Ppx8OC/kY2w0uUz0mZzFoTM3JJoBqYbpFvYbeFcd4OoxaKgdhLpOIgq1IaINfc4c6mYuVRpsmitB31RdKV3u2sWoRT4zR5T7GtWrEGqVAsD1RxtFotp1egmMihf9TQiNK6chx6QB3DGZhMCd8wl+kUnl4PK78IlU/iXipiWkeUXriM/m54qR5VfBfZkL4vRyDIHlSc5hymVLTnRwQkh12GnJqI4xGSSECdFQQLt7iAkLmAgv6qKdvDrPSLWJWAFsinGk78vSivdErQ8YejFHiFVxSUeLCCarfDWwJVWdUwyNZmj262Byy82TOO/L6Is4bwvmsE/OsBTYhFXjjre2VUp3izt92HnPyVluWsvR1UabUzOMgcd0pFPz7WCrdRWT841Bx3UVk9OtgY+qK2ennQVfEBbPTnlCrRaWz05V46qb/Gv5UXb4/r1ZeRutER0Yqx+Vxjyw/i5JchzybS+5XmhbW6y7RbkeBBnbDBCRhOvaVrZSNYojoNQJo51ez8pXmKiggFtQeVXVwgLyHFxVtrXdCqaMjTtI5+agvTaCI4EEsucXVgMUQTIPchukKI4sPCj1LIBGsrCXEyN2pKxkIBEhKD8Emfa0qau56bPkzEX4MoTZmoTlXfsKmPFW0n10O9kIafMIf/sGDlkWm15kC1rW+mpoU/SsAgKAVwrkyueL8oLcHUUvinpd7JQVGZ64mCtvGv74qtKRcpHJGYUXGUjXIwalFDpNmpw2dKgJswPWaNv3dh/tGJkZhEujC23blS0rKVg19HD5USdYP1Bgd+bPcKEcPkkR3xU5rWNdsRdFZsAQfZQ5a7pgCZTbyYaxjCCEmOXlj1pPKvZ4CGauY3xm8cwBh0tVpwkhMjDS066j5Hl4NZDpvy43Ecm81KXpUQAayCF5gU5owN7uO77MElNX3jJdrOGEXCpEZH7+PTu5Hty8awZ2JFJQABNxHXIn7ehg/TT1n7Dpixbq8WZadikjFRL4jyD1SLuWLigAxqwokSxDtSElxuORZ6VbsN4WsI1XDWmJhc8F+UKAZUZ1yabnHMFWIorabaKKjkx3Qa2BON64Q/nrXuhQolmmcPccmYpFwX0JFPvPCYEyEULLdqWQlHI37PAQhbA3endw1Xmgu8mXzZmnZxrASvJ0387OUcGKckvnD6/Q5V8ju7x4GnnAzgF9LAsA0tyJRedTs6Tg0pyJMCk6d5bsUNnuAlKM4AT8D2s22nI6uFZAff3hfKd7tNBSEGFv4O2bjBDi1sHHzBOmpKyAFuRMZAPsiTnHj/k+iiJIU3Mtudm8fErxi1Dpq7VJcCF2aCxutSmeMuJhyBJrQAiHFadowBQhSdZw6QauqDtTI1sHVWeMfi4rsK0ezgnZkjXc4rqMxXTJqo8YzdMSbt5jyBHURW2VUR5pjSgiB164DORCtsmqjxjEgZl8tagAarAN7XSbDqiBZo8w0mzXinHH92tC9875/xqYNJr6MLHgoeNR80H/Udi6wdhUUr2O0zfCqxd42IpiaVm0R7txkpcW5/jRnF6sMq17HEiRKxnQDtV3JyQd1PxLMPJk7RRnOISZlspnnuluMOeyqoiXAna0PSaNMQVSWbPqd0DBEYJtq9Uw1FXRjREF6miqbtrU6fkxNLZx4moOQE8qRxDho4b6ejNJDiVgWSITcNKiRLt76bhVYWSaXyAGTVpyHTYjQq8SZx81N3d8/ZWdEzJ2ehR+sCJRRzgkjutjr9ymbctFImSeBkm3+Fvv4PkUgB0l0Y8QhwbLbyFx0F0NwMN08g2Bq3zxSqDZ00NRB3+ub81yMZGAGzBzkTR/XSM2TehFTtdI3Y2BRk5UGeBITDSuPENFVFMimIecCKXCzCeOcgflakV3odAGbnczgJVfJlvIGSxBlfHdj5NlL7Oj1zXAWKjhuw+Ju5rG4pIRXQfj+jRh+JREd3HI4HLmEQlX/JAiVBUatL1N5F88a+rlSQDxvGLGXTYqdsvldM3iHQ+n+1AgprjEkitmvBJLRcMM59ts9SoglzVpLyeJ0bqq2IsqZ5Zdwc3lck2TaFzJ6SdV//Oh5CchqlkOyfpySMtvTAkYJpD5s/QOWRsNHV1pbWcDmBEeIvWcgagf07cbAQacTgdxyXDIXaoc/TmSM6bh9kUCTc6+dh+4iZ69sCrXBqCe3joaXBqHNobmcaADyH0w6vXOipylUNDcA8PLYt4NQqt63VtdUkjeEsJ6Gsq6j+r9SzmPEq1rd60HJb+k1oDU9LZeiSRKFzMu7xXsIyQv7QHhcstmBllAkY/jiFBMYrdB7KVcY+eaVLyNwTFFpxOiriixVsXeXjaZ9FEWomJpLfT+T2LkbmxvNT1iXOIdkKt8lsp2RaRoJdGVWY7NM1TAPiG3B4KvDRpZlAS20qArIShWL8NmnJ7KGi3QUNsKwEyiqPuu1rx61Lb9acz7XIjqNkQrfIlKenPmjbxrYT8Zwc93LtpvYvQRqkDoJeUdvsIBPdllbMjErQ36G3SDemJTJjuax4oFfpu4KCn5T71h0TSPZCmKEZVWCvHys/qjyr3HbLvQzNx7s23y7fLk0KL+tJVfj6vY8jVO5uTmB+loe/KOnzvMGmD86rPhQpB3UPejSs7zOtCy6XIzLXC5LXaOa0uXJHIThJuKQl6Ss3USu5JsFo3SaUdYTsI9YrvthAKMtlq3WUVLqYbTOlKjM6i1nK7RXOOqyvX5fIaj5pj+ZAjXYAHQT2AHs5oHXhcTp9+Ciso3fqJVkv613t6V6e664PckpWQOD/R2yNeqgaMplESJFUgxwMeBMkUSA14XI7KGkajuJxdrS5XXf3jGZ5Odm/9XAa2lwmi8VTnW7RQkCUZVz6EVVV9StUgfIwc0mhK7VyPZp+TyJrye8ySHEpCOymkv5MlwBTXDF34VYkS+u/sYYOZVt1zgd3QdFVC+jBwP3JJXiewH2WmFfsP3+tCrgjU4LR2u75evdZWw3CzO0JRyqWWu7nETiOH5K4RW3bXsB+5JE9923NFobqNhQFIbF1XOoZmO2cGZ1Ql6t+Xkjh9wA5LmG7g9vg/ymzWl4SZAf7nIDtxd6+SMN59ieTDbHE3kIaUUpEmlYOjVfka2gU3xCMKZPnjs5JLGpWFXAjPv7LQXtel/FszToeNfPpIcMEwBahQdUzBKajzHbCSUCX7QZDggjUUWxayfHyhZXJorRpVZJicYtBclSrh20U+v0dxgGTvgFCgcZALU3DL2o4pNjn5g0taWaqaDbXTOMjV3+ci34kfunpcwfKiekYhO3RknYeqhqH8yusGhSgNFVlwqafyMYrS9YojFBRe19h/cgF/rAtUCszcoQDFA8cXIk1L8vrB99awyiUCzmVJgeb3h2qEPkjsJ+CFA2cdImwubICLaF+HVrtolIbM8dzgfuCKW4k96VG6pUtaURcPLkzdip676bYi/oBCnF29pYsO1jjKWJwhEAnRj9RVU1u0xd2cLX9Cua4vUZPkTkmKVhdCLndYNSTsaNd1kNKxfpp/NbKprWG2NbTjHMKIl1n7xmS6d2PHjKw4fe4qGNsYoTgNew4o0YUaQdWRWRZpXUVSKGxEVaOkkcFpsyUkvkRSkd1olaRuG2pbCatpwfFVl8P6FOHrU3X5guAUQjp+FIZK3bQyoQJByr4yrTIbYPeVriiMU2vjiXOm8uWnszOZQMynt1ekUf4oE2eUgOspr0xZg2tjYLIGZ2JwGIkoZuRT37Jj2eOSY2kVWCCxy66Qf2XJxF/fIysy38JkRU7COGCMCwkj6uZk2hZ1d5BeHXNko81BpMEBZ3ZGjk2DsCgL7+HhoChGxGHJYdEUqau/0u63NKt2qB6O6IH4uu2wUhEMszpAD5+PWAzZOQDhUhbew0PVL0Kag9hRooGPYRJrh/J790CYNCH6OEUZC4amcuBBkVMDQoLTY2xFEbmcEIpRGaCHD2+QQbiUhffxiMP/xi0BjE3Kwnt4/JahDMYYheQeBgnyoz1MDTqI7uNArgM06TAEJkfqAD18VuTzKzg6Nfm91qG7LIBNXQOhhxFxywIhwgX34ZOQwDBZcxAtPccUDa10DmLLQjuX4ypjCZ0M6oI7Wah6qPWii1zVWhpSnbCFxO49qkrV0YnfkNztGoZrjt5MLyR247L6ohW4EKljRxnt+mNp0s3ABxc99i6DXXz6dHHbN8ljX5m36/UouzDqxoGdwQQbVfl9fRn9eFRb2UNEpkM9MAYkwuUPXb1SWrKtnUApz/GjaGlHkZSevpWmWCMSvNZK6MjxwSWuoAZdVcZT+tgoxBlNKN9yA51YB3kCMLrVQSKLfC9ZrCUAqzIFoJZ0JNgaWrnc+BvkpF6C30Uh2bSJrfjZsMpBX6uYSXCCEyay/Ykycll+C/5j7KaQ+IV8Af4GS/lOdiFOFfwgXITs7shRFyDkQrgA2bahYHPJIkw32ksPGpRhC+GtyHTiDgpfIIg45MEs6AUfUCzqGCIeaWw68Ub2FIcyhZJ4ATqynT0QMhctRk0sOFgmW4gLVd5yyWJM087iB7COpAogYhCkcRjJRvRRhj9IF2Dv750tEDAXLUL1LRuyUlXki8ZFssE0VYF9pwWRRj4BgcwlizDv7eRbKFQuW4SrdgmsMnTjrtfqjHtvvf72OyDsg3Ax8rcnsr4NA5Bz4QLkp29fvQPC5aJbUMlFDhbYSLSGIGy9ZQ+PdGDnUTHZF2aSRWSngCfgxFI3eLbj54gdMslxxYxMHX32MFJmR5+OX+ro1YcSa+/14zjUMMwdwosjC1iFroZOYgCnHFfYns9CKLpv5aNphjCIVNfcIbrXND8fxKxr7h7da5q5D2LWNasv7iMny2rz8KszaO9zZHcQ9BIsg7dwoxY27WSe9qzBQMDy7OfLmzOSIrw5/bzGyemPoauE5XzjjFfuX8nNnEYXUguxKzKYHc6EeiPnhqqIa4G7yZnj78L4WSeySHK7zsdXlueRO+q1ql6RKhqvpricZRF36r9dnTzh/4ALbh56ml3eany4PX/75s0PpwV1eoatlZdoMTSSvV9Zci19L4S54V9fsftlhmYVerL8yMPv6pXmQEcMJcNpkB2GMOqx0dneCuTP443gUwIS8LlN0xXdJOWfweWZGEqGE5SNRECdeYYrmxU4yRQFu4olxQq+KJWQuhhdBOQY5CT1vwIlwwncSCWgLj4r3JbidmIKG1WgZDiB26gEJMHnPD9wOp2pKogKDKcy3Hn9CG6F3SkWT6KX4e//Ih0NWp1UE6aXyxUekQNmYxuYHK9p7MShRGPN54Rcz0EiW2cb/Z2MSLyAxQe2uTzIGvVB9kFWO5Cm8XxZmgjsGWfCOvyZREnVAleR1w2oS8OaxJap0udwt5OP8NiD6TFhRk2wAHqNntLrwHvmX2lSmhMQihfQWNGyfkZvGRtuguZsvSq1D1jrQkFdrgBcg9HruH2GJvXtzQ9ssDPc0Akik9jIevZCyzHqMvtgR6jbAaywGKKljonlivsHEnCFuXoNgta1ApFfV1lhkxOuXPDHmefjFUwZYyKv8oTerIZnFhFOsaH3guDXm9ghiNb7V0vyf6evXn9DHr169frw6A1OTFSpp/XtbGnF/vJx6y+xBjvMzz85OfF36YbEK0jD0LP3lhvU0+F3iXNff2qHRAox1RK/XdJTEEtsBxS/p6Gxl+a7N9+/evfdt+9eHaJk+7gcee8dlNixGxFD/OlHo/mMuUBWDIaf/UjPviA7xf8+WhytLq9uPl+eXa5/NVfrr+eX1+bV9fnXzxero/dH//l3bKnM9VI3uHiivvfJ3dH7//yvBbkNxQ8fkIN/bi0vQYviQ3YUnH5H/YcwdnFo7dDALYp3t+sL85wFWMsz+vDu4DJqkqTVl/SUPzve76BNtsuvfqx+FLmB8DkJny2+L1L8TRqzQ9eVt/Su7Dwox4PlZey0F7EOzouMHJV+f3f0Y27t91dX9OE3T74XJO/zpz/d3d0d7dM0em8Yj4+PvCTgQmEkCRmWk4+WiGhJvvwmNzJNlsYZe+g69HdmLxnukjY+y8zO7V2srS13tk1TRI5fEfGnO1pW6AELMqZMcMEn9ZQBLf83+dMgHxWFh6vzJ2qTnBZWmEj8x2JsubGyNMSsaeE4K275yTOAv2QBUEjrZK7Cs6XnVN6ykNUspWlbqYV7+poAErWbnprYW4HjMUe8rteN1EV0NfZF0hTQ+KJdBg0v6FJfOPvFlaQ18kkHjv6AZak5jVy0TxvFr1iaZidef3j4js8UFuX5zqI5al/UZw6L7s2hRWMMvhBvYCxqezmL9s0W8SsmujJKW4iXlxetK5jCN7UUlQU20Yva95UFedGL2veVxSnRC/H3lRWajvcstXjpWfSCfd8cdNcfsu+Es5JF4XG/KB1kWBTbMIuad/yi5q2+KHuPL8oO3YvCx3pR9nxeNJyRFwLX4EXVTXdR+AUtyv44i4oTzOLgXLsoebwuCi/URd03dFFx1VyUHFcWjVtFFCOLDxKQh8YelLYUUlw1fSk4tmLSSnRrxbTVSOT9iTuiTasmLgWMlk2aByWqxm3uStx2w4ZCmiK+h3ya/BoX+QSi+1cUUg9Iw+82kU9RXKahkKS4D0MlTXzoBuXS9N4WIyGpcQOFfJriUgeFJMW9E9Jpeu/o6JLUHnS0P1UjqKZiknLwT9WkpSBvqknzeJgDkh1iWaom5sEoJdO1xDKUTN0fRFJVEI8C2Z1OEPxPKYF8pgqCIHYlUAz3riqqIwa+jKiuWOJj0vMw4EoyBPHgx6TnodxlZHTGpR4s4BBRWkGEOL74YAGHyOACEcODAuoQ1j5CGxIGUkmMIJrGkPT1WBhDZIgCbo2RU4snM0ZU5yhzUBS4MXLa47aNkVqPuTZGVsdYdESksVHSGjHCxkorx/caI6scn2uUnFJ8rTFyihBZY4QcglyNklILUDVOVi2a0xhhPCLTKBlFTKUhUjomNSNDseqVWERRHSW2Gah0iLgidtGQxI3AQ0OEFNGDBiUuIgDJpJYIT6NBDA+3o0sUY8XPUC9qZ6YX5dguC36geVEPwrIojrEtiiPIC36QbFE5wbUonRdeVE5QLSqnlhbV870LwcGhRfkQ7qJ8LnbRdehgIfYSWzSdAxbkdvfiwug31NRvlifLN0ax7ZYYdP+UewKQQXicuGxTVYMI4d7tAIF4UL6L3HAsLzLFeW1rkBI9+hqkJFo0wrkep6OUItOeQ67bkiJqy6qOQ0eVVm2VUFUOm5iQKuKmz0Nl5PseQzm4CKEfXr02yyM/ZRnRqOQDDZBPYHlq2axkayBFcaCOP76d0T0Mw967EaXF2yBZTnJSyT6XoqnkBDtWaoEIxk1sZeNBo9zKyr9GuexDzXJJk2HbEQxpKhz/ABDLtiP1y42Sqh+TZtkxHkxus8AGkJ4PHEDY0+cwBZCJ9h90F5LSOEpna0caZ/fm6itZVtixfzlhip9FfmZakZtobK/bsBq5bR6GwLpwCYaDUJR4+A8zCW0A+eX6oFc6H3iz3Ncsu1yw9Ihmno68Kc5wt6S3Gh/kk80RXJzcEE9xXKS5rcsdNvPcbYEaazEndok/R774zX7l7gjn7AdfaGc/zbPTL6P1UwfV050q416sf54F1Lw6PZsH+ObnX6cH/ljajJ4Q9vL1DEa+OrucHvTL6Zfz6VFXpzOourqZAfTr6vR2PQfsh1lAZyhLGBWoKZ6gi7kAa84/gRV3sMYRrAHEXZf5+fTLD9+/fX0KgwDWoIHl4tfzq1OYMSKVDMOZNqYwpOHaabC2uHTgrHGmCA6qcbZtPFSEYuqOb3kmf0RWFqzsyYzRFsUowIAPIfXy0zKN6gG2iS+gmUUOOSAEjEVmcJYzfp1KAsa23UlgyIFQdqRqCrR4GtuNX7+WQtFXfztgHGsSm6FtlkxSfxDZ7pwEKNiTw4yOuXX9KfAmgtlFjm9NApREkzRB7utJCrj7epLq6k7SkIaR5Y/fG5AAih4nKdS/oUmK2m8TFWmCw1wsp0CLA/BBFoWZquFJHDfUt47YCeSjSYp3Mk2Pl/juNHabphYlU+FQN6PpkMw9spyDvysoYsWzFhQpm6h1IDjc4XwSvMTS4A8jAfRgyTu5jYB5zOLxW/89OPUDzJBAuavEWzMCLeZkA7ey1KBrZasFi0+XJ4BhM7IJgCpe26BItDGaCKdojKbAo42RLqA49PmaYTHet+x7V+N4UgBBHtnevb7a2oahcbGpDUJfA9eCoHdZpg1E65JMC4jO5ZEWCL1LIy0gUfhIIgpaD+DZonPu3QKhdULcgqFzetoCQU9Gmbq8uKXA9LhQ9kGRDhMaROvAvQND+6C9DcuLkoT0MNqA+Fl6YbAQ3dtcDbBijMu80VnMD9MN0i0MJg8V0IKpa/DRjlmLbqINkLqoeuiBHTzNzwXpm3OJ5DuJ5josAiFe1qAAkefByofmr7/LFsLEoY2SJMRQKEg07qiKwGK007oOJ8ZIcVqV442DUDSuvYnk4wfRFDlCKrpJ5m7AbQpA/yZAeXx09E1uygB8KktbLYi2vThI4Xmw8g+tCiQMqR6Q8svVAxSnVD0gcQ7VAxKFVo8xAI8uCVufJIa135CBFYq3Fv6m5Jcz1o+1B0HTIdI+FGpDSIQiDimI9BDUOtF9avo7f1xD24NBDk5ByidCcW3BA/bYebRiPDOmUbshET0r4BMTDZMvGTQaWwquphTB+uAAyCY0ve+CHlucAGb8vKcFiDfBZIZICp7/lhyYhGiMRUghGBIJvlGNqwIJYfLPALHYdH6TwWOwwgaGUq08WmBQHAchC2JA/qWnojChFcsw6Voob93Ypy18Fu1iiwRtrD5gkXAmhNJis32YpKR2589LGW0GdmSS13p0cm0/4he3RIeYyrqlajFK3inR8YNivBYZuXxtUTWYjYpsUlYodVdXv10B0DmwrQim5bFogAAA3DAlpfseaRp2VoRTp0c79HTOLCoAxLMSsuAohniSF6zfII/u1tU6bvTp5SuGT29yycP7aeq7WQvFmZPGSnvb0oQYv0fXJ5xW1B2LAVe7qUkPYN6X1w2mM09KEO06AQDmmz0Y1o6RQxaaLU9vaWsA0WY1D+Rmj1sgOmDFja5Sp9y8O8NVckMCwG7xVAc9hrFe8pUuTYvgdB8jyyF3m7LRM/XRy7zUZS+Q/Bog71EM0tyVmz7petYqQWRWDUKVe6d2WQMHA+0C1Xqhqpx8gJxbf1j+5QWuzfqyQvnm8SZx8rEM25dHqbOR1q5diIv/9x22+3eaZGFRYyUluF4puJu1SVEb97VJeZYvQi0iMgWHs8JTAKWkkJg+u2ut1BlrFDWg+koIdQKt4pRDcErI1C5wQHvTJrVoeQ6jOtWWoiGyGPVoFGVurMS1TRvFKVaeXEuARxqH+2B0QgwYMkkLx002udi0R3Jc3MVc0jcxrEey++YicvHp4fmSxp7uOxDQLzLCYxRi1nv0TEXeo57ZQ4dIEg9v6yLPwT0RFTZI0O9ZjLDd8NDGp/fiDRdlW+Tn8OTUQhpEcNsOkeA/42HhvZvWs36MrDF8SJlH8SijMBGjSNAhcrlWaBKlgZSzI0/HFFvSztNNRgUBYbqnnYVD7p1Nfe5e9vTtq3d5o0P+SVq5w1Gb/Ela+klj0pt2QictL+bC4qLJXdGff7RLi1+MHXMHW2xFnGKX/OEMebhpG/d8dhHqM35JZTWzefo/mnVfjAnPqCdCLuMGT9g/4MTO/9hzqD3nt+R/HS2OVpdXN58vzy7Xv5qr9dfzy2vz5vxqdfT+6Mc/Y0vc3X1DXMMw1E93RyfLV3dH+Akid4bjlgo/+rr+ePzD3dGfMSYGzTHxJ4Hlo59EtfCMNQ5VVYlQnDbCve3zysZ/46Rc1hEVjT/A///jNvQcFB/ks6am8g3/Eo/rD98dbpsxCQHSC+OXOQmEs4dZmDykd3WSJ7QEMXN2yuYz3/yUxIPlZWwmqA2BX453VvgAaRPdjJ2m0y4tF8iAQKRx6GkVHrllryttYukdqmzb1kGbbDcS40eD1YnyI5fFIr2x0j3+mcUuMVWaOW74njcLBq85TFbRXNBf38BU/TXyiVMO0lX580FHf+1n1++SZ+YqPFt6DsUsmuqDoZvWl6pAZ8XSQ56LekSza8SZZDxvSS0v3OkGYBdAljb04ITbeoUXF90y+dpN35APxZ9eW+zStVh7uBpD24GiEk3WEHTOGgc3BuKZuLBtaIwheO0VfN2Shm0Jtn7fkooNHntStaZ9d/IklbRFgG9nCslbbRX3aS0va+9GA2W12YjMOEcIbBFbXMKiQXgXBLndRRsEB6o0O61Xx9zx5oF8/974JfQyHyXGbbGOtXNTo1TFZE6VjLjJptl+ajRC5a6eeRSvUNClrKAHmFtQrdOrXZ0Db/s64nhT11Wq3zQ0gU51SO1KCS5ngldLAAqiWONWq2lUa8COUU5DBW32QIGevrNh8OKqPlhDF8GQOZz20lO95RJemyqednWqxyLh1aniaVenFBMHXpcSGEgjVb2Sc5qKU8WEUSu/DHQihXI08P5xMo1qoCCKNe4RnUa1Bqx25SpX6MIrVYGDUGbK9qECB6HMIYjqJMoc4KAah6nrTwVS/zSndpsuvE51RP0qsZMAE7YIdUQglfK7lKfSJ4ebbTozLrH0fvIImbpWJRvNTPsVu3CZL3vJ7+zTW+GYuna3MrSZWmBH2Ua6GEykXzv6MDUHZv7QZI2NHRYKSdseR+m6Or2tCr18FGK343w82U75l2xTEnajgylRuiT1DqAq8LBZA64FB93g4Gjs5vOXoTnjMoXa+R3oL0LtnMtEavNb2F+K6pzPVOrnd8G/GPVzPlOoX9xI/yKUL9hMoXp+8fOLUDznMoXa+bXUL0LtnMsUan85/XL+YvTmZKZQPL/L+0XonXOZRO2bF6T2zWRqFxd/vwjFCzbTqP7hBSn+YUK1X07DxslMpPjLGbBzMv+MPlkQXiMa1kuFZUPoVT9N8cjXtpoM9LssiM7eTK5klcHLWredbxlH64pNTauLqefpFxom4jUdPk09MPukYfRV02HqmaOG2WFNg6kngRomejUNbn7+1fx8+uWH79++Pp1UlTqwRp2mnqppmI7VNZi4cuuv21/Pr6YtTxxQpw6TTwK1TPQaWkw7n9MwZxOVJaBd9fayNHYTXVSWJlWCI066D8yVr81TDjco6t2FBfOaL98dDJllPdcWg7jHVW7inUG5AhvG+e9wsfTEupWQwfItv2t6jiIZwzk9H664nkMxOEfUysXac9Q0jg2mXX7Z9gy65chgmhV3fM+gW4ENpl31ptIZVKwSgNPzca7ymSODacZvVJ9BNQ4Npls8S/9dQgbTrHGB/Aw6NjgAawt6bEFKV7hjDAUOv4RuDh05Nph22XxdYQbdExIA8zG2omi2DKxTgNO1fKPzHIqW8f9JjqyQm4ajPYotL9d4qPN6i3yQ4yu2F9r3ZhY5edRjyLLQNBA9v1KnAHPiOQaLMdGjXgkdRDO2iDKfbgU+iHa0SwMLECSh3oEAiH60V5tPOw4PplvRm82rY5kGjK6JxeLEz6Ukx5/db2SKhflKlwE8ghEYnYxk6hTAeq151CuhA/Za8+kGt/VgZU9mjLYoRoGNzIfQS4EPgvZo28kHJG8tZ85Sm6MDhQMCX2nrqo823GIbYWix6K8zKlghAaMn+OZSl35wG0w2vHNup2Jwm9SONWdrkqPD9IFTbAh29YGgm4Io2JM42s4UO4NdStZogOg6r4qQmk2y+dmhG+wG6G6CrbMu5SC3z9zXc7abOTqQZnP2dTk6jGZzjr5cuFFXGFk+WDAsCdUKfBhHM3jXgg7dIN0LfkNzNo85Ooxm87b8oI4TRLhJL0GfWcMDCZiNTHjnkA4FQR1EZh51xaCjrsRxQ/AYKR3aFfhA2vlozv6gwIfRbtZV2wTQXTzx3VkLZQ4Po9usnR1kX5fMrBqobs9JnM45iTsQANTP3CPLIVvsc+tZJgLpyzCfngcCcL4M82kH6iA4pXNgj47gDoLMl2BGJTk+iHYPljOjbjk6iGaPWQzuXd2hGofXH07dA76WoEe5Cj6EdnkA97dmNFfv0CTxT+KUi7Ptof+CUEWhwYMvutB0PFktHr7dpYxdH2JuSWRQ0w3SLbTTWp4DBjEauzevk4q2gF8t+hMa5h4Xfwo7n/JNHhpaFn33RYJ48QlzhhrCQVsrm8xTqpIrpPlr4QBdFpsVYGrFu6m8iBL5kjoTeheOhx6Q9weJXrEJwQe7JaMUQ8EcFsYfKJnmjJ1IrzI2zAZw5GdzKMZxYfZHPW8OnXJYGJXmySbQXJosEIBQM/goAFEcYuJJiGFQkMA7ugrVFHCA2UFEuylW/UU6lqCBVEsxNxc+DqlYuRI4jHrwS/5CxQAX+jFYNGOlq8GDre2bZHFlngFXDR5mWXiqM+MiBbUdGG9V7/HRAV9gFGnGcV/awT2w2xLpWBN63aVkaH5EkuOCjXFn0CmHhR4QzqFZBR2sp51BsxwWvKedQbUaPHhPO4eKVXjgnnYGBSvgcD3tDJpx3D/q1lbVkKVAupCGLAXwUbecssLqCerDlkc3Rh6eYiuPXRqSfOSH8fPgC2grueVbnhfa5ibbboHCmXC9DUbbaCKCZ16LHVEcB6Gue3zHjkrbtmIoSdB8oQjVPcAC9CVE5h67B1GzLNMNYD5VMyiZRhVYf8ibrnFxCFD60isIpkj2BVEcWPhRatkgg5Mic5lRalvmQgoaY/MzUJOOglLXc9PnCXUUIOtXjRmSGHEXW2QZ09xbgePBxGfqULSTh161D2XHjpFDFm8tD7YHbiu7Nfx/wkZfUIwhe4Dc0LkjgwB5ygo0raKdPIDUnkPFP2yv7tp+pGfukJsjIjdKQDZbhLFRAxto+nYFIItQQ4EBZUdX9m/d2H+0YmRmEa6gzlAH1Jola1JpxQctE3U16g8KBloKilA4ZImRU2/GYjR8NN82EGJrObDjn/LA54Cnqy2ZbHjO1NAyJm/1ALU8b4MnMuY2xm8ewxh4VlVxvxZiz1XS032MLAe32rrKu8tPNGRe6jLpCGTHoLBuoYLRgT6Xffdhkpq+nWlbZyDqaZ07uI9P706+N5PQNgM7Mglh0OziFsmft+H/IUef1n7Dlkq21uDDL9BLS6RhJQcgcBaQY0e4EQLN7opJij2hJgG9k6fIs9JtGE+tWg0ZRieTE5hPuQoFiHWjTTaDdhVorVqRbqlo5iZXrIGuUbd6ZQ7nbk1CgJrHCgY7gjBTqSzA/wmXL/MYxD7wrLNq3VLwY3+8W7EwgG5qmelzhEAOF/doVQXXrRmbW86gVQGsWSP/7QzaMFDNmoRzlLYQopRF93iasPNBnIN79ClDa9YqS2apORxWszaEIOl491bs0PW7BKUZSMTRHv3aiejW2LMCfmoX7tR0n7ZCEhCaOmjrBrP0YHV4wPH4tMoJ0IF0AzuvK6mdljO7zdE4YzS5XiXcP+Ta1PBBe/deAOjWYtDYCxhu/tZoEEGSWgHMRR51TQSQurUhu2jUVi5wu11TqY6rV68J5hwVfcZONdr0oKvfRdMynT5NXL16uWFKerN7BDter+hUxdSrDw2hbYfeBDP4ik5NXL16kfDgM7R4DVjNWqVWmk2pToGnV4+JC5v2Mvbobt0pxme5FjW4l3RMRurTno/6Xg8LutcMq4dS4oVg+lZg7ci5Jhn1xm1Sij3VNlbi2jrdhYu4W1UNyx7RQkz5gtSlCG7KydvptCgD6lHBRnGK65htpQi3eXiIN12OiJBHKgVPXpakSkMy1gOky7MYyiDMs6OGBG0YtQmu2CzahkZtpik5Wg8cD4mJO8EUlHOUsWTdSM9IR4JxGWos7ak4ayNMx0dTsa6CjW2qwfnKktQxkGtpsDaJk89fh425RjV42ATORpeZD5qwuK5c9uBSgCW47NwhHMUSwFie32E538EyLSCG1yw8dxp/D3MLy4Pw4fy0LB+18RuwTlTn96ytGa2Tex7XZmbjb4dqYZbJ3/w0x4x3E1qxozrfZUsKM0xzWYhezHjsuJsKKZZGYh78N5f8osfZB6YjC2zFBocAyLnkwVWpkJJvrGexluNQ7WybOGOGTrvIDYHs25A+hqf72oajWRE+hmX06MOxrAgfwzKBzPJEV47nl33BEa3Jf6ldFt/gUe21yPRqnqVZOrHTf2KOG8Ig8vkaWgfWy19XI+Q1W4UvpHHRL7pv78i/kRW+apXy7o8Ya0xDxcTqWgfsYK5r+Y9K0+tX0M56jB9BC3UtC1TtjLUsSdH6B0XxJXdXzMtUeYol2eU0Da3phDmjzXsV6XPkw9bxZBtNwf16juOSYT8LrKXBhSHXm1+fJxIvVdIaTG0/cRNdPn9Vlg3RAxnqarJr7FSbacFkByH0w6vXehq6KruG6IEMNW3I1Mgp7r20twZaaUmXtKFNafuLessRc/at7UezQT5sjPetYdXsaT2S+MIutkh5d30ZIX9pD7zks+BvlGkZ/Ug9hm8lHsXuA3EJuEfPVBz5G4Z4C5Iycdx4xFsXeQ4eqlJBmumK5KuR/D2LkbmxvNT1iRMvAM1WBCWitkWk6iZXlapGiJYUEFINyQOI8ZKrnVdJsBItsseAYgh7NSUPIAZgr4ZgJVpkbkAP7mlmVZerZiu66lZu3rUbrRVhBFGIzG0DUKLpPzvo4d5N6x2lRqIdEIOoAthSIHpIZjs7IhWgC2uT30ZSdZodpvtez9uaym7goKflPvWH3fJ4UJRiG1VxynoJXoge1fXeIfs+NBPn3ny7fLs8EViguYCex6BRGDIPWsMYMatPQ9+tHitN0sxxw/cG1tTgCtQn60WqYXOljZuqQuZJxqwIhMlrUewOCXBR+kFM3JIo9JSaqZXck9sQ3SStnRjrZ9Ura5itUJD5qvbhaYYhWkmCYuUCcUg1dA1mUEkYl/94ChTXY9xKoB5SDUT1cKFQBuWJhmraWCSU0lRu7W/Y6ufgtd7uumZL6shDXPXIGlWL1LiUUo0qz4qoh1RjyrMqKE8Es5LWUuTOrlaXK9X+/CyM5UIyNlJeBraXKcWSrs/HadkkC5JuPWS90MZUP4MQNnJsoyli8HYWE0Vumao7NqmRKUkYzCX9nSywp7jKDiJSTT7SIjtbYszWao089XAOdGWsFohKmkIp8WAGfpSZVuw/fD+IQiX1zI71t+vr1etZ6zruh2StSMnWClOefHBWhomZuvb9MAqlxNDuJis6BR1ubEyV3Djo1m5F6lWV4RrV5C91C37gsV52Ltp0A3fg8ZKxfmMlAmaA/9mfRdwJvZSSDzREwl66M1SDc291FBmgEn2oKmzmZtYN8ZgTWe0rMaDFi6PLFyuegpepsoRRzsy5HDNOJQbQfWy4lJdeugvrSZfqQmPuH1CSoM3+o9lwKTNXLnaT7jxVi2HTtka+PLNExcSwKmKk5zgRdY/iAHkj+RyEvPTqVTagdJnOdT64xJdF6MuDcXwOQl7qiAv5TvygOt6S2mWAKCzIDh3UnydUqfLKYJFu5pYuePDfzHEAGsOSAKNW5knUMGY9koYdyq0lHn6AGAsahD4a1dyhAMUyo1KR7qXE41jsLYn2RMQgTzga3dx6VrIfzOGQfBwTL5SZr4tI8JTgB2TGjCrKFYaHLvbc4F5mpb+kNOnNu0VpyIVBhHhK6Fzw3M3wXMCJKdmzq7d0wdJS0BSnNQTpX24f3m8pXXtZeFBj14NjtZiTWJGUmVKSF3QkgbOSaIeIInQUcUgyYN8pT63SF9WA5XsieHdu4lku75aS7t3YMSMrTp9Vy+k2RihOw4FBDOgas1IjMnbZVpj3h6XutnpD7GmUzGRwvdkyOV/GrQhSaP+Vwz+O3ywQGoJr1blr0GcLvnpfF6YcFLOFmx+FYftITZldIQ4kv8Z0sGx6OqZ6RGGcWhtvSLmoSfp0dqbrFsHT2yvSbX/UeXETUXRA5WUWNriZDKylwekZXKbGOwOISN+y43BA8e3lWgj+Q14KcIX8K0vX5a97ZEXmWw0FImdlHAS+pNC+LaZ09XQGPc6jvUbMaRhq7qQdhHDxzkgEsvGUypJGknJQFCPimu2wO2LoMdd2xzhpiu1yRxJGD+SQwA5bINJAsy5tJLmPGIZsjI8nVpY0klSne6U0IRV/yw4yPkoSa4fMTbbddnhwSdNqyhtLMMrY3QHNc7zDCDbkaSD4GFtRhGJN9MrSRpLjPc94YmVJY0nF4X/jRkiDtcqSRpL6LUOZBjMVYkbSSZAf7TXUx4OcsYRSEoyGDgo1ZFxd2khyKyLuShO3mrDRdqN777ra14a4kfSIP/l4VlzKWDLkXjUNOXiQA7poIh5NDp4llCUMXuyvDKAGU6lLGUyn0/W+l4acD34HPGuNB+MXyYd7GFSq62AiDTHD/dJxTR1RMIrkwwmwujmcQZF+bj8mtBt+qQx1GHlw0eOo1eqLT58ubsfOy5kU83a9ls8UprtxUMNgUoyqsLG9OhUm3x30sNIxzjiop4sVFzbfcrHG7SPhyejqKlAULe0okjzX7Vtpim1HLseyEjrcf3DJ0RyD7o1ZaRgbhUCjHdS33EAv6kFiByzdUSaRLr+XjvomAV2V2gFvKdzQVMMtl19/g5zUS/C7KCT75LEVPxtW8zKmOnoSnGABifzNSsocygg9TB5jN4VlUiB0MNlgad+9BaNxEN/Fwd2R89dgHArxHRxsG45ALrsL3Y32tcGYVgKF+F4OdKUHmEiB0cUmDwVIL7aG41NH6WKUxqYTb3ZwZEoAHTyQ7ezBOHDh3fiJBUmASe9kAFdCc9nd6KadxQ+AXVkVootLkMZhJB/BVZnIQX4Hi/29swWjwIV34fuWDVs1Kwhdozr560ZUKfiN+0bqS9gIrgfLZXeh39vJt3D4XHoXg9xtDY5ECaCDR7K3Xn/7HRiLg/huDt+evIbkkIvv4PD07at3YAy48B58ctmsBTjKrmF09hq2Dhb5PRzsCzPJIrIHxhNwiqkbPNvxc8QO9ObI3dxMPWOKYfRMiTEH/kjPqGMoxf5RSRyHWobwQxhy7A5+oaulcxrALkfu7D1mohY1zhE0mGmbEQ2iJzNXiu61rWoM4iiz4hHda1vvGMRRZi2Ed/A0avlcTOsc+ns4+bu29VItw/ewpNY37WSu9rHBoYPv2c+XN2ckZXhz+nmNxdAfw9dqy7nKua/cvz69O/ne6MLqoXhFhuRjONHTMbnxKgJ7gG9yXfD3Yfysl4NIdr8djq8szwtt7eaoyO0abae4XGYRPx93uzp5wv+BF/X8wir3kRalD7fnb9+8+eG0UIIexm9l1rU4HUXSUW4ld0P2nYA3PNUVuzl6eEaiJ8uPPPyuXuEOxMRgKuwG2mYIN0m7ne2toB4rAIhZCaqD2W2arqh/AP8cMkfFYCrs4OwmgpLKUVxhrcBJpqkKVTQlflMUuRKWDLeLgARbmKgVqYCpsJvAcCUoGWYr3FrjVmcau1XAVNhNYLcSlAKz8zxCxZTmq2AO4DqdMc/F8TtqPE8xDImgjNP9ReG2IXV6TSBpVld4hgGayW1wagynsh0H6xofPyfk6lByf1K2gejSRAAdfD4wp4SBFqpPFg7S+iG1zVDK8rpgn3FWrcOfyW0TmoArEuWg9Wldk9kzNfwc7nb1YPUj0D0mzqiJ7iCxRk/pdeA986+1GYJTEQJ0EFrR+nIWBlt3lFma6xlVubIUNC+q1CV30NCSJXUGstlAau+bH9jwbEw2JIhM7iPr2Qstx6hLlSUwygQdFAYsJmmqqWLJ3T0UiZbHXBgHktC1bkMD+NX4VKjnR0purHSvaY1GLwDvpmGk1iudXhQalEizwLbVX/1AxbF4nYJ///13My8pyCGrecc8+qJOlHLtCTx2qwfbawdRqgrnhhNBKW5d0MhSUFxEDg0ToYHYudYJgFfjmUpJf+8xkljLvc48zOwmccwktO8RIBaLv17M7qjGvp0ZTuySi1DyIFTsV37XwDn7camlZOmgZdNx6PxEYEtDgNLHMCbHpumGxXxFIg59bvnJOZDQeIa9dyM46E1oxQ5Hns3IEYqpA7/lmfzRTMaesXIVRT8PDDsdi0eX9BZJQty9gnAmbNf269O6KWC3buw/WjEys2gXW1O28AfNZ7F34pnB1H1tAW7tN6Yb4GHH1iK3OMzV7rDpsIceWEAFGBI0Ao8devTKbs0w4puOQQDy240hLHSIZy8hv+euzKESmrehjZNUuY5rqKiWq4SGiqvfHjBcTh6/V1GAZIBRbVKroVJ0ixWGkxyb0+ULbcZls8IwYtCZ/rGaHq4VqUmikZLOi8B9d5V1XXP162p9gW19/eXj5Sfz6+rCXF2f/eVivZKVcvG3tXl5+3+xhK9f1nRF9sHyMvLm+29lZXz8fLr62bw5/YTRL//fRUXK21fvvpOVc/Xh4nz9ecW1+Xj5uSrr7u5//ZaF6f/JZ+XHZC5wnK94HNt8VyT/SBb0+mZ9eYVZm+vLL7+e3f56szZPV1eyqW9ur3+5XF1efzHPfj798uXis3nx5fTD54vzCvETWXGry7/+zWyuWbZ/f3t61bT5q6dXr169xf979fWzrKSD9je32B7ry18upMsQZv0Jk746OTm5+rT+cCqd7vMlJk/VHWQsnvzDq3EC/mZenX3NM85khfnD6eri3Lz428XZ1zXOXR3yz66vrnA5YfKvrs8v9AilVeX29Pzy2vxwfXp7Tqmbv5AWCUQ8lvx6qOhcxJfTq6ryrMbyRTa1+ltIvb34RSD09NVrZXlfLtYkt26uv1x8wa3jl7PPX89JjZYTYJqr9en68gwn/Hz5paoo9eew8QM38Nyg3gd3V3OSr/VqbstX8Lam4vXWVmknhHXm8ubqq3l6cynfYnzOhdD6axJqV0U3Nqx0NTohVX2uP378fH16TnL/r9e3fyG5ePYX+SZQpdUuMHP7XSsYrmz+yy/ri9uPp2fS2q5PzfOLCzxs+Ez+LLdIA9ps6az+6+XHyxEVivXsX77i4nv+F3P98+0FzqXP12enuBCtr29Jjt9cU1OsKkXntQLFA7uz0/Xp5+tPuBu8WF2QIZGcjNv1mg6/6NihXMGkSRQxoczVxVmj02GN2OEjYaOWby99rGy67+z6kFL4WRDiIajMh0nq2P/+751fyo3GJW7fETOQ0sevfZSGoXcd5TYnPy4d/NXh6TKzl/wuemr5kD7u+GppPz2ZJK6JY8VOJbOwfRoVRAaf/LL3lht0Eyg+W9pRVgXGkzD0dOy/nQJ8WwPfRg9vj5P6qiUMtBdaqWlt3GrvGm7T7RB8dtVWN3h+HRf7a2XHbpRWwP+FRCQmKzlWloY7FBjsS7L+Y67Cs6XnwBfIbRbY5KGZIPp3UmGYxll9xAHAwbFSSyu+QuYEVhCatonbgzk0D303Nbcxbn7MKKTLuTOQwAZATzaK5sp+jB+nqTtxxnPHmSsror3A9HrbLT3Bu3fw2I9WHLjBLllanjeD6gU8ekpja04CEXKsgEywKt2S5SVTkiC7ZzRQRDIHDfKF7/5Ojw1UO0f3dzl437pHpNfCivhLMiZLrXiH0jp+y2eNIcmxj5/8pDYwGUkh3Wf+pkYifwYPXh8VHfv4yU/52OjYOamvhsKQEI6PMBXy/Bg//0lhrNQAOTR6vXwOn7a1kMd4PvGTbDPZIT/3rpYjQyLHtg3eGSHpEbxmSqL+83gbhMfs6SyEWgYUlFb53XRliTe2Zr3HO/4rfTKtmWDZDLJLsys+/mv+bCbbgDFSsU9r73h8Pbr8qloGkouKTdonbMdb8u748G5aA01GTMVa3VPs4y1/P5vVJieoVP+6p8jHW/LBMf3guPhg4mo5FUXx9Lbls/Z1p3HLTSNZ0QWXxnLLMR7pIjv5ibxd0n9OwYWvAZjst+lbUZXV33J5d98cX1nRT//yr9df1zdf1+b55e2/Gf/yrze31/9xcbYmm5P/tqSJxxS8Bms3sQX3dVCxn90kLUQfekc8usqCLEHOcWSR4tYoab0ievKhN33d9dc4GEHBNPswSf9wtlHTFWu2ZG6VS9dB+J9vXjONnXTJfPadTeZ6Dl3CXu6CbFlqdUjw/rpJSgJrX7OPlsRmS+qESK5KemnW600vvCKm4/ttfrvksYeCXbr/qb6tBp1bZDKkkl/l7/8nx0bnGNtKpLmVb7PUMyD3CQ2j+qrX4+7dyff+ycmJv0s3AycbLR2RcrOV4R9mFONBw9akSzGKNv2rtzg+3tktQze55LgkkTnZcfz4hOXsfOJyrLeZn8ha8C10PrCQap/Jt7yme87Ws3bJDGVDd+YOaykV7JZ/zS33z2K3RgtCTlr7Gy1jnyf8oxB3/Oim++NmCIgXUjdUxdlubGeeFTsoQoGDAvt52HbSy9EowK2i05ghyW8GjamBGtQ41GaFrPnRyDtp+uubH//85HvkUxSTeBj445Ml89hFJIKJG+zwo6/rj8c/3B39mQngnXzhzZPZSz90MlyjaCSUpcPinK1QmtJNtyLGxpK6O+GEWESE4vR5ZeO/f2JXT9NxgwHHKrNv2CcqfMploH7PYz65FzUQ1cgqSzu2zdwF3o4ZIslLbJ0ic/CjIsCEuDKV7/CbIBPP6NGb3GQ3uKJ8oKVvoO0iLIAW31WKoj9h+pXfE6k0RhmWFUeLo9Xl1c3ny7PL9a/mav2VuF7f3F7fXNyuLy9WR++P/n53VAop8/4OP7jDI13rAWFVQ/v+Fyt2yUmchDx+T/4gH5D/cAsQufgr5/5zaLOF5/zFe/6PHbLvQzNx7s23y7fLE/54wf9BTsFcR810jYF2/vwf7A8s4CiPTfiHofwPnBUMnfiUJNjy//lfR//4/7krwd8==END_SIMPLICITY_STUDIO_METADATA
