# Copyright (c) 2024 Project CHIP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Generates a gni file containing all data_model files (XML)
that are used by matter_testing_infrastructure.

These files are to be bundled with whl packages of the matter_testing_infrastructure
so that methods requiring data model files work just by installing the python
package without requiring a full chip SDK checkout.
"""
import os
from pathlib import Path


import jinja2

# Set chip_root to be dynamically based on the script's location
chip_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "../../.."))
data_model_dir = os.path.join(chip_root, "data_model")
credentials_dir = os.path.join(chip_root, "credentials")

# Template for generating the GNI file content with proper indentation
GNI_HEADER = """\
# Copyright (c) 2024-2025 Project CHIP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# This file is generated by
# src/python_testing/matter_testing_infrastructure/generate_data_model_xmls_gni.py
#
# Manually re-generate this file on any changes to the files in this directory.

import("//build_overrides/chip.gni")
"""
DM_PREFIX = "data_model_XMLS"
CREDENTIALS_PREFIX = "credentials"

GNI_TEMPLATE = """\

{{ prefix }}_{{ dir }} = [
{% for name in file_list %}
  "{{ name }}",
{% endfor %}
]

"""


def get_file_names(directory: str, file_globs: list[str]):
    ''' Function to find and collect all .xml files'''
    file_list = []
    globs = []
    for g in file_globs:
        globs += Path(directory).rglob(g)
    for file in globs:
        # Replace absolute path with `${chip_root}` for GNI compatibility
        relative_path = os.path.join("${chip_root}", os.path.relpath(file, chip_root))
        file_list.append(relative_path)
    # Sort files alphabetically
    file_list.sort()
    return file_list


def _generate_gni_file(zip_dir: str, prefix: str, file_extensions: tuple[str], output_filename: str):
    '''Main function to generate the data_model_xmls.gni file'''
    environment = jinja2.Environment(trim_blocks=True, lstrip_blocks=True)
    template = environment.from_string(GNI_TEMPLATE)
    output_content_per_dir = []

    # Step 1: Find all files and create the sorted file list
    if zip_dir == credentials_dir:
        dirs = ["development", "production"]
    else:
        dirs = sorted([d for d in os.listdir(zip_dir) if os.path.isdir(os.path.join(zip_dir, d))])

    for directory in dirs:
        file_list = get_file_names(os.path.join(zip_dir, directory), file_extensions)
        # Step 2: Render the template with the file list
        output_content_per_dir.append(template.render(prefix=prefix, dir=directory.replace('.', '_'), file_list=file_list))

    output_content = GNI_HEADER + "".join(output_content_per_dir)

    # Step 3: Dynamically generate the output file path
    # Get the script's directory (where this script is located)
    script_dir = os.path.dirname(os.path.realpath(__file__))  # Directory of the current script

    # Step 4: Ensure we are in the correct `src/python_testing/` directory
    base_dir = os.path.abspath(os.path.join(script_dir, "../.."))  # Go up two levels to src/python_testing/
    # Now append `matter_testing_infrastructure`
    output_dir = os.path.join(base_dir, "python_testing", "matter_testing_infrastructure")
    output_file = os.path.join(output_dir, output_filename)

    # Step 5: Write the rendered content to the output file
    os.makedirs(output_dir, exist_ok=True)  # Ensure the output directory exists
    with open(output_file, "wt") as f:
        f.write(output_content)
    print(f"{output_file} has been generated successfully.")


def generate_dm_gni_file():
    _generate_gni_file(data_model_dir, DM_PREFIX, ["*.xml"], "data_model_xmls.gni")


def generate_credential_gni_file():
    _generate_gni_file(credentials_dir, CREDENTIALS_PREFIX, [
                       "**/paa-root-certs/**/*.der", "**/paa-root-certs/**/*.pem", "**/cd-certs/**/*.der", "**/cd-certs/**/*.pem"], "credential_files.gni")


# Run the function to generate the .gni file
if __name__ == "__main__":
    generate_dm_gni_file()
    generate_credential_gni_file()
