/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP
// This file is generated from clusters-Commands.ipp.zapt

#include <clusters/ContentLauncher/Commands.h>

#include <app/data-model/Decode.h>
#include <app/data-model/RequiredFieldSet.h>
#include <app/data-model/StructDecodeIterator.h>
#include <app/data-model/WrappedStructEncoder.h>

namespace chip {
namespace app {
namespace Clusters {
namespace ContentLauncher {
namespace Commands {
namespace LaunchContent {

CHIP_ERROR Type::Encode(TLV::TLVWriter & aWriter, TLV::Tag aTag) const
{
    DataModel::WrappedStructEncoder encoder{ aWriter, aTag };
    encoder.Encode(to_underlying(Fields::kSearch), search);
    encoder.Encode(to_underlying(Fields::kAutoPlay), autoPlay);
    encoder.Encode(to_underlying(Fields::kData), data);
    encoder.Encode(to_underlying(Fields::kPlaybackPreferences), playbackPreferences);
    encoder.Encode(to_underlying(Fields::kUseCurrentContext), useCurrentContext);
    encoder.Encode(to_underlying(Fields::kContentAppVendorID), contentAppVendorID);
    encoder.Encode(to_underlying(Fields::kContentAppProductID), contentAppProductID);
    return encoder.Finalize();
}

CHIP_ERROR DecodableType::Decode(TLV::TLVReader & reader)
{
    enum class RequiredFields : uint16_t
    {
        kFieldSearch,
        kFieldAutoPlay,
        kCount,
    };
    DataModel::RequiredFieldSet<to_underlying(RequiredFields::kCount)> __required_fields;
    detail::StructDecodeIterator __iterator(reader);
    while (true)
    {
        uint8_t __context_tag = 0;
        CHIP_ERROR err        = __iterator.Next(__context_tag);
        if (err == CHIP_ERROR_END_OF_TLV)
        {
            return __required_fields.Check();
        }
        ReturnErrorOnFailure(err);

        if (__context_tag == to_underlying(Fields::kSearch))
        {
            err = DataModel::Decode(reader, search, DataModel::DecodeContext::kWrite);
            __required_fields.MarkPresent(to_underlying(RequiredFields::kFieldSearch));
        }
        else if (__context_tag == to_underlying(Fields::kAutoPlay))
        {
            err = DataModel::Decode(reader, autoPlay, DataModel::DecodeContext::kWrite);
            __required_fields.MarkPresent(to_underlying(RequiredFields::kFieldAutoPlay));
        }
        else if (__context_tag == to_underlying(Fields::kData))
        {
            err = DataModel::Decode(reader, data, DataModel::DecodeContext::kWrite);
        }
        else if (__context_tag == to_underlying(Fields::kPlaybackPreferences))
        {
            err = DataModel::Decode(reader, playbackPreferences, DataModel::DecodeContext::kWrite);
        }
        else if (__context_tag == to_underlying(Fields::kUseCurrentContext))
        {
            err = DataModel::Decode(reader, useCurrentContext, DataModel::DecodeContext::kWrite);
        }
        else if (__context_tag == to_underlying(Fields::kContentAppVendorID))
        {
            err = DataModel::Decode(reader, contentAppVendorID, DataModel::DecodeContext::kWrite);
        }
        else if (__context_tag == to_underlying(Fields::kContentAppProductID))
        {
            err = DataModel::Decode(reader, contentAppProductID, DataModel::DecodeContext::kWrite);
        }

        ReturnErrorOnFailure(err);
    }
}
} // namespace LaunchContent
namespace LaunchURL {

CHIP_ERROR Type::Encode(TLV::TLVWriter & aWriter, TLV::Tag aTag) const
{
    DataModel::WrappedStructEncoder encoder{ aWriter, aTag };
    encoder.Encode(to_underlying(Fields::kContentURL), contentURL);
    encoder.Encode(to_underlying(Fields::kDisplayString), displayString);
    encoder.Encode(to_underlying(Fields::kBrandingInformation), brandingInformation);
    encoder.Encode(to_underlying(Fields::kPlaybackPreferences), playbackPreferences);
    encoder.Encode(to_underlying(Fields::kContentType), contentType);
    encoder.Encode(to_underlying(Fields::kContentHeaders), contentHeaders);
    encoder.Encode(to_underlying(Fields::kOffsetMillisecs), offsetMillisecs);
    encoder.Encode(to_underlying(Fields::kQueueType), queueType);
    encoder.Encode(to_underlying(Fields::kNextUrl), nextUrl);
    return encoder.Finalize();
}

CHIP_ERROR DecodableType::Decode(TLV::TLVReader & reader)
{
    enum class RequiredFields : uint16_t
    {
        kFieldContentURL,
        kCount,
    };
    DataModel::RequiredFieldSet<to_underlying(RequiredFields::kCount)> __required_fields;
    detail::StructDecodeIterator __iterator(reader);
    while (true)
    {
        uint8_t __context_tag = 0;
        CHIP_ERROR err        = __iterator.Next(__context_tag);
        if (err == CHIP_ERROR_END_OF_TLV)
        {
            return __required_fields.Check();
        }
        ReturnErrorOnFailure(err);

        if (__context_tag == to_underlying(Fields::kContentURL))
        {
            err = DataModel::Decode(reader, contentURL, DataModel::DecodeContext::kWrite);
            __required_fields.MarkPresent(to_underlying(RequiredFields::kFieldContentURL));
        }
        else if (__context_tag == to_underlying(Fields::kDisplayString))
        {
            err = DataModel::Decode(reader, displayString, DataModel::DecodeContext::kWrite);
        }
        else if (__context_tag == to_underlying(Fields::kBrandingInformation))
        {
            err = DataModel::Decode(reader, brandingInformation, DataModel::DecodeContext::kWrite);
        }
        else if (__context_tag == to_underlying(Fields::kPlaybackPreferences))
        {
            err = DataModel::Decode(reader, playbackPreferences, DataModel::DecodeContext::kWrite);
        }
        else if (__context_tag == to_underlying(Fields::kContentType))
        {
            err = DataModel::Decode(reader, contentType, DataModel::DecodeContext::kWrite);
        }
        else if (__context_tag == to_underlying(Fields::kContentHeaders))
        {
            err = DataModel::Decode(reader, contentHeaders, DataModel::DecodeContext::kWrite);
        }
        else if (__context_tag == to_underlying(Fields::kOffsetMillisecs))
        {
            err = DataModel::Decode(reader, offsetMillisecs, DataModel::DecodeContext::kWrite);
        }
        else if (__context_tag == to_underlying(Fields::kQueueType))
        {
            err = DataModel::Decode(reader, queueType, DataModel::DecodeContext::kWrite);
        }
        else if (__context_tag == to_underlying(Fields::kNextUrl))
        {
            err = DataModel::Decode(reader, nextUrl, DataModel::DecodeContext::kWrite);
        }

        ReturnErrorOnFailure(err);
    }
}
} // namespace LaunchURL
namespace LauncherResponse {

CHIP_ERROR Type::Encode(DataModel::FabricAwareTLVWriter & aWriter, TLV::Tag aTag) const
{
    DataModel::WrappedStructEncoder encoder{ aWriter, aTag };
    encoder.Encode(to_underlying(Fields::kStatus), status);
    encoder.Encode(to_underlying(Fields::kData), data);
    return encoder.Finalize();
}

CHIP_ERROR DecodableType::Decode(TLV::TLVReader & reader)
{
    enum class RequiredFields : uint16_t
    {
        kFieldStatus,
        kCount,
    };
    DataModel::RequiredFieldSet<to_underlying(RequiredFields::kCount)> __required_fields;
    detail::StructDecodeIterator __iterator(reader);
    while (true)
    {
        uint8_t __context_tag = 0;
        CHIP_ERROR err        = __iterator.Next(__context_tag);
        if (err == CHIP_ERROR_END_OF_TLV)
        {
            return __required_fields.Check();
        }
        ReturnErrorOnFailure(err);

        if (__context_tag == to_underlying(Fields::kStatus))
        {
            err = DataModel::Decode(reader, status, DataModel::DecodeContext::kRead);
            __required_fields.MarkPresent(to_underlying(RequiredFields::kFieldStatus));
        }
        else if (__context_tag == to_underlying(Fields::kData))
        {
            err = DataModel::Decode(reader, data, DataModel::DecodeContext::kRead);
        }

        ReturnErrorOnFailure(err);
    }
}
} // namespace LauncherResponse
namespace ContentReplicationRequest {

CHIP_ERROR Type::Encode(TLV::TLVWriter & aWriter, TLV::Tag aTag) const
{
    DataModel::WrappedStructEncoder encoder{ aWriter, aTag };
    return encoder.Finalize();
}

CHIP_ERROR DecodableType::Decode(TLV::TLVReader & reader)
{
    enum class RequiredFields : uint16_t
    {
        kCount,
    };
    DataModel::RequiredFieldSet<to_underlying(RequiredFields::kCount)> __required_fields;
    detail::StructDecodeIterator __iterator(reader);
    while (true)
    {
        uint8_t __context_tag = 0;
        CHIP_ERROR err        = __iterator.Next(__context_tag);
        if (err == CHIP_ERROR_END_OF_TLV)
        {
            return __required_fields.Check();
        }
        ReturnErrorOnFailure(err);

        ReturnErrorOnFailure(err);
    }
}
} // namespace ContentReplicationRequest
namespace ContentReplicationResponse {

CHIP_ERROR Type::Encode(DataModel::FabricAwareTLVWriter & aWriter, TLV::Tag aTag) const
{
    DataModel::WrappedStructEncoder encoder{ aWriter, aTag };
    encoder.Encode(to_underlying(Fields::kStatus), status);
    encoder.Encode(to_underlying(Fields::kReplicationInfo), replicationInfo);
    return encoder.Finalize();
}

CHIP_ERROR DecodableType::Decode(TLV::TLVReader & reader)
{
    enum class RequiredFields : uint16_t
    {
        kFieldStatus,
        kCount,
    };
    DataModel::RequiredFieldSet<to_underlying(RequiredFields::kCount)> __required_fields;
    detail::StructDecodeIterator __iterator(reader);
    while (true)
    {
        uint8_t __context_tag = 0;
        CHIP_ERROR err        = __iterator.Next(__context_tag);
        if (err == CHIP_ERROR_END_OF_TLV)
        {
            return __required_fields.Check();
        }
        ReturnErrorOnFailure(err);

        if (__context_tag == to_underlying(Fields::kStatus))
        {
            err = DataModel::Decode(reader, status, DataModel::DecodeContext::kRead);
            __required_fields.MarkPresent(to_underlying(RequiredFields::kFieldStatus));
        }
        else if (__context_tag == to_underlying(Fields::kReplicationInfo))
        {
            err = DataModel::Decode(reader, replicationInfo, DataModel::DecodeContext::kRead);
        }

        ReturnErrorOnFailure(err);
    }
}
} // namespace ContentReplicationResponse
namespace PlayPreset {

CHIP_ERROR Type::Encode(TLV::TLVWriter & aWriter, TLV::Tag aTag) const
{
    DataModel::WrappedStructEncoder encoder{ aWriter, aTag };
    encoder.Encode(to_underlying(Fields::kPresetID), presetID);
    return encoder.Finalize();
}

CHIP_ERROR DecodableType::Decode(TLV::TLVReader & reader)
{
    enum class RequiredFields : uint16_t
    {
        kFieldPresetID,
        kCount,
    };
    DataModel::RequiredFieldSet<to_underlying(RequiredFields::kCount)> __required_fields;
    detail::StructDecodeIterator __iterator(reader);
    while (true)
    {
        uint8_t __context_tag = 0;
        CHIP_ERROR err        = __iterator.Next(__context_tag);
        if (err == CHIP_ERROR_END_OF_TLV)
        {
            return __required_fields.Check();
        }
        ReturnErrorOnFailure(err);

        if (__context_tag == to_underlying(Fields::kPresetID))
        {
            err = DataModel::Decode(reader, presetID, DataModel::DecodeContext::kWrite);
            __required_fields.MarkPresent(to_underlying(RequiredFields::kFieldPresetID));
        }

        ReturnErrorOnFailure(err);
    }
}
} // namespace PlayPreset
} // namespace Commands
} // namespace ContentLauncher
} // namespace Clusters
} // namespace app
} // namespace chip
