/**
 *
 *    Copyright (c) 2020 Silicon Labs
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */
/***************************************************************************//**
 * @file
 * @brief
 *******************************************************************************
   ******************************************************************************/

#ifdef EMBER_AF_HAS_SECURITY_PROFILE_NONE
{
  EMBER_AF_SECURITY_PROFILE_NONE,
  EMBER_AF_SECURITY_PROFILE_NONE_TC_SECURITY_BITMASK,
  EMBER_AF_SECURITY_PROFILE_NONE_TC_EXTENDED_SECURITY_BITMASK,
  EMBER_AF_SECURITY_PROFILE_NONE_NODE_SECURITY_BITMASK,
  EMBER_AF_SECURITY_PROFILE_NONE_NODE_EXTENDED_SECURITY_BITMASK,
  EMBER_AF_SECURITY_PROFILE_NONE_TC_LINK_KEY_REQUEST_POLICY,
  EMBER_AF_SECURITY_PROFILE_NONE_APP_LINK_KEY_REQUEST_POLICY,
  EMBER_AF_SECURITY_PROFILE_NONE_PRECONFIGURED_KEY,
},
#endif
#ifdef EMBER_AF_HAS_SECURITY_PROFILE_HA
{
  EMBER_AF_SECURITY_PROFILE_HA,
  EMBER_AF_SECURITY_PROFILE_HA_TC_SECURITY_BITMASK,
  EMBER_AF_SECURITY_PROFILE_HA_TC_EXTENDED_SECURITY_BITMASK,
  EMBER_AF_SECURITY_PROFILE_HA_NODE_SECURITY_BITMASK,
  EMBER_AF_SECURITY_PROFILE_HA_NODE_EXTENDED_SECURITY_BITMASK,
  EMBER_AF_SECURITY_PROFILE_HA_TC_LINK_KEY_REQUEST_POLICY,
  EMBER_AF_SECURITY_PROFILE_HA_APP_LINK_KEY_REQUEST_POLICY,
  EMBER_AF_SECURITY_PROFILE_HA_PRECONFIGURED_KEY,
},
#endif
#ifdef EMBER_AF_HAS_SECURITY_PROFILE_HA12
{
  EMBER_AF_SECURITY_PROFILE_HA12,
  EMBER_AF_SECURITY_PROFILE_HA12_TC_SECURITY_BITMASK,
  EMBER_AF_SECURITY_PROFILE_HA12_TC_EXTENDED_SECURITY_BITMASK,
  EMBER_AF_SECURITY_PROFILE_HA12_NODE_SECURITY_BITMASK,
  EMBER_AF_SECURITY_PROFILE_HA12_NODE_EXTENDED_SECURITY_BITMASK,
  EMBER_AF_SECURITY_PROFILE_HA12_TC_LINK_KEY_REQUEST_POLICY,
  EMBER_AF_SECURITY_PROFILE_HA12_APP_LINK_KEY_REQUEST_POLICY,
  EMBER_AF_SECURITY_PROFILE_HA12_PRECONFIGURED_KEY,
},
#endif
#ifdef EMBER_AF_HAS_SECURITY_PROFILE_SE_TEST
{
  EMBER_AF_SECURITY_PROFILE_SE_TEST,
  EMBER_AF_SECURITY_PROFILE_SE_TEST_TC_SECURITY_BITMASK,
  EMBER_AF_SECURITY_PROFILE_SE_TEST_TC_EXTENDED_SECURITY_BITMASK,
  EMBER_AF_SECURITY_PROFILE_SE_TEST_NODE_SECURITY_BITMASK,
  EMBER_AF_SECURITY_PROFILE_SE_TEST_NODE_EXTENDED_SECURITY_BITMASK,
  EMBER_AF_SECURITY_PROFILE_SE_TEST_TC_LINK_KEY_REQUEST_POLICY,
  EMBER_AF_SECURITY_PROFILE_SE_TEST_APP_LINK_KEY_REQUEST_POLICY,
  EMBER_AF_SECURITY_PROFILE_SE_TEST_PRECONFIGURED_KEY,
},
#endif
#ifdef EMBER_AF_HAS_SECURITY_PROFILE_SE_FULL
{
  EMBER_AF_SECURITY_PROFILE_SE_FULL,
  EMBER_AF_SECURITY_PROFILE_SE_FULL_TC_SECURITY_BITMASK,
  EMBER_AF_SECURITY_PROFILE_SE_FULL_TC_EXTENDED_SECURITY_BITMASK,
  EMBER_AF_SECURITY_PROFILE_SE_FULL_NODE_SECURITY_BITMASK,
  EMBER_AF_SECURITY_PROFILE_SE_FULL_NODE_EXTENDED_SECURITY_BITMASK,
  EMBER_AF_SECURITY_PROFILE_SE_FULL_TC_LINK_KEY_REQUEST_POLICY,
  EMBER_AF_SECURITY_PROFILE_SE_FULL_APP_LINK_KEY_REQUEST_POLICY,
  EMBER_AF_SECURITY_PROFILE_SE_FULL_PRECONFIGURED_KEY,
},
#endif
#ifdef EMBER_AF_HAS_SECURITY_PROFILE_Z3
{
  EMBER_AF_SECURITY_PROFILE_Z3,
  EMBER_AF_SECURITY_PROFILE_Z3_TC_SECURITY_BITMASK,
  EMBER_AF_SECURITY_PROFILE_Z3_TC_EXTENDED_SECURITY_BITMASK,
  EMBER_AF_SECURITY_PROFILE_Z3_NODE_SECURITY_BITMASK,
  EMBER_AF_SECURITY_PROFILE_Z3_NODE_EXTENDED_SECURITY_BITMASK,
  EMBER_AF_SECURITY_PROFILE_Z3_TC_LINK_KEY_REQUEST_POLICY,
  EMBER_AF_SECURITY_PROFILE_Z3_APP_LINK_KEY_REQUEST_POLICY,
  EMBER_AF_SECURITY_PROFILE_Z3_PRECONFIGURED_KEY,
},
#endif
#ifdef EMBER_AF_HAS_SECURITY_PROFILE_CUSTOM
{
  EMBER_AF_SECURITY_PROFILE_CUSTOM,
  EMBER_AF_SECURITY_PROFILE_CUSTOM_TC_SECURITY_BITMASK,
  EMBER_AF_SECURITY_PROFILE_CUSTOM_TC_EXTENDED_SECURITY_BITMASK,
  EMBER_AF_SECURITY_PROFILE_CUSTOM_NODE_SECURITY_BITMASK,
  EMBER_AF_SECURITY_PROFILE_CUSTOM_NODE_EXTENDED_SECURITY_BITMASK,
  EMBER_AF_SECURITY_PROFILE_CUSTOM_TC_LINK_KEY_REQUEST_POLICY,
  EMBER_AF_SECURITY_PROFILE_CUSTOM_APP_LINK_KEY_REQUEST_POLICY,
  EMBER_AF_SECURITY_PROFILE_CUSTOM_PRECONFIGURED_KEY,
},
#endif
