/*
 * SPDX-FileCopyrightText: 2020-2021 Project CHIP Authors
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 */
#pragma once

#define _CHIP_JNI_ERROR(e) CHIP_APPLICATION_ERROR((e))

#define CHIP_JNI_ERROR_EXCEPTION_THROWN _CHIP_JNI_ERROR(0)
#define CHIP_JNI_ERROR_TYPE_NOT_FOUND _CHIP_JNI_ERROR(1)
#define CHIP_JNI_ERROR_METHOD_NOT_FOUND _CHIP_JNI_ERROR(2)
#define CHIP_JNI_ERROR_FIELD_NOT_FOUND _CHIP_JNI_ERROR(3)
#define CHIP_JNI_ERROR_NO_ENV _CHIP_JNI_ERROR(4)
#define CHIP_JNI_ERROR_NULL_OBJECT _CHIP_JNI_ERROR(5)
#define CHIP_JNI_ERROR_DEVICE_NOT_FOUND _CHIP_JNI_ERROR(6)
#define CHIP_JNI_ERROR_JAVA_ERROR _CHIP_JNI_ERROR(7)
