/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP
// This file is generated from clusters-Commands.ipp.zapt

#include <clusters/JointFabricAdministrator/Commands.h>

#include <app/data-model/Decode.h>
#include <app/data-model/RequiredFieldSet.h>
#include <app/data-model/StructDecodeIterator.h>
#include <app/data-model/WrappedStructEncoder.h>

namespace chip {
namespace app {
namespace Clusters {
namespace JointFabricAdministrator {
namespace Commands {
namespace ICACCSRRequest {

CHIP_ERROR Type::Encode(TLV::TLVWriter & aWriter, TLV::Tag aTag) const
{
    DataModel::WrappedStructEncoder encoder{ aWriter, aTag };
    return encoder.Finalize();
}

CHIP_ERROR DecodableType::Decode(TLV::TLVReader & reader)
{
    enum class RequiredFields : uint16_t
    {
        kCount,
    };
    DataModel::RequiredFieldSet<to_underlying(RequiredFields::kCount)> __required_fields;
    detail::StructDecodeIterator __iterator(reader);
    while (true)
    {
        uint8_t __context_tag = 0;
        CHIP_ERROR err        = __iterator.Next(__context_tag);
        if (err == CHIP_ERROR_END_OF_TLV)
        {
            return __required_fields.Check();
        }
        ReturnErrorOnFailure(err);

        ReturnErrorOnFailure(err);
    }
}
} // namespace ICACCSRRequest
namespace ICACCSRResponse {

CHIP_ERROR Type::Encode(DataModel::FabricAwareTLVWriter & aWriter, TLV::Tag aTag) const
{
    DataModel::WrappedStructEncoder encoder{ aWriter, aTag };
    encoder.Encode(to_underlying(Fields::kStatusCode), statusCode);
    encoder.Encode(to_underlying(Fields::kIcaccsr), icaccsr);
    return encoder.Finalize();
}

CHIP_ERROR DecodableType::Decode(TLV::TLVReader & reader)
{
    enum class RequiredFields : uint16_t
    {
        kFieldStatusCode,
        kCount,
    };
    DataModel::RequiredFieldSet<to_underlying(RequiredFields::kCount)> __required_fields;
    detail::StructDecodeIterator __iterator(reader);
    while (true)
    {
        uint8_t __context_tag = 0;
        CHIP_ERROR err        = __iterator.Next(__context_tag);
        if (err == CHIP_ERROR_END_OF_TLV)
        {
            return __required_fields.Check();
        }
        ReturnErrorOnFailure(err);

        if (__context_tag == to_underlying(Fields::kStatusCode))
        {
            err = DataModel::Decode(reader, statusCode, DataModel::DecodeContext::kRead);
            __required_fields.MarkPresent(to_underlying(RequiredFields::kFieldStatusCode));
        }
        else if (__context_tag == to_underlying(Fields::kIcaccsr))
        {
            err = DataModel::Decode(reader, icaccsr, DataModel::DecodeContext::kRead);
        }

        ReturnErrorOnFailure(err);
    }
}
} // namespace ICACCSRResponse
namespace AddICAC {

CHIP_ERROR Type::Encode(TLV::TLVWriter & aWriter, TLV::Tag aTag) const
{
    DataModel::WrappedStructEncoder encoder{ aWriter, aTag };
    encoder.Encode(to_underlying(Fields::kICACValue), ICACValue);
    return encoder.Finalize();
}

CHIP_ERROR DecodableType::Decode(TLV::TLVReader & reader)
{
    enum class RequiredFields : uint16_t
    {
        kFieldICACValue,
        kCount,
    };
    DataModel::RequiredFieldSet<to_underlying(RequiredFields::kCount)> __required_fields;
    detail::StructDecodeIterator __iterator(reader);
    while (true)
    {
        uint8_t __context_tag = 0;
        CHIP_ERROR err        = __iterator.Next(__context_tag);
        if (err == CHIP_ERROR_END_OF_TLV)
        {
            return __required_fields.Check();
        }
        ReturnErrorOnFailure(err);

        if (__context_tag == to_underlying(Fields::kICACValue))
        {
            err = DataModel::Decode(reader, ICACValue, DataModel::DecodeContext::kWrite);
            __required_fields.MarkPresent(to_underlying(RequiredFields::kFieldICACValue));
        }

        ReturnErrorOnFailure(err);
    }
}
} // namespace AddICAC
namespace ICACResponse {

CHIP_ERROR Type::Encode(DataModel::FabricAwareTLVWriter & aWriter, TLV::Tag aTag) const
{
    DataModel::WrappedStructEncoder encoder{ aWriter, aTag };
    encoder.Encode(to_underlying(Fields::kStatusCode), statusCode);
    return encoder.Finalize();
}

CHIP_ERROR DecodableType::Decode(TLV::TLVReader & reader)
{
    enum class RequiredFields : uint16_t
    {
        kFieldStatusCode,
        kCount,
    };
    DataModel::RequiredFieldSet<to_underlying(RequiredFields::kCount)> __required_fields;
    detail::StructDecodeIterator __iterator(reader);
    while (true)
    {
        uint8_t __context_tag = 0;
        CHIP_ERROR err        = __iterator.Next(__context_tag);
        if (err == CHIP_ERROR_END_OF_TLV)
        {
            return __required_fields.Check();
        }
        ReturnErrorOnFailure(err);

        if (__context_tag == to_underlying(Fields::kStatusCode))
        {
            err = DataModel::Decode(reader, statusCode, DataModel::DecodeContext::kRead);
            __required_fields.MarkPresent(to_underlying(RequiredFields::kFieldStatusCode));
        }

        ReturnErrorOnFailure(err);
    }
}
} // namespace ICACResponse
namespace OpenJointCommissioningWindow {

CHIP_ERROR Type::Encode(TLV::TLVWriter & aWriter, TLV::Tag aTag) const
{
    DataModel::WrappedStructEncoder encoder{ aWriter, aTag };
    encoder.Encode(to_underlying(Fields::kCommissioningTimeout), commissioningTimeout);
    encoder.Encode(to_underlying(Fields::kPAKEPasscodeVerifier), PAKEPasscodeVerifier);
    encoder.Encode(to_underlying(Fields::kDiscriminator), discriminator);
    encoder.Encode(to_underlying(Fields::kIterations), iterations);
    encoder.Encode(to_underlying(Fields::kSalt), salt);
    return encoder.Finalize();
}

CHIP_ERROR DecodableType::Decode(TLV::TLVReader & reader)
{
    enum class RequiredFields : uint16_t
    {
        kFieldCommissioningTimeout,
        kFieldPAKEPasscodeVerifier,
        kFieldDiscriminator,
        kFieldIterations,
        kFieldSalt,
        kCount,
    };
    DataModel::RequiredFieldSet<to_underlying(RequiredFields::kCount)> __required_fields;
    detail::StructDecodeIterator __iterator(reader);
    while (true)
    {
        uint8_t __context_tag = 0;
        CHIP_ERROR err        = __iterator.Next(__context_tag);
        if (err == CHIP_ERROR_END_OF_TLV)
        {
            return __required_fields.Check();
        }
        ReturnErrorOnFailure(err);

        if (__context_tag == to_underlying(Fields::kCommissioningTimeout))
        {
            err = DataModel::Decode(reader, commissioningTimeout, DataModel::DecodeContext::kWrite);
            __required_fields.MarkPresent(to_underlying(RequiredFields::kFieldCommissioningTimeout));
        }
        else if (__context_tag == to_underlying(Fields::kPAKEPasscodeVerifier))
        {
            err = DataModel::Decode(reader, PAKEPasscodeVerifier, DataModel::DecodeContext::kWrite);
            __required_fields.MarkPresent(to_underlying(RequiredFields::kFieldPAKEPasscodeVerifier));
        }
        else if (__context_tag == to_underlying(Fields::kDiscriminator))
        {
            err = DataModel::Decode(reader, discriminator, DataModel::DecodeContext::kWrite);
            __required_fields.MarkPresent(to_underlying(RequiredFields::kFieldDiscriminator));
        }
        else if (__context_tag == to_underlying(Fields::kIterations))
        {
            err = DataModel::Decode(reader, iterations, DataModel::DecodeContext::kWrite);
            __required_fields.MarkPresent(to_underlying(RequiredFields::kFieldIterations));
        }
        else if (__context_tag == to_underlying(Fields::kSalt))
        {
            err = DataModel::Decode(reader, salt, DataModel::DecodeContext::kWrite);
            __required_fields.MarkPresent(to_underlying(RequiredFields::kFieldSalt));
        }

        ReturnErrorOnFailure(err);
    }
}
} // namespace OpenJointCommissioningWindow
namespace TransferAnchorRequest {

CHIP_ERROR Type::Encode(TLV::TLVWriter & aWriter, TLV::Tag aTag) const
{
    DataModel::WrappedStructEncoder encoder{ aWriter, aTag };
    return encoder.Finalize();
}

CHIP_ERROR DecodableType::Decode(TLV::TLVReader & reader)
{
    enum class RequiredFields : uint16_t
    {
        kCount,
    };
    DataModel::RequiredFieldSet<to_underlying(RequiredFields::kCount)> __required_fields;
    detail::StructDecodeIterator __iterator(reader);
    while (true)
    {
        uint8_t __context_tag = 0;
        CHIP_ERROR err        = __iterator.Next(__context_tag);
        if (err == CHIP_ERROR_END_OF_TLV)
        {
            return __required_fields.Check();
        }
        ReturnErrorOnFailure(err);

        ReturnErrorOnFailure(err);
    }
}
} // namespace TransferAnchorRequest
namespace TransferAnchorResponse {

CHIP_ERROR Type::Encode(DataModel::FabricAwareTLVWriter & aWriter, TLV::Tag aTag) const
{
    DataModel::WrappedStructEncoder encoder{ aWriter, aTag };
    encoder.Encode(to_underlying(Fields::kStatusCode), statusCode);
    return encoder.Finalize();
}

CHIP_ERROR DecodableType::Decode(TLV::TLVReader & reader)
{
    enum class RequiredFields : uint16_t
    {
        kFieldStatusCode,
        kCount,
    };
    DataModel::RequiredFieldSet<to_underlying(RequiredFields::kCount)> __required_fields;
    detail::StructDecodeIterator __iterator(reader);
    while (true)
    {
        uint8_t __context_tag = 0;
        CHIP_ERROR err        = __iterator.Next(__context_tag);
        if (err == CHIP_ERROR_END_OF_TLV)
        {
            return __required_fields.Check();
        }
        ReturnErrorOnFailure(err);

        if (__context_tag == to_underlying(Fields::kStatusCode))
        {
            err = DataModel::Decode(reader, statusCode, DataModel::DecodeContext::kRead);
            __required_fields.MarkPresent(to_underlying(RequiredFields::kFieldStatusCode));
        }

        ReturnErrorOnFailure(err);
    }
}
} // namespace TransferAnchorResponse
namespace TransferAnchorComplete {

CHIP_ERROR Type::Encode(TLV::TLVWriter & aWriter, TLV::Tag aTag) const
{
    DataModel::WrappedStructEncoder encoder{ aWriter, aTag };
    return encoder.Finalize();
}

CHIP_ERROR DecodableType::Decode(TLV::TLVReader & reader)
{
    enum class RequiredFields : uint16_t
    {
        kCount,
    };
    DataModel::RequiredFieldSet<to_underlying(RequiredFields::kCount)> __required_fields;
    detail::StructDecodeIterator __iterator(reader);
    while (true)
    {
        uint8_t __context_tag = 0;
        CHIP_ERROR err        = __iterator.Next(__context_tag);
        if (err == CHIP_ERROR_END_OF_TLV)
        {
            return __required_fields.Check();
        }
        ReturnErrorOnFailure(err);

        ReturnErrorOnFailure(err);
    }
}
} // namespace TransferAnchorComplete
namespace AnnounceJointFabricAdministrator {

CHIP_ERROR Type::Encode(TLV::TLVWriter & aWriter, TLV::Tag aTag) const
{
    DataModel::WrappedStructEncoder encoder{ aWriter, aTag };
    encoder.Encode(to_underlying(Fields::kEndpointID), endpointID);
    return encoder.Finalize();
}

CHIP_ERROR DecodableType::Decode(TLV::TLVReader & reader)
{
    enum class RequiredFields : uint16_t
    {
        kFieldEndpointID,
        kCount,
    };
    DataModel::RequiredFieldSet<to_underlying(RequiredFields::kCount)> __required_fields;
    detail::StructDecodeIterator __iterator(reader);
    while (true)
    {
        uint8_t __context_tag = 0;
        CHIP_ERROR err        = __iterator.Next(__context_tag);
        if (err == CHIP_ERROR_END_OF_TLV)
        {
            return __required_fields.Check();
        }
        ReturnErrorOnFailure(err);

        if (__context_tag == to_underlying(Fields::kEndpointID))
        {
            err = DataModel::Decode(reader, endpointID, DataModel::DecodeContext::kWrite);
            __required_fields.MarkPresent(to_underlying(RequiredFields::kFieldEndpointID));
        }

        ReturnErrorOnFailure(err);
    }
}
} // namespace AnnounceJointFabricAdministrator
} // namespace Commands
} // namespace JointFabricAdministrator
} // namespace Clusters
} // namespace app
} // namespace chip
