# Stage 3: Copy relevant cert bins to a minimal image to reduce size.
FROM ubuntu:24.04
LABEL org.opencontainers.image.source=https://github.com/project-chip/connectedhomeip
ENV TZ=Etc/UTC
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

ARG TARGETPLATFORM
# COMMITHASH defines the target commit to build from. May be passed in using --build-arg.
ARG COMMITHASH=c1ec2d777456924dcaa59b53351b00d73caf378f

# Ensure TARGETPLATFORM is set
# Right now this is only called from a specific github action, so only arm64 is supported.
RUN case ${TARGETPLATFORM} in \
    "linux/arm64") \
    echo "Building for linux/arm64" \
    ;; \
    *) \
    if [ -z "$TARGETPLATFORM" ] ;\
    then \
    echo "TARGETPLATFORM not defined! Please run from buildkit (buildx)." \
    && exit 1 ;\
    else \
    echo "Unsupported platform ${TARGETPLATFORM}." \
    && exit 1 ;\
    fi \
    ;; \
    esac

RUN apt-get update -y \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        avahi-utils \
        ffmpeg \
        gstreamer1.0-plugins-good \
        gstreamer1.0-plugins-ugly \
        iproute2 \
        libavahi-client3 \
        libcairo2 \
        libcurl4 \
        libdbus-1-3 \
        # commands still fail without the dev packages from libevent
        libevent-dev \
        libglib2.0-0t64 \
        libgstreamer1.0-0 \
        libgstreamer-plugins-base1.0-0 \
        libpcsclite1 \
        libssl3t64 \
        pcscd \
        python3 \
        python3-pip \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /root/
RUN echo $COMMITHASH > .sdk-sha-version
COPY --chmod=0755 apps ./apps
COPY --chmod=0755 examples/fabric-admin/scripts/fabric-sync-app.py ./apps/fabric-sync-app
COPY --chmod=0755 src/tools/push_av_server ./apps/push_av_server
COPY --chmod=0755 dist-packages /usr/local/lib/python3.12/dist-packages
COPY --chmod=0755 usr-local-bin /usr/local/bin

# Create symbolic links for now since this allows users to use existing configurations
# for running just `app-name` instead of `apps/app-name`
RUN ln -s apps/* .

# Stage 3.1: Setup the Matter Python environment
COPY --chmod=0755 src/python_testing ./python_testing/scripts/sdk
COPY --chmod=0755 data_model ./python_testing/data_model

# Stage 3.2: Setup the Mock Server
COPY --chmod=0755 integrations/mock_server ./mock_server

# Copy device attestation revocation set and device attestation test vectors
COPY --chmod=0755 credentials/test/revoked-attestation-certificates/dac-provider-test-vectors ./credentials/test/revoked-attestation-certificates/dac-provider-test-vectors
COPY --chmod=0755 credentials/test/revoked-attestation-certificates/revocation-sets ./credentials/test/revoked-attestation-certificates/revocation-sets
