# Copyright (c) 2021 Project CHIP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Build example - NXP

on:
    push:
        branches:
            - master
            - "v*-branch"
    pull_request:
    merge_group:

concurrency:
    group:
        ${{ github.ref }}-${{ github.workflow }}-${{ (github.event_name ==
        'pull_request' && github.event.number) || (github.event_name ==
        'workflow_dispatch' && github.run_number) || github.sha }}
    cancel-in-progress: true

env:
    CHIP_LOG_TIMESTAMPS: false

jobs:
    FreeRTOS:
        name: FREERTOS

        env:
            BUILD_TYPE: gn_FreeRTOS

        runs-on: ubuntu-latest
        if: github.actor != 'restyled-io[bot]'

        container:
            image: ghcr.io/project-chip/chip-build-nxp:200
            volumes:
                - "/:/runner-root-volume"
                - "/tmp/bloat_reports:/tmp/bloat_reports"
        steps:
            - name: Checkout
              uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
            - name: Checkout submodules & Bootstrap
              uses: ./.github/actions/checkout-submodules-and-bootstrap
              with:
                  platform: nxp
                  extra-submodule-parameters: --recursive

            - name: Detect changed paths
              uses: dorny/paths-filter@7b450fff21473bca461d4b92ce414b9d0420d706 # v4
              id: changed_paths
              with:
                  filters: |
                      nxp:
                        - '**/nxp/**'
                        - 'third_party/simw-top-mini/**'

            - name: Set up environment for size reports
              uses: ./.github/actions/setup-size-reports
              if: ${{ !env.ACT }}
              with:
                  gh-context: ${{ toJson(github) }}

            - name: Build MCXW72 examples
              run: |
                  scripts/run_in_build_env.sh "\
                      ./scripts/build/build_examples.py \
                      --target nxp-mcxw72-freertos-contact-sensor-thread-mtd-low-power-frdm-ota-factory \
                      build \
                  "

            - name: clean build
              run: rm -rf ./out

            - name: Build RT1060 thermostat example app
              if:
                  github.event_name == 'push' || steps.changed_paths.outputs.nxp
                  == 'true' || steps.changed_paths.outputs.pigweed == 'true'
              run: |
                  scripts/run_in_build_env.sh "\
                      ./scripts/build/build_examples.py \
                      --target nxp-rt1060-freertos-thermostat-thread-wifi-ota-evkc-iwx12 \
                      build \
                  "

            - name: clean build
              run: rm -rf ./out

            - name: Build RT1170 thermostat example app
              if:
                  github.event_name == 'push' || steps.changed_paths.outputs.nxp
                  == 'true' || steps.changed_paths.outputs.pigweed == 'true'
              run: |
                  scripts/run_in_build_env.sh "\
                      ./scripts/build/build_examples.py \
                      --target nxp-rt1170-freertos-thermostat-thread-wifi-ota-iwx12 \
                      build \
                  "

            - name: clean build
              run: rm -rf ./out

            - name: Build RW61X thermostat OTBR example app
              run: |
                  scripts/run_in_build_env.sh "\
                      ./scripts/build/build_examples.py \
                      --target nxp-rw61x-freertos-thermostat-thread-wifi-ota-factory \
                      --target nxp-rw61x-freertos-thermostat-wifi-se05x-factory \
                      build \
                  "
            - name: clean build
              run: rm -rf ./out
            - name: Build RW61X thermostat ethernet example app
              run: |
                  scripts/run_in_build_env.sh "\
                      ./scripts/build/build_examples.py \
                      --target nxp-rw61x-freertos-thermostat-ethernet-frdm \
                      build \
                  "

            - name: clean build
              run: rm -rf ./out

            - name: Uploading Size Reports
              uses: ./.github/actions/upload-size-reports
              if: ${{ !env.ACT }}
              with:
                  platform-name: NXP-FREERTOS
            - name: Notify Slack on Failure
              if: failure()
              uses: ./.github/actions/notify-slack-failure
              with:
                slack-webhook: ${{ secrets.SWTT_SLACK_WEBHOOK }}
    zephyr:
        name: ZEPHYR

        runs-on: ubuntu-latest
        if: github.actor != 'restyled-io[bot]'

        container:
            image: ghcr.io/project-chip/chip-build-nxp-zephyr:203
            volumes:
                - "/:/runner-root-volume"

        steps:
            - name: Checkout
              uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
            - name: Checkout submodules & Bootstrap
              uses: ./.github/actions/checkout-submodules-and-bootstrap
              with:
                  platform: nxp
            - name: Detect changed paths
              uses: dorny/paths-filter@7b450fff21473bca461d4b92ce414b9d0420d706 # v4
              id: changed_paths
              with:
                  filters: |
                      nxp:
                        - '**/nxp/**'
                        - '**/Zephyr/**'
                        - '**/zephyr/**'
                        - 'third_party/simw-top-mini/**'
                      pigweed:
                        - 'src/pw_backends/**'
                        - 'third_party/pigweed/**'
            - name: Build NXP Zephyr all-clusters example
              if:
                  github.event_name == 'push' || steps.changed_paths.outputs.nxp
                  == 'true' || steps.changed_paths.outputs.pigweed == 'true'
              run: |
                  scripts/run_in_build_env.sh "\
                      ./scripts/build/build_examples.py \
                      --target nxp-rw61x-zephyr-all-clusters \
                      build \
                  "

            - name: clean build
              run: rm -rf ./out

            - name: Build NXP Zephyr thermostat Wi-Fi OTA example
              if:
                  github.event_name == 'push' || steps.changed_paths.outputs.nxp
                  == 'true' || steps.changed_paths.outputs.pigweed == 'true'
              run: |
                  scripts/run_in_build_env.sh "\
                      ./scripts/build/build_examples.py \
                      --target nxp-rw61x-zephyr-thermostat-ota \
                      build \
                  "

            - name: clean build
              run: rm -rf ./out

            - name: Build NXP Zephyr thermostat Thread example
              if:
                  github.event_name == 'push' || steps.changed_paths.outputs.nxp
                  == 'true' || steps.changed_paths.outputs.pigweed == 'true'
              run: |
                  scripts/run_in_build_env.sh "\
                      ./scripts/build/build_examples.py \
                      --target nxp-rw61x-zephyr-thermostat-thread \
                      build \
                  "

            - name: clean build
              run: rm -rf ./out

            - name: Build NXP Zephyr laundry-washer-factory example
              if:
                  github.event_name == 'push' || steps.changed_paths.outputs.nxp
                  == 'true' || steps.changed_paths.outputs.pigweed == 'true'
              run: |
                  scripts/run_in_build_env.sh "\
                      ./scripts/build/build_examples.py \
                      --target nxp-rw61x-zephyr-laundry-washer-factory \
                      build \
                  "

            - name: clean build
              run: rm -rf ./out

            - name: Build NXP Zephyr Unit Tests
              if:
                  github.event_name == 'push' || steps.changed_paths.outputs.nxp
                  == 'true' || steps.changed_paths.outputs.pigweed == 'true'
              run: |
                  scripts/run_in_build_env.sh "\
                      ./scripts/build/build_examples.py \
                      --target nxp-rw61x-zephyr-unit-test \
                      build \
                  "
            - name: Notify Slack on Failure
              if: failure()
              uses: ./.github/actions/notify-slack-failure
              with:
                slack-webhook: ${{ secrets.SWTT_SLACK_WEBHOOK }}
