# Copyright (c) 2022 Project CHIP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Build example - MTK Genio

on:
  push:
    branches: 
      - master
      - 'mtk-*'
  workflow_dispatch:
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}-${{ (github.event_name == 'pull_request' && github.event.number) || (github.event_name == 'workflow_dispatch' && github.run_number) || github.sha }}
  cancel-in-progress: true

# 限制 GITHUB_TOKEN 為最小權限 (least privilege)
permissions:
  contents: read

env:
    CHIP_LOG_TIMESTAMPS: false

jobs:
  build_mt7933:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    
    container:
      image: ghcr.io/project-chip/chip-build:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Fix git safe directory
        run: git config --global --add safe.directory '*'

      - name: Build MT7933 Lighting App
        shell: bash
        run: |
          ./scripts/checkout_submodules.py --platform genio
          source scripts/activate.sh
          ./scripts/examples/gn_build_example.sh examples/lighting-app/genio out/lighting-app

      - name: Upload Bootstrap Logs
        uses: actions/upload-artifact@v5
        if: ${{ always() && !env.ACT }}
        with:
          name: bootstrap-logs-mt7933
          path: |
            .environment/gn_out/.ninja_log
            .environment/pigweed-venv/*.log

      - name: Upload Artifacts
        uses: actions/upload-artifact@v5
        with:
          name: mt7933-lighting-bin
          path: out/lighting-app/*.bin
