name: MediaTek Genio MT7933

on:
  push:
    branches: 
      - master
      - mtk-1.5-filogic
  pull_request:
    branches: 
      - master
      - mtk-1.5-filogic
  workflow_dispatch:

jobs:
  build_mt7933:
    runs-on: ubuntu-latest
    
    container:
      image: ghcr.io/project-chip/chip-build:latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Fix git safe directory
        run: git config --global --add safe.directory '*'

      - name: Build MT7933 Lighting App
        shell: bash
        run: |
          ./scripts/checkout_submodules.py --platform mt793x
          source scripts/activate.sh
          ./scripts/examples/gn_build_example.sh examples/lighting-app/mt793x out/lighting-app

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mt7933-lighting-bin
          path: out/lighting-app/*.bin
