name: Restyled

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  restyled:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - uses: restyled-io/actions/setup@v4

      - id: restyler
        uses: restyled-io/actions/run@v4
        with:
          fail-on-differences: true

      - if: ${{ !cancelled() && steps.restyler.outputs.success == 'true' && steps.restyler.outputs.git-patch }}
        run: |
          cat >/tmp/pr-${{ github.event.pull_request.number }}-restyled.patch <<'EOM'
          ${{ steps.restyler.outputs.git-patch }}
          EOM

      - id: upload
        if: ${{ !cancelled() && steps.restyler.outputs.success == 'true' && steps.restyler.outputs.git-patch }}
        uses: actions/upload-artifact@v4
        with:
          name: pr-${{ github.event.pull_request.number }}-restyled
          path: /tmp/pr-${{ github.event.pull_request.number }}-restyled.patch
          if-no-files-found: ignore
          overwrite: true
          retention-days: 1

      - if: ${{ !cancelled() && steps.restyler.outputs.success == 'true' && steps.upload.outputs.artifact-url }}
        run: |
          cat >>"$GITHUB_STEP_SUMMARY" <<'EOM'
          ## Restyled

          To apply these fixes locally,

          1. Download [this patch](${{ steps.upload.outputs.artifact-url }})
          2. Unzip it: `unzip pr-${{ github.event.pull_request.number }}-restyled.zip`
          3. Apply it: `git am < pr-${{ github.event.pull_request.number }}-restyled.patch`

          EOM